Repository storj/storj, pull requests merged in 2018-11, with the labels that each got.

#563 bypass data checker and repairer in captplanet
  cmd/captplanet/run.go
Labels: cla-signed

#565 Run repairer and checker early
  pkg/audit/service.go
  pkg/datarepair/checker/checker.go
  pkg/datarepair/repairer/config.go
  pkg/datarepair/repairer/repairer.go
Labels: cla-signed

#557 better waitlist-gating
  examples/piecestore-client/main.go
  examples/pointerdb-client/main.go
  examples/statdb-client/main.go
  pkg/audit/reporter.go
  pkg/auth/signature_test.go
  pkg/kademlia/kademlia_test.go
  pkg/kademlia/workers_test.go
  pkg/node/id.go
  pkg/node/node_test.go
  pkg/overlay/cache_test.go
  pkg/overlay/client_test.go
  pkg/peertls/peertls.go
  pkg/peertls/peertls_test.go
  pkg/peertls/utils.go
  pkg/piecestore/rpc/server/server_test.go
  pkg/pointerdb/pdbclient/client_test.go
  pkg/pointerdb/pointerdb_test.go
  pkg/provider/cert_authority_test.go
  pkg/provider/certificate_authority.go
  pkg/provider/identity.go
  pkg/provider/identity_test.go
  pkg/provider/provider.go
  pkg/provider/utils.go
  pkg/transport/transport_test.go
  scripts/cert-gating.sh
Labels: Request Code Review, cla-signed

#567 Bandwidth fix
  pkg/piecestore/rpc/server/psdb/psdb.go
  pkg/piecestore/rpc/server/psdb/psdb_test.go
Labels: cla-signed

#566 reproduce interval errors
  scripts/test-captplanet.sh
Labels: cla-signed

#546 Agreement Receiver service
  pkg/agreementreceiver/config.go
  pkg/agreementreceiver/server.go
Labels: cla-signed

#512 Use `sync.Cond` with kademlia workers
  pkg/kademlia/kademlia.go
  pkg/kademlia/kademlia_test.go
  pkg/kademlia/lookup.go
  pkg/kademlia/peer_discovery.go
  pkg/kademlia/queue.go
Labels: cla-signed

#572 Disable debug logging for routing table
  pkg/kademlia/routing.go
Labels: cla-signed

#564 download with specific number of nodes V3-353
  pkg/storage/ec/client.go
  pkg/storage/ec/client_test.go
  pkg/storage/segments/store.go
Labels: cla-signed, wip

#571 Optimize sortByXOR
  pkg/kademlia/routing.go
  pkg/kademlia/routing_helpers.go
  pkg/kademlia/routing_helpers_test.go
Labels: cla-signed

#569 adds MaxNodes and Start to FindStorageNodes
  pkg/overlay/server.go
  pkg/pb/overlay.pb.go
  pkg/pb/overlay.proto
Labels: cla-signed

#528 internal/testplanet
  internal/testplanet/gen_identities.go
  internal/testplanet/identities.go
  internal/testplanet/identities_table.go
  internal/testplanet/node.go
  internal/testplanet/planet.go
  internal/testplanet/planet_test.go
  pkg/pointerdb/pdbclient/client.go
Labels: cla-signed

#560 Fix 'message not signed by the satellite' problem
  internal/testplanet/planet_test.go
  pkg/audit/cursor_test.go
  pkg/audit/service.go
  pkg/auth/signature.go
  pkg/auth/signature_test.go
  pkg/pb/pointerdb.pb.go
  pkg/pb/pointerdb.proto
  pkg/pointerdb/pdbclient/client.go
  pkg/pointerdb/pdbclient/client_test.go
  pkg/pointerdb/pdbclient/mocks/mock_client.go
  pkg/pointerdb/pointerdb.go
  pkg/pointerdb/pointerdb_test.go
  pkg/storage/segments/store.go
Labels: Request Code Review, cla-signed

#547 Satellite bw usage v3 121
  examples/piecestore-client/main.go
  go.sum
  pkg/agreementreceiver/server.go
  pkg/bwagreement/common.go
  pkg/bwagreement/config.go
  pkg/bwagreement/dbx/bwagreement.dbx
  pkg/bwagreement/dbx/bwagreement.dbx.go
  pkg/bwagreement/dbx/bwagreement.dbx.postgres.sql
  pkg/bwagreement/dbx/gen.go
  pkg/bwagreement/server.go
  pkg/bwagreement/server_test.go
Labels: Request Code Review, cla-signed

#580 metainfo readonly stream
  pkg/metainfo/kvmetainfo/buckets.go
  pkg/metainfo/kvmetainfo/metainfo.go
  pkg/metainfo/kvmetainfo/objects.go
  pkg/metainfo/kvmetainfo/paths.go
  pkg/metainfo/kvmetainfo/stream.go
  pkg/storage/segments/store.go
  pkg/storage/streams/store.go
  pkg/storj/encryption.go
  pkg/storj/metainfo.go
  pkg/storj/object.go
Labels: cla-signed

#575 fix test-captplanet.sh script on MacOS/BSD
  scripts/test-captplanet.sh
Labels: cla-signed

#577 s3-benchmark test with uplink
  cmd/s3-benchmark/awscli.go
  cmd/s3-benchmark/main.go
  cmd/s3-benchmark/minio.go
  cmd/s3-benchmark/uplink.go
Labels: cla-signed

#582 Integrate SegmentStore Repair method with repair service
  cmd/captplanet/run.go
  cmd/captplanet/setup.go
  pkg/datarepair/repairer/config.go
  pkg/datarepair/repairer/repairer.go
  pkg/storage/segments/mock_store.go
  pkg/storage/segments/store.go
  pkg/storage/segments/store_test.go
Labels: cla-signed

#578 Use Nodes array from pdb.Get
  examples/pointerdb-client/main.go
  pkg/audit/cursor.go
  pkg/pointerdb/pdbclient/client.go
  pkg/pointerdb/pdbclient/client_test.go
  pkg/pointerdb/pdbclient/mocks/mock_client.go
  pkg/storage/segments/store.go
  pkg/storage/segments/store_test.go
Labels: Request Code Review, cla-signed

#573 Waitlist script
  scripts/cert-gating.sh
  scripts/utils.sh
  scripts/waitlist/storj.sh
  scripts/waitlist/user.sh
Labels: Request Code Review, cla-signed

#574 Use transport client and cleanup all the clients
  cmd/captplanet/run.go
  cmd/storagenode/main.go
  examples/piecestore-cli/main.go
  examples/piecestore-client/main.go
  internal/testplanet/node.go
  internal/testplanet/planet.go
  pkg/audit/verifier.go
  pkg/datarepair/repairer/config.go
  pkg/dht/mocks/mock_dht.go
  pkg/miniogw/config.go
  pkg/overlay/client.go
  pkg/overlay/client_test.go
  pkg/overlay/overlay_test.go
  pkg/overlay/service.go
  pkg/piecestore/psclient/client.go
  pkg/piecestore/psclient/pieceid.go
  pkg/piecestore/psclient/pieceid_test.go
  pkg/piecestore/psclient/pieceranger.go
  pkg/piecestore/psclient/pieceranger_test.go
  pkg/piecestore/psclient/readerwriter.go
  pkg/piecestore/psserver/agreementsender/agreementsender.go
  pkg/piecestore/psserver/psdb/psdb.go
  pkg/piecestore/psserver/psdb/psdb_test.go
  pkg/piecestore/psserver/readerwriter.go
  pkg/piecestore/psserver/retrieve.go
  pkg/piecestore/psserver/server.go
  pkg/piecestore/psserver/server_test.go
  pkg/piecestore/psserver/store.go
  pkg/pointerdb/pdbclient/client.go
  pkg/pointerdb/pdbclient/client_test.go
  pkg/pointerdb/pdbclient/mocks/mock_client.go
  pkg/statdb/sdbclient/client.go
  pkg/storage/ec/client.go
  pkg/storage/ec/client_test.go
  pkg/storage/ec/mocks/mock_client.go
  pkg/storage/ec/psclient_mock_test.go
  pkg/storage/segments/store.go
  pkg/transport/client.go
  pkg/transport/transport.go
  storage/postgreskv/schema/data.go
Labels: Request Code Review, cla-signed

#521 audit cron fixes for error handling and the global Run
  cmd/captplanet/run.go
  cmd/satellite/main.go
  pkg/audit/cursor.go
  pkg/audit/reporter.go
  pkg/audit/service.go
  pkg/audit/verifier.go
  pkg/statdb/sdbclient/client.go
Labels: Request Code Review, cla-signed

#588 Allow S3 clients to reupload stale parts
  pkg/miniogw/multipart.go
Labels: cla-signed

#590 audit: don't panic in case of a 0-size pointer
  pkg/audit/cursor.go
Labels: cla-signed

#592 Build the gateway binary too
  Makefile
Labels: cla-signed

#584 Don't count current channel when testing for slowness
  pkg/eestream/encode.go
Labels: cla-signed

#589 metainfo: Add redundancy share information
  pkg/metainfo/kvmetainfo/objects.go
Labels: cla-signed

#586 Diagnostic tool for Satellite
  cmd/satellite/main.go
  pkg/bwagreement/dbx/bwagreement.dbx
  pkg/bwagreement/dbx/bwagreement.dbx.go
  pkg/bwagreement/server.go
  pkg/bwagreement/server_test.go
Labels: Request Code Review, cla-signed

#583 Don't encrypt empty content for buckets and 0-byte objects
  pkg/encryption/encryption.go
Labels: cla-signed

#576 Diagnostic tool to inspect storage node bandwidth allocation databases
  cmd/storagenode/main.go
Labels: Request Code Review, cla-signed

#555 Ensure datarepair.Queue can run in parallel on multiple computers
  pkg/datarepair/checker/checker_test.go
  pkg/datarepair/checker/config.go
  pkg/datarepair/queue/queue.go
  pkg/datarepair/queue/queue_test.go
  pkg/datarepair/repairer/config.go
  pkg/overlay/cache.go
  storage/common.go
  storage/redis/client.go
  storage/redis/client_queue.go
  storage/redis/client_test.go
  storage/redis/queue_test.go
  storage/testqueue/queue.go
  storage/testqueue/queue_test.go
  storage/testsuite/test_queue.go
Labels: cla-signed

#591 V3-664 Extend User repository. Reimplemented with dbx
  go.mod
  pkg/satellite/database.go
  pkg/satellite/satellitedb/db.go
  pkg/satellite/satellitedb/db/.keep
  pkg/satellite/satellitedb/dbx/accountdb.dbx
  pkg/satellite/satellitedb/dbx/accountdb.dbx.go
  pkg/satellite/satellitedb/dbx/accountdb.dbx.sqlite3.sql
  pkg/satellite/satellitedb/dbx/gen.go
  pkg/satellite/satellitedb/users.go
  pkg/satellite/satellitedb/users_test.go
  pkg/satellite/users.go
Labels: cla-signed

#581 Add creation time to Payer Bandwidth Allocation
  examples/piecestore-client/main.go
  pkg/audit/verifier.go
  pkg/pb/piecestore.pb.go
  pkg/pb/piecestore.proto
  pkg/pointerdb/pointerdb.go
Labels: cla-signed

#568 Creates Accounting Pkg to tally at rest node storage
  pkg/accounting/common.go
  pkg/accounting/config.go
  pkg/accounting/tally.go
  pkg/accounting/tally_test.go
  pkg/datarepair/checker/checker.go
  pkg/datarepair/checker/checker_test.go
  pkg/datarepair/checker/config.go
  pkg/datarepair/repairer/config.go
  pkg/datarepair/repairer/repairer.go
  pkg/node/server.go
  pkg/utils/utils.go
Labels: cla-signed

#603 removes error when attempting to audit inline segment
  pkg/audit/service.go
Labels: cla-signed

#606 V3-665 Creating Companies repository
  pkg/satellite/companies.go
  pkg/satellite/database.go
  pkg/satellite/satellitedb/companies.go
  pkg/satellite/satellitedb/companies_test.go
  pkg/satellite/satellitedb/db.go
  pkg/satellite/satellitedb/dbx/accountdb.dbx
  pkg/satellite/satellitedb/dbx/satellitedb.dbx
  pkg/satellite/satellitedb/dbx/satellitedb.dbx.go
  pkg/satellite/satellitedb/dbx/satellitedb.dbx.sqlite3.sql
  pkg/satellite/satellitedb/users.go
  pkg/satellite/satellitedb/users_test.go
  pkg/satellite/users.go
Labels: cla-signed

#605 Check for go.mod validity
  .travis.yml
  go.mod
  go.sum
  pkg/process/metrics.go
  pkg/statdb/sdbclient/client.go
  scripts/setup-gopath.ps1
  scripts/setup-gopath.sh
  storage/postgreskv/schema/migrate.go
Labels: cla-signed

#596 [WIP] MVP of Kad inspection tools
  cmd/kad/main.go
  pkg/miniogw/logging/logger_mock_test.go
  pkg/pb/gen.go
  pkg/pb/kadcli.pb.go
  pkg/pb/kadcli.proto
  pkg/pb/overlay.pb.go
Labels: cla-signed, wip

#601 Data at rest accounting database
  pkg/accounting/dbx/accounting.dbx
  pkg/accounting/dbx/accounting.dbx.go
  pkg/accounting/dbx/accounting.dbx.postgres.sql
  pkg/accounting/dbx/accounting.dbx.sqlite3.sql
  pkg/accounting/dbx/gen.go
Labels: cla-signed

#602 update dbx generation script for statdb
  pkg/statdb/dbx/gen.go
  pkg/statdb/dbx/statdb.dbx.go
Labels: cla-signed

#612 Coyle/tls verify
  examples/grpc-debug/main.go
  pkg/bwagreement/server_test.go
  pkg/kademlia/kademlia_test.go
  pkg/kademlia/workers_test.go
  pkg/node/node_test.go
  pkg/piecestore/psserver/agreementsender/agreementsender.go
  pkg/piecestore/psserver/server_test.go
  pkg/provider/identity.go
  pkg/transport/transport.go
Labels: cla-signed

#609 Check schemas while creating tables
  internal/migrate/create.go
  internal/migrate/create_test.go
  internal/testcontext/context_test.go
  pkg/bwagreement/server.go
  pkg/bwagreement/server_test.go
  pkg/satellite/satellitedb/db.go
  pkg/statdb/statdb.go
  pkg/utils/utils_test.go
Labels: Request Code Review, backward incompatible, cla-signed

#610 refactored byte to uuid converting
  pkg/satellite/satellitedb/companies.go
  pkg/satellite/satellitedb/companies_test.go
  pkg/satellite/satellitedb/db/.keep
  pkg/satellite/satellitedb/users.go
  pkg/satellite/satellitedb/utils.go
  pkg/satellite/satellitedb/utils_test.go
Labels: cla-signed

#623 Update golangci-lint v1.12.2
  .travis.yml
Labels: cla-signed

#597 remove bad nodes from originalNodes list when repairing
  pkg/storage/segments/store.go
Labels: cla-signed

#625 Issues in overlay rebuild allowed to continue
  pkg/overlay/cache.go
  pkg/overlay/config.go
Labels: cla-signed

#604 Signature verification
  cmd/satellite/main.go
  pkg/bwagreement/common.go
  pkg/bwagreement/config.go
  pkg/bwagreement/server.go
  pkg/bwagreement/server_test.go
Labels: Code Review In-Progress, cla-signed

#637 Configurable encryption type for paths
  pkg/encryption/examples_test.go
  pkg/encryption/path.go
  pkg/encryption/path_test.go
  pkg/metainfo/kvmetainfo/buckets_test.go
  pkg/metainfo/kvmetainfo/objects.go
  pkg/miniogw/config.go
  pkg/storage/buckets/prefixed.go
  pkg/storage/buckets/store.go
  pkg/storage/objects/store.go
  pkg/storage/streams/store.go
  pkg/storage/streams/store_test.go
Labels: cla-signed

#630 Cleanup agreement sender
  cmd/captplanet/setup.go
  pkg/piecestore/psserver/agreementsender/agreementsender.go
  pkg/piecestore/psserver/psdb/psdb.go
Labels: Request Code Review, cla-signed

#645 metainfo: Fix listing paths
  pkg/metainfo/kvmetainfo/objects.go
Labels: cla-signed

#611 account api: infrastructure, login, register, getUser
  cmd/captplanet/run.go
  go.mod
  go.sum
  pkg/satellite/auth.go
  pkg/satellite/satelliteauth/claims.go
  pkg/satellite/satelliteauth/hmac.go
  pkg/satellite/satelliteauth/token.go
  pkg/satellite/satellitedb/users.go
  pkg/satellite/satelliteweb/api.go
  pkg/satellite/satelliteweb/config.go
  pkg/satellite/satelliteweb/gateway.go
  pkg/satellite/satelliteweb/satelliteql/mutation.go
  pkg/satellite/satelliteweb/satelliteql/query.go
  pkg/satellite/satelliteweb/satelliteql/typecreator.go
  pkg/satellite/satelliteweb/satelliteql/user.go
  pkg/satellite/service.go
  pkg/satellite/users.go
Labels: cla-signed, wip

#647 Satellitedb refactoring
  pkg/satellite/projects.go
  pkg/satellite/satellitedb/companies.go
  pkg/satellite/satellitedb/companies_test.go
  pkg/satellite/satellitedb/db.go
  pkg/satellite/satellitedb/dbx/satellitedb.dbx
  pkg/satellite/satellitedb/dbx/satellitedb.dbx.go
  pkg/satellite/satellitedb/dbx/satellitedb.dbx.sqlite3.sql
  pkg/satellite/satellitedb/projects.go
  pkg/satellite/satellitedb/projects_test.go
  pkg/satellite/satellitedb/users.go
  pkg/satellite/satellitedb/users_test.go
  pkg/satellite/satellitedb/utils_test.go
Labels: cla-signed

#651 [WIP] Header satellite ui initial markup
  web/satellite/.gitignore
  web/satellite/package-lock.json
  web/satellite/src/components/common/Button.vue
  web/satellite/src/components/common/Checkbox.vue
  web/satellite/src/components/common/HeaderedInput.vue
  web/satellite/src/components/dashboard/DashboardHeader.vue
  web/satellite/src/components/dashboard/account/AccountArea.vue
  web/satellite/src/components/dashboard/account/AccountButton.vue
  web/satellite/src/components/dashboard/newProject/NewProjectArea.vue
  web/satellite/src/components/dashboard/newProject/NewProjectPopup.vue
  web/satellite/src/components/dashboard/projectSelection/ProjectSelectionArea.vue
  web/satellite/src/components/dashboard/projectSelection/ProjectSelectionDropdown.vue
  web/satellite/src/components/navigation/NavigationArea.vue
  web/satellite/src/router/index.ts
  web/satellite/src/utils/constants/navigationLinks.ts
  web/satellite/src/utils/constants/routerConstants.ts
  web/satellite/src/views/Dashboard.vue
  web/satellite/src/views/Register.vue
  web/satellite/static/images/dashboard/Add.png
  web/satellite/static/images/dashboard/CreateNewProject.png
  web/satellite/static/images/dashboard/Logo.png
  web/satellite/tests/unit/Button.spec.ts
  web/satellite/tests/unit/Checkbox.spec.ts
  web/satellite/tests/unit/HeaderedInput.spec.ts
  web/satellite/tests/unit/__snapshots__/Button.spec.ts.snap
  web/satellite/tests/unit/__snapshots__/HeaderedInput.spec.ts.snap
  web/satellite/webpack.config.dev.js
Labels: cla-signed, wip

#653 Auth pages markup
  web/satellite/src/App.vue
  web/satellite/src/components/HeaderlessInput.vue
  web/satellite/src/components/common/Button.vue
  web/satellite/src/components/common/Checkbox.vue
  web/satellite/src/components/common/HeaderedInput.vue
  web/satellite/src/views/Login.vue
  web/satellite/src/views/Register.vue
  web/satellite/static/images/login/Background.svg
  web/satellite/static/images/login/Logo.svg
  web/satellite/tests/unit/HeaderlessInput.spec.ts
  web/satellite/tests/unit/__snapshots__/HeaderlessInput.spec.ts.snap
Labels: cla-signed

#654 added creation date to graphql user and removed redundant check from …
  pkg/satellite/satelliteweb/api.go
  pkg/satellite/satelliteweb/gateway.go
  pkg/satellite/satelliteweb/satelliteql/user.go
Labels: cla-signed

#540 Verify overlay cache is accurately and fully tested
  pkg/kademlia/kademlia.go
  pkg/overlay/cache.go
  pkg/overlay/cache_test.go
  storage/common.go
  storage/testqueue/queue.go
Labels: cla-signed

#650 Update statdb
  examples/statdb-client/main.go
  pkg/statdb/proto/statdb.pb.go
  pkg/statdb/proto/statdb.proto
  pkg/statdb/sdbclient/client.go
  pkg/statdb/sdbclient/mock_client.go
  pkg/statdb/statdb.go
  pkg/statdb/statdb_test.go
Labels: cla-signed

#649 testplanet: add logger
  internal/testplanet/node.go
  internal/testplanet/planet.go
  internal/testplanet/planet_test.go
  pkg/metainfo/kvmetainfo/buckets_test.go
Labels: cla-signed

#661 added copyright to every file in satellite pkg
  pkg/satellite/auth.go
  pkg/satellite/satelliteweb/api.go
  pkg/satellite/satelliteweb/config.go
  pkg/satellite/satelliteweb/gateway.go
  pkg/satellite/satelliteweb/satelliteql/mutation.go
  pkg/satellite/satelliteweb/satelliteql/query.go
  pkg/satellite/satelliteweb/satelliteql/typecreator.go
  pkg/satellite/satelliteweb/satelliteql/user.go
  pkg/satellite/service.go
Labels: cla-signed

#664 Fail linter when copyright is missing.
  .travis.yml
  Makefile
  cmd/kad/main.go
  scripts/check-copyright.go
  scripts/check-for-header.sh
Labels: cla-signed

#655 Fix for uplink cat writing additional bytes
  cmd/uplink/cmd/cat.go
  cmd/uplink/cmd/cp.go
  cmd/uplink/cmd/put.go
Labels: Request Code Review, cla-signed

#662 metainfo objects tests
  pkg/metainfo/kvmetainfo/objects.go
  pkg/metainfo/kvmetainfo/objects_test.go
  pkg/metainfo/kvmetainfo/stream.go
  storage/boltdb/client.go
  storage/common.go
  storage/postgreskv/client.go
  storage/redis/client.go
  storage/teststore/store.go
Labels: cla-signed

#659 Use better defaults and naming for postgres database
  .travis.yml
  cmd/satellite/main.go
  docker-compose.yaml
  internal/migrate/create_test.go
  pkg/bwagreement/config.go
  pkg/bwagreement/server_test.go
  storage/postgreskv/client_test.go
Labels: cla-signed

#641 Refactor basystem
  cmd/captplanet/run.go
  cmd/satellite/main.go
  pkg/bwagreement/config.go
  pkg/bwagreement/database-manager/database-manager.go
  pkg/bwagreement/database-manager/dbx/bwagreement.dbx
  pkg/bwagreement/database-manager/dbx/bwagreement.dbx.go
  pkg/bwagreement/database-manager/dbx/bwagreement.dbx.postgres.sql
  pkg/bwagreement/database-manager/dbx/bwagreement.dbx.sqlite3.sql
  pkg/bwagreement/database-manager/dbx/gen.go
  pkg/bwagreement/dbx/gen.go
  pkg/bwagreement/server.go
  pkg/bwagreement/server_test.go
  pkg/pb/bandwidth.pb.go
  pkg/pb/bandwidth.proto
  pkg/pb/piecestore.pb.go
  pkg/pb/piecestore.proto
  pkg/piecestore/psclient/readerwriter.go
  pkg/piecestore/psserver/agreementsender/agreementsender.go
Labels: Request Code Review, cla-signed

#669 Adding a "Version: Alpha" badge
  README.md
Labels: cla-signed

#656 Diagnostic tool to inspect repair queue
  cmd/satellite/main.go
  pkg/datarepair/queue/queue.go
  pkg/datarepair/queue/queue_test.go
  storage/common.go
  storage/redis/client_queue.go
  storage/testqueue/queue.go
  storage/testsuite/test_queue.go
Labels: Request Code Review, cla-signed

#670 Telemetry in metainfo implementation
  pkg/metainfo/kvmetainfo/buckets.go
  pkg/metainfo/kvmetainfo/metainfo.go
  pkg/metainfo/kvmetainfo/objects.go
  pkg/metainfo/kvmetainfo/stream.go
Labels: cla-signed

#668 operationName and variables fields added to graphql json parsing
  pkg/satellite/satelliteweb/api.go
Labels: cla-signed

#660 Simplify and fix tests
  cmd/overlay/cache.go
  pkg/audit/cursor_test.go
  pkg/overlay/cache.go
  pkg/overlay/cache_test.go
  pkg/overlay/client_test.go
  pkg/overlay/config.go
  pkg/overlay/config_test.go
  pkg/overlay/overlay_test.go
Labels: cla-signed

#674 Metainfo handle inline segments in ReadOnlyStream
  pkg/metainfo/kvmetainfo/objects_test.go
  pkg/metainfo/kvmetainfo/stream.go
Labels: cla-signed

#678 Use testplanet to test Refresh
  internal/testplanet/node.go
  internal/testplanet/planet.go
  pkg/overlay/cache.go
  pkg/overlay/cache_test.go
  pkg/transport/transport.go
Labels: cla-signed

#640 Remove unused workers
  pkg/kademlia/kademlia_test.go
  pkg/kademlia/workers.go
  pkg/kademlia/workers_test.go
Labels: Request Code Review, cla-signed

#673 [V3-770] user settings markup updated
  web/satellite/src/components/common/Checkbox.vue
  web/satellite/src/components/common/HeaderedInput.vue
  web/satellite/src/components/common/HeaderlessInput.vue
  web/satellite/src/components/dashboard/DashboardHeader.vue
  web/satellite/src/components/dashboard/account/AccountArea.vue
  web/satellite/src/components/dashboard/account/AccountButton.vue
  web/satellite/src/components/dashboard/account/AccountDropdown.vue
  web/satellite/src/components/dashboard/newProject/NewProjectArea.vue
  web/satellite/src/components/dashboard/newProject/NewProjectPopup.vue
  web/satellite/src/components/dashboard/projectSelection/ProjectSelectionArea.vue
  web/satellite/src/components/dashboard/projectSelection/ProjectSelectionDropdown.vue
  web/satellite/src/components/navigation/NavigationArea.vue
  web/satellite/src/types/register.d.ts
  web/satellite/src/views/Dashboard.vue
  web/satellite/src/views/Login.vue
  web/satellite/src/views/Register.vue
Labels: cla-signed

#666 Block ports in range 0 to 10000 when running tests
  .travis.yml
  scripts/use-ports.go
Labels: cla-signed

#677 Add overlay server to testplanet
  internal/testplanet/node.go
  internal/testplanet/planet.go
  pkg/overlay/client.go
  pkg/overlay/config.go
  pkg/overlay/overlay_test.go
  pkg/overlay/server.go
  pkg/overlay/server_test.go
Labels: cla-signed

#685 Detect goroutines running for too long in testcontext
  internal/testcontext/context.go
  internal/testcontext/context_test.go
Labels: Request Code Review, cla-signed

#683 V3-805 Extend satellitedb with Project members entity
  pkg/satellite/database.go
  pkg/satellite/projectmembers.go
  pkg/satellite/projects.go
  pkg/satellite/satellitedb/companies.go
  pkg/satellite/satellitedb/companies_test.go
  pkg/satellite/satellitedb/db.go
  pkg/satellite/satellitedb/dbx/satellitedb.dbx
  pkg/satellite/satellitedb/dbx/satellitedb.dbx.go
  pkg/satellite/satellitedb/dbx/satellitedb.dbx.sqlite3.sql
  pkg/satellite/satellitedb/projectmembers.go
  pkg/satellite/satellitedb/projectmembers_test.go
  pkg/satellite/satellitedb/projects.go
  pkg/satellite/satellitedb/projects_test.go
  pkg/satellite/satellitedb/users.go
  pkg/satellite/satellitedb/users_test.go
Labels: cla-signed

#643 Enable checker in captplanet and staging
  cmd/captplanet/run.go
  cmd/satellite/main.go
  go.mod
  pkg/accounting/rollup/rollup.go
  pkg/accounting/tally/tally.go
  pkg/datarepair/checker/checker.go
  pkg/datarepair/checker/config.go
  pkg/datarepair/queue/queue.go
  pkg/datarepair/repairer/repairer.go
  pkg/overlay/config.go
  pkg/overlay/mocks/overlay.go
  pkg/overlay/server.go
  pkg/provider/identity.go
  pkg/statdb/dbx/gen.go
Labels: cla-signed, wip

#627 Coyle/disable mock
  cmd/captplanet/run.go
  cmd/captplanet/setup.go
  cmd/satellite/main.go
  internal/testplanet/planet.go
  pkg/dht/dht.go
  pkg/dht/mocks/mock_dht.go
  pkg/kademlia/config.go
  pkg/kademlia/kademlia.go
  pkg/kademlia/routing.go
  pkg/kademlia/routing_helpers.go
  pkg/kademlia/routing_helpers_test.go
  pkg/kademlia/test_utils.go
  pkg/node/connection_pool.go
  pkg/node/connection_pool_test.go
  pkg/node/node.go
  pkg/node/server.go
  pkg/overlay/cache.go
  pkg/overlay/config.go
  pkg/overlay/server.go
  pkg/overlay/server_test.go
  pkg/piecestore/psserver/agreementsender/agreementsender.go
  pkg/provider/provider.go
  pkg/transport/transport.go
Labels: cla-signed, wip

#690 rename `size` fields in protobuf messages for gogo compatibility
  examples/piecestore-client/main.go
  pkg/accounting/tally/tally.go
  pkg/audit/cursor.go
  pkg/audit/cursor_test.go
  pkg/audit/verifier.go
  pkg/audit/verifier_test.go
  pkg/metainfo/kvmetainfo/objects.go
  pkg/pb/bandwidth.pb.go
  pkg/pb/datarepair.pb.go
  pkg/pb/gen.go
  pkg/pb/kadcli.pb.go
  pkg/pb/meta.pb.go
  pkg/pb/overlay.pb.go
  pkg/pb/piecestore.pb.go
  pkg/pb/piecestore.proto
  pkg/pb/pointerdb.pb.go
  pkg/pb/pointerdb.proto
  pkg/piecestore/psclient/pieceranger.go
  pkg/piecestore/psclient/pieceranger_test.go
  pkg/piecestore/psserver/readerwriter.go
  pkg/piecestore/psserver/retrieve.go
  pkg/piecestore/psserver/server.go
  pkg/piecestore/psserver/server_test.go
  pkg/pointerdb/pdbclient/client_test.go
  pkg/pointerdb/pointerdb.go
  pkg/pointerdb/pointerdb_test.go
  pkg/storage/segments/store.go
  pkg/storage/segments/store_test.go
Labels: Request Code Review, cla-signed

#695 updates the refresh interval in captplanet test script
  go.mod
  scripts/test-captplanet.sh
Labels: cla-signed

#587 Write access for uplink mount command
  cmd/uplink/cmd/mount.go
  cmd/uplink/cmd/rm.go
Labels: cla-signed

#691 Use designated error classes for common bucket and object errors
  cmd/uplink/cmd/cp.go
  cmd/uplink/cmd/ls.go
  cmd/uplink/cmd/mb.go
  cmd/uplink/cmd/mount.go
  cmd/uplink/cmd/rb.go
  cmd/uplink/cmd/rm.go
  cmd/uplink/cmd/root.go
  pkg/metainfo/kvmetainfo/buckets_test.go
  pkg/metainfo/kvmetainfo/objects.go
  pkg/metainfo/kvmetainfo/objects_test.go
  pkg/miniogw/gateway-storj.go
  pkg/miniogw/gateway-storj_test.go
  pkg/storage/buckets/prefixed.go
  pkg/storage/buckets/store.go
  pkg/storage/objects/store.go
  pkg/storj/object.go
Labels: cla-signed

#696 Metainfo remote segment test
  pkg/metainfo/kvmetainfo/buckets_test.go
  pkg/metainfo/kvmetainfo/objects_test.go
Labels: cla-signed

#671 Add metadata to pb.Node (email and wallet)
  pkg/kademlia/config.go
  pkg/kademlia/kademlia.go
  pkg/kademlia/kademlia_test.go
  pkg/pb/overlay.pb.go
  pkg/pb/overlay.proto
Labels: cla-signed

#687 Update register api call to create company on user registration,…
  pkg/satellite/companies.go
  pkg/satellite/satelliteweb/api.go
  pkg/satellite/satelliteweb/config.go
  pkg/satellite/satelliteweb/gateway.go
  pkg/satellite/satelliteweb/satelliteql/company.go
  pkg/satellite/satelliteweb/satelliteql/mutation.go
  pkg/satellite/satelliteweb/satelliteql/query.go
  pkg/satellite/satelliteweb/satelliteql/typecreator.go
  pkg/satellite/satelliteweb/satelliteql/user.go
  pkg/satellite/service.go
  pkg/satellite/users.go
Labels: cla-signed

#657 Kademlia Inspector CLI
  cmd/captplanet/run.go
  cmd/inspector/main.go
  cmd/kad/main.go
  pkg/dht/dht.go
  pkg/dht/mocks/mock_dht.go
  pkg/inspector/config.go
  pkg/inspector/server.go
  pkg/kademlia/routing.go
  pkg/overlay/cache.go
  pkg/pb/gen.go
  pkg/pb/inspector.pb.go
  pkg/pb/inspector.proto
  pkg/pb/kadcli.pb.go
  pkg/pb/kadcli.proto
Labels: cla-signed

#626 Statdb inspection tool
  cmd/inspector/main.go
  cmd/inspector/testnodes.csv
  pkg/inspector/config.go
  pkg/inspector/server.go
  pkg/pb/inspector.pb.go
  pkg/pb/inspector.proto
  pkg/statdb/config.go
Labels: Request Code Review, cla-signed

#699 updated login api
  pkg/satellite/satelliteweb/api.go
  pkg/satellite/satelliteweb/satelliteql/query.go
  pkg/satellite/satelliteweb/satelliteql/token.go
  pkg/satellite/satelliteweb/satelliteql/typecreator.go
  pkg/satellite/satelliteweb/satelliteql/user.go
  pkg/satellite/service.go
Labels: Request Code Review, cla-signed

#704 Satellite project details markup, adaptation and tests fixes
  web/satellite/index.html
  web/satellite/src/components/common/Button.vue
  web/satellite/src/components/common/HeaderedInput.vue
  web/satellite/src/components/common/HeaderlessInput.vue
  web/satellite/src/components/dashboard/DashboardHeader.vue
  web/satellite/src/components/dashboard/account/AccountArea.vue
  web/satellite/src/components/dashboard/account/AccountButton.vue
  web/satellite/src/components/dashboard/account/AccountDropdown.vue
  web/satellite/src/components/dashboard/newProject/NewProjectArea.vue
  web/satellite/src/components/dashboard/projectSelection/ProjectSelectionArea.vue
  web/satellite/src/components/dashboard/projectSelection/ProjectSelectionDropdown.vue
  web/satellite/src/components/navigation/NavigationArea.vue
  web/satellite/src/components/projectDetails/ProjectDetailsArea.vue
  web/satellite/src/router/index.ts
  web/satellite/src/utils/constants/navigationLinks.ts
  web/satellite/src/utils/constants/routerConstants.ts
  web/satellite/src/views/Dashboard.vue
  web/satellite/src/views/Login.vue
  web/satellite/src/views/Register.vue
  web/satellite/static/images/projectDetails/Portability.png
  web/satellite/tests/unit/common/HeaderedInput.spec.ts
  web/satellite/tests/unit/common/__snapshots__/Button.spec.ts.snap
  web/satellite/tests/unit/common/__snapshots__/HeaderedInput.spec.ts.snap
Labels: cla-signed

#702 Update protos to fit style guide (easy review)
  pkg/kademlia/kademlia.go
  pkg/kademlia/kademlia_test.go
  pkg/overlay/client.go
  pkg/overlay/mocks/overlay.go
  pkg/overlay/server.go
  pkg/overlay/server_test.go
  pkg/pb/overlay.pb.go
  pkg/pb/overlay.proto
  pkg/pb/piecestore.pb.go
  pkg/pb/piecestore.proto
  pkg/piecestore/psclient/client.go
  pkg/piecestore/psclient/readerwriter.go
  pkg/piecestore/psserver/readerwriter.go
  pkg/piecestore/psserver/retrieve.go
  pkg/piecestore/psserver/server_test.go
  pkg/piecestore/psserver/store.go
  pkg/utils/utils.go
Labels: Request Code Review, cla-signed

#697 Metainfo stream download
  pkg/metainfo/kvmetainfo/objects_test.go
  pkg/stream/common.go
  pkg/stream/download.go
Labels: cla-signed

#703 Satellite projects api
  pkg/satellite/projects.go
  pkg/satellite/satelliteweb/satelliteql/mutation.go
  pkg/satellite/satelliteweb/satelliteql/project.go
  pkg/satellite/satelliteweb/satelliteql/query.go
  pkg/satellite/satelliteweb/satelliteql/typecreator.go
  pkg/satellite/service.go
Labels: Request Code Review, cla-signed

#595 Fix builds for ARM
  .dockerignore
  Makefile
Labels: cla-signed

#706 Satellitedb company-user relation changed to 1-to-1
  pkg/satellite/companies.go
  pkg/satellite/satellitedb/companies.go
  pkg/satellite/satellitedb/companies_test.go
  pkg/satellite/satellitedb/dbx/satellitedb.dbx
  pkg/satellite/satellitedb/dbx/satellitedb.dbx.go
  pkg/satellite/satellitedb/dbx/satellitedb.dbx.sqlite3.sql
Labels: Request Code Review, cla-signed

#705 Auth logic
  web/satellite/package.json
  web/satellite/src/components/common/Checkbox.vue
  web/satellite/src/components/dashboard/account/AccountButton.vue
  web/satellite/src/main.ts
  web/satellite/src/router/index.ts
  web/satellite/src/store/index.ts
  web/satellite/src/store/modules/auth.ts
  web/satellite/src/store/mutationConstants.ts
  web/satellite/src/types/auth.d.ts
  web/satellite/src/types/register.d.ts
  web/satellite/src/utils/apolloManager.ts
  web/satellite/src/utils/constants/routerConstants.ts
  web/satellite/src/utils/qraphql/createUserQuery.ts
  web/satellite/src/utils/qraphql/loginQuery.ts
  web/satellite/src/views/Login.vue
  web/satellite/src/views/Register.vue
  web/satellite/tests/unit/common/Checkbox.spec.ts
  web/satellite/tests/unit/common/__snapshots__/Checkbox.spec.ts.snap
Labels: cla-signed

#698 Node selection 0/4: Update statdb auth/functionality
  examples/statdb-client/main.go
  pkg/audit/reporter.go
  pkg/auth/apikey.go
  pkg/statdb/config.go
  pkg/statdb/proto/statdb.pb.go
  pkg/statdb/proto/statdb.proto
  pkg/statdb/sdbclient/client.go
  pkg/statdb/statdb.go
  pkg/statdb/statdb_test.go
Labels: Request Code Review, cla-signed

#708 Bandwidth allocations need method designation (GET/PUT)
  examples/pointerdb-client/main.go
  pkg/audit/cursor.go
  pkg/audit/cursor_test.go
  pkg/metainfo/kvmetainfo/objects.go
  pkg/metainfo/kvmetainfo/stream.go
  pkg/pb/pointerdb.pb.go
  pkg/pb/pointerdb.proto
  pkg/pointerdb/pdbclient/client.go
  pkg/pointerdb/pdbclient/client_test.go
  pkg/pointerdb/pdbclient/mocks/mock_client.go
  pkg/pointerdb/pdbclient/pdbclient_mock_test.go
  pkg/pointerdb/pointerdb.go
  pkg/storage/segments/store.go
  pkg/storage/segments/store_test.go
Labels: Request Code Review, cla-signed

#688 made accounting use migrate
  pkg/accounting/db.go
  pkg/accounting/rollup/config.go
  pkg/accounting/rollup/rollup.go
  pkg/accounting/tally/config.go
  pkg/accounting/tally/tally.go
  pkg/accounting/tally/tally_test.go
  pkg/statdb/statdb_test.go
Labels: cla-signed

#709 eestream avoids waiting for pending readers if lots of errors
  pkg/eestream/rs_test.go
  pkg/eestream/stripe.go
Labels: cla-signed

#710 Auth logic additions
  web/satellite/src/App.vue
  web/satellite/src/components/common/Button.vue
  web/satellite/src/components/common/Checkbox.vue
  web/satellite/src/components/common/HeaderedInput.vue
  web/satellite/src/components/common/HeaderlessInput.vue
  web/satellite/src/components/dashboard/DashboardHeader.vue
  web/satellite/src/components/dashboard/account/AccountArea.vue
  web/satellite/src/components/dashboard/account/AccountButton.vue
  web/satellite/src/components/dashboard/account/AccountDropdown.vue
  web/satellite/src/components/dashboard/newProject/NewProjectArea.vue
  web/satellite/src/components/dashboard/newProject/NewProjectPopup.vue
  web/satellite/src/components/dashboard/projectSelection/ProjectSelectionArea.vue
  web/satellite/src/components/dashboard/projectSelection/ProjectSelectionDropdown.vue
  web/satellite/src/components/navigation/NavigationArea.vue
  web/satellite/src/components/projectDetails/ProjectDetailsArea.vue
  web/satellite/src/main.ts
  web/satellite/src/router/index.ts
  web/satellite/src/store/index.ts
  web/satellite/src/store/modules/auth.ts
  web/satellite/src/store/mutationConstants.ts
  web/satellite/src/types/auth.d.ts
  web/satellite/src/types/fetch.d.ts
  web/satellite/src/types/register.d.ts
  web/satellite/src/types/tsx.d.ts
  web/satellite/src/types/vue.d.ts
  web/satellite/src/utils/apolloManager.ts
  web/satellite/src/utils/constants/navigationLinks.ts
  web/satellite/src/utils/constants/routerConstants.ts
  web/satellite/src/utils/dataservice.ts
  web/satellite/src/utils/qraphql/createUserQuery.ts
  web/satellite/src/utils/qraphql/loginQuery.ts
  web/satellite/src/utils/tokenManager.ts
  web/satellite/src/utils/validation.ts
  web/satellite/src/views/Dashboard.vue
  web/satellite/src/views/Login.vue
  web/satellite/src/views/Register.vue
  web/satellite/tests/unit/common/Button.spec.ts
  web/satellite/tests/unit/common/Checkbox.spec.ts
  web/satellite/tests/unit/common/HeaderedInput.spec.ts
  web/satellite/tests/unit/common/HeaderlessInput.spec.ts
  web/satellite/tests/unit/dashboard/account/AccountDropdown.spec.ts
Labels: cla-signed

#712 Add copyright checks for vue, js and ts
  scripts/check-copyright.go
  web/satellite/babel.config.js
  web/satellite/vue.config.js
  web/satellite/webpack.config.dev.js
Labels: cla-signed

#714 V3-760 Create logic for New project popup
  pkg/satellite/satelliteweb/gateway.go
  pkg/satellite/service.go
  web/satellite/package.json
  web/satellite/src/components/common/HeaderedInput.vue
  web/satellite/src/components/dashboard/DashboardHeader.vue
  web/satellite/src/components/dashboard/newProject/NewProjectPopup.vue
  web/satellite/src/components/dashboard/projectSelection/ProjectSelectionArea.vue
  web/satellite/src/store/index.ts
  web/satellite/src/store/modules/auth.ts
  web/satellite/src/store/modules/projects.ts
  web/satellite/src/store/mutationConstants.ts
  web/satellite/src/types/projects.d.ts
  web/satellite/src/utils/apolloManager.ts
  web/satellite/src/utils/qraphql/createProjectsQuery.ts
Labels: cla-signed

#707 Satellite user delete
  pkg/satellite/auth.go
  pkg/satellite/satelliteweb/api.go
  pkg/satellite/satelliteweb/config.go
  pkg/satellite/satelliteweb/gateway.go
  pkg/satellite/satelliteweb/satelliteql/mutation.go
  pkg/satellite/satelliteweb/satelliteql/token.go
  pkg/satellite/satelliteweb/satelliteql/user.go
  pkg/satellite/service.go
Labels: cla-signed

#716 testcontext: Add stack-trace and remove testcase with testing
  internal/testcontext/context.go
  internal/testcontext/context_test.go
Labels: cla-signed

#717 Stops logging repairer errors for empty queue
  pkg/datarepair/queue/queue.go
  pkg/datarepair/repairer/repairer.go
  storage/redis/client_queue.go
Labels: Request Code Review, cla-signed

#711 Add statdb to overlay cache (node selection)
  cmd/overlay/cache.go
  internal/testplanet/node.go
  internal/testplanet/planet.go
  pkg/audit/cursor_test.go
  pkg/overlay/cache.go
  pkg/overlay/client_test.go
  pkg/overlay/config.go
  pkg/overlay/config_test.go
  pkg/pb/overlay.pb.go
  pkg/pb/overlay.proto
Labels: Request Code Review, cla-signed

#684 Fix default basepath location
  cmd/uplink/cmd/root.go
  cmd/uplink/cmd/setup.go
Labels: cla-signed

#723 updates dbx/gen.go to name generated package correctly
  pkg/pb/bandwidth.pb.go
  pkg/pb/datarepair.pb.go
  pkg/pb/meta.pb.go
  pkg/pb/pointerdb.pb.go
  pkg/satellite/satellitedb/dbx/gen.go
Labels: cla-signed

#713 Fix panic in Audit service
  pkg/audit/verifier.go
  pkg/audit/verifier_test.go
Labels: cla-signed

#719 Implemented check for Token before any route
  web/satellite/src/router/index.ts
Labels: cla-signed

#721 V3-757 Create logic for projects dropdown
  web/satellite/src/api/projects.ts
  web/satellite/src/components/dashboard/newProject/NewProjectPopup.vue
  web/satellite/src/components/dashboard/projectSelection/ProjectSelectionArea.vue
  web/satellite/src/components/dashboard/projectSelection/ProjectSelectionDropdown.vue
  web/satellite/src/store/modules/projects.ts
  web/satellite/src/store/mutationConstants.ts
  web/satellite/src/types/projects.d.ts
Labels: cla-signed

#715 update user api
  pkg/satellite/satellitedb/users.go
  pkg/satellite/satellitedb/users_test.go
  pkg/satellite/satelliteweb/satelliteql/mutation.go
  pkg/satellite/satelliteweb/satelliteql/user.go
  pkg/satellite/service.go
Labels: Request Code Review, cla-signed

#725 update company api
  pkg/satellite/satellitedb/companies.go
  pkg/satellite/satelliteweb/satelliteql/company.go
  pkg/satellite/satelliteweb/satelliteql/mutation.go
  pkg/satellite/satelliteweb/satelliteql/user.go
  pkg/satellite/service.go
Labels: Request Code Review, cla-signed

#728 V3-763 Create logic for project details
  pkg/satellite/projects.go
  pkg/satellite/satelliteweb/satelliteql/mutation.go
  pkg/satellite/satelliteweb/satelliteql/project.go
  pkg/satellite/satelliteweb/satelliteql/query.go
  pkg/satellite/service.go
  web/satellite/index.html
  web/satellite/src/api/projects.ts
  web/satellite/src/components/common/HeaderedInput.vue
  web/satellite/src/components/dashboard/DashboardHeader.vue
  web/satellite/src/components/dashboard/account/AccountArea.vue
  web/satellite/src/components/dashboard/newProject/NewProjectPopup.vue
  web/satellite/src/components/dashboard/projectSelection/ProjectSelectionArea.vue
  web/satellite/src/components/navigation/NavigationArea.vue
  web/satellite/src/components/projectDetails/EmptyStateProjectArea.vue
  web/satellite/src/components/projectDetails/ProjectDetailsArea.vue
  web/satellite/src/store/modules/auth.ts
  web/satellite/src/store/modules/projects.ts
  web/satellite/src/types/projects.d.ts
  web/satellite/src/views/Login.vue
  web/satellite/src/views/Register.vue
  web/satellite/static/images/login/1024.svg
  web/satellite/static/images/login/1280.svg
  web/satellite/static/images/login/1920.svg
  web/satellite/static/images/login/320.svg
  web/satellite/static/images/login/640.png
  web/satellite/static/images/login/800.svg
  web/satellite/static/images/projectDetails/checked.svg
  web/satellite/static/images/projectDetails/emptyState.svg
Labels: cla-signed

#730 fixes Linux default base path for uplink
  cmd/uplink/cmd/root.go
Labels: cla-signed

#732 Ensure that we only choose storage nodes
  cmd/overlay/main.go
  examples/piecestore-client/main.go
  internal/testplanet/node.go
  internal/testplanet/planet.go
  pkg/accounting/tally/tally_test.go
  pkg/audit/verifier_test.go
  pkg/datarepair/checker/checker_test.go
  pkg/inspector/server.go
  pkg/kademlia/config.go
  pkg/kademlia/kademlia.go
  pkg/kademlia/kademlia_test.go
  pkg/overlay/client_test.go
  pkg/overlay/server.go
Labels: cla-signed

#729 intial user validation
  pkg/satellite/service.go
  pkg/satellite/users.go
  pkg/satellite/validation.go
Labels: Request Code Review, cla-signed

#733 Reduce noise in logging
  pkg/accounting/tally/tally.go
  pkg/datarepair/checker/checker.go
  pkg/pointerdb/pointerdb.go
  pkg/process/exec_conf.go
  pkg/statdb/statdb.go
Labels: cla-signed

#737 cleanup and bugfix
  pkg/satellite/validation.go
  pkg/storj/node.go
Labels: Request Code Review, cla-signed

#739 Fix import groupings
  cmd/inspector/main.go
  cmd/overlay/main.go
  cmd/satellite/main.go
  cmd/storagenode/main.go
  examples/grpc-debug/main.go
  internal/testplanet/node.go
  pkg/audit/verifier_test.go
  pkg/bwagreement/config.go
  pkg/bwagreement/database-manager/database-manager.go
  pkg/inspector/server.go
  pkg/kademlia/kademlia_test.go
  pkg/kademlia/replacement_cache_test.go
  pkg/kademlia/routing_helpers.go
  pkg/kademlia/routing_helpers_test.go
  pkg/kademlia/routing_test.go
  pkg/node/connection_pool.go
  pkg/node/server_test.go
  pkg/overlay/cache.go
  pkg/overlay/cache_test.go
  pkg/overlay/config.go
  pkg/overlay/mocks/overlay.go
  pkg/overlay/server.go
  pkg/piecestore/psclient/pieceranger_test.go
  pkg/piecestore/psserver/agreementsender/agreementsender.go
  pkg/piecestore/psserver/psdb/psdb.go
  pkg/piecestore/psserver/psdb/psdb_test.go
  pkg/provider/identity.go
  pkg/provider/utils.go
  pkg/satellite/satellitedb/companies.go
  pkg/satellite/satellitedb/db.go
  pkg/satellite/satellitedb/projects_test.go
  pkg/satellite/satellitedb/users_test.go
  pkg/satellite/satelliteweb/config.go
  pkg/satellite/satelliteweb/gateway.go
  pkg/satellite/service.go
  pkg/statdb/statdb.go
  pkg/storage/ec/client.go
  pkg/storage/ec/client_test.go
  pkg/storage/segments/store_test.go
  pkg/transport/transport.go
  scripts/check-imports.go
Labels: cla-signed

#726 metainfo: basic upload
  internal/memory/size.go
  pkg/metainfo/kvmetainfo/buckets_test.go
  pkg/metainfo/kvmetainfo/objects.go
  pkg/metainfo/kvmetainfo/objects_test.go
  pkg/metainfo/kvmetainfo/stream.go
  pkg/pointerdb/pdbclient/client.go
  pkg/storj/encryption.go
  pkg/storj/metainfo.go
  pkg/storj/redundancy.go
  pkg/stream/upload.go
Labels: cla-signed

#676 Linting protobuf files
  .travis.yml
  Makefile
  cmd/uplink/cmd/cp.go
  cmd/uplink/cmd/mount.go
  go.mod
  go.sum
  pkg/miniogw/gateway-storj.go
  pkg/miniogw/gateway-storj_test.go
  pkg/miniogw/multipart.go
  pkg/miniogw/objstore_mock_test.go
  pkg/pb/bandwidth.pb.go
  pkg/pb/datarepair.pb.go
  pkg/pb/inspector.pb.go
  pkg/pb/meta.pb.go
  pkg/pb/meta.proto
  pkg/pb/node.pb.go
  pkg/pb/node.proto
  pkg/pb/overlay.pb.go
  pkg/pb/piecestore.pb.go
  pkg/pb/pointerdb.pb.go
  pkg/pb/streams.pb.go
  pkg/pb/streams.proto
  pkg/pb/types.go
  pkg/statdb/proto/gen.go
  pkg/statdb/proto/statdb.pb.go
  pkg/storage/buckets/prefixed.go
  pkg/storage/buckets/store.go
  pkg/storage/objects/meta.pb.go
  pkg/storage/objects/meta.proto
  pkg/storage/objects/store.go
  scripts/build-protos.sh
  scripts/check-imports.go
  scripts/protobuf.go
Labels: cla-signed

#738 User account settings
  web/satellite/src/api/users.ts
  web/satellite/src/components/common/HeaderedInput.vue
  web/satellite/src/components/dashboard/account/AccountArea.vue
  web/satellite/src/components/dashboard/account/AccountButton.vue
  web/satellite/src/store/index.ts
  web/satellite/src/store/modules/auth.ts
  web/satellite/src/store/modules/users.ts
  web/satellite/src/store/mutationConstants.ts
  web/satellite/src/types/users.d.ts
  web/satellite/src/utils/apolloManager.ts
  web/satellite/src/utils/qraphql/createUserQuery.ts
  web/satellite/src/utils/qraphql/loginQuery.ts
  web/satellite/src/views/Login.vue
  web/satellite/src/views/Register.vue
Labels: cla-signed

#743 pretty print kad inspector
  cmd/inspector/main.go
  pkg/inspector/server.go
Labels: Request Code Review, cla-signed, wip
