Repository storj/storj, pull requests merged in 2018-12, with the labels that each got.

#740 cleanup
  pkg/kademlia/routing_helpers.go
  pkg/kademlia/routing_helpers_test.go
Labels: Request Code Review, cla-signed

#747 Object.Bucket as storj.Bucket instead of string
  pkg/metainfo/kvmetainfo/objects.go
  pkg/metainfo/kvmetainfo/objects_test.go
  pkg/storj/metainfo.go
  pkg/storj/object.go
  pkg/stream/download.go
  pkg/stream/upload.go
Labels: cla-signed

#741 Use OS related default setup directory
  cmd/captplanet/main.go
  cmd/satellite/main.go
  cmd/storagenode/main.go
  cmd/uplink/cmd/root.go
  cmd/uplink/cmd/setup.go
  internal/fpath/path.go
  scripts/test-captplanet.sh
Labels: cla-signed

#753 add sdb apikey to config struct
  pkg/statdb/config.go
Labels: Request Code Review, cla-signed

#749 move clients to internal/s3api
  cmd/s3-benchmark/main.go
  internal/s3client/awscli.go
  internal/s3client/common.go
  internal/s3client/minio.go
  internal/s3client/uplink.go
Labels: cla-signed

#746 Kad inspector fixes
  pkg/inspector/server.go
  pkg/kademlia/kademlia.go
Labels: Request Code Review, cla-signed

#752 Allow config generation into empty directory
  cmd/captplanet/setup.go
  cmd/satellite/main.go
  cmd/uplink/cmd/setup.go
  internal/fpath/path.go
Labels: cla-signed

#759 Ensure that restrictions are consistent.
  pkg/inspector/server.go
  pkg/kademlia/kademlia.go
Labels: cla-signed

#760 Upload with target as prefix save file with prefix name
  cmd/uplink/cmd/cp.go
Labels: Request Code Review, cla-signed

#758 Fix queue implementation
  pkg/kademlia/peer_discovery.go
  pkg/kademlia/peer_discovery_test.go
  pkg/kademlia/queue.go
  pkg/kademlia/queue_test.go
  pkg/storj/node.go
Labels: cla-signed

#745 Migrate Uplink CLI to Metainfo API
  cmd/uplink/cmd/cat.go
  cmd/uplink/cmd/cp.go
  cmd/uplink/cmd/ls.go
  cmd/uplink/cmd/mb.go
  cmd/uplink/cmd/mount.go
  cmd/uplink/cmd/put.go
  cmd/uplink/cmd/rb.go
  cmd/uplink/cmd/rm.go
  cmd/uplink/cmd/root.go
  cmd/uplink/cmd/run.go
  pkg/metainfo/kvmetainfo/objects_test.go
  pkg/miniogw/config.go
Labels: cla-signed

#761 Get rid of statdb grpc stuff
  cmd/captplanet/run.go
  cmd/inspector/main.go
  examples/statdb-client/README.md
  examples/statdb-client/main.go
  internal/testplanet/node.go
  pkg/audit/reporter.go
  pkg/inspector/server.go
  pkg/overlay/cache.go
  pkg/overlay/config_test.go
  pkg/pb/inspector.pb.go
  pkg/pb/inspector.proto
  pkg/statdb/config.go
  pkg/statdb/sdbclient/client.go
  pkg/statdb/sdbclient/common.go
  pkg/statdb/sdbclient/mock_client.go
  pkg/statdb/statdb.go
  pkg/statdb/statdb_test.go
Labels: Request Code Review, cla-signed

#720 Filter nodes by reputation and IP address (node selection)
  cmd/overlay/cache.go
  cmd/overlay/main.go
  internal/testplanet/node.go
  internal/testplanet/planet.go
  pkg/overlay/cache.go
  pkg/overlay/cache_test.go
  pkg/overlay/client.go
  pkg/overlay/client_test.go
  pkg/overlay/server.go
  pkg/overlay/utils_test.go
  pkg/pb/node.pb.go
  pkg/pb/node.proto
  pkg/statdb/statdb.go
Labels: Request Code Review, cla-signed

#731 Improvements to Kad Lookups
  cmd/inspector/main.go
  go.sum
  pkg/inspector/server.go
  pkg/kademlia/kademlia.go
  pkg/kademlia/lookup_test.go
  pkg/kademlia/peer_discovery.go
  pkg/miniogw/logging/logger_mock_test.go
  pkg/pb/bandwidth.pb.go
  pkg/pb/datarepair.pb.go
  pkg/pb/inspector.pb.go
  pkg/pb/inspector.proto
  pkg/pb/meta.pb.go
  pkg/pb/node.pb.go
  pkg/pb/overlay.pb.go
  pkg/pb/piecestore.pb.go
  pkg/pb/pointerdb.pb.go
  pkg/pb/streams.pb.go
  pkg/statdb/proto/statdb.pb.go
Labels: cla-signed, wip

#757 Install gogo/protobuf version that is specified in go.mod
  go.mod
  go.sum
  scripts/protobuf.go
Labels: Request Code Review, cla-signed

#735 Initial satellite master database setup
  cmd/captplanet/run.go
  cmd/satellite/main.go
  satellite/satellitedb/database.go
  satellite/satellitedb/database_test.go
  satellite/satellitedb/dbx/gen.go
  satellite/satellitedb/dbx/satellitedb.dbx
  satellite/satellitedb/dbx/satellitedb.dbx.go
  satellite/satellitedb/dbx/satellitedb.dbx.postgres.sql
  satellite/satellitedb/dbx/satellitedb.dbx.sqlite3.sql
Labels: cla-signed

#755 Kademlia listen on configured address
  pkg/kademlia/config.go
Labels: cla-signed

#742 redo tally query
  pkg/accounting/db.go
  pkg/accounting/dbx/accounting.dbx
  pkg/accounting/dbx/accounting.dbx.go
  pkg/accounting/dbx/accounting.dbx.postgres.sql
  pkg/accounting/dbx/accounting.dbx.sqlite3.sql
  pkg/accounting/dbx/gen.go
  pkg/accounting/tally/config.go
  pkg/accounting/tally/tally.go
  pkg/accounting/tally/tally_test.go
  pkg/bwagreement/database-manager/database-manager.go
  pkg/bwagreement/database-manager/dbx/bwagreement.dbx
  pkg/bwagreement/database-manager/dbx/bwagreement.dbx.go
  pkg/bwagreement/test/server.go
  pkg/bwagreement/test/server_test.go
Labels: cla-signed

#765 Simplify peer discovery implementation
  pkg/kademlia/kademlia.go
  pkg/kademlia/peer_discovery.go
Labels: cla-signed

#768 Changed SelfAddr -> ExternalAddress
  pkg/kademlia/config.go
Labels: cla-signed

#774 Change statdb.FindValidNodes to FindInvalidNodes
  pkg/statdb/proto/statdb.pb.go
  pkg/statdb/proto/statdb.proto
  pkg/statdb/statdb.go
  pkg/statdb/statdb_test.go
Labels: cla-signed

#769 V3-896 Added TS & Vue lint rules
  web/satellite/package.json
  web/satellite/tslint.json
Labels: Request Code Review, cla-signed

#764 Move irreparabledb under datarepair
  pkg/datarepair/checker/checker.go
  pkg/datarepair/checker/checker_test.go
  pkg/datarepair/checker/config.go
  pkg/datarepair/irreparabledb/dbx/gen.go
  pkg/datarepair/irreparabledb/dbx/irreparabledb.dbx
  pkg/datarepair/irreparabledb/dbx/irreparabledb.dbx.go
  pkg/datarepair/irreparabledb/dbx/irreparabledb.dbx.postgres.sql
  pkg/datarepair/irreparabledb/dbx/irreparabledb.dbx.sqlite3.sql
  pkg/datarepair/irreparabledb/irreparabledb.go
  pkg/datarepair/irreparabledb/irreparabledb_test.go
  pkg/irreparabledb/common.go
Labels: cla-signed

#776 satellite projectmembers add and delete api
  pkg/satellite/satelliteweb/satelliteql/mutation.go
  pkg/satellite/satelliteweb/satelliteql/project.go
  pkg/satellite/service.go
Labels: Request Code Review, cla-signed

#772 Satellite Projects db entity and api updated
  pkg/satellite/projects.go
  pkg/satellite/satellitedb/dbx/satellitedb.dbx
  pkg/satellite/satellitedb/dbx/satellitedb.dbx.go
  pkg/satellite/satellitedb/dbx/satellitedb.dbx.sqlite3.sql
  pkg/satellite/satellitedb/projects.go
  pkg/satellite/satellitedb/projects_test.go
  pkg/satellite/satelliteweb/satelliteql/project.go
  pkg/satellite/satelliteweb/satelliteql/query.go
  pkg/satellite/satelliteweb/satelliteql/typecreator.go
  pkg/satellite/service.go
  web/satellite/src/api/projects.ts
  web/satellite/src/components/common/HeaderedInput.vue
  web/satellite/src/components/dashboard/newProject/NewProjectPopup.vue
  web/satellite/src/components/projectDetails/ProjectDetailsArea.vue
  web/satellite/src/store/modules/projects.ts
  web/satellite/src/types/projects.d.ts
Labels: Request Code Review, cla-signed

#778 Fix race in connection pool
  pkg/node/connection_pool.go
  pkg/node/connection_pool_test.go
Labels: cla-signed

#754 Use audit results in checker
  pkg/datarepair/checker/checker.go
  pkg/datarepair/checker/checker_test.go
  pkg/datarepair/checker/config.go
Labels: Request Code Review, cla-signed

#780 adds pointerdb inspector tool
  cmd/pdbinspect/main.go
Labels: cla-signed

#786 clean up uplink config section
  cmd/captplanet/run.go
  cmd/captplanet/setup.go
  cmd/uplink/cmd/mb.go
  cmd/uplink/cmd/root.go
  cmd/uplink/cmd/run.go
  cmd/uplink/cmd/setup.go
  pkg/miniogw/config.go
Labels: cla-signed

#794 removes check for mock overlay in data repair checker config
  pkg/datarepair/checker/config.go
Labels: cla-signed

#770 Merge bwagreement db into satellite master db
  cmd/captplanet/run.go
  cmd/satellite/main.go
  pkg/accounting/tally/config.go
  pkg/accounting/tally/tally.go
  pkg/accounting/tally/tally_test.go
  pkg/bwagreement/config.go
  pkg/bwagreement/database-manager/database-manager.go
  pkg/bwagreement/database-manager/dbx/bwagreement.dbx
  pkg/bwagreement/database-manager/dbx/bwagreement.dbx.go
  pkg/bwagreement/database-manager/dbx/bwagreement.dbx.postgres.sql
  pkg/bwagreement/database-manager/dbx/bwagreement.dbx.sqlite3.sql
  pkg/bwagreement/database-manager/dbx/gen.go
  pkg/bwagreement/server.go
  pkg/bwagreement/test/server.go
  satellite/satellitedb/bandwidthagreement.go
  satellite/satellitedb/database.go
  satellite/satellitedb/dbx/satellitedb.dbx
  satellite/satellitedb/dbx/satellitedb.dbx.go
  satellite/satellitedb/dbx/satellitedb.dbx.postgres.sql
  satellite/satellitedb/dbx/satellitedb.dbx.sqlite3.sql
Labels: Request Code Review, cla-signed

#796 Use testcontext with tally tests
  pkg/accounting/tally/tally_test.go
Labels: cla-signed

#795 Bwagreement tests cleanup
  pkg/bwagreement/test/common.go
  pkg/bwagreement/test/server_test.go
Labels: cla-signed

#797 Add time limit to ensure that travis prints something when it fails.
  .travis.yml
Labels: cla-signed

#771 TLS extension processing
  Makefile
  cmd/captplanet/run.go
  cmd/captplanet/setup.go
  cmd/uplink/cmd/run.go
  internal/testplanet/identities.go
  internal/testplanet/node.go
  pkg/miniogw/config.go
  pkg/peertls/extensions.go
  pkg/peertls/peertls.go
  pkg/peertls/peertls_test.go
  pkg/peertls/utils.go
  pkg/provider/certificate_authority.go
  pkg/provider/identity.go
  pkg/provider/identity_test.go
  pkg/provider/provider.go
  pkg/provider/utils.go
Labels: Request Code Review, cla-signed

#763 cleaning up todos in Kademlia pkg
  pkg/kademlia/config.go
Labels: cla-signed

#784 better database error handling
  pkg/accounting/db.go
  pkg/accounting/dbx/gen.go
  pkg/datarepair/irreparabledb/dbx/gen.go
  pkg/datarepair/irreparabledb/irreparabledb.go
  pkg/kademlia/kademlia_test.go
  pkg/miniogw/config.go
  pkg/piecestore/psserver/psdb/psdb.go
  pkg/satellite/satellitedb/db.go
  pkg/satellite/satellitedb/dbx/gen.go
  pkg/statdb/dbx/gen.go
  pkg/statdb/statdb.go
  satellite/satellitedb/database.go
  satellite/satellitedb/dbx/gen.go
  storage/boltdb/client.go
Labels: cla-signed

#788 pstore: fix blob permissions
  pkg/piecestore/pstore.go
Labels: cla-signed

#792 capt: default to debug logs
  cmd/captplanet/setup.go
Labels: cla-signed

#787 change default encryption key to be more obviously bad
  cmd/captplanet/setup.go
Labels: cla-signed

#790 capt: clean up heavy client naming
  cmd/captplanet/setup.go
Labels: cla-signed

#802 Remove mock kademlia
  pkg/kademlia/test_utils.go
Labels: cla-signed

#775 Migrate Minio Gateway to the new Metainfo API
  cmd/uplink/cmd/cp.go
  cmd/uplink/cmd/mount.go
  pkg/metainfo/kvmetainfo/buckets_test.go
  pkg/metainfo/kvmetainfo/objects.go
  pkg/metainfo/kvmetainfo/objects_test.go
  pkg/miniogw/config.go
  pkg/miniogw/gateway-storj.go
  pkg/miniogw/gateway-storj_test.go
  pkg/miniogw/multipart.go
  pkg/storj/metainfo.go
  pkg/storj/object.go
  pkg/stream/upload.go
Labels: cla-signed

#798 Fix deadlock on testplanet shutdown
  internal/testplanet/node.go
  pkg/kademlia/kademlia.go
Labels: cla-signed

#803 Enable audit service on satellite
  cmd/satellite/main.go
Labels: cla-signed

#779 Adding CODE_OF_CONDUCT to storj/storj repo
  CODE_OF_CONDUCT.md
Labels: cla-signed

#806 Fix sqlite registration
  pkg/datarepair/irreparabledb/dbx/irreparabledb.dbx.go
  pkg/satellite/satellitedb/dbx/satellitedb.dbx.go
  satellite/satellitedb/dbx/satellitedb.dbx.go
Labels: cla-signed

#807 Fix "key not found" error on uploading files with uplink cli
  cmd/uplink/cmd/cp.go
Labels: cla-signed

#801 [WIP] get project members of current project
  pkg/satellite/satelliteweb/satelliteql/project.go
  pkg/satellite/satelliteweb/satelliteql/projectmember.go
  pkg/satellite/satelliteweb/satelliteql/typecreator.go
  pkg/satellite/service.go
Labels: cla-signed, wip

#810 Update .clabot
  .clabot
Labels: cla-signed

#808 Updating users repository
  pkg/satellite/satellitedb/dbx/satellitedb.dbx
  pkg/satellite/satellitedb/dbx/satellitedb.dbx.go
  pkg/satellite/satellitedb/users.go
  pkg/satellite/satellitedb/users_test.go
  pkg/satellite/service.go
  pkg/satellite/users.go
Labels: cla-signed

#811 Better error handling of stream.Upload.Close
  cmd/uplink/cmd/cp.go
  pkg/miniogw/gateway-storj.go
Labels: cla-signed

#812 Verify bucket exists before starting multipart upload
  pkg/miniogw/multipart.go
Labels: cla-signed

#809 Simplify testing with all supported DBs
  pkg/bwagreement/test/server_test.go
  satellite/satellitedb/database_test.go
  satellite/satellitedb/satellitedbtest/utils.go
Labels: cla-signed

#813 Improve piece retrieving log with offset and length
  pkg/piecestore/psserver/retrieve.go
Labels: cla-signed

#767 updated user updated api, separated company and user creation
  pkg/satellite/satellitedb/users.go
  pkg/satellite/satelliteweb/satelliteql/mutation.go
  pkg/satellite/satelliteweb/satelliteql/user.go
  pkg/satellite/service.go
  pkg/satellite/users.go
  pkg/satellite/validation.go
Labels: Request Code Review, cla-signed, wip

#815 V3-808 Implement graphql queries for team members page
  pkg/satellite/satelliteweb/satelliteql/project.go
  web/satellite/src/api/projectMembers.ts
  web/satellite/src/types/projects.d.ts
Labels: cla-signed

#777 Merge the irreparable DB into the master database
  pkg/datarepair/checker/checker.go
  pkg/datarepair/checker/checker_test.go
  pkg/datarepair/checker/config.go
  pkg/datarepair/irreparable/irreparable.go
  pkg/datarepair/irreparable/test/irreparable_test.go
  pkg/datarepair/irreparabledb/dbx/gen.go
  pkg/datarepair/irreparabledb/dbx/irreparabledb.dbx
  pkg/datarepair/irreparabledb/dbx/irreparabledb.dbx.go
  pkg/datarepair/irreparabledb/dbx/irreparabledb.dbx.postgres.sql
  pkg/datarepair/irreparabledb/dbx/irreparabledb.dbx.sqlite3.sql
  pkg/datarepair/irreparabledb/irreparabledb_test.go
  satellite/satellitedb/database.go
  satellite/satellitedb/dbx/satellitedb.dbx
  satellite/satellitedb/dbx/satellitedb.dbx.go
  satellite/satellitedb/dbx/satellitedb.dbx.postgres.sql
  satellite/satellitedb/dbx/satellitedb.dbx.sqlite3.sql
  satellite/satellitedb/irreparabledb.go
Labels: Request Code Review, cla-signed

#814 Run windows tests only when windows is in commit message.
  .travis.yml
Labels: cla-signed

#816 Optimize compilation memory usage
  pkg/miniogw/config.go
  pkg/miniogw/gateway.go
  pkg/miniogw/gateway_test.go
  pkg/miniogw/integration_test.go
  pkg/miniogw/logging.go
  pkg/miniogw/logging/gw_mock_test.go
  pkg/miniogw/logging/logger_mock_test.go
  pkg/miniogw/logging/logging.go
  pkg/miniogw/logging/objlayer_mock_test.go
  pkg/miniogw/objstore_mock_test.go
Labels: cla-signed

#822 Small fixes around master db
  cmd/captplanet/run.go
  cmd/satellite/main.go
  pkg/accounting/tally/tally_test.go
  pkg/bwagreement/test/server_test.go
  pkg/datarepair/checker/checker_test.go
  pkg/datarepair/irreparable/test/irreparable_test.go
  satellite/satellitedb/database.go
  satellite/satellitedb/database_test.go
  satellite/satellitedb/satellitedbtest/utils.go
Labels: cla-signed

#825 Reduce ranger test output
  pkg/ranger/content_test.go
  pkg/ranger/file_test.go
  pkg/ranger/http_test.go
  pkg/ranger/reader_test.go
  pkg/ranger/readerat_test.go
Labels: cla-signed

#817 Fix images and all-in-one
  cmd/gateway/entrypoint
  cmd/satellite/Dockerfile
  cmd/satellite/entrypoint
  docker-compose.yaml
Labels: cla-signed

#826 Skip TestUploadDownload
  pkg/miniogw/integration_test.go
Labels: Request Code Review, cla-signed

#828 Satellite graphql: take authorized user id if no id was provided in iput
  pkg/satellite/satelliteweb/satelliteql/mutation.go
  pkg/satellite/satelliteweb/satelliteql/query.go
  pkg/satellite/satelliteweb/satelliteql/utils.go
Labels: Request Code Review, cla-signed

#827 Randomize node selection during GETs
  pkg/storage/ec/client.go
  pkg/storage/ec/client_test.go
  pkg/storage/segments/store.go
  pkg/storage/segments/store_test.go
Labels: cla-signed

#835 Enable overlay by default
  pkg/pointerdb/config.go
Labels: cla-signed

#782 adds node selection config
  pkg/datarepair/repairer/config.go
  pkg/metainfo/kvmetainfo/buckets_test.go
  pkg/miniogw/config.go
  pkg/miniogw/gateway_test.go
  pkg/overlay/client.go
  pkg/storage/segments/store.go
  pkg/storage/segments/store_test.go
Labels: Request Code Review, cla-signed

#818 fix test-captplanet script for mac
  scripts/test-captplanet.sh
Labels: cla-signed

#793 Reduce number of nodes in captplanet to 10
  cmd/captplanet/run.go
  cmd/captplanet/setup.go
  cmd/storagenode/main.go
  pkg/datarepair/repairer/config.go
  pkg/kademlia/config.go
  pkg/kademlia/kademlia_test.go
  pkg/provider/certificate_authority.go
Labels: cla-signed

#785 cfgstruct.Bind: support nested config paths
  cmd/captplanet/setup.go
  pkg/cfgstruct/bind.go
  pkg/cfgstruct/bind_test.go
Labels: cla-signed

#832 [V3-593] grammar validation error in register page fixed
  web/satellite/src/views/Register.vue
Labels: cla-signed

#831 [V3-873] Error pages markup and 404 logic
  web/satellite/src/components/dashboard/newProject/NewProjectPopup.vue
  web/satellite/src/components/dashboard/projectSelection/ProjectSelectionDropdown.vue
  web/satellite/src/components/errors/Page404.vue
  web/satellite/src/components/errors/Page50X.vue
  web/satellite/src/router/index.ts
  web/satellite/static/images/team/404.svg
  web/satellite/static/images/team/50X.svg
Labels: cla-signed

#751 added tally to capt run.go
  cmd/captplanet/run.go
  cmd/overlay/cache.go
  pkg/accounting/db.go
  pkg/accounting/rollup/config.go
  pkg/accounting/tally/config.go
  pkg/accounting/tally/tally.go
  pkg/overlay/config.go
  pkg/overlay/config_test.go
  pkg/pointerdb/config.go
  pkg/satellite/satellitedb/db.go
  pkg/satellite/satelliteweb/config.go
  pkg/statdb/statdb.go
  pkg/statdb/statdb_test.go
  pkg/utils/utils.go
  satellite/satellitedb/database.go
  satellite/satellitedb/irreparabledb.go
  storage/redis/client.go
Labels: cla-signed, wip

#829 [V3-895] Satellite notification logic
  web/satellite/src/App.vue
  web/satellite/src/components/notifications/Notification.vue
  web/satellite/src/components/notifications/NotificationArea.vue
  web/satellite/src/store/index.ts
  web/satellite/src/store/modules/notifications.ts
  web/satellite/src/store/mutationConstants.ts
  web/satellite/src/utils/constants/notification.ts
  web/satellite/src/utils/entities/DelayedNotification.ts
  web/satellite/src/utils/idGenerator.ts
  web/satellite/tests/unit/notifications/Notification.spec.ts
  web/satellite/tests/unit/notifications/NotificationArea.spec.ts
  web/satellite/tests/unit/notifications/__snapshots__/Notification.spec.ts.snap
  web/satellite/tests/unit/notifications/__snapshots__/NotificationArea.spec.ts.snap
Labels: cla-signed

#834 Faster tests
  pkg/encryption/crc_test.go
  pkg/encryption/transform_test.go
  pkg/kademlia/lookup_test.go
Labels: Request Code Review, cla-signed

#839 datarepair: remove unneeded debug message
  cmd/overlay/cache.go
  pkg/datarepair/checker/checker.go
  pkg/datarepair/irreparable/irreparable_test.go
  pkg/datarepair/queue/queue_test.go
  pkg/kademlia/routing_helpers_test.go
  pkg/pointerdb/config.go
Labels: Request Code Review, cla-signed

#841 Clean up node tests
  internal/testplanet/node.go
  internal/testplanet/planet.go
  pkg/dht/mocks/mock_dht.go
  pkg/kademlia/config.go
  pkg/kademlia/kademlia.go
  pkg/kademlia/kademlia_test.go
  pkg/node/connection_pool_test.go
  pkg/node/node.go
  pkg/node/node_test.go
  pkg/node/server.go
  pkg/node/server_test.go
  pkg/pb/utils.go
Labels: cla-signed

#842 [V3-874] Satellite team logic implementation
  web/satellite/src/api/projectMembers.ts
  web/satellite/src/components/dashboard/projectSelection/ProjectSelectionArea.vue
  web/satellite/src/components/team/TeamArea.vue
  web/satellite/src/components/team/TeamMemberItem.vue
  web/satellite/src/components/team/footerArea/DeleteUserArea.vue
  web/satellite/src/router/index.ts
  web/satellite/src/store/index.ts
  web/satellite/src/store/modules/projectMembers.ts
  web/satellite/src/store/modules/projects.ts
  web/satellite/src/store/mutationConstants.ts
  web/satellite/src/types/projects.d.ts
Labels: cla-signed

#843 wait captplanet startup before trying to upload
  scripts/test-captplanet.sh
Labels: cla-signed

#819 Cut off piecestore Puts if they exceed alloced bandwidth/space
  pkg/piecestore/psserver/readerwriter.go
  pkg/piecestore/psserver/readerwriter_test.go
  pkg/piecestore/psserver/server.go
  pkg/piecestore/psserver/server_test.go
  pkg/piecestore/psserver/store.go
Labels: Request Code Review, cla-signed

#844 Enable -race in captplanet tests
  .travis.yml
Labels: cla-signed

#838 Data repairer should use the redundancy strategy from segment's pointer
  pkg/datarepair/repairer/config.go
  pkg/datarepair/repairer/repairer.go
  pkg/datarepair/repairer/repairer_test.go
  pkg/storage/segments/repairer.go
  pkg/storage/segments/repairer_test.go
  pkg/storage/segments/store.go
  pkg/storage/segments/store_test.go
Labels: cla-signed

#850 [V3-349] markup for delete account dialog
  web/satellite/src/components/dashboard/account/AccountArea.vue
  web/satellite/src/components/dashboard/account/DeleteAccontPopup.vue
  web/satellite/src/utils/constants/emptyStatesImages.ts
  web/satellite/tests/unit/notifications/NotificationArea.spec.ts
Labels: cla-signed

#837 Remove utils.LogClose from identity saving
  internal/testplanet/gen_identities.go
  pkg/provider/certificate_authority.go
  pkg/provider/identity.go
  pkg/provider/utils.go
Labels: Request Code Review, cla-signed

#851 Fix ConfNested on Windows
  pkg/cfgstruct/bind_test.go
Labels: cla-signed

#853 Update monkit-hw to not poll /proc on non-linux
  go.mod
  go.sum
Labels: Request Code Review, cla-signed

#855 pdbinspect time format fix
  cmd/pdbinspect/main.go
Labels: cla-signed

#836 Certificate revocation
  Makefile
  cmd/captplanet/setup.go
  go.mod
  go.sum
  internal/testpeertls/certificates.go
  pkg/peertls/extensions.go
  pkg/peertls/peertls.go
  pkg/peertls/peertls_test.go
  pkg/peertls/utils.go
  pkg/provider/certificate_authority.go
  pkg/provider/identity.go
  pkg/provider/identity_test.go
  pkg/satellite/satelliteweb/satelliteql/query.go
  scripts/test-captplanet.sh
Labels: Request Code Review, cla-signed

#857 Inspector port
  cmd/inspector/main.go
Labels: cla-signed

#858 fixed revocation db setup in capt
  cmd/captplanet/setup.go
Labels: cla-signed

#849 Better transport tests
  cmd/satellite/Dockerfile
  cmd/satellite/entrypoint
  pkg/transport/transport_test.go
Labels: Request Code Review, cla-signed

#864 Parameters cleanup
  pkg/bwagreement/config.go
  pkg/datarepair/checker/config.go
  pkg/piecestore/psclient/client.go
  pkg/piecestore/psserver/agreementsender/agreementsender.go
  pkg/piecestore/psserver/psdb/psdb.go
  pkg/process/metrics.go
Labels: cla-signed

#863 Add gen.go for protobuf
  pkg/pb/gen.go
Labels: cla-signed

#852 satellite user delete updated to require user password
  pkg/satellite/satelliteweb/satelliteql/mutation.go
  pkg/satellite/service.go
Labels: cla-signed

#805 Discovery service
  cmd/captplanet/run.go
  cmd/satellite/main.go
  internal/testplanet/node.go
  internal/testplanet/planet.go
  pkg/discovery/config.go
  pkg/discovery/server.go
  pkg/discovery/service.go
  pkg/discovery/service_test.go
  pkg/overlay/cache.go
  pkg/overlay/cache_test.go
  pkg/overlay/config.go
  pkg/pb/discovery.pb.go
  pkg/pb/discovery.proto
  scripts/test-captplanet.sh
Labels: Request Code Review, cla-signed, proposal

#830 Statdb master db v3 848
  cmd/captplanet/run.go
  cmd/overlay/cache.go
  cmd/overlay/main.go
  cmd/satellite/main.go
  internal/testplanet/node.go
  pkg/audit/reporter.go
  pkg/audit/verifier.go
  pkg/datarepair/checker/checker.go
  pkg/datarepair/checker/checker_test.go
  pkg/datarepair/checker/config.go
  pkg/discovery/config.go
  pkg/discovery/service.go
  pkg/inspector/config.go
  pkg/inspector/server.go
  pkg/overlay/cache.go
  pkg/overlay/cache_test.go
  pkg/overlay/config.go
  pkg/overlay/config_test.go
  pkg/pb/bandwidth.pb.go
  pkg/pb/datarepair.pb.go
  pkg/pb/inspector.pb.go
  pkg/pb/meta.pb.go
  pkg/pb/node.pb.go
  pkg/pb/overlay.pb.go
  pkg/pb/piecestore.pb.go
  pkg/pb/pointerdb.pb.go
  pkg/pb/streams.pb.go
  pkg/pb/utils.go
  pkg/statdb/config.go
  pkg/statdb/dbx/gen.go
  pkg/statdb/dbx/statdb.dbx
  pkg/statdb/dbx/statdb.dbx.go
  pkg/statdb/dbx/statdb.dbx.postgres.sql
  pkg/statdb/dbx/statdb.dbx.sqlite3.sql
  pkg/statdb/proto/gen.go
  pkg/statdb/proto/statdb.pb.go
  pkg/statdb/proto/statdb.proto
  pkg/statdb/statdb.go
  pkg/statdb/statdb_test.go
  pkg/statdb/test/statdb_test.go
  satellite/satellitedb/database.go
  satellite/satellitedb/dbx/gen.go
  satellite/satellitedb/dbx/satellitedb.dbx
  satellite/satellitedb/dbx/satellitedb.dbx.go
  satellite/satellitedb/dbx/satellitedb.dbx.postgres.sql
  satellite/satellitedb/dbx/satellitedb.dbx.sqlite3.sql
  satellite/satellitedb/statdb.go
Labels: Code Review In-Progress, cla-signed

#870 fix `defaultConfDir` initialization
  cmd/captplanet/main.go
Labels: Request Code Review, cla-signed

#866 RevocationDB fixes
  cmd/captplanet/setup.go
  pkg/peertls/extensions.go
  pkg/provider/identity.go
  scripts/test-captplanet.sh
Labels: Request Code Review, cla-signed

#833 Add '--dir' param for all CLI parts (replace --base-path)
  cmd/captplanet/main.go
  cmd/captplanet/setup.go
  cmd/satellite/main.go
  cmd/storagenode/main.go
  cmd/uplink/cmd/root.go
  cmd/uplink/cmd/setup.go
  pkg/cfgstruct/bind.go
  pkg/process/exec_conf.go
Labels: Request Code Review, cla-signed

#878 Update go.sum
  go.mod
  go.sum
Labels: cla-signed

#869 Upgrade hrtime package
  go.mod
  go.sum
Labels: Request Code Review, cla-signed

#862 Simplify provider tests
  internal/testplanet/identities.go
  internal/testplanet/planet.go
  pkg/peertls/peertls.go
  pkg/provider/cert_authority_test.go
  pkg/provider/identity.go
  pkg/provider/identity_test.go
  pkg/storj/node_test.go
Labels: Request Code Review, cla-signed

#856 Add logger to piecestore server/node started log
  internal/testplanet/planet.go
  pkg/piecestore/psserver/retrieve.go
  pkg/piecestore/psserver/server.go
  pkg/piecestore/psserver/server_test.go
  pkg/piecestore/psserver/store.go
Labels: cla-signed

#854 Default config for storagenode binary to join captplanet
  cmd/storagenode/main.go
Labels: cla-signed

#879 unify logging messages
  cmd/captplanet/run.go
Labels: cla-signed

#860 adds discovery function to overlay for random lookups
  pkg/discovery/config.go
  pkg/discovery/service.go
Labels: Request Code Review, cla-signed

#876 Payments API protobuf definition
  pkg/pb/payments.pb.go
  pkg/pb/payments.proto
Labels: cla-signed

#867 removes a few todos
  go.sum
  pkg/accounting/tally/tally.go
  pkg/pb/pointerdb.proto
  pkg/ranger/content_test.go
Labels: cla-signed

#881 Flatten statdb test directory
  pkg/statdb/statdb_test.go
Labels: cla-signed

#880 Overlay error handling
  pkg/overlay/cache.go
  pkg/overlay/cache_test.go
  pkg/overlay/client_test.go
  pkg/storj/node.go
Labels: cla-signed

#888 Fix irreparable db transaction usage
  satellite/satellitedb/irreparabledb.go
Labels: cla-signed

#877 Overlay Cache master db merge
  pkg/overlay/cache_test.go
  pkg/overlay/config.go
  pkg/overlay/config_test.go
  satellite/satellitedb/database.go
  satellite/satellitedb/dbx/gen.go
  satellite/satellitedb/dbx/satellitedb.dbx
  satellite/satellitedb/dbx/satellitedb.dbx.go
  satellite/satellitedb/dbx/satellitedb.dbx.postgres.sql
  satellite/satellitedb/dbx/satellitedb.dbx.sqlite3.sql
  satellite/satellitedb/overlaycache.go
Labels: cla-signed

#892 set TTL to 0
  storage/redis/client.go
Labels: cla-signed

#893 Limit Jenkins builds
  Jenkinsfile
Labels: cla-signed

#891 moves node selection config setup from uplink to satellite
  internal/testplanet/planet.go
  pkg/datarepair/repairer/config.go
  pkg/metainfo/kvmetainfo/buckets_test.go
  pkg/miniogw/config.go
  pkg/miniogw/gateway_test.go
  pkg/overlay/client.go
  pkg/overlay/config.go
  pkg/overlay/server.go
  pkg/overlay/server_test.go
  pkg/storage/segments/repairer.go
  pkg/storage/segments/repairer_test.go
  pkg/storage/segments/store.go
  pkg/storage/segments/store_test.go
Labels: Request Code Review, cla-signed

#848 Cert revocation CLI
  cmd/identity/certificate_authority.go
  cmd/identity/identity.go
  cmd/identity/main.go
  pkg/peertls/extensions.go
  pkg/peertls/peertls.go
  pkg/peertls/peertls_test.go
  pkg/peertls/utils.go
  pkg/provider/cert_authority_test.go
  pkg/provider/certificate_authority.go
  pkg/provider/identity.go
  pkg/provider/utils.go
Labels: Request Code Review, cla-signed

#899 Use fixed logger for Kademlia and make not being able to connect in discovery debug statement.
  internal/testplanet/node.go
  pkg/kademlia/config.go
  pkg/kademlia/kademlia.go
  pkg/kademlia/kademlia_test.go
  pkg/kademlia/peer_discovery.go
Labels: cla-signed

#874 Updates accounting tables and allows tally to update at raw table for at rest data
  pkg/accounting/common.go
  pkg/accounting/db.go
  pkg/accounting/tally/tally.go
  pkg/accounting/tally/tally_test.go
  satellite/satellitedb/accounting.go
  satellite/satellitedb/dbx/satellitedb.dbx
  satellite/satellitedb/dbx/satellitedb.dbx.go
  satellite/satellitedb/dbx/satellitedb.dbx.postgres.sql
  satellite/satellitedb/dbx/satellitedb.dbx.sqlite3.sql
Labels: cla-signed

#897 Validate farmers wallet and email configuration
  cmd/storagenode/main.go
Labels: cla-signed

#884 updated project and user deletion
  pkg/satellite/service.go
Labels: cla-signed

#898 KBucket clean up. V3-923
  pkg/dht/dht.go
  pkg/inspector/server.go
  pkg/kademlia/bucket.go
  pkg/kademlia/bucket_test.go
  pkg/kademlia/routing.go
  pkg/kademlia/routing_test.go
Labels: Request Code Review, cla-signed

#902 Do not error if Discovery can not find Node
  pkg/discovery/service.go
Labels: cla-signed

#895 Fix overlay commands after master db merge
  cmd/overlay/cache.go
  cmd/overlay/main.go
  satellite/satellitedb/dbx/satellitedb.dbx
  satellite/satellitedb/dbx/satellitedb.dbx.go
  satellite/satellitedb/overlaycache.go
Labels: cla-signed

#907 satellite project members pagination api
  pkg/satellite/projectmembers.go
  pkg/satellite/satellitedb/projectmembers.go
  pkg/satellite/satellitedb/projectmembers_test.go
  pkg/satellite/satelliteweb/satelliteql/project.go
  pkg/satellite/service.go
Labels: cla-signed

#887 Refactor statdb
  pkg/audit/reporter.go
  pkg/audit/service.go
  pkg/audit/verifier.go
  pkg/audit/verifier_test.go
  pkg/datarepair/checker/checker.go
  pkg/inspector/server.go
  pkg/overlay/cache.go
  pkg/statdb/statdb.go
  pkg/statdb/statdb_test.go
  satellite/satellitedb/statdb.go
Labels: Request Code Review, cla-signed

#911 Statdb transactions
  satellite/satellitedb/statdb.go
Labels: Request Code Review, cla-signed

#912 Upgrade errs package
  go.mod
  go.sum
Labels: cla-signed

#914 Cleanup overlay methods and names.
  cmd/overlay/cache.go
  cmd/overlay/main.go
  internal/testplanet/node.go
  internal/testplanet/planet.go
  pkg/audit/cursor_test.go
  pkg/audit/service.go
  pkg/datarepair/repairer/config.go
  pkg/inspector/server.go
  pkg/miniogw/config.go
  pkg/overlay/cache.go
  pkg/overlay/cache_test.go
  pkg/overlay/client.go
  pkg/overlay/client_test.go
  pkg/overlay/config.go
  pkg/overlay/config_test.go
  pkg/overlay/server.go
  pkg/overlay/server_test.go
  pkg/piecestore/psserver/agreementsender/agreementsender.go
Labels: Request Code Review, cla-signed

#894 Implement memory and file pipe
  internal/sync2/io.go
  internal/sync2/limiter_test.go
  internal/sync2/pipe.go
  internal/sync2/pipe_test.go
  internal/sync2/throttle_test.go
Labels: Request Code Review, cla-signed

#916 delete and add projectmember api now accepts list of users
  pkg/satellite/satelliteweb/satelliteql/mutation.go
Labels: cla-signed

#917 Removing company and project ownership
  pkg/satellite/companies.go
  pkg/satellite/database.go
  pkg/satellite/projects.go
  pkg/satellite/satellitedb/companies.go
  pkg/satellite/satellitedb/companies_test.go
  pkg/satellite/satellitedb/db.go
  pkg/satellite/satellitedb/dbx/satellitedb.dbx
  pkg/satellite/satellitedb/dbx/satellitedb.dbx.go
  pkg/satellite/satellitedb/dbx/satellitedb.dbx.sqlite3.sql
  pkg/satellite/satellitedb/projectmembers_test.go
  pkg/satellite/satellitedb/projects.go
  pkg/satellite/satellitedb/projects_test.go
  pkg/satellite/satelliteweb/satelliteql/company.go
  pkg/satellite/satelliteweb/satelliteql/mutation.go
  pkg/satellite/satelliteweb/satelliteql/project.go
  pkg/satellite/satelliteweb/satelliteql/typecreator.go
  pkg/satellite/satelliteweb/satelliteql/user.go
  pkg/satellite/service.go
  web/satellite/src/api/projectMembers.ts
  web/satellite/src/api/projects.ts
  web/satellite/src/api/users.ts
  web/satellite/src/components/dashboard/account/AccountArea.vue
  web/satellite/src/components/dashboard/newProject/NewProjectPopup.vue
  web/satellite/src/components/dashboard/projectSelection/ProjectSelectionArea.vue
  web/satellite/src/components/projectDetails/ProjectDetailsArea.vue
  web/satellite/src/store/modules/projectMembers.ts
  web/satellite/src/store/modules/projects.ts
  web/satellite/src/store/modules/users.ts
  web/satellite/src/store/mutationConstants.ts
  web/satellite/src/types/projects.d.ts
  web/satellite/src/types/register.d.ts
  web/satellite/src/types/users.d.ts
  web/satellite/src/utils/tokenManager.ts
  web/satellite/src/views/Dashboard.vue
  web/satellite/src/views/Login.vue
  web/satellite/src/views/Register.vue
Labels: cla-signed

#910 [V3-956] Satellite delete account dialog logic
  web/satellite/src/api/users.ts
  web/satellite/src/components/dashboard/DashboardHeader.vue
  web/satellite/src/components/dashboard/account/AccountArea.vue
  web/satellite/src/components/dashboard/account/DeleteAccountPopup.vue
  web/satellite/src/components/notifications/NotificationArea.vue
  web/satellite/src/utils/constants/emptyStatesImages.ts
  web/satellite/src/utils/entities/DelayedNotification.ts
Labels: cla-signed

#918 [V3-959] implemented delete project dialog
  web/satellite/src/components/common/HeaderedInput.vue
  web/satellite/src/components/projectDetails/DeleteProjectPopup.vue
  web/satellite/src/components/projectDetails/ProjectDetailsArea.vue
  web/satellite/src/utils/constants/emptyStatesImages.ts
Labels: cla-signed

#903 add monkit to Satellite DB Service
  pkg/satellite/service.go
Labels: cla-signed

#908 Add the ability for Kademlia to do a refresh for each bucket
  internal/testplanet/planet.go
  pkg/dht/dht.go
  pkg/discovery/service.go
  pkg/kademlia/config.go
  pkg/kademlia/kademlia.go
  pkg/kademlia/kademlia_test.go
  pkg/kademlia/peer_discovery.go
  pkg/kademlia/routing.go
  pkg/kademlia/routing_helpers.go
  pkg/kademlia/routing_test.go
  pkg/node/node.go
Labels: cla-signed

#923 Use errs.Combine in storage
  storage/boltdb/client.go
  storage/boltdb/client_test.go
  storage/filestore/dir.go
  storage/filestore/store.go
  storage/postgreskv/alternateclient.go
  storage/postgreskv/client.go
  storage/postgreskv/client_test.go
  storage/testsuite/long_bench.go
Labels: Request Code Review, cla-signed

#927 Add sleep for satellite startup
  cmd/captplanet/run.go
Labels: Request Code Review, cla-signed

#865 repair queue masterDB support
  cmd/satellite/main.go
  pkg/datarepair/checker/checker.go
  pkg/datarepair/checker/config.go
  pkg/datarepair/queue/queue_test.go
  pkg/datarepair/repairer/config.go
  satellite/satellitedb/database.go
  satellite/satellitedb/dbx/satellitedb.dbx
  satellite/satellitedb/dbx/satellitedb.dbx.go
  satellite/satellitedb/dbx/satellitedb.dbx.postgres.sql
  satellite/satellitedb/dbx/satellitedb.dbx.sqlite3.sql
  satellite/satellitedb/repairqueue.go
Labels: cla-signed, wip

#928 Satellite add/delete project members by email api
  pkg/satellite/satelliteweb/satelliteql/mutation.go
  pkg/satellite/satelliteweb/satelliteql/user.go
  pkg/satellite/service.go
Labels: Request Code Review, cla-signed

#929 Fix detection of existing config in docker images
  cmd/gateway/Dockerfile
  cmd/gateway/entrypoint
  cmd/satellite/Dockerfile
  cmd/satellite/entrypoint
  cmd/storagenode/Dockerfile
  cmd/storagenode/entrypoint
  cmd/uplink/Dockerfile
  cmd/uplink/entrypoint
Labels: Request Code Review, cla-signed

#921 adds delete functions and tests for cache
  pkg/overlay/cache.go
  pkg/overlay/cache_test.go
Labels: cla-signed

#922 Adds a logger to RoutingTable
  internal/testplanet/node.go
  pkg/discovery/config.go
  pkg/discovery/service.go
  pkg/kademlia/kademlia.go
  pkg/kademlia/routing.go
Labels: cla-signed

#920 Node lifecycle hooks
  internal/testplanet/node.go
  pkg/discovery/config.go
  pkg/discovery/lifecycle.go
  pkg/discovery/service.go
  pkg/kademlia/kademlia.go
  pkg/kademlia/routing.go
  pkg/node/client.go
  pkg/node/connection_pool.go
  pkg/overlay/cache.go
  pkg/overlay/client.go
  pkg/transport/transport.go
Labels: Request Code Review, cla-signed

#934 web/satellite notifications added, users and projects api updated
  pkg/satellite/satelliteweb/satelliteql/mutation.go
  pkg/satellite/service.go
  web/satellite/src/api/projects.ts
  web/satellite/src/api/users.ts
  web/satellite/src/components/dashboard/account/AccountArea.vue
  web/satellite/src/components/dashboard/account/DeleteAccontPopup.vue
  web/satellite/src/components/dashboard/account/DeleteAccountPopup.vue
  web/satellite/src/components/dashboard/newProject/NewProjectPopup.vue
  web/satellite/src/components/dashboard/projectSelection/ProjectSelectionArea.vue
  web/satellite/src/components/dashboard/projectSelection/ProjectSelectionDropdown.vue
  web/satellite/src/components/projectDetails/DeleteProjectPopup.vue
  web/satellite/src/components/projectDetails/ProjectDetailsArea.vue
  web/satellite/src/store/modules/projects.ts
  web/satellite/src/store/modules/users.ts
  web/satellite/src/types/response.d.ts
  web/satellite/src/types/users.d.ts
  web/satellite/src/views/Dashboard.vue
  web/satellite/src/views/Login.vue
  web/satellite/src/views/Register.vue
Labels: Request Code Review, cla-signed

#931 Satellite api keys repo and service method added
  pkg/satellite/apikeys.go
  pkg/satellite/database.go
  pkg/satellite/satellitedb/apikeys.go
  pkg/satellite/satellitedb/db.go
  pkg/satellite/satellitedb/dbx/satellitedb.dbx
  pkg/satellite/satellitedb/dbx/satellitedb.dbx.go
  pkg/satellite/satellitedb/dbx/satellitedb.dbx.sqlite3.sql
  pkg/satellite/service.go
Labels: Request Code Review, cla-signed

#935 [V3-963] Satellite team members add dialog
  pkg/satellite/satelliteweb/satelliteql/mutation.go
  web/satellite/src/api/projectMembers.ts
  web/satellite/src/api/users.ts
  web/satellite/src/components/dashboard/AddUserPopup.vue
  web/satellite/src/components/dashboard/projectSelection/ProjectSelectionDropdown.vue
  web/satellite/src/components/navigation/NavigationArea.vue
  web/satellite/src/components/projectDetails/ProjectDetailsArea.vue
  web/satellite/src/components/team/TeamArea.vue
  web/satellite/src/components/team/footerArea/DeleteUserArea.vue
  web/satellite/src/components/team/headerArea/HeaderArea.vue
  web/satellite/src/store/index.ts
  web/satellite/src/store/modules/appState.ts
  web/satellite/src/store/modules/projectMembers.ts
  web/satellite/src/store/mutationConstants.ts
  web/satellite/src/utils/entities/EmailInput.ts
  web/satellite/src/utils/validation.ts
Labels: cla-signed

#938 Fix ignored config logger settings
  pkg/process/exec_conf.go
Labels: cla-signed

#932 Implement mutex around satellitedb
  cmd/satellite/main.go
  internal/testplanet/node.go
  pkg/accounting/tally/tally.go
  pkg/accounting/tally/tally_test.go
  pkg/bwagreement/test/server_test.go
  pkg/datarepair/checker/checker.go
  pkg/datarepair/checker/checker_test.go
  pkg/datarepair/irreparable/irreparable_test.go
  pkg/datarepair/queue/queue.go
  pkg/datarepair/queue/queue_test.go
  pkg/datarepair/repairer/repairer.go
  pkg/overlay/cache_test.go
  pkg/statdb/statdb_test.go
  satellite/db.go
  satellite/satellitedb/database.go
  satellite/satellitedb/database_test.go
  satellite/satellitedb/dbx/satellitedb.dbx
  satellite/satellitedb/dbx/satellitedb.dbx.go
  satellite/satellitedb/dbx/satellitedb.dbx.postgres.sql
  satellite/satellitedb/dbx/satellitedb.dbx.sqlite3.sql
  satellite/satellitedb/mutex.go
  satellite/satellitedb/overlaycache.go
  satellite/satellitedb/repairqueue.go
  satellite/satellitedb/satellitedbtest/utils.go
Labels: Request Code Review, cla-signed

#937 [V3-911] fixed registration mandatory fields validation
  web/satellite/src/types/register.d.ts
  web/satellite/src/utils/validation.ts
  web/satellite/src/views/Register.vue
Labels: cla-signed
