Repository storj/storj, pull requests merged in 2018-10, with the labels that each got.

#402 cmd/s3-benchmark: add exit error information
  cmd/s3-benchmark/awscli.go
Labels: cla-signed

#403 add missing copyright headers
  cmd/s3-benchmark/awscli.go
  cmd/s3-benchmark/minio.go
  cmd/s3-benchmark/plot.go
  internal/memory/size_test.go
  internal/memory/sizes.go
  internal/memory/string.go
  storage/blob.go
Labels: cla-signed

#373 Streams Store mock test
  pkg/storage/segments/mock_store.go
  pkg/storage/streams/store_test.go
Labels: cla-signed, wip

#410 examples: piecestore-client, use cobra directly
  examples/piecestore-client/main.go
  examples/piecestore-client/rpc/client/main.go
Labels: cla-signed

#409 examples: piecestore-cli use cobra directly
  examples/piecestore-cli/main.go
Labels: cla-signed

#378 setup repairer loop
  cmd/satellite/main.go
  pkg/datarepair/checker/checker.go
  pkg/datarepair/checker/checker_test.go
  pkg/datarepair/repair.go
  pkg/datarepair/repairer/repairer.go
  pkg/datarepair/repairer/repairer_test.go
Labels: cla-signed

#411 Little-endian incrementBytes
  pkg/eestream/bits.go
  pkg/eestream/bits_test.go
Labels: cla-signed

#415 remove urfave/cli from dependencies
  go.mod
  go.sum
Labels: cla-signed

#405 examples: turn paths binary to Go documentation example
  examples/paths/main.go
  go.mod
  go.sum
  pkg/paths/examples_test.go
Labels: cla-signed

#416 captplanet: add ctrl+\ for dumping goroutines
  .gitignore
  cmd/captplanet/main.go
Labels: cla-signed

#417 Fix check for pending readers in StripeReader
  pkg/eestream/stripe.go
Labels: cla-signed

#408 Clean up last segment handling
  pkg/eestream/aesgcm.go
  pkg/eestream/encryption.go
  pkg/pb/meta.pb.go
  pkg/pb/meta.proto
  pkg/storage/segments/mock_store.go
  pkg/storage/segments/store.go
  pkg/storage/segments/store_test.go
  pkg/storage/streams/store.go
  pkg/storage/streams/store_test.go
Labels: backward incompatible, cla-signed

#418 Remove multipart threshold config for AWS CLI
  README.md
Labels: cla-signed

#419 Reorganize repair
  cmd/satellite/main.go
  pkg/datarepair/checker/checker.go
  pkg/datarepair/queue/queue.go
  pkg/datarepair/repair.go
  pkg/datarepair/repairer/repairer.go
Labels: Code Review In-Progress, cla-signed

#404 examples: remove udp forwarder
  examples/udp-forwarder/forwarder.go
Labels: cla-signed

#414 uplink: encryption key setup
  cmd/uplink/cmd/run.go
  cmd/uplink/cmd/setup.go
Labels: cla-signed

#381 Handle CTRL+C and clean up the partial segments and pieces
  cmd/uplink/cmd/cp.go
  pkg/process/exec_conf.go
  pkg/storage/ec/client.go
  pkg/storage/streams/store.go
Labels: Code Review In-Progress, cla-signed

#407 Pointer lookup
  cmd/satellite/main.go
  go.mod
  go.sum
  pkg/overlay/config.go
  pkg/pb/pointerdb.pb.go
  pkg/pb/pointerdb.proto
  pkg/pointerdb/config.go
  pkg/pointerdb/pdbclient/client.go
  pkg/pointerdb/pdbclient/client_test.go
  pkg/pointerdb/pointerdb.go
  pkg/pointerdb/pointerdb_test.go
  pkg/statdb/proto/statdb.pb.go
Labels: cla-signed

#420 Repair cron
  cmd/captplanet/run.go
  cmd/satellite/main.go
  pkg/datarepair/checker/checker.go
Labels: cla-signed

#375 Stripe selection
  go.sum
  pkg/pointerdb/audit/audit_segment.go
  pkg/pointerdb/audit/audit_segment_test.go
  pkg/pointerdb/audit/common.go
  pkg/pointerdb/pdbclient/client.go
Labels: Code Review In-Progress, Request Code Review, cla-signed

#427 Repairer points to redis server
  cmd/captplanet/run.go
  cmd/satellite/main.go
  pkg/datarepair/checker/checker.go
  pkg/datarepair/queue/queue.go
  pkg/datarepair/repairer/repairer.go
  storage/redis/client.go
Labels: cla-signed

#432 Restore go.sum
  go.sum
Labels: cla-signed

#294 Remove BKAD dependency from pkg/kademlia
  .gitignore
  cmd/captplanet/run.go
  cmd/satellite/main.go
  db/.keep
  internal/pkg/node/mocknode.go
  internal/test/utils.go
  pkg/kademlia/config.go
  pkg/kademlia/db/.keep
  pkg/kademlia/kademlia.go
  pkg/kademlia/kademlia_test.go
  pkg/kademlia/node_id.go
  pkg/kademlia/queue.go
  pkg/kademlia/queue_test.go
  pkg/kademlia/routing.go
  pkg/kademlia/routing_helpers.go
  pkg/kademlia/routing_test.go
  pkg/kademlia/workers.go
  pkg/kademlia/workers_test.go
  pkg/node/client.go
  pkg/node/id.go
  pkg/node/id_test.go
  pkg/node/node.go
  pkg/node/node_test.go
  pkg/node/server.go
  pkg/node/server_test.go
  pkg/overlay/cache.go
  pkg/overlay/cache_test.go
  pkg/overlay/client_test.go
  pkg/overlay/mocks/mock_client.go
  pkg/overlay/mocks/overlay.go
  pkg/overlay/overlay_test.go
  pkg/overlay/utils_test.go
  pkg/pb/meta.pb.go
  pkg/pb/overlay.pb.go
  pkg/pb/overlay.proto
  pkg/pb/piecestore.pb.go
  pkg/pb/pointerdb.pb.go
  pkg/piecestore/rpc/client/pieceid_test.go
  pkg/pointerdb/pdbclient/client.go
  pkg/pointerdb/pointerdb.go
  pkg/pool/connection_pool.go
  pkg/pool/connection_pool_test.go
  pkg/provider/identity.go
  pkg/statdb/proto/statdb.pb.go
  pkg/storage/segments/store.go
  scripts/check-for-header.sh
Labels: cla-signed

#438 Improve deployment
  Makefile
  scripts/deploy.staging.sh
Labels: cla-signed

#441 captplanet: api and encryption key setup
  cmd/captplanet/setup.go
Labels: cla-signed

#436 Rename MinInlineSegmentSize to MinRemoteSegmentSize
  pkg/pointerdb/config.go
  pkg/pointerdb/pointerdb.go
Labels: cla-signed

#439 create db directory if it does not exist
  pkg/kademlia/config.go
  pkg/kademlia/db/.keep
  pkg/kademlia/kademlia.go
  pkg/kademlia/kademlia_test.go
  pkg/overlay/cache_test.go
Labels: cla-signed

#396 Add StatDB to Satellite
  cmd/satellite/main.go
  cmd/statdb/README.md
  cmd/statdb/main.go
  examples/statdb-client/main.go
  pkg/statdb/config.go
  pkg/statdb/sdbclient/client.go
  pkg/statdb/sdbclient/common.go
  pkg/statdb/service.go
  pkg/statdb/statdb.go
  pkg/statdb/statdb_test.go
Labels: cla-signed

#435 Reduce garbage errors in captplanet when streaming
  pkg/provider/provider.go
Labels: cla-signed

#442 Include GCC Hint for Windows
  README.md
Labels: cla-signed

#445 Don't override file if remote file doesn't exist
  cmd/uplink/cmd/cp.go
Labels: cla-signed

#383 Use context to propagate API Key
  cmd/captplanet/run.go
  cmd/satellite/main.go
  cmd/storagenode/main.go
  examples/pointerdb-client/main.go
  pkg/auth/apikey.go
  pkg/auth/grpcauth/authentication.go
  pkg/auth/grpcauth/authentication_test.go
  pkg/miniogw/config.go
  pkg/pb/pointerdb.pb.go
  pkg/pb/pointerdb.proto
  pkg/pointerdb/audit/audit_segment_test.go
  pkg/pointerdb/pdbclient/client.go
  pkg/pointerdb/pdbclient/client_test.go
  pkg/pointerdb/pointerdb.go
  pkg/pointerdb/pointerdb_test.go
  pkg/provider/identity.go
  pkg/provider/provider.go
Labels: cla-signed

#398 Method to identify injured segments to repair
  big-upload-testfile
  pkg/datarepair/checker/checker.go
  pkg/datarepair/checker/checker_test.go
  pkg/datarepair/checker/common.go
  pkg/datarepair/queue/common.go
  pkg/datarepair/queue/queue.go
  pkg/datarepair/queue/queue_test.go
  pkg/datarepair/repairer/common.go
  pkg/datarepair/repairer/repairer.go
  pkg/overlay/server.go
  pkg/pb/datarepair.pb.go
  pkg/pb/pointerdb.pb.go
  pkg/pb/pointerdb.proto
  pkg/pointerdb/pointerdb.go
  small-upload-testfile
Labels: cla-signed

#443 Kad flags
  pkg/kademlia/config.go
  pkg/kademlia/kademlia.go
  pkg/kademlia/kademlia_test.go
  pkg/overlay/cache_test.go
Labels: cla-signed

#380 audits stripes
  pkg/audit/audit.go
  pkg/audit/audit_test.go
  pkg/audit/common.go
Labels: cla-signed

#449 moves all audit files to pkg/audit
  pkg/audit/audit_segment.go
  pkg/audit/audit_segment_test.go
  pkg/audit/audit_stripe.go
  pkg/audit/audit_stripe_test.go
  pkg/pointerdb/audit/common.go
Labels: cla-signed

#434 metainfo database: add interfaces and types
  pkg/storj/encryption.go
  pkg/storj/metainfo.go
  pkg/storj/node.go
  pkg/storj/object.go
  pkg/storj/path.go
  pkg/storj/redundancy.go
Labels: cla-signed

#452 Remove unneeded constants
  pkg/audit/audit_segment_test.go
Labels: cla-signed

#430 Tracking bandwidth v3-446
  pkg/piecestore/rpc/server/psdb/psdb.go
  pkg/piecestore/rpc/server/psdb/psdb_test.go
  pkg/piecestore/rpc/server/retrieve.go
  pkg/piecestore/rpc/server/store.go
Labels: Code Review In-Progress, cla-signed, wip

#446 addnode fail to add should log not error
  pkg/kademlia/kademlia.go
Labels: cla-signed

#457 remove TODO
  pkg/audit/verifier.go
Labels: cla-signed

#453 Satellite signature generation
  pkg/audit/cursor_test.go
  pkg/auth/grpcauth/authentication.go
  pkg/auth/signature.go
  pkg/auth/signature_test.go
  pkg/datarepair/checker/checker_test.go
  pkg/pb/piecestore.pb.go
  pkg/pb/piecestore.proto
  pkg/pointerdb/config.go
  pkg/pointerdb/pdbclient/client.go
  pkg/pointerdb/pdbclient/client_test.go
  pkg/pointerdb/pointerdb.go
  pkg/provider/identity.go
Labels: Request Code Review, cla-signed

#460 Fix TestBootstrap and TestLookup
  pkg/kademlia/kademlia_test.go
Labels: Request Code Review, cla-signed

#461 Use use utils combineErrors
  pkg/datarepair/repairer/repairer.go
Labels: cla-signed

#458 Kad identity
  pkg/kademlia/kademlia_test.go
  pkg/node/id.go
  pkg/node/id_test.go
  pkg/node/node_test.go
Labels: cla-signed

#464 Kademlia Sequential Lookup
  pkg/kademlia/kademlia.go
  pkg/kademlia/kademlia_test.go
  pkg/kademlia/lookup.go
  pkg/kademlia/workers_test.go
  pkg/pointerdb/pdbclient/client.go
  pkg/pointerdb/pdbclient/client_test.go
  pkg/pointerdb/pointerdb.go
Labels: cla-signed

#465 reproduce captplanet kademlia problems
  big-upload-testfile
  scripts/test-captplanet.sh
  small-upload-testfile
Labels: cla-signed

#470 Start redis
  cmd/captplanet/run.go
  cmd/captplanet/setup.go
  pkg/datarepair/repairer/config.go
  pkg/datarepair/repairer/repairer.go
Labels: cla-signed

#468 Remove `newID` function
  go.sum
  pkg/node/id.go
  pkg/overlay/cache_test.go
  pkg/overlay/overlay_test.go
  pkg/piecestore/rpc/client/pieceid_test.go
Labels: Request Code Review, cla-signed

#475 Cleanups related to transport
  internal/test/utils.go
  pkg/kademlia/kademlia.go
  pkg/overlay/cache_test.go
  pkg/overlay/mocks/overlay.go
  pkg/pb/meta.pb.go
  pkg/pb/overlay.pb.go
  pkg/pb/overlay.proto
  pkg/provider/provider.go
  pkg/storage/ec/client.go
  pkg/storage/ec/client_test.go
  pkg/storage/ec/transportclient_mock_test.go
  pkg/transport/client.go
  pkg/transport/transport.go
  pkg/transport/transport_test.go
Labels: cla-signed

#423 Improve path handling + filepath handling framework
  cmd/uplink/cmd/cat.go
  cmd/uplink/cmd/cp.go
  cmd/uplink/cmd/ls.go
  cmd/uplink/cmd/mb.go
  cmd/uplink/cmd/put.go
  cmd/uplink/cmd/rb.go
  cmd/uplink/cmd/rm.go
  internal/fpath/path.go
  internal/fpath/path_test.go
  internal/fpath/path_unix_test.go
  internal/fpath/path_windows_test.go
  pkg/storage/ec/client.go
Labels: cla-signed

#477 Add @wthorp to CLA
  .clabot
Labels: cla-signed

#448 Path Encryption
  go.mod
  go.sum
  pkg/storage/streams/store.go
Labels: backward incompatible, cla-signed

#476 Delete dead code in overlay
  pkg/overlay/service.go
  pkg/overlay/service_test.go
Labels: cla-signed

#426 filter out excluded nodes when repairing
  pkg/kademlia/workers_test.go
  pkg/overlay/client.go
  pkg/overlay/client_test.go
  pkg/overlay/mocks/mock_client.go
  pkg/overlay/server.go
  pkg/pb/overlay.pb.go
  pkg/pb/overlay.proto
  pkg/storage/segments/store.go
  pkg/storage/segments/store_test.go
Labels: cla-signed

#474 Fix nonce reuse for encrypting the encryption key
  pkg/eestream/encryption.go
  pkg/pb/meta.pb.go
  pkg/pb/meta.proto
  pkg/storage/streams/store.go
  pkg/storage/streams/store_test.go
Labels: backward incompatible, cla-signed

#456 updates to piecestore stats to report available bandwidth and total used bandwidth
  examples/piecestore-client/main.go
  pkg/pb/piecestore.pb.go
  pkg/pb/piecestore.proto
  pkg/piecestore/rpc/server/psdb/psdb.go
  pkg/piecestore/rpc/server/server.go
Labels: Request Code Review, cla-signed

#481 Separate storj.io packages in imports
  .golangci.yml
  cmd/captplanet/main.go
  cmd/captplanet/run.go
  cmd/satellite/main.go
  examples/grpc-debug/main.go
  pkg/dht/mocks/mock_dht.go
  pkg/kademlia/queue_test.go
  pkg/kademlia/workers.go
  pkg/kademlia/workers_test.go
  pkg/miniogw/gateway-storj_test.go
  pkg/miniogw/logging/logger_mock_test.go
  pkg/miniogw/logging/logging_test.go
  pkg/overlay/config_test.go
  pkg/overlay/mocks/mock_client.go
  pkg/overlay/server.go
  pkg/piecestore/rpc/client/client.go
  pkg/piecestore/rpc/client/pieceid_test.go
  pkg/piecestore/rpc/server/psdb/psdb.go
  pkg/piecestore/rpc/server/psdb/psdb_test.go
  pkg/piecestore/rpc/server/readerwriter.go
  pkg/piecestore/rpc/server/server.go
  pkg/piecestore/rpc/server/store.go
  pkg/pointerdb/pdbclient/mocks/mock_client.go
  pkg/pointerdb/pdbclient/pdbclient_mock_test.go
  pkg/pointerdb/pointerdb_test.go
  pkg/provider/identity.go
  pkg/ranger/content_test.go
  pkg/ranger/file_test.go
  pkg/statdb/statdb_test.go
  pkg/storage/buckets/mocks/mock_buckets.go
  pkg/storage/buckets/store.go
  pkg/storage/ec/psclient_mock_test.go
  pkg/storage/ec/transportclient_mock_test.go
  pkg/storage/objects/store.go
  pkg/storage/segments/mock_store.go
  pkg/storage/segments/store_test.go
  pkg/storage/streams/store_test.go
  storage/boltdb/client.go
  storage/redis/redisserver/server.go
  storage/storelogger/logger.go
  storage/storelogger/logger_test.go
  storage/testsuite/test_list.go
  storage/testsuite/test_listv2.go
  storage/testsuite/utils.go
Labels: cla-signed

#480 Uplink cp upload improvements
  cmd/uplink/cmd/cp.go
Labels: cla-signed

#484 use net.JoinHostPort
  pkg/overlay/cache_test.go
Labels: cla-signed

#454 handle nil nodes in ec Put
  pkg/storage/ec/client.go
  pkg/storage/ec/client_test.go
Labels: cla-signed

#479 Travis with go1.11 and modules
  .travis.yml
  pkg/kademlia/lookup.go
  pkg/miniogw/multipart.go
  scripts/install-awscli.sh
  scripts/setup-gopath.sh
  scripts/travis-deps.sh
Labels: cla-signed

#467 adds Reporter to the audit package to record failed audits
  examples/statdb-client/main.go
  pkg/audit/reporter.go
  pkg/audit/service.go
  pkg/audit/verifier.go
  pkg/audit/verifier_test.go
  pkg/statdb/proto/statdb.pb.go
  pkg/statdb/proto/statdb.proto
  pkg/statdb/sdbclient/client.go
  pkg/statdb/statdb.go
  pkg/statdb/statdb_test.go
Labels: Code Review In-Progress, cla-signed

#488 reassigns test ids to match test pattern in testgetnodes
  pkg/kademlia/kademlia_test.go
Labels: cla-signed

#487 Clean up Makefile
  Makefile
Labels: cla-signed

#429 Give Windows builds some love
  .gitignore
  Makefile
  cmd/captplanet/main.go
  pkg/process/exec.go
  pkg/process/exec_conf.go
  resources/README.md
  resources/icon.ico
  resources/icon.png
  resources/logo.png
  resources/versioninfo.json
Labels: cla-signed

#483 Add S3 Scheme as valid URL Scheme
  internal/fpath/path.go
  internal/fpath/path_test.go
Labels: cla-signed

#466 Audit cron
  pkg/audit/service.go
Labels: Code Review In-Progress, cla-signed

#486 remove gopkg.toml
  Gopkg.lock
  Gopkg.toml
Labels: cla-signed

#462 Encrypt metadata
  pkg/pb/meta.pb.go
  pkg/pb/meta.proto
  pkg/storage/streams/store.go
  pkg/storage/streams/store_test.go
Labels: Request Code Review, backward incompatible, cla-signed, enhancement

#469 Satellite verification on storage node
  examples/piecestore-client/main.go
  pkg/audit/service.go
  pkg/audit/verifier.go
  pkg/audit/verifier_test.go
  pkg/auth/auth.go
  pkg/auth/signature.go
  pkg/auth/signature_test.go
  pkg/pb/piecestore.pb.go
  pkg/pb/piecestore.proto
  pkg/piecestore/rpc/client/client.go
  pkg/piecestore/rpc/client/pieceranger.go
  pkg/piecestore/rpc/client/pieceranger_test.go
  pkg/piecestore/rpc/server/retrieve.go
  pkg/piecestore/rpc/server/server.go
  pkg/piecestore/rpc/server/server_test.go
  pkg/piecestore/rpc/server/store.go
  pkg/pointerdb/pdbclient/client.go
  pkg/pointerdb/pdbclient/client_test.go
  pkg/pointerdb/pdbclient/mocks/mock_client.go
  pkg/storage/ec/client.go
  pkg/storage/ec/client_test.go
  pkg/storage/ec/mocks/mock_client.go
  pkg/storage/ec/psclient_mock_test.go
  pkg/storage/segments/store.go
  pkg/storage/segments/store_test.go
Labels: Request Code Review, cla-signed

#478 return multiple errors when captplanet fails
  cmd/captplanet/run.go
Labels: cla-signed

#495 Use GOPROXY, if available
  Makefile
Labels: cla-signed

#497 Extract encryption package from eestream
  examples/eestream/serve-collected/main.go
  examples/eestream/serve/main.go
  examples/eestream/store/main.go
  pkg/eestream/decode.go
  pkg/eestream/encode.go
  pkg/eestream/rs_test.go
  pkg/encryption/aesgcm.go
  pkg/encryption/aesgcm_test.go
  pkg/encryption/bits.go
  pkg/encryption/bits_test.go
  pkg/encryption/common.go
  pkg/encryption/crc_test.go
  pkg/encryption/encryption.go
  pkg/encryption/secretbox.go
  pkg/encryption/secretbox_test.go
  pkg/encryption/transform.go
  pkg/encryption/transform_test.go
  pkg/storage/streams/store.go
Labels: cla-signed

#502 Fix error message
  pkg/storage/ec/client.go
Labels: cla-signed

#498 Make kademlia use less file-descriptors
  pkg/kademlia/kademlia.go
  pkg/kademlia/routing.go
  pkg/kademlia/routing_helpers_test.go
  storage/boltdb/client.go
  storage/boltdb/client_test.go
Labels: cla-signed

#496 pkg/utils `CollectErrors` tests
  pkg/utils/utils_test.go
Labels: cla-signed

#513 Adapt storj and encryption packages
  examples/eestream/serve-collected/main.go
  examples/eestream/serve/main.go
  examples/eestream/store/main.go
  pkg/eestream/rs_test.go
  pkg/encryption/aesgcm.go
  pkg/encryption/aesgcm_test.go
  pkg/encryption/encryption.go
  pkg/encryption/secretbox.go
  pkg/encryption/secretbox_test.go
  pkg/miniogw/config.go
  pkg/storage/streams/store.go
  pkg/storj/encryption.go
Labels: cla-signed

#508 Increase test coverage for overlay client Choose method
  pkg/overlay/client_test.go
  pkg/overlay/utils_test.go
Labels: cla-signed

#511 Handle CTRL+C while using AWS CLI
  pkg/storage/streams/store.go
Labels: Request Code Review, cla-signed, wip

#516 fix captplanet and satellite overwrite flags
  cmd/captplanet/setup.go
  cmd/satellite/main.go
Labels: cla-signed

#517 Updates captainplanet test scripts to use /tmp/capt for test files
  scripts/test-captplanet.sh
Labels: cla-signed

#514 Travis quiet parallel tests
  .travis.yml
Labels: cla-signed

#520 Improve error handling in encryption pkg
  pkg/encryption/aesgcm.go
  pkg/encryption/common.go
  pkg/encryption/encryption.go
  pkg/encryption/secretbox.go
Labels: cla-signed

#503 Pieces must be name spaced by Satellite
  pkg/pb/piecestore.pb.go
  pkg/pb/piecestore.proto
  pkg/piecestore/rpc/server/retrieve.go
  pkg/piecestore/rpc/server/server.go
  pkg/piecestore/rpc/server/store.go
Labels: backward incompatible, cla-signed

#519 Travis Windows
  .travis.yml
  scripts/setup-gopath.ps1
  scripts/setup-gopath.sh
Labels: Request Code Review, cla-signed

#523 Fix repairing run
  internal/sync2/limiter.go
  internal/sync2/limiter_test.go
  pkg/datarepair/repairer/config.go
  pkg/datarepair/repairer/repairer.go
Labels: Request Code Review, cla-signed

#529 Update .clabot to add RichardLitt
  .clabot
Labels: cla-signed

#525 Option for generating sample TLS certs for Minio GW
  cmd/captplanet/setup.go
  cmd/uplink/cmd/setup.go
  pkg/miniogw/config.go
  pkg/peertls/templates.go
Labels: cla-signed

#345 Add 'mount' command for uplink cli (read-only access)
  cmd/uplink/cmd/mount.go
  go.mod
  go.sum
Labels: Request Code Review, cla-signed

#531 moved poll, removed ctx params
  pkg/node/client.go
  pkg/node/connection_pool.go
  pkg/node/connection_pool_test.go
  pkg/node/node.go
  pkg/pool/pool.go
Labels: cla-signed

#482 Implement buckets metainfo as a wrapper over storage/buckets
  pkg/metainfo/kvmetainfo/buckets.go
  pkg/metainfo/kvmetainfo/paths.go
  pkg/storage/buckets/store.go
  pkg/storj/metainfo.go
Labels: cla-signed

#535 remove ctx from repairer struct
  pkg/datarepair/repairer/config.go
  pkg/datarepair/repairer/repairer.go
Labels: cla-signed

#522 Refactor Path type
  cmd/uplink/cmd/cp.go
  cmd/uplink/cmd/ls.go
  cmd/uplink/cmd/mount.go
  cmd/uplink/cmd/rb.go
  cmd/uplink/cmd/rm.go
  examples/pointerdb-client/main.go
  pkg/audit/cursor.go
  pkg/audit/cursor_test.go
  pkg/encryption/encryption.go
  pkg/encryption/examples_test.go
  pkg/encryption/path.go
  pkg/encryption/path_test.go
  pkg/miniogw/config.go
  pkg/miniogw/gateway-storj.go
  pkg/miniogw/gateway-storj_test.go
  pkg/miniogw/multipart.go
  pkg/miniogw/objstore_mock_test.go
  pkg/paths/common.go
  pkg/paths/examples_test.go
  pkg/paths/paths.go
  pkg/paths/paths_test.go
  pkg/pointerdb/pdbclient/client.go
  pkg/pointerdb/pdbclient/client_test.go
  pkg/pointerdb/pdbclient/mocks/mock_client.go
  pkg/pointerdb/pointerdb_test.go
  pkg/storage/buckets/prefixed.go
  pkg/storage/buckets/store.go
  pkg/storage/objects/store.go
  pkg/storage/segments/mock_store.go
  pkg/storage/segments/store.go
  pkg/storage/segments/store_test.go
  pkg/storage/streams/store.go
  pkg/storage/streams/store_test.go
  pkg/storj/path.go
  pkg/storj/path_test.go
Labels: backward incompatible, cla-signed

#537 uplink: fix mount and cli/gateway logical merge conflict
  cmd/uplink/cmd/mount.go
Labels: cla-signed

#534 Wait-list gating
  pkg/peertls/peertls.go
  pkg/peertls/peertls_test.go
  pkg/peertls/utils.go
  pkg/provider/identity.go
  pkg/provider/identity_test.go
  pkg/provider/provider.go
Labels: cla-signed

#507 Disconnects nodeclient, routing table dbs when done with kademlia
  .gitignore
  db/.keep
  pkg/dht/mocks/mock_dht.go
  pkg/kademlia/config.go
  pkg/kademlia/kademlia.go
  pkg/kademlia/kademlia_test.go
  pkg/node/client.go
  pkg/node/connection_pool.go
  pkg/node/connection_pool_test.go
  pkg/node/node.go
Labels: cla-signed

#491 Added ping support to node client
  pkg/kademlia/kademlia.go
  pkg/node/client.go
  pkg/node/connection_pool.go
  pkg/node/connection_pool_test.go
  pkg/node/node.go
  pkg/node/node_test.go
  pkg/provider/identity.go
  pkg/transport/transport.go
Labels: cla-signed

#533 Ensure we can create kademlia with custom storage
  pkg/kademlia/config.go
  pkg/kademlia/kademlia.go
  pkg/kademlia/kademlia_test.go
  pkg/kademlia/routing.go
  pkg/kademlia/routing_helpers_test.go
  pkg/kademlia/routing_test.go
  pkg/overlay/cache.go
  pkg/overlay/cache_test.go
Labels: Request Code Review, cla-signed

#545 testcontext
  go.mod
  internal/test/utils.go
  internal/testcontext/context.go
  internal/testcontext/context_test.go
  pkg/node/node_test.go
  pkg/overlay/overlay_test.go
Labels: cla-signed

#542 Add tparse to tests
  .travis.yml
Labels: cla-signed

#548 Some README edits
  README.md
Labels: cla-signed

#552 Skip flaky TestPing
  pkg/node/node_test.go
Labels: cla-signed

#543 In-memory piecestore database
  pkg/piecestore/rpc/server/psdb/psdb.go
  pkg/piecestore/rpc/server/psdb/psdb_test.go
  pkg/piecestore/rpc/server/server.go
Labels: Request Code Review, cla-signed

#530 Add FindValidNodes() to statdb
  pkg/pb/overlay.pb.go
  pkg/pb/overlay.proto
  pkg/statdb/proto/statdb.pb.go
  pkg/statdb/proto/statdb.proto
  pkg/statdb/sdbclient/client.go
  pkg/statdb/statdb.go
  pkg/statdb/statdb_test.go
Labels: cla-signed

#544 RPC Ping Request/Response
  pkg/kademlia/workers_test.go
  pkg/node/node.go
  pkg/node/node_test.go
  pkg/node/server.go
  pkg/pb/overlay.pb.go
  pkg/pb/overlay.proto
Labels: Request Code Review, cla-signed

#556 Piecestore proto change
  examples/piecestore-client/main.go
  pkg/audit/verifier.go
  pkg/pb/piecestore.pb.go
  pkg/pb/piecestore.proto
  pkg/piecestore/rpc/client/client.go
  pkg/piecestore/rpc/client/pieceranger_test.go
  pkg/piecestore/rpc/client/readerwriter.go
  pkg/pointerdb/pointerdb.go
  pkg/storage/ec/client.go
Labels: Request Code Review, cla-signed

#490 creates run loop for data repair checker
  pkg/datarepair/checker/checker.go
  pkg/datarepair/checker/checker_test.go
  pkg/datarepair/checker/config.go
  pkg/datarepair/repairer/config.go
  pkg/datarepair/repairer/repairer.go
  pkg/overlay/config.go
  pkg/pointerdb/config.go
Labels: cla-signed

#559 moves bulk of code from ticker case to outside for indentation's sake
  pkg/datarepair/checker/checker.go
  pkg/datarepair/repairer/repairer.go
Labels: cla-signed

#549 captplanet: fix output line name
  cmd/captplanet/run.go
Labels: cla-signed

#562 Fix statdb query to avoid sql injection
  pkg/statdb/dbx/gen.go
  pkg/statdb/dbx/statdb.dbx
  pkg/statdb/dbx/statdb.dbx.go
  pkg/statdb/dbx/statdb.dbx.postgres.sql
  pkg/statdb/dbx/statdb.dbx.sqlite3.sql
  pkg/statdb/sdbclient/client.go
  pkg/statdb/statdb.go
  pkg/statdb/statdb_test.go
Labels: cla-signed

#561 Add repairer & checker to Satelite
  cmd/captplanet/run.go
  pkg/datarepair/checker/config.go
  pkg/datarepair/repairer/config.go
  pkg/pointerdb/config.go
Labels: cla-signed

#505 bandwidth agreements protobuf
  examples/piecestore-client/main.go
  pkg/pb/bandwidth.pb.go
  pkg/pb/bandwidth.proto
  pkg/pb/gen.go
  pkg/piecestore/rpc/server/agreementsender/agreementsender.go
  pkg/piecestore/rpc/server/psdb/psdb.go
  pkg/piecestore/rpc/server/server.go
  pkg/piecestore/rpc/server/server_test.go
Labels: Request Code Review, cla-signed

#553 Don't try to remove empty directory
  internal/testcontext/context.go
Labels: Request Code Review, cla-signed

#541 Uplink mount better prefix handling
  cmd/uplink/cmd/mount.go
Labels: Request Code Review, cla-signed
