Repository storj/storj, pull requests merged in 2019-06, with the labels that each got.

#2072 Check errors for possible outcomes from audit's DownloadShares
  internal/testplanet/uplink.go
  pkg/audit/containment_test.go
  pkg/audit/newverifier_test.go
  pkg/audit/service.go
  pkg/audit/timeout_test.go
  pkg/audit/verifier.go
  scripts/testdata/satellite-config.yaml.lock
  storage/filestore/dir.go
  storage/filestore/store.go
  storagenode/pieces/store.go
  storagenode/piecestore/endpoint.go
Labels: cla-signed

#2081 Fix storage and object_count calculations on console
  satellite/console/usagerollups.go
  satellite/satellitedb/usagerollups.go
  web/satellite/src/components/buckets/BucketItem.vue
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2094 pkg/storj: use proper unquoting of json data in NodeID and PieceID
  pkg/storj/node.go
  pkg/storj/node_test.go
  pkg/storj/pieceid.go
  pkg/storj/pieceid_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2080 Console add stripe service
  go.mod
  go.sum
  satellite/console/consoleweb/consoleql/mutation_test.go
  satellite/console/consoleweb/consoleql/query_test.go
  satellite/console/consoleweb/server.go
  satellite/console/service.go
  satellite/payments/localpayments/local.go
  satellite/payments/service.go
  satellite/payments/stripepayments/stripe.go
  satellite/peer.go
  scripts/testdata/satellite-config.yaml.lock
Labels: Do Not Merge, Request Code Review, cla-signed

#2095 satellitedb/overlaycache: avoid tx leak in case of error
  satellite/satellitedb/overlaycache.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2097 rename VetNode to IsVetted
  pkg/overlay/cache.go
  pkg/overlay/cache_test.go
  satellite/satellitedb/locked.go
  satellite/satellitedb/overlaycache.go
  satellite/vouchers/service.go
Labels: cla-signed

#2092 internal/memory: don't convert to float to avoid losing precision.
  internal/memory/size.go
  internal/memory/size_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2109 pkg/*: add monkit task to missing places
  cmd/certificates/auth.go
  cmd/certificates/claims.go
  cmd/identity/certificate_authority.go
  cmd/identity/revocations.go
  examples/eestream/serve-collected/main.go
  pkg/accounting/projectusage.go
  pkg/accounting/rollup/rollup.go
  pkg/accounting/tally/tally.go
  pkg/audit/cursor.go
  pkg/audit/reporter.go
  pkg/audit/service.go
  pkg/audit/verifier.go
  pkg/auth/apikey.go
  pkg/auth/signedMessage.go
  pkg/auth/signing/peers.go
  pkg/auth/signing/verify.go
  pkg/bwagreement/server.go
  pkg/certificates/certificates.go
  pkg/certificates/certificates_test.go
  pkg/certificates/config.go
  pkg/datarepair/checker/checker.go
  pkg/datarepair/irreparable/inspector.go
  pkg/datarepair/repairer/repairer.go
  pkg/discovery/lifecycle.go
  pkg/discovery/service.go
  pkg/eestream/decode.go
  pkg/eestream/encode.go
  pkg/eestream/pad.go
  pkg/eestream/stripe.go
  pkg/encryption/transform.go
  pkg/identity/generate.go
  pkg/identity/revocation_db.go
  pkg/identity/revocation_db_test.go
  pkg/kademlia/dialer.go
  pkg/kademlia/endpoint.go
  pkg/kademlia/inspector.go
  pkg/kademlia/kademlia.go
  pkg/kademlia/peer_discovery.go
  pkg/kademlia/routing.go
  pkg/kademlia/routing_helpers.go
  pkg/macaroon/apikey.go
  pkg/metainfo/kvmetainfo/objects.go
  pkg/metainfo/kvmetainfo/stream.go
  pkg/overlay/cache.go
  pkg/overlay/inspector.go
  pkg/peertls/extensions/revocations.go
  pkg/peertls/extensions/revocations_test.go
  pkg/peertls/tlsopts/tls_test.go
  pkg/ranger/content.go
  pkg/ranger/file.go
  pkg/ranger/http.go
  pkg/ranger/http_test.go
  pkg/ranger/reader.go
  pkg/ranger/readerat.go
  pkg/storage/buckets/store.go
  pkg/storage/ec/client.go
  pkg/storage/streams/store.go
  pkg/telemetry/client.go
  pkg/transport/slowtransport.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2108 satellite: add monkit task to missing places
  internal/post/sender.go
  satellite/console/consoleweb/consoleql/mutation_test.go
  satellite/console/consoleweb/server.go
  satellite/console/registrationtoken.go
  satellite/console/service.go
  satellite/inspector/inspector.go
  satellite/mailservice/service.go
  satellite/mailservice/simulate/linkclicker.go
  satellite/metainfo/metainfo.go
  satellite/metainfo/service.go
  satellite/orders/service.go
  satellite/payments/localpayments/local.go
  satellite/payments/stripepayments/stripe.go
  satellite/peer.go
  satellite/satellitedb/apikeys.go
  satellite/satellitedb/bandwidthagreement.go
  satellite/satellitedb/bucketusage.go
  satellite/satellitedb/certdb.go
  satellite/satellitedb/containment.go
  satellite/satellitedb/irreparabledb.go
  satellite/satellitedb/orders.go
  satellite/satellitedb/overlaycache.go
  satellite/satellitedb/projectaccounting.go
  satellite/satellitedb/projectmembers.go
  satellite/satellitedb/projects.go
  satellite/satellitedb/projects_test.go
  satellite/satellitedb/regtokens.go
  satellite/satellitedb/repairqueue.go
  satellite/satellitedb/resetpasstokens.go
  satellite/satellitedb/storagenodeaccounting.go
  satellite/satellitedb/usagerollups.go
  satellite/satellitedb/users.go
  satellite/satellitedb/users_test.go
  satellite/vouchers/service.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2111 Add VitaliiShpital to CLA List
  .clabot
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2105 repairer: fix config comments
  pkg/datarepair/checker/checker.go
  pkg/datarepair/repairer/repairer.go
  scripts/testdata/satellite-config.yaml.lock
Labels: cla-signed

#2107 storagenode: add monkit task to missing places
  storagenode/inspector/inspector.go
  storagenode/monitor/monitor.go
  storagenode/orders/sender.go
  storagenode/peer.go
  storagenode/pieces/readwrite.go
  storagenode/pieces/store.go
  storagenode/pieces/store_test.go
  storagenode/piecestore/endpoint.go
  storagenode/piecestore/verification.go
  storagenode/storagenodedb/bandwidthdb.go
  storagenode/storagenodedb/certdb.go
  storagenode/storagenodedb/orders.go
  storagenode/storagenodedb/pieceinfo.go
  storagenode/storagenodedb/usedserials.go
  storagenode/trust/service.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2096 go.mod: update grpc to latest version
  go.mod
  go.sum
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2067 add capability of logging all GRPC calls/payloads
  pkg/server/config.go
  pkg/server/interceptors.go
  pkg/server/server.go
  satellite/peer.go
  scripts/testdata/satellite-config.yaml.lock
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2110 nobuckets state implemented
  web/satellite/src/components/buckets/BucketArea.vue
  web/satellite/src/components/buckets/NoBucketsArea.vue
  web/satellite/static/images/buckets/arrow.svg
  web/satellite/static/images/buckets/foldericon.svg
  web/satellite/static/images/buckets/uplink.svg
Labels: cla-signed

#2106 storagenode/piecestore: add meters to upload/download rates
  storagenode/piecestore/endpoint.go
Labels: cla-signed

#1977 jenkins: check that lock file is updated properly
  Jenkinsfile.public
  Makefile
  proto.lock
  scripts/check-satellite-config-lock.sh
  scripts/protobuf.go
  scripts/test-satellite-cfg-change.sh
  scripts/update-satellite-config-lock.sh
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2117 db: set max open conns, conn max lifetime, add db stat monitoring
  internal/dbutil/defaults.go
  internal/dbutil/pgutil/db.go
  satellite/satellitedb/database.go
  scripts/testdata/satellite-config.yaml.lock
  storage/postgreskv/client.go
  storagenode/storagenodedb/infodb.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2046 Change for free credit design doc
  docs/design/marketing-offer-program.md
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2119 Fix Config Comments in DButil Package
  internal/dbutil/defaults.go
  scripts/testdata/satellite-config.yaml.lock
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2120 Update Notification Text to new Config Update Process
  scripts/check-satellite-config-lock.sh
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2114 api key text bug fix
  web/satellite/src/components/apiKeys/CopyApiKeyPopup.vue
Labels: Reviewer Can Merge, cla-signed

#2124 storage/filestore: add monkit task to missing places
  storage/blob.go
  storage/filestore/blob.go
  storage/filestore/dir.go
  storage/filestore/store.go
  storage/filestore/store_test.go
  storagenode/pieces/readwrite.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2123 pkg/auth: add monkit task to missing places
  pkg/auth/signature.go
  pkg/auth/signature_test.go
  pkg/auth/signedMessage.go
  pkg/auth/signing/encode.go
  pkg/auth/signing/peers.go
  pkg/auth/signing/sign.go
  pkg/auth/signing/verify.go
  pkg/bwagreement/server_test.go
  pkg/bwagreement/testbwagreement/common.go
  pkg/macaroon/apikey.go
  pkg/macaroon/apikey_test.go
  pkg/storage/ec/client.go
  pkg/storage/ec/client_planet_test.go
  satellite/metainfo/metainfo.go
  satellite/orders/endpoint.go
  satellite/orders/service.go
  satellite/vouchers/service.go
  storagenode/orders/db_test.go
  storagenode/pieces/db_test.go
  storagenode/piecestore/endpoint.go
  storagenode/piecestore/endpoint_test.go
  storagenode/piecestore/verification.go
  storagenode/piecestore/verification_test.go
  uplink/piecestore/buffering.go
  uplink/piecestore/download.go
  uplink/piecestore/upload.go
  uplink/piecestore/verification.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2126 Fix storing struct in context
  internal/fpath/temp_data.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2122 storage: add monkit task to missing places
  internal/testplanet/uplink_test.go
  pkg/accounting/tally/tally.go
  pkg/audit/cursor.go
  pkg/audit/cursor_test.go
  pkg/certificates/certificates.go
  pkg/certificates/certificates_test.go
  pkg/datarepair/checker/checker.go
  pkg/datarepair/checker/checker_test.go
  pkg/datarepair/datarepair_test.go
  pkg/identity/revocation_db.go
  pkg/identity/revocation_db_test.go
  pkg/kademlia/kademlia.go
  pkg/kademlia/kademlia_test.go
  pkg/kademlia/routing.go
  pkg/kademlia/routing_helpers.go
  pkg/kademlia/routing_helpers_test.go
  pkg/kademlia/routing_test.go
  pkg/storage/segments/repairer.go
  pkg/storage/segments/repairer_test.go
  satellite/inspector/inspector.go
  satellite/inspector/inspector_test.go
  satellite/metainfo/metainfo.go
  satellite/metainfo/service.go
  storage/boltdb/client.go
  storage/boltdb/client_test.go
  storage/common.go
  storage/iterator.go
  storage/listkeys.go
  storage/listv2.go
  storage/postgreskv/alternateclient.go
  storage/postgreskv/client.go
  storage/postgreskv/client_test.go
  storage/redis/client.go
  storage/storelogger/logger.go
  storage/teststore/store.go
  storage/testsuite/bench.go
  storage/testsuite/long_bench.go
  storage/testsuite/test.go
  storage/testsuite/test_crud.go
  storage/testsuite/test_iterate.go
  storage/testsuite/test_iterate_all.go
  storage/testsuite/test_list.go
  storage/testsuite/test_listv2.go
  storage/testsuite/test_parallel.go
  storage/testsuite/test_prefix.go
  storage/testsuite/utils.go
  storage/util.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2118 internal,lib,uplink: add monkit task to missing places
  internal/post/oauth2/auth.go
  internal/sync2/copy.go
  internal/version/service.go
  lib/uplink/object.go
  lib/uplink/uplink.go
  satellite/peer.go
  uplink/piecestore/client.go
  uplink/piecestore/download.go
  uplink/piecestore/upload.go
  uplink/piecestore/verification.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2128 satellite/orders: monitor order settlement more
  satellite/orders/endpoint.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2116 Value Attribution DBX Model
  satellite/satellitedb/dbx/satellitedb.dbx
  satellite/satellitedb/dbx/satellitedb.dbx.go
  satellite/satellitedb/dbx/satellitedb.dbx.postgres.sql
  satellite/satellitedb/dbx/satellitedb.dbx.sqlite3.sql
  satellite/satellitedb/migrate.go
  satellite/satellitedb/testdata/postgres.v27.sql
Labels: Code Review In-Progress, Reviewer Can Merge, cla-signed

#2088 Better metainfo Create/Commit request validation
  satellite/metainfo/metainfo.go
  satellite/metainfo/metainfo_test.go
  satellite/metainfo/validation.go
Labels: Request Code Review, cla-signed

#2129 postgreskv: actually monitor the iterate call
  storage/postgreskv/alternateclient.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2093 Fix flaky audit test
  go.mod
  go.sum
  pkg/audit/newverifier_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2102 add disqualified check to node selection queries
  pkg/overlay/statdb_test.go
  satellite/satellitedb/overlaycache.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2079 node disqualification design draft
  docs/design/disqualification.md
Labels: Request Code Review, cla-signed

#2132 monitor macaroon parse/serialization perf
  pkg/macaroon/serialize.go
Labels: cla-signed

#2136 pkg/audit: Fix code style named result parameters
  pkg/audit/service.go
Labels: Enhancement, Request Code Review, Reviewer Can Merge, cla-signed

#2138 pkg/bwagreements: remove service
  .github/CODEOWNERS
  cmd/satellite/main.go
  internal/testplanet/planet.go
  pkg/auth/apikey.go
  pkg/auth/signature.go
  pkg/auth/signature_test.go
  pkg/auth/signedMessage.go
  pkg/bwagreement/bwagreement_test.go
  pkg/bwagreement/server.go
  pkg/bwagreement/server_test.go
  pkg/bwagreement/testbwagreement/common.go
  pkg/pb/bandwidth.pb.go
  pkg/pb/bandwidth.proto
  proto.lock
  satellite/peer.go
  satellite/satellitedb/bandwidthagreement.go
  satellite/satellitedb/database.go
  satellite/satellitedb/dbx/satellitedb.dbx
  satellite/satellitedb/dbx/satellitedb.dbx.go
  satellite/satellitedb/dbx/satellitedb.dbx.postgres.sql
  satellite/satellitedb/dbx/satellitedb.dbx.sqlite3.sql
  satellite/satellitedb/locked.go
  satellite/satellitedb/migrate.go
  satellite/satellitedb/testdata/postgres.v28.sql
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2137 sync2: prioritize Cycle stopping messages
  internal/sync2/cycle.go
  internal/sync2/cycle_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2140 Remove bwagreement leftovers
  pkg/accounting/common.go
  pkg/pb/bandwidth_utils.go
  pkg/pb/piecestore.proto
  pkg/pb/pointerdb.pb.go
  pkg/pb/pointerdb.proto
  pkg/pb/scannerValuer.go
  pkg/pb/utils.go
  proto.lock
  satellite/satellitedb/migrate.go
  satellite/satellitedb/pbold/order.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2141 Web/register success popup close issue
  web/satellite/src/App.vue
  web/satellite/src/components/common/registrationSuccessPopup.html
Labels: cla-signed

#2139 Web/reload issue
  web/satellite/src/router/index.ts
Labels: cla-signed

#2100 Console add payments to service
  satellite/console/database.go
  satellite/console/projectinvoicestamps.go
  satellite/console/projectinvoicestamps_test.go
  satellite/console/projectpayments.go
  satellite/console/projectpayments_test.go
  satellite/console/projects.go
  satellite/console/service.go
  satellite/console/userpayments.go
  satellite/console/userpayments_test.go
  satellite/payments/localpayments/local.go
  satellite/payments/service.go
  satellite/payments/stripepayments/stripe.go
  satellite/satellitedb/consoledb.go
  satellite/satellitedb/dbx/satellitedb.dbx
  satellite/satellitedb/dbx/satellitedb.dbx.go
  satellite/satellitedb/dbx/satellitedb.dbx.postgres.sql
  satellite/satellitedb/dbx/satellitedb.dbx.sqlite3.sql
  satellite/satellitedb/locked.go
  satellite/satellitedb/migrate.go
  satellite/satellitedb/projectinvoicestamps.go
  satellite/satellitedb/projectpaymentinfos.go
  satellite/satellitedb/projects.go
  satellite/satellitedb/testdata/postgres.v29.sql
  satellite/satellitedb/userpayments.go
  satellite/satellitedb/users.go
Labels: Request Code Review, cla-signed

#2127 frontend bug fixes
  web/satellite/src/components/account/Profile.vue
  web/satellite/src/components/account/billing/BillingArea.vue
  web/satellite/src/components/navigation/TabNavigation.vue
  web/satellite/src/components/project/ProjectOverviewArea.vue
  web/satellite/src/components/project/UsageReport.vue
  web/satellite/src/components/project/billing/BillingArea.vue
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2103 makes sure all uplink cli configs get passed to libuplink, add stripeSize
  cmd/uplink/cmd/mb.go
  cmd/uplink/cmd/root.go
  internal/testplanet/uplink.go
  lib/uplink/bucket_attrs_test.go
  lib/uplink/project.go
  pkg/metainfo/kvmetainfo/buckets.go
  pkg/metainfo/kvmetainfo/buckets_test.go
  pkg/metainfo/kvmetainfo/objects.go
  pkg/metainfo/kvmetainfo/objects_test.go
  pkg/miniogw/gateway_test.go
  pkg/storj/redundancy.go
  uplink/config.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2143 Ensure Storage Nodes collect expired used serial numbers
  storagenode/collector/service.go
  storagenode/collector/service_test.go
  storagenode/peer.go
  storagenode/storagenodedb/usedserials.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2130 Adding RS values to the info log and Node ID to tracing.
  pkg/storage/ec/client.go
  pkg/transport/transport.go
  uplink/piecestore/upload.go
Labels: cla-signed

#2145 discovery: remove graveyard
  internal/testplanet/planet.go
  pkg/datarepair/datarepair_test.go
  pkg/discovery/service.go
  pkg/discovery/service_test.go
  pkg/kademlia/kademlia.go
  pkg/kademlia/lookup_test.go
  pkg/kademlia/routing.go
  pkg/kademlia/routing_helpers_test.go
  scripts/testdata/satellite-config.yaml.lock
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2148 Fixed error notification on fail project member deletion.
  web/satellite/src/components/team/footerArea/DeleteUserArea.vue
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2147 satellite: Fix Peer.Run method doc comment
  satellite/peer.go
Labels: Enhancement, Request Code Review, Reviewer Can Merge, cla-signed

#2125 Improve error analysis in audit service
  pkg/audit/newverifier_test.go
  pkg/audit/reporter.go
  pkg/audit/reporter_test.go
  pkg/audit/service.go
  pkg/audit/verifier.go
  pkg/audit/verifier_test.go
  pkg/storj/node.go
Labels: Request Code Review, Sprint Release Goal, cla-signed

#2149 pkg/kademlia: Fix bug using ref of var range loop
  pkg/kademlia/kademlia.go
Labels: Bug, Request Code Review, Reviewer Can Merge, cla-signed

#2151 update to the reporting section to calculate bandwidth
  docs/design/value-attribution.md
Labels: cla-signed

#2135 Reputation / node selection doc
  docs/design/node-selection.md
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2090 uplink: enc.encryption-key flag is only available for setup command
  cmd/gateway/main.go
  cmd/storj-sim/network.go
  cmd/uplink/cmd/common.go
  cmd/uplink/cmd/common_test.go
  cmd/uplink/cmd/cp.go
  cmd/uplink/cmd/ls.go
  cmd/uplink/cmd/rb.go
  cmd/uplink/cmd/rm.go
  cmd/uplink/cmd/root.go
  cmd/uplink/cmd/setup.go
  cmd/uplink/cmd/share.go
  scripts/test-uplink.sh
  uplink/config.go
  uplink/config_test.go
  uplink/encryption_key.go
  uplink/encryption_key_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2121 Storagenode vouchers table
  storagenode/peer.go
  storagenode/storagenodedb/infodb.go
  storagenode/storagenodedb/testdata/sqlite.v3.sql
  storagenode/storagenodedb/vouchers.go
  storagenode/vouchers/db_test.go
  storagenode/vouchers/service.go
Labels: Request Code Review, cla-signed

#2154 pkg/audit: Rename verifier test files
  pkg/audit/newverifier_test.go
  pkg/audit/verifier_test.go
  pkg/audit/verifier_unit_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2156 Moved monkit tracing after the limit nil check & fix node id formatting.
  pkg/storage/ec/client.go
  pkg/transport/transport.go
  uplink/piecestore/upload.go
Labels: cla-signed

#2157 dbutil: reduce defaults so sum is < 100
  internal/dbutil/defaults.go
  scripts/testdata/satellite-config.yaml.lock
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2099 Re-enabling and fixing repairer tests
  internal/testplanet/planet.go
  pkg/datarepair/checker/checker_test.go
  pkg/datarepair/datarepair_test.go
  pkg/storage/segments/repairer_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2159 Update golangci-lint
  .golangci.yml
  Dockerfile.jenkins
  Makefile
  internal/migrate/versions.go
  pkg/certificates/certificates_test.go
  pkg/kademlia/config.go
  scripts/testdata/satellite-config.yaml.lock
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2155 Enforce our Minimum Requirements for Node Operators and sanity check them
  cmd/storj-sim/network.go
  internal/testplanet/planet.go
  storagenode/monitor/monitor.go
  storagenode/peer.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2160 Always use difficulty larger than 8 for identites
  internal/testidentity/identity.go
  lib/uplink/uplink.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2146 satellite/orders: batch update storage node allocations
  satellite/orders/endpoint.go
  satellite/orders/service.go
  satellite/satellitedb/locked.go
  satellite/satellitedb/orders.go
Labels: cla-signed

#2161 Revert "add disqualified check to node selection queries (#2102)"
  pkg/overlay/statdb_test.go
  satellite/satellitedb/overlaycache.go
Labels: cla-signed

#2170 Log upload and download start
  storagenode/piecestore/endpoint.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2164 Audit service should download erasure shares in parallel
  pkg/audit/verifier.go
  pkg/audit/verifier_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2150 reputation: Add configuration parameters
  pkg/overlay/config.go
  scripts/testdata/satellite-config.yaml.lock
Labels: Enhancement, Request Code Review, cla-signed

#2171 Add email to self node info
  bootstrap/peer.go
  pkg/discovery/service.go
  pkg/overlay/cache_test.go
  satellite/peer.go
  storagenode/peer.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1901 Open a new port on satellite for admin GUI
  cmd/storj-sim/network.go
  go.mod
  go.sum
  satellite/marketing/marketingweb/server.go
  satellite/marketing/marketingweb/static/css/style.css
  satellite/marketing/marketingweb/static/img/off.jpg
  satellite/marketing/marketingweb/static/img/on.jpg
  satellite/marketing/marketingweb/static/pages/404.html
  satellite/marketing/marketingweb/static/pages/banner.html
  satellite/marketing/marketingweb/static/pages/base.html
  satellite/marketing/marketingweb/static/pages/foModal.html
  satellite/marketing/marketingweb/static/pages/freeOffers.html
  satellite/marketing/marketingweb/static/pages/home.html
  satellite/marketing/marketingweb/static/pages/index.html
  satellite/marketing/marketingweb/static/pages/refOffers.html
  satellite/marketing/marketingweb/static/pages/roModal.html
  satellite/peer.go
  scripts/testdata/satellite-config.yaml.lock
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2163 add const stripesPerBlock const to calc blocksize
  cmd/uplink/cmd/cp.go
  lib/uplink/bucket_attrs_test.go
  pkg/eestream/encode.go
  pkg/eestream/pad.go
  pkg/eestream/rs_test.go
  pkg/metainfo/kvmetainfo/buckets_test.go
  pkg/metainfo/kvmetainfo/objects_test.go
  uplink/config.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1946 add segment.io into satellite GUI
  web/satellite/.env.example
  web/satellite/package.json
  web/satellite/src/main.ts
  web/satellite/src/plugins/analytics.ts
  web/satellite/src/types/vue.d.ts
  web/satellite/src/utils/constants/analyticsEventNames.ts
  web/satellite/src/utils/doNotTrack.ts
  web/satellite/src/views/forgotPassword/ForgotPassword.vue
  web/satellite/src/views/login/Login.vue
  web/satellite/src/views/register/Register.vue
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2144 pkg/audit: Add more reverify tests
  pkg/audit/containment_test.go
  pkg/audit/reverify_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2177 Fix marketingweb code
  cmd/storj-sim/network.go
  go.mod
  internal/testplanet/planet.go
  satellite/marketing/marketingweb/server.go
  satellite/marketing/marketingweb/static/pages/404.html
  scripts/testdata/satellite-config.yaml.lock
  web/marketing/css/style.css
  web/marketing/img/off.jpg
  web/marketing/img/on.jpg
  web/marketing/pages/banner.html
  web/marketing/pages/base.html
  web/marketing/pages/foModal.html
  web/marketing/pages/freeOffers.html
  web/marketing/pages/home.html
  web/marketing/pages/index.html
  web/marketing/pages/internal-server-error.html
  web/marketing/pages/page-not-found.html
  web/marketing/pages/refOffers.html
  web/marketing/pages/roModal.html
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2134 satellite/orders: TODOs about transactions
  satellite/orders/endpoint.go
  satellite/orders/service.go
Labels: cla-signed

#2133 split update methods into two for offer data
  satellite/marketing/offers.go
  satellite/marketing/offers_test.go
  satellite/marketing/service.go
  satellite/satellitedb/locked.go
  satellite/satellitedb/offers.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2181 fix satellite gui build issue
  web/satellite/src/components/apiKeys/ApiKeysDropdown.vue
  web/satellite/src/types/vue.d.ts
Labels: cla-signed

#2184 Add Isaac
  .clabot
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2180 only parse templates for the first requests
  satellite/marketing/marketingweb/server.go
  satellite/peer.go
Labels: Code Review In-Progress, Reviewer Can Merge, cla-signed

#2189 lib/uplink: expose restrict on api keys
  cmd/uplink/cmd/share.go
  lib/uplink/apikey.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2091 initial value attribution check development
  go.mod
  pkg/pb/metainfo.pb.go
  pkg/pb/metainfo.proto
  proto.lock
  satellite/metainfo/metainfo.go
  satellite/metainfo/metainfo_test.go
  satellite/satellitedb/database.go
  uplink/metainfo/client.go
Labels: Request Code Review, cla-signed

#2182 Removing bucket_id and adding project_id and bucket_name as primary key
  satellite/satellitedb/dbx/satellitedb.dbx
  satellite/satellitedb/dbx/satellitedb.dbx.go
  satellite/satellitedb/dbx/satellitedb.dbx.postgres.sql
  satellite/satellitedb/dbx/satellitedb.dbx.sqlite3.sql
  satellite/satellitedb/migrate.go
  satellite/satellitedb/testdata/postgres.v30.sql
Labels: Code Review In-Progress, Reviewer Can Merge, cla-signed

#2195 testcontext: sanitize folder name
  cmd/uplink/cmd/setup_test.go
  internal/testcontext/context.go
  pkg/accounting/db_test.go
  pkg/audit/verifier_unit_test.go
  pkg/macaroon/macaroon_test.go
  pkg/storj/encryption_test.go
  storage/boltdb/client_test.go
  storagenode/collector/service_test.go
  uplink/encryption_key_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2085 add user credits table
  satellite/satellitedb/dbx/satellitedb.dbx
  satellite/satellitedb/dbx/satellitedb.dbx.go
  satellite/satellitedb/dbx/satellitedb.dbx.postgres.sql
  satellite/satellitedb/dbx/satellitedb.dbx.sqlite3.sql
  satellite/satellitedb/migrate.go
  satellite/satellitedb/testdata/postgres.v31.sql
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2185 fix export name for DatePicker
  web/satellite/src/components/project/DatePicker.vue
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2188 kademlia/routing: add contexts to more places so monkit works
  pkg/dht/dht.go
  pkg/kademlia/endpoint.go
  pkg/kademlia/inspector.go
  pkg/kademlia/kademlia.go
  pkg/kademlia/kademlia_test.go
  pkg/kademlia/replacement_cache_test.go
  pkg/kademlia/routing.go
  pkg/kademlia/routing_helpers.go
  pkg/kademlia/routing_helpers_test.go
  pkg/kademlia/routing_integration_test.go
  pkg/kademlia/routing_test.go
  pkg/kademlia/testrouting/testrouting.go
  pkg/kademlia/testrouting/utils.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2196 Uplink C bindings part 1
  internal/testcontext/compile.go
  internal/testcontext/context.go
  internal/testcontext/context_test.go
  lib/uplink/bucket.go
  lib/uplink/project.go
  lib/uplinkc/alias.go
  lib/uplinkc/apikey.go
  lib/uplinkc/main.go
  lib/uplinkc/project.go
  lib/uplinkc/scope.go
  lib/uplinkc/testdata/apikey_test.c
  lib/uplinkc/testdata/helpers2.h
  lib/uplinkc/testdata/require.h
  lib/uplinkc/testdata_test.go
  lib/uplinkc/universe.go
  lib/uplinkc/universe_test.go
  lib/uplinkc/uplink.go
  lib/uplinkc/uplink_definitions.h
  lib/uplinkc/uplink_test.go
  lib/uplinkc/utils_test.go
  pkg/metainfo/kvmetainfo/objects.go
Labels: Request Code Review, cla-signed

#2199 Clean up NodeSelectionConfig
  cmd/overlay/cache.go
  cmd/overlay/main.go
  pkg/overlay/cache_test.go
  pkg/overlay/config.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2168 Use release build of uplink for container image
  cmd/uplink/Dockerfile
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2176 pkg/process: prometheus support
  pkg/process/debug.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2191 pkg/process/logging: different defaults for release/dev
  pkg/process/logging.go
  scripts/testdata/satellite-config.yaml.lock
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2165 Fix bucket_storage_tally data
  pkg/accounting/tally/tally.go
  pkg/accounting/tally/tally_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2202 NodeSelectionConfig inits and test cleanup
  internal/testplanet/planet.go
  pkg/overlay/cache_test.go
  pkg/overlay/selection_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2194 Repair should not corrupt files
  examples/eestream/serve-collected/main.go
  examples/eestream/serve/main.go
  pkg/datarepair/checker/checker.go
  pkg/datarepair/checker/checker_test.go
  pkg/datarepair/datarepair_test.go
  pkg/eestream/decode.go
  pkg/eestream/rs_test.go
  pkg/eestream/stripe.go
  pkg/storage/ec/client.go
  pkg/storage/segments/repairer.go
  pkg/storage/segments/repairer_test.go
Labels: Request Code Review, cla-signed

#2197 gitignore: cleanup old things
  .gitignore
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2208 increase audit timeout
  pkg/audit/service.go
  scripts/testdata/satellite-config.yaml.lock
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2204 fix satellite gui build
  web/satellite/src/types/segment.d.ts
  web/satellite/src/types/vue.d.ts
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2173 monkit: start reporting 10th percentile, remove init.ializers from everything
  go.mod
  go.sum
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2214 add fake id for segment.io
  web/satellite/src/plugins/analytics.ts
Labels: cla-signed

#2211 docs/design: Fix typos in disqualification
  docs/design/disqualification.md
Labels: Enhancement, Request Code Review, Reviewer Can Merge, cla-signed

#2209 Uplink C bindings part 2
  Makefile
  internal/testcontext/compile.go
  lib/uplink/object.go
  lib/uplinkc/alias.go
  lib/uplinkc/apikey.go
  lib/uplinkc/bucket.go
  lib/uplinkc/convert.go
  lib/uplinkc/project.go
  lib/uplinkc/testdata/apikey_test.c
  lib/uplinkc/testdata/bucket_test.c
  lib/uplinkc/testdata/helpers2.h
  lib/uplinkc/testdata/project_test.c
  lib/uplinkc/testdata_test.go
  lib/uplinkc/universe.go
  lib/uplinkc/uplink.go
  lib/uplinkc/uplink_definitions.h
  lib/uplinkc/uplink_test.go
  lib/uplinkc/utils_test.go
Labels: Code Review In-Progress, cla-signed

#2192 config: update release values to match prod
  pkg/accounting/live/live.go
  pkg/datarepair/checker/checker.go
  pkg/datarepair/repairer/repairer.go
  satellite/console/consoleweb/server.go
  scripts/testdata/satellite-config.yaml.lock
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2226 draft of removing stats from inspector
  cmd/inspector/main.go
  pkg/overlay/cache.go
  pkg/overlay/inspector.go
  pkg/pb/inspector.pb.go
  pkg/pb/inspector.proto
  pkg/pb/node.pb.go
  pkg/pb/node.proto
  proto.lock
Labels: Request Code Review, cla-signed

#2219 improve logging
  storagenode/piecestore/endpoint.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2220 add index on pieceinfo expireation for faster GetExpired calls
  storagenode/storagenodedb/infodb.go
  storagenode/storagenodedb/testdata/sqlite.v4.sql
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2223 Use zap.Stringer instead of zap.String
  pkg/audit/verifier.go
  pkg/certificates/certificates.go
  pkg/certificates/config.go
  pkg/discovery/service.go
  pkg/kademlia/endpoint.go
  satellite/console/consoleweb/consoleql/mutation.go
  satellite/console/consoleweb/server.go
  satellite/mailservice/service.go
  satellite/orders/endpoint.go
  satellite/orders/service.go
  storage/storelogger/logger.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2224 Use mail.test as domain in emails
  cmd/storj-sim/console.go
  cmd/storj-sim/network.go
  docs/design/marketing-offer-program.md
  internal/testplanet/planet.go
  pkg/certificates/certificates_test.go
  pkg/overlay/benchmark_test.go
  pkg/overlay/statdb_test.go
  satellite/console/consoleauth/claims_test.go
  satellite/console/consoleweb/consoleql/mutation_test.go
  satellite/console/consoleweb/consoleql/query_test.go
  satellite/console/projectmembers_test.go
  satellite/console/projectpayments_test.go
  satellite/console/projects_test.go
  satellite/console/resetpasswordtoken_test.go
  satellite/console/userpayments_test.go
  satellite/console/users_test.go
  satellite/payments/localpayments/local.go
  satellite/satellitedb/testdata/postgres.v0.sql
  satellite/satellitedb/testdata/postgres.v1.sql
  satellite/satellitedb/testdata/postgres.v10.sql
  satellite/satellitedb/testdata/postgres.v11.sql
  satellite/satellitedb/testdata/postgres.v12.sql
  satellite/satellitedb/testdata/postgres.v13.sql
  satellite/satellitedb/testdata/postgres.v14.sql
  satellite/satellitedb/testdata/postgres.v15.sql
  satellite/satellitedb/testdata/postgres.v16.sql
  satellite/satellitedb/testdata/postgres.v17.sql
  satellite/satellitedb/testdata/postgres.v18.sql
  satellite/satellitedb/testdata/postgres.v19.sql
  satellite/satellitedb/testdata/postgres.v2.sql
  satellite/satellitedb/testdata/postgres.v20.sql
  satellite/satellitedb/testdata/postgres.v21.sql
  satellite/satellitedb/testdata/postgres.v22.sql
  satellite/satellitedb/testdata/postgres.v23.sql
  satellite/satellitedb/testdata/postgres.v24.sql
  satellite/satellitedb/testdata/postgres.v25.sql
  satellite/satellitedb/testdata/postgres.v26.sql
  satellite/satellitedb/testdata/postgres.v27.sql
  satellite/satellitedb/testdata/postgres.v28.sql
  satellite/satellitedb/testdata/postgres.v29.sql
  satellite/satellitedb/testdata/postgres.v3.sql
  satellite/satellitedb/testdata/postgres.v30.sql
  satellite/satellitedb/testdata/postgres.v31.sql
  satellite/satellitedb/testdata/postgres.v4.sql
  satellite/satellitedb/testdata/postgres.v5.sql
  satellite/satellitedb/testdata/postgres.v6.sql
  satellite/satellitedb/testdata/postgres.v7.sql
  satellite/satellitedb/testdata/postgres.v8.sql
  satellite/satellitedb/testdata/postgres.v9.sql
  satellite/satellitedb/users_test.go
  scripts/test-certificate-signing.sh
  web/satellite/src/components/team/AddUserPopup.vue
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2175 update UI to reflect final mockups
  go.mod
  go.sum
  satellite/marketing/marketingweb/server.go
  web/marketing/css/style.css
  web/marketing/img/off.jpg
  web/marketing/img/on.jpg
  web/marketing/pages/banner.html
  web/marketing/pages/base.html
  web/marketing/pages/free-offers-modal.html
  web/marketing/pages/free-offers.html
  web/marketing/pages/freeOffers.html
  web/marketing/pages/home.html
  web/marketing/pages/index.html
  web/marketing/pages/internal-server-error.html
  web/marketing/pages/logo.html
  web/marketing/pages/page-not-found.html
  web/marketing/pages/refOffers.html
  web/marketing/pages/referral-offers-modal.html
  web/marketing/pages/referral-offers.html
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2203 Adds test coverage to CalculateBucketAtRestData
  pkg/accounting/tally/tally_test.go
Labels: cla-signed

#2101 Design Doc Notification System
  docs/design/notification-system.md
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2212 [v3-1914] Storage node disqualification: Change type from bool to timestamp
  docs/design/disqualification.md
  pkg/overlay/cache.go
  satellite/satellitedb/dbx/satellitedb.dbx
  satellite/satellitedb/dbx/satellitedb.dbx.go
  satellite/satellitedb/dbx/satellitedb.dbx.postgres.sql
  satellite/satellitedb/dbx/satellitedb.dbx.sqlite3.sql
  satellite/satellitedb/migrate.go
  satellite/satellitedb/overlaycache.go
  satellite/satellitedb/testdata/postgres.v32.sql
Labels: Request Code Review, cla-signed

#2166 Fix project email sign in and project links and comments
  web/satellite/static/emails/Invite.html
  web/satellite/static/emails/Welcome.html
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2217 Add node churn and containment/reverify monkit stats
  pkg/audit/verifier.go
  satellite/satellitedb/overlaycache.go
Labels: Request Code Review, Sprint Release Goal, cla-signed

#2200 value attribution DB interface Insert & Get method support
  pkg/valueattribution/valueattribution.go
  pkg/valueattribution/valueattribution_test.go
  satellite/peer.go
  satellite/satellitedb/database.go
  satellite/satellitedb/dbx/satellitedb.dbx
  satellite/satellitedb/dbx/satellitedb.dbx.go
  satellite/satellitedb/locked.go
  satellite/satellitedb/valueattribution.go
Labels: Code Review In-Progress, Request Code Review, Reviewer Can Merge, cla-signed

#2228 Modify build scripts for satellite ui
  satellite/console/consoleweb/server.go
  web/satellite/index.html
  web/satellite/package.json
  web/satellite/vue.config.js
Labels: Request Code Review, cla-signed

#2215 nodes db - adds alpha and beta reputation fields
  docs/design/node-selection.md
  satellite/satellitedb/dbx/satellitedb.dbx
  satellite/satellitedb/dbx/satellitedb.dbx.go
  satellite/satellitedb/dbx/satellitedb.dbx.postgres.sql
  satellite/satellitedb/dbx/satellitedb.dbx.sqlite3.sql
  satellite/satellitedb/migrate.go
  satellite/satellitedb/overlaycache.go
  satellite/satellitedb/testdata/postgres.v33.sql
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2230 Fix the gateway image build process
  cmd/gateway/Dockerfile
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2169 add db implementation for user_credits table
  satellite/console/database.go
  satellite/console/usercredits.go
  satellite/satellitedb/consoledb.go
  satellite/satellitedb/locked.go
  satellite/satellitedb/usercredits.go
  satellite/satellitedb/usercredits_test.go
Labels: Code Review In-Progress, Reviewer Can Merge, cla-signed

#2236 Console: Remove payments checks during project creation and member deletion
  satellite/console/service.go
  satellite/payments/localpayments/local.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2235 Speed up builds
  Makefile
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2234 removed fields
  pkg/overlay/benchmark_test.go
  pkg/overlay/cache.go
  pkg/overlay/statdb_test.go
  satellite/satellitedb/overlaycache.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2232 change ReputationAuditOmega (et al.) to AuditReputationWeight
  internal/testplanet/planet.go
  pkg/overlay/cache_test.go
  pkg/overlay/config.go
  scripts/testdata/satellite-config.yaml.lock
Labels: cla-signed

#2205 Expand the inspector tool to provide node id's for each segment, rather than just numeric totals
  cmd/inspector/main.go
  go.mod
  pkg/overlay/cache.go
  pkg/pb/inspector.pb.go
  pkg/pb/inspector.proto
  pkg/pb/metainfo.pb.go
  pkg/pb/node.pb.go
  proto.lock
  satellite/inspector/inspector.go
  satellite/satellitedb/locked.go
  satellite/satellitedb/overlaycache.go
Labels: Request Code Review, Sprint Release Goal, cla-signed

#2183 Always encrypt inline segments without padding
  lib/uplink/project.go
  lib/uplink/uplink.go
  pkg/accounting/tally/tally_test.go
  pkg/metainfo/kvmetainfo/buckets_test.go
  pkg/miniogw/gateway_test.go
  pkg/storage/streams/store.go
  pkg/storage/streams/store_test.go
  uplink/config.go
Labels: Backward Incompatible, Code Review In-Progress, Reviewer Can Merge, cla-signed

#2233 Avoid reporting audit failures for files deleted during audit
  pkg/audit/reverify_test.go
  pkg/audit/service.go
  pkg/audit/verifier.go
  pkg/audit/verifier_test.go
Labels: Request Code Review, cla-signed

#2238 Fixes for value attribution
  docs/design/value-attribution.md
  pkg/pb/metainfo.pb.go
  pkg/pb/metainfo.proto
  pkg/valueattribution/valueattribution.go
  pkg/valueattribution/valueattribution_test.go
  proto.lock
  satellite/attribution/db.go
  satellite/attribution/db_test.go
  satellite/metainfo/metainfo.go
  satellite/metainfo/metainfo_test.go
  satellite/peer.go
  satellite/satellitedb/attribution.go
  satellite/satellitedb/database.go
  satellite/satellitedb/dbx/satellitedb.dbx
  satellite/satellitedb/dbx/satellitedb.dbx.go
  satellite/satellitedb/locked.go
  satellite/satellitedb/valueattribution.go
  uplink/metainfo/client.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2245 code updates with comments
  docs/design/value-attribution.md
  satellite/satellitedb/dbx/satellitedb.dbx
Labels: cla-signed

#2222 Create protocol buffer for garbage collection
  docs/design/garbage-collection.md
  pkg/pb/gc.pb.go
  pkg/pb/gc.proto
  proto.lock
Labels: Request Code Review, cla-signed

#2241 add support to hide config settings
  pkg/cfgstruct/bind.go
  pkg/cfgstruct/bind_test.go
  pkg/cfgstruct/flags.go
  pkg/process/exec_conf.go
  pkg/process/exec_conf_test.go
  uplink/config.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2248 fix `C.time_t` error
  lib/uplinkc/convert.go
  lib/uplinkc/uplink_definitions.h
Labels: Code Review In-Progress, Reviewer Can Merge, cla-signed

#2249 Reduce expected disk size for storj-sim and testplanet
  cmd/storj-sim/network.go
  internal/testplanet/planet.go
Labels: cla-signed

#2237 update pr template
  .github/pull_request_template.md
Labels: cla-signed

#2243 cmd/storj-sim: ensure prefix writer can be used concurrently
  cmd/storj-sim/prefix.go
  cmd/storj-sim/prefix_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2253 Bind Jenkins Builds to specific nodes
  Jenkinsfile.gerrit
  Jenkinsfile.public
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2246 Fix checks around repair threshold
  internal/testplanet/uplink.go
  pkg/datarepair/checker/checker.go
  pkg/datarepair/checker/checker_test.go
  pkg/storage/ec/client.go
  satellite/metainfo/metainfo.go
  satellite/metainfo/metainfo_test.go
  storagenode/collector/service_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2254 Adding Andrew Harding
  .clabot
Labels: cla-signed

#2240 add user credit usage method into console service
  satellite/console/service.go
  satellite/console/usercredits.go
  satellite/satellitedb/locked.go
  satellite/satellitedb/usercredits.go
  satellite/satellitedb/usercredits_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2113 pkg/bloomfilter: implementation and benchmark results
  docs/design/garbage-collection.md
  pkg/bloomfilter/filter.go
  pkg/bloomfilter/filter_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2112 V3-1819 Storage node operator server and service started
  cmd/storj-sim/network.go
  go.sum
  storagenode/console/bandwidth.go
  storagenode/console/consoleserver/server.go
  storagenode/console/diskspace.go
  storagenode/console/service.go
  storagenode/peer.go
  storagenode/pieces/store.go
  storagenode/storagenodedb/consoledb.go
  storagenode/storagenodedb/pieceinfo.go
  web/operator/dist/build.js
  web/operator/dist/index.html
Labels: Request Code Review, cla-signed

#2255 Create graphql query for getting user credit usage
  satellite/console/consoleweb/consoleql/query.go
  satellite/console/consoleweb/consoleql/typecreator.go
  satellite/console/consoleweb/consoleql/usercredit.go
  web/satellite/src/api/usage.ts
  web/satellite/src/types/usage.d.ts
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2227 incorporate new reputation model into overlay cache methods
  pkg/audit/verifier.go
  pkg/overlay/benchmark_test.go
  pkg/overlay/cache.go
  pkg/overlay/cache_test.go
  pkg/overlay/config.go
  pkg/overlay/selection_test.go
  pkg/overlay/statdb_test.go
  satellite/orders/service.go
  satellite/satellitedb/dbx/satellitedb.dbx.go
  satellite/satellitedb/locked.go
  satellite/satellitedb/overlaycache.go
  scripts/testdata/satellite-config.yaml.lock
Labels: Request Code Review, cla-signed

#2259 pkg/audit: Move test helper funcs to separated file
  pkg/audit/testplanet_helpers_test.go
  pkg/audit/verifier_test.go
Labels: Enhancement, Request Code Review, Reviewer Can Merge, cla-signed

#2264 pkg/overlay: update node selection config values for reputation
  pkg/overlay/config.go
  scripts/testdata/satellite-config.yaml.lock
Labels: cla-signed

#2250 fix tally test flakiness
  pkg/accounting/tally/tally_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2269 internal/testplanet: add missing consoleserver.Config
  internal/testplanet/dir.go
  internal/testplanet/planet.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2257 lib/uplink: minor fixes
  lib/uplink/project.go
  pkg/metainfo/kvmetainfo/buckets.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2273 accounting_test compilation fixes
  pkg/accounting/db_test.go
  pkg/accounting/projectusage_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2261 Include Node ID and Piece ID in piecestore errors
  uplink/piecestore/download.go
Labels: Request Code Review, Sprint Release Goal, cla-signed

#2278 satellite: send external address in order limits
  pkg/pb/orders.pb.go
  pkg/pb/orders.proto
  proto.lock
  satellite/orders/service.go
  satellite/peer.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2251 satellite: make order expiration configurable
  internal/testplanet/planet.go
  satellite/orders/service.go
  satellite/peer.go
  scripts/testdata/satellite-config.yaml.lock
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2277 kvmetainfo: merge with storage/buckets
  lib/uplink/project.go
  lib/uplink/uplink.go
  pkg/metainfo/kvmetainfo/buckets.go
  pkg/metainfo/kvmetainfo/buckets_test.go
  pkg/metainfo/kvmetainfo/metainfo.go
  pkg/metainfo/kvmetainfo/objects.go
  pkg/metainfo/kvmetainfo/objects_test.go
  pkg/metainfo/kvmetainfo/prefixed.go
  pkg/metainfo/kvmetainfo/project.go
  pkg/miniogw/gateway_test.go
  pkg/storage/buckets/store.go
  uplink/config.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed
