Repository storj/storj, pull requests merged in 2019-03, with the labels that each got.

#1387 accounting: support null wallet addresses
  satellite/satellitedb/accounting.go
Labels: cla-signed

#1380 More fixes to piecestore
  pkg/piecestore/psserver/collector.go
  pkg/piecestore/psserver/psdb/migrate_test.go
  pkg/piecestore/psserver/psdb/psdb.go
  pkg/piecestore/psserver/psdb/psdb_test.go
  pkg/piecestore/psserver/retrieve.go
  pkg/piecestore/psserver/server.go
  pkg/piecestore/psserver/server_test.go
  pkg/piecestore/pstore.go
  storagenode/peer.go
  storagenode/storagenodedb/database.go
Labels: Request Code Review, cla-signed

#1388 remove unused date field
  pkg/accounting/common.go
Labels: cla-signed

#1368 Change payments to use statDB for wallet addresses rather than Overlay cache
  cmd/satellite/usage.go
  pkg/discovery/service.go
  pkg/statdb/statdb.go
  pkg/statdb/statdb_test.go
  satellite/satellitedb/dbx/satellitedb.dbx
  satellite/satellitedb/dbx/satellitedb.dbx.go
  satellite/satellitedb/dbx/satellitedb.dbx.postgres.sql
  satellite/satellitedb/dbx/satellitedb.dbx.sqlite3.sql
  satellite/satellitedb/locked.go
  satellite/satellitedb/migrate.go
  satellite/satellitedb/migrate_postgres_test.go
  satellite/satellitedb/statdb.go
  satellite/satellitedb/testdata/postgres.v5.sql
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1393 web ui: change default graphql endpoint
  web/satellite/src/utils/apolloManager.ts
Labels: cla-signed

#1394 Use DialNode for requesting node info
  cmd/inspector/main.go
  pkg/discovery/service.go
  pkg/kademlia/dialer.go
  pkg/kademlia/inspector.go
  pkg/kademlia/kademlia.go
  pkg/kademlia/kademlia_planet_test.go
  pkg/pb/inspector.pb.go
  pkg/pb/inspector.proto
  pkg/transport/transport.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1302 Add mail service to the satellite
  cmd/storj-sim/network.go
  internal/post/message.go
  internal/post/oauth2/auth.go
  internal/post/sender.go
  internal/testplanet/planet.go
  satellite/console/consoleweb/consoleql/mail.go
  satellite/console/consoleweb/consoleql/mutation.go
  satellite/console/consoleweb/consoleql/mutation_test.go
  satellite/console/consoleweb/consoleql/query_test.go
  satellite/console/consoleweb/consoleql/schema.go
  satellite/console/consoleweb/consoleql/testdata/Welcome.html
  satellite/console/consoleweb/consoleql/typecreator.go
  satellite/console/consoleweb/server.go
  satellite/console/service.go
  satellite/mailservice/service.go
  satellite/mailservice/simulate/linkclicker.go
  satellite/peer.go
  web/satellite/static/emails/Forgot.html
  web/satellite/static/emails/Invite.html
  web/satellite/static/emails/Welcome.html
Labels: Request Code Review, cla-signed

#1396 Reduce Log Messages on Production Settings
  pkg/accounting/tally/tally.go
  pkg/piecestore/psclient/readerwriter.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1397 Ensure ECClient upload timer is stopped when no more status is expected
  pkg/storage/ec/client.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1382 Cleanup errors handling around piece hash verification
  pkg/piecestore/psclient/client.go
  pkg/piecestore/psclient/readerwriter.go
Labels: cla-signed

#1391 Handles zero bucket count and bucket with no files
  pkg/accounting/tally/tally.go
Labels: cla-signed

#1395 [V3-1320] fix empty node ID verification non-error
  cmd/certificates/verify.go
  examples/grpc-debug/main.go
  pkg/auth/signedMessage.go
  pkg/bwagreement/server_test.go
  pkg/certificates/certificates.go
  pkg/certificates/certificates_test.go
  pkg/identity/certificate_authority.go
  pkg/identity/identity.go
  pkg/kademlia/dialer.go
  pkg/kademlia/dialer_test.go
  pkg/kademlia/kademlia.go
  pkg/kademlia/peer_discovery.go
  pkg/kademlia/routing_integration_helpers_test.go
  pkg/kademlia/routing_integration_test.go
  pkg/peertls/tlsopts/options.go
  pkg/peertls/tlsopts/options_test.go
  pkg/peertls/tlsopts/tls.go
  pkg/peertls/tlsopts/tls_helpers_test.go
  pkg/peertls/tlsopts/tls_test.go
  pkg/piecestore/psserver/server_test.go
  pkg/transport/transport.go
  pkg/transport/transport_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1401 Update .clabot
  .clabot
Labels: cla-signed

#1399 tlsconfig refactor / cleanup
  pkg/peertls/tlsopts/options.go
  pkg/peertls/tlsopts/options_test.go
  pkg/peertls/tlsopts/tls.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1400 Update README.md
  cmd/uplink/README.md
Labels: cla-signed

#1405 V3-1284 Node bootstrap web frontend
  web/bootstrap/.gitignore
  web/bootstrap/babel.config.js
  web/bootstrap/index.html
  web/bootstrap/package.json
  web/bootstrap/src/App.vue
  web/bootstrap/src/api/bootstrap.ts
  web/bootstrap/src/main.ts
  web/bootstrap/src/router/index.ts
  web/bootstrap/src/store/index.ts
  web/bootstrap/src/types/nodeStatus.ts
  web/bootstrap/src/utils/apolloManager.ts
  web/bootstrap/src/utils/constants.ts
  web/bootstrap/src/views/Failure.vue
  web/bootstrap/src/views/Loading.vue
  web/bootstrap/src/views/Search.vue
  web/bootstrap/src/views/Success.vue
  web/bootstrap/tsconfig.json
  web/bootstrap/tslint.json
  web/bootstrap/vue.config.js
  web/bootstrap/webpack.config.dev.js
Labels: cla-signed

#1406 Implemented API keys fetch on login.
  web/satellite/src/components/header/projectSelection/ProjectSelectionDropdown.vue
  web/satellite/src/views/Dashboard.vue
Labels: cla-signed

#1407 convert psserver dashboard into an inspector
  cmd/storagenode/dashboard.go
  pkg/pb/inspector.pb.go
  pkg/pb/inspector.proto
  pkg/pb/piecestore.pb.go
  pkg/pb/piecestore.pb.mock.go
  pkg/pb/piecestore.proto
  pkg/piecestore/psclient/liteclient.go
  pkg/piecestore/psserver/bucket_refresher.go
  pkg/piecestore/psserver/inspector.go
  pkg/piecestore/psserver/server.go
  proto.lock
  scripts/check-imports.go
  storagenode/peer.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1374 Enhance the Storage Node to keep all BWA's for 90 days
  pkg/piecestore/psserver/agreementsender/agreementsender.go
  pkg/piecestore/psserver/psdb/psdb.go
  pkg/piecestore/psserver/psdb/psdb_test.go
  pkg/piecestore/psserver/psdb/testdata/sqlite.v2.sql
Labels: Request Code Review, cla-signed

#1404 allocates 1kb for audit bandwidth agreements instead of 256kb
  pkg/audit/verifier.go
Labels: cla-signed

#1411 Add new piece id definition
  internal/testplanet/identities.go
  pkg/piecestore/psclient/pieceid_test.go
  pkg/storj/node.go
  pkg/storj/object.go
  pkg/storj/pieceid.go
  pkg/storj/pieceid_test.go
Labels: cla-signed

#1403 [V3-1147] Ensure certificate validation happens properly
  pkg/peertls/tlsopts/options.go
  pkg/peertls/tlsopts/options_test.go
  pkg/peertls/tlsopts/tls.go
  pkg/transport/transport_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1412 V3-1095 Update service to send invitations in project
  satellite/console/consoleweb/consoleql/mutation.go
  satellite/console/consoleweb/consoleql/query_test.go
  satellite/console/consoleweb/consoleql/testdata/Invite.html
  satellite/console/service.go
  web/satellite/static/images/emails/Logo.png
Labels: cla-signed

#1340 Bucket usage info rollup table creation and implementation
  pkg/accounting/bucketusage.go
  pkg/accounting/bucketusage_test.go
  satellite/console/database.go
  satellite/mailservice/service.go
  satellite/satellitedb/bucketusage.go
  satellite/satellitedb/consoledb.go
  satellite/satellitedb/dbx/satellitedb.dbx
  satellite/satellitedb/dbx/satellitedb.dbx.go
  satellite/satellitedb/dbx/satellitedb.dbx.postgres.sql
  satellite/satellitedb/dbx/satellitedb.dbx.sqlite3.sql
  satellite/satellitedb/locked.go
  satellite/satellitedb/migrate.go
  satellite/satellitedb/testdata/postgres.v6.sql
Labels: Request Code Review, cla-signed

#1415 codeowners
  .github/CODEOWNERS
Labels: cla-signed

#1416 Latest containers for release branches
  Makefile
Labels: cla-signed

#1419 Activation status pages
  web/satellite/static/activation/error.css
  web/satellite/static/activation/error.html
  web/satellite/static/activation/success.css
  web/satellite/static/activation/success.html
Labels: cla-signed

#1420 Adding fix for release branch latest tag pushing
  Makefile
Labels: cla-signed

#1398 add private listener to grpc server
  bootstrap/peer.go
  cmd/inspector/main.go
  cmd/storagenode/dashboard.go
  cmd/storagenode/main.go
  cmd/storj-sim/network.go
  pkg/certificates/certificates_test.go
  pkg/piecestore/psserver/server_test.go
  pkg/server/config.go
  pkg/server/server.go
  pkg/transport/insecure.go
  satellite/peer.go
  storagenode/peer.go
Labels: Request Code Review, cla-signed

#1423 Fixing tabs in makefile
  Makefile
Labels: cla-signed

#1426 psdb: index on serial number for bandwidth_agreements
  pkg/piecestore/psserver/psdb/psdb.go
  pkg/piecestore/psserver/psdb/testdata/sqlite.v3.sql
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1408 Improve bwa tests
  pkg/bwagreement/server_test.go
  pkg/piecestore/psserver/server_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1429 Hammer: auth/signing package
  pkg/auth/signing/encode.go
  pkg/auth/signing/peers.go
  pkg/auth/signing/sign.go
  pkg/auth/signing/verify.go
Labels: WIP, cla-signed

#1427 Hammer: uplink/piecestore streaming
  pkg/utils/io.go
  storagenode/piecestore/encoding.go
  storagenode/piecestore/endpoint.go
  storagenode/piecestore/verification.go
  storagenode/trust/service.go
  uplink/piecestore/client.go
  uplink/piecestore/download.go
  uplink/piecestore/signatures.go
  uplink/piecestore/streaming.go
  uplink/piecestore/upload.go
Labels: WIP, cla-signed

#1421 Satellite console new activation flow
  cmd/storj-sim/console.go
  cmd/storj-sim/network.go
  satellite/console/consoleweb/consoleql/mutation.go
  satellite/console/consoleweb/consoleql/mutation_test.go
  satellite/console/consoleweb/consoleql/query_test.go
  satellite/console/consoleweb/server.go
  satellite/console/service.go
  web/satellite/src/api/users.ts
  web/satellite/src/store/modules/users.ts
  web/satellite/src/views/Dashboard.vue
  web/satellite/static/activation/success.html
  web/satellite/static/errors/404.css
  web/satellite/static/errors/404.html
Labels: cla-signed

#1432 Metainfo API
  pkg/pb/metainfo.pb.go
  pkg/pb/metainfo.proto
  pkg/pointerdb/allocation.go
  pkg/storage/ec/client.go
  pkg/storage/segments/repairer.go
  pkg/storage/segments/store.go
  satellite/metainfo/metainfo.go
  satellite/peer.go
  uplink/config.go
  uplink/metainfo/client.go
Labels: cla-signed

#1433 Ensure we only listen on 127.0.0.1
  internal/testplanet/planet.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1431 Hammer: piecestore.Client and piecestore.Endpoint communication
  internal/testplanet/uplink.go
  storagenode/peer.go
  storagenode/piecestore/endpoint.go
  storagenode/piecestore/endpoint_test.go
  storagenode/piecestore/serials.go
  storagenode/piecestore/verification.go
  storagenode/trust/service.go
  uplink/piecestore/client.go
  uplink/piecestore/verification.go
Labels: WIP, cla-signed

#1438 add index created_at on bwagreements
  satellite/satellitedb/migrate.go
  satellite/satellitedb/testdata/postgres.v7.sql
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1437 filestore changes for piece store
  storage/blob.go
  storage/filestore/blob.go
  storage/filestore/dir.go
  storage/filestore/dir_unix.go
  storage/filestore/dir_windows.go
  storage/filestore/offset.go
  storage/filestore/store.go
  storage/filestore/store_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1440 Hammer: implement piece storage
  pkg/pkcrypto/hashing.go
  storagenode/peer.go
  storagenode/pieces/readwrite.go
  storagenode/pieces/store.go
  storagenode/piecestore/endpoint.go
  storagenode/storagenodedb/database.go
  uplink/piecestore/upload.go
Labels: Request Code Review, cla-signed

#1441 Signing improvements
  satellite/metainfo/metainfo.go
  satellite/peer.go
  uplink/piecestore/download.go
  uplink/piecestore/upload.go
Labels: cla-signed

#1442 hammer: fix nil order
  storagenode/piecestore/endpoint.go
Labels: cla-signed

#1443 Use WhitelistedSatelliteIDs in testplanet
  internal/testplanet/planet.go
Labels: cla-signed

#1447 hammer: ensure trust all works in storagenode/trust
  internal/testplanet/planet.go
  pkg/piecestore/psserver/server.go
  storagenode/peer.go
  storagenode/piecestore/verification.go
  storagenode/trust/service.go
  uplink/piecestore/upload.go
Labels: cla-signed

#1450 hammer: add better error messages
  storagenode/piecestore/endpoint.go
  uplink/piecestore/download.go
Labels: cla-signed

#1444 ECClient uses new piecestore.Client
  pkg/pb/pointerdb.pb.go
  pkg/pb/pointerdb.proto
  pkg/storage/ec/client.go
  pkg/storage/segments/repairer.go
  pkg/storage/segments/store.go
  satellite/metainfo/metainfo.go
  storagenode/piecestore/endpoint.go
  uplink/config.go
  uplink/metainfo/client.go
Labels: cla-signed

#1455 hammer: EOF handling
  pkg/accounting/tally/tally.go
  pkg/audit/service.go
  storage/filestore/dir.go
  storage/filestore/dir_windows.go
  storagenode/piecestore/endpoint.go
  storagenode/piecestore/verification.go
  uplink/piecestore/client.go
  uplink/piecestore/download.go
  uplink/piecestore/upload.go
Labels: WIP, cla-signed

#1456 hammer: reenable integration
  .travis.yml
Labels: cla-signed

#1457 hammer: upload/download buffering
  uplink/piecestore/buffering.go
  uplink/piecestore/client.go
  uplink/piecestore/download.go
  uplink/piecestore/upload.go
Labels: cla-signed

#1430 Development defaults for configuration
  cmd/bootstrap/main.go
  cmd/certificates/main.go
  cmd/gateway/main.go
  cmd/identity/batch.go
  cmd/identity/certificate_authority.go
  cmd/identity/identity.go
  cmd/identity/main.go
  cmd/identity/revocations.go
  cmd/overlay/main.go
  cmd/satellite/main.go
  cmd/statreceiver/main.go
  cmd/storagenode/main.go
  cmd/storj-sim/main.go
  cmd/storj-sim/network.go
  cmd/uplink/cmd/root.go
  cmd/uplink/cmd/setup.go
  examples/grpc-debug/main.go
  internal/testplanet/uplink.go
  pkg/accounting/rollup/rollup.go
  pkg/accounting/tally/tally.go
  pkg/cfgstruct/bind.go
  pkg/cfgstruct/bind_test.go
  pkg/miniogw/integration_test.go
Labels: Request Code Review, cla-signed

#1439 framework to delete raw accounting tallies
  pkg/accounting/db.go
  pkg/accounting/rollup/rollup.go
  pkg/accounting/rollup/rollup_test.go
  satellite/satellitedb/accounting.go
  satellite/satellitedb/dbx/gen.go
  satellite/satellitedb/locked.go
Labels: Request Code Review, cla-signed

#1451 Add Application Name to PostgreSQL Connection String
  internal/dbutil/pgutil/db.go
  satellite/satellitedb/database.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1425 judicious import path checking
  pkg/identity/common.go
  pkg/peertls/peertls.go
  pkg/process/exec.go
  pkg/storj/node.go
Labels: cla-signed

#1460 hammer: quick fix for data-race
  uplink/piecestore/buffering.go
  uplink/piecestore/download.go
  uplink/piecestore/upload.go
Labels: cla-signed

#1459 Extracts utility methods for properly calculating piece size
  pkg/eestream/encode.go
  pkg/encryption/encryption.go
  pkg/pb/metainfo.pb.go
  pkg/pb/metainfo.proto
  pkg/storage/segments/repairer.go
  pkg/storage/segments/store.go
  satellite/metainfo/metainfo.go
  uplink/config.go
  uplink/metainfo/client.go
Labels: cla-signed

#1461 hammer: cleaner lazy ranger construction
  pkg/storage/ec/client.go
Labels: cla-signed

#1384 Warn about permissions when creating identity
  cmd/certificates/setup.go
  cmd/identity/identity.go
  cmd/identity/main.go
  pkg/identity/certificate_authority.go
  pkg/identity/identity.go
  pkg/identity/utils.go
  pkg/utils/utils.go
Labels: Request Code Review, cla-signed

#1464 Move iswriteable to fpath
  cmd/identity/main.go
  internal/fpath/os.go
  pkg/utils/utils.go
Labels: cla-signed

#1462 fix piece id derivation
  pkg/storj/pieceid.go
  pkg/storj/pieceid_test.go
Labels: Request Code Review, cla-signed

#1435 Removes concept of email from kademlia metadata
  bootstrap/peer.go
  pkg/discovery/service.go
  pkg/kademlia/kademlia_test.go
  satellite/peer.go
  storagenode/peer.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1436 framework for deleting expired Orders from Satellite
  pkg/accounting/tally/tally.go
  pkg/bwagreement/bwagreement_test.go
  pkg/bwagreement/server.go
  pkg/storj/node.go
  pkg/storj/node_test.go
  satellite/satellitedb/bandwidthagreement.go
  satellite/satellitedb/dbx/satellitedb.dbx
  satellite/satellitedb/dbx/satellitedb.dbx.go
  satellite/satellitedb/locked.go
Labels: Request Code Review, cla-signed

#1465 Fix kvmetainfo tests
  internal/testplanet/uplink.go
  pkg/metainfo/kvmetainfo/buckets_test.go
  pkg/metainfo/kvmetainfo/objects_test.go
  pkg/storage/segments/store.go
  uplink/config.go
Labels: cla-signed

#1446 hammer: new sqlite schema for storage node
  cmd/storagenode/main.go
  pkg/storj/pieceid.go
  storage/filestore/store.go
  storagenode/pieces/store.go
  storagenode/storagenodedb/bandwidthusage.go
  storagenode/storagenodedb/bandwidthusage_test.go
  storagenode/storagenodedb/certdb.go
  storagenode/storagenodedb/certdb_test.go
  storagenode/storagenodedb/database.go
  storagenode/storagenodedb/infodb.go
  storagenode/storagenodedb/orders.go
  storagenode/storagenodedb/orders_test.go
  storagenode/storagenodedb/pieceinfo.go
  storagenode/storagenodedb/pieceinfo_test.go
  storagenode/storagenodedb/usedserials.go
  storagenode/storagenodedb/usedserials_test.go
Labels: cla-signed

#1469 New orders protobuf
  pkg/pb/metainfo.pb.go
  pkg/pb/metainfo.proto
  pkg/pb/orders.pb.go
  pkg/pb/orders.proto
  pkg/pb/piecestore2.pb.go
  pkg/pb/piecestore2.proto
  pkg/pb/pointerdb.pb.go
  pkg/pb/pointerdb.proto
  pkg/pointerdb/pointerdb.go
  pkg/storage/segments/store.go
  proto.lock
  satellite/metainfo/metainfo.go
Labels: cla-signed

#1470 Rework ECClient tests on testplanet
  pkg/storage/ec/client.go
  pkg/storage/ec/client_planet_test.go
  pkg/storage/ec/client_test.go
  pkg/storage/ec/psclient_mock_test.go
  pkg/storage/ec/transportclient_mock_test.go
Labels: cla-signed

#1474 hammer: move database interfaces to a better place
  storagenode/bandwidth/db_test.go
  storagenode/bandwidth/usage.go
  storagenode/orders/db_test.go
  storagenode/orders/sender.go
  storagenode/peer.go
  storagenode/pieces/db_test.go
  storagenode/pieces/store.go
  storagenode/piecestore/endpoint.go
  storagenode/piecestore/inspector.go
  storagenode/piecestore/serials.go
  storagenode/piecestore/serials_test.go
  storagenode/storagenodedb/bandwidthdb.go
  storagenode/storagenodedb/bandwidthusage_test.go
  storagenode/storagenodedb/certdb.go
  storagenode/storagenodedb/certdb_test.go
  storagenode/storagenodedb/orders.go
  storagenode/storagenodedb/orders_test.go
  storagenode/storagenodedb/pieceinfo.go
  storagenode/storagenodedb/pieceinfo_test.go
  storagenode/storagenodedb/storagenodedbtest/run.go
  storagenode/storagenodedb/storagenodedbtest/run_test.go
  storagenode/storagenodedb/usedserials.go
  storagenode/storagenodedb/usedserials_test.go
  storagenode/trust/certdb.go
  storagenode/trust/certdb_test.go
Labels: cla-signed

#1473 Update gateway tests
  pkg/miniogw/gateway_test.go
Labels: cla-signed

#1477 hammer: removing stubs from endpoint
  storagenode/collector/service.go
  storagenode/peer.go
  storagenode/pieces/db_test.go
  storagenode/pieces/store.go
  storagenode/piecestore/endpoint.go
  storagenode/piecestore/serials.go
  storagenode/piecestore/verification.go
  storagenode/storagenodedb/pieceinfo.go
Labels: Request Code Review, cla-signed

#1478 hammer: reenable all tests
  .travis.yml
Labels: cla-signed

#1480 hammer: Fix pointerdb tests
  pkg/pointerdb/pointerdb_test.go
Labels: cla-signed

#1482 hammer: Use concactenated der format
  storagenode/storagenodedb/certdb.go
  storagenode/storagenodedb/orders.go
  storagenode/storagenodedb/pieceinfo.go
Labels: cla-signed

#1483 hammer: reenable linter
  .travis.yml
Labels: cla-signed

#1481 Adapt Repairer to new API
  internal/testplanet/planet.go
  pkg/datarepair/repairer/config.go
  pkg/datarepair/repairer/repairer.go
  pkg/storage/segments/repairer.go
  pkg/storage/segments/store.go
  satellite/metainfo/metainfo.go
  satellite/peer.go
Labels: cla-signed

#1484 hammer: uplink cancellation
  pkg/storage/ec/client.go
  scripts/test-uplink.sh
  storagenode/piecestore/endpoint.go
  uplink/piecestore/buffering.go
  uplink/piecestore/download.go
  uplink/piecestore/upload.go
Labels: WIP, cla-signed

#1485 hammer: linting errors
  pkg/accounting/tally/tally.go
  pkg/audit/service.go
  pkg/auth/signing/encode.go
  pkg/auth/signing/peers.go
  pkg/auth/signing/sign.go
  pkg/auth/signing/verify.go
  pkg/pointerdb/allocation.go
  satellite/peer.go
  storagenode/bandwidth/db_test.go
  storagenode/collector/service.go
  storagenode/monitor/service.go
  storagenode/orders/sender.go
  storagenode/pieces/readwrite.go
  storagenode/pieces/store.go
  storagenode/piecestore/verification.go
  uplink/config.go
  uplink/piecestore/buffering.go
  uplink/piecestore/client.go
  uplink/piecestore/download.go
  uplink/piecestore/upload.go
  uplink/piecestore/verification.go
Labels: cla-signed

#1486 hammer: more linting
  cmd/storj-sim/network.go
  pkg/auth/signing/sign.go
  pkg/storage/ec/client_planet_test.go
  storagenode/pieces/store.go
  storagenode/piecestore/endpoint.go
  storagenode/piecestore/verification.go
  storagenode/storagenodedb/database.go
  storagenode/storagenodedb/infodb.go
  storagenode/trust/service.go
  uplink/piecestore/client.go
Labels: cla-signed

#1471 Web buckets page markup
  web/satellite/src/components/buckets/BucketArea.vue
  web/satellite/src/components/buckets/BucketItem.vue
  web/satellite/src/components/buckets/PaginationArea.vue
  web/satellite/src/components/buckets/SearchArea.vue
  web/satellite/src/components/buckets/SortingHeader.vue
  web/satellite/src/components/navigation/NavigationArea.vue
  web/satellite/src/router/index.ts
  web/satellite/src/utils/constants/navigationLinks.ts
  web/satellite/src/utils/constants/routerConstants.ts
Labels: cla-signed

#1489 hammer: consistent KB vs KiB usage
  cmd/s3-benchmark/main.go
  internal/sync2/copy_test.go
  internal/testcontext/context.go
  internal/testplanet/planet.go
  pkg/metainfo/kvmetainfo/buckets_test.go
  pkg/metainfo/kvmetainfo/metainfo.go
  pkg/metainfo/kvmetainfo/objects.go
  pkg/metainfo/kvmetainfo/objects_test.go
  pkg/miniogw/gateway_test.go
  storagenode/trust/service.go
Labels: cla-signed

#1488 hammer: Adapt audit service to new API
  pkg/audit/cursor.go
  pkg/audit/cursor_test.go
  pkg/audit/service.go
  pkg/audit/verifier.go
Labels: cla-signed

#1491 hammer: Remove old repairer tests - Moby will add new tests
  pkg/storage/ec/mocks/mock_client.go
  pkg/storage/segments/repairer_test.go
Labels: cla-signed

#1490 hammer: remove psclient
  pkg/piecestore/psclient/client.go
  pkg/piecestore/psclient/pieceid.go
  pkg/piecestore/psclient/pieceid_test.go
  pkg/piecestore/psclient/pieceranger.go
  pkg/piecestore/psclient/pieceranger_test.go
  pkg/piecestore/psclient/readerwriter.go
  pkg/storage/ec/client_test.go
Labels: cla-signed

#1487 hammer: Piecestore inspector/dashboard
  cmd/storagenode/dashboard.go
  pkg/pb/inspector.pb.go
  pkg/pb/inspector.proto
  pkg/piecestore/psserver/inspector.go
  proto.lock
  storagenode/bandwidth/usage.go
  storagenode/peer.go
  storagenode/pieces/store.go
  storagenode/piecestore/endpoint.go
  storagenode/piecestore/inspector.go
  storagenode/piecestore/inspector_test.go
  storagenode/storagenodedb/pieceinfo.go
Labels: cla-signed

#1472 hammer: Update segment.Store tests
  pkg/metainfo/kvmetainfo/buckets_test.go
  pkg/miniogw/gateway_test.go
  pkg/storage/ec/client_planet_test.go
  pkg/storage/segments/store.go
  pkg/storage/segments/store_test.go
  satellite/metainfo/metainfo.go
  uplink/config.go
Labels: cla-signed

#1493 hammer: Replace old PieceID with the new definition
  internal/teststorj/pieceid.go
  pkg/audit/cursor.go
  pkg/audit/cursor_test.go
  pkg/datarepair/checker/checker_test.go
  pkg/metainfo/kvmetainfo/objects_test.go
  pkg/metainfo/kvmetainfo/stream.go
  pkg/pb/pointerdb.pb.go
  pkg/pb/pointerdb.proto
  pkg/pb/streams.pb.go
  pkg/pb/types.go
  pkg/pointerdb/allocation.go
  pkg/pointerdb/pdbclient/client_test.go
  pkg/storage/ec/client_planet_test.go
  pkg/storage/segments/repairer.go
  pkg/storage/segments/store.go
  pkg/storj/object.go
  pkg/storj/pieceid.go
  proto.lock
  satellite/metainfo/metainfo.go
  storagenode/pieces/store.go
  storagenode/storagenodedb/pieceinfo.go
  uplink/metainfo/client.go
Labels: cla-signed

#1466 Repair queue isolation level fix
  pkg/accounting/db.go
  pkg/accounting/rollup/rollup.go
  pkg/accounting/tally/tally.go
  pkg/bwagreement/bwagreement_test.go
  pkg/bwagreement/server.go
  pkg/datarepair/queue/queue_test.go
  pkg/pb/scannerValuer.go
  satellite/satellitedb/accounting.go
  satellite/satellitedb/bandwidthagreement.go
  satellite/satellitedb/locked.go
  satellite/satellitedb/repairqueue.go
Labels: Request Code Review, cla-signed

#1497 hammer: few tests for piecestore and pieces
  internal/testplanet/uplink.go
  pkg/piecestore/pstore_test.go
  storagenode/bandwidth/usage.go
  storagenode/pieces/store_test.go
  storagenode/piecestore/endpoint_test.go
  uplink/piecestore/client.go
Labels: cla-signed

#1496 hammer: Fix repairer identity issue
  pkg/datarepair/repairer/config.go
  pkg/datarepair/repairer/repairer.go
  pkg/storage/segments/repairer.go
Labels: cla-signed

#1498 hammer: set node restrictions in FindStorageNodesRequest
  satellite/metainfo/metainfo.go
Labels: cla-signed

#1500 hammer: disable collector
  storagenode/peer.go
Labels: cla-signed

#1448 Add ability to view irreparable segments on satellite
  cmd/inspector/main.go
  go.mod
  pkg/datarepair/checker/checker.go
  pkg/datarepair/checker/checker_test.go
  pkg/datarepair/irreparable/inspector.go
  pkg/datarepair/irreparable/irreparable.go
  pkg/datarepair/irreparable/irreparable_test.go
  pkg/pb/bandwidth.pb.go
  pkg/pb/certificate.pb.go
  pkg/pb/datarepair.pb.go
  pkg/pb/inspector.pb.go
  pkg/pb/inspector.proto
  pkg/pb/meta.pb.go
  pkg/pb/node.pb.go
  pkg/pb/overlay.pb.go
  pkg/pb/pointerdb.pb.go
  pkg/pb/streams.pb.go
  satellite/peer.go
  satellite/satellitedb/dbx/satellitedb.dbx
  satellite/satellitedb/dbx/satellitedb.dbx.go
  satellite/satellitedb/irreparabledb.go
  satellite/satellitedb/locked.go
Labels: cla-signed

#1504 some fixes to repairer.Repair()
  pkg/storage/segments/repairer.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1505 Use share size instead of piece size as limit for audits
  pkg/audit/cursor.go
Labels: cla-signed

#1506 Rename Action protobuf to PieceAction
  pkg/audit/cursor.go
  pkg/pb/orders.pb.go
  pkg/pb/orders.proto
  pkg/pointerdb/allocation.go
  pkg/storage/ec/client_planet_test.go
  pkg/storage/segments/repairer.go
  proto.lock
  satellite/metainfo/metainfo.go
  storagenode/bandwidth/db_test.go
  storagenode/bandwidth/usage.go
  storagenode/orders/db_test.go
  storagenode/piecestore/endpoint.go
  storagenode/storagenodedb/bandwidthdb.go
Labels: cla-signed

#1499 hammer: storage node monitor
  storage/blob.go
  storage/filestore/dir.go
  storage/filestore/store.go
  storagenode/inspector/inspector.go
  storagenode/inspector/inspector_test.go
  storagenode/monitor/monitor.go
  storagenode/monitor/monitor_test.go
  storagenode/monitor/service.go
  storagenode/peer.go
  storagenode/pieces/store.go
  storagenode/piecestore/endpoint.go
Labels: Request Code Review, cla-signed

#1508 Add serial number type
  pkg/pb/inspector.pb.go
  pkg/pb/metainfo.pb.go
  pkg/pb/orders.pb.go
  pkg/pb/orders.proto
  pkg/pb/piecestore2.pb.go
  pkg/pb/pointerdb.pb.go
  pkg/pb/streams.pb.go
  pkg/pb/types.go
  pkg/pointerdb/allocation.go
  pkg/storage/ec/client_planet_test.go
  pkg/storj/pieceid.go
  pkg/storj/pieceid_test.go
  pkg/storj/serialnumber.go
  pkg/storj/serialnumber_test.go
  storagenode/orders/db_test.go
  storagenode/piecestore/serials.go
  storagenode/piecestore/serials_test.go
  storagenode/piecestore/verification.go
  storagenode/storagenodedb/usedserials.go
Labels: Request Code Review, cla-signed

#1511 storagenode/pieces: ensure we can call Commit or Cancel only once
  storage/filestore/blob.go
  storage/filestore/store_test.go
  storagenode/pieces/readwrite.go
  storagenode/pieces/store_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1512 fix startup message formatting
  bootstrap/peer.go
  satellite/peer.go
  storagenode/peer.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1510 Remove overlay client
  internal/testplanet/uplink.go
  pkg/overlay/client.go
  pkg/overlay/client_test.go
  pkg/overlay/mocks/mock_client.go
Labels: Request Code Review, cla-signed

#1516 remove free disk check since it's unreliable
  storagenode/monitor/monitor_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1453 better way to check if err is ErrorCode_NoRows
  satellite/satellitedb/dbx/satellitedb.dbx
  satellite/satellitedb/dbx/satellitedb.dbx.go
  satellite/satellitedb/statdb.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1519 Fix storage node path handling
  cmd/storagenode/main.go
  cmd/storj-sim/network.go
  cmd/storj-sim/process.go
  pkg/piecestore/psserver/config.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1507 faster agreement sender
  pkg/accounting/tally/tally_test.go
  pkg/bwagreement/server.go
  pkg/pb/bandwidth.pb.go
  pkg/pb/bandwidth.proto
  pkg/piecestore/psserver/agreementsender/agreementsender.go
Labels: Request Code Review, cla-signed

#1509 Add Repair method to ECClient
  pkg/datarepair/repairer/config.go
  pkg/storage/ec/client.go
  pkg/storage/segments/repairer.go
Labels: cla-signed

#1523 backport of agreement sender fixes
  pkg/accounting/tally/tally_test.go
  pkg/bwagreement/server.go
  pkg/identity/identity.go
  pkg/kademlia/kademlia.go
  pkg/pb/bandwidth.pb.go
  pkg/pb/bandwidth.proto
  pkg/pb/certificate.pb.go
  pkg/pb/datarepair.pb.go
  pkg/pb/meta.pb.go
  pkg/pb/node.pb.go
  pkg/pb/overlay.pb.go
  pkg/pb/pointerdb.pb.go
  pkg/pb/streams.pb.go
  pkg/piecestore/psserver/agreementsender/agreementsender.go
Labels: Request Code Review, cla-signed

#1517 add ability to specify redundancy scheme in testplanet upload
  internal/testplanet/uplink.go
Labels: cla-signed

#1524 Restrict slash in bucket name
  satellite/metainfo/metainfo.go
  storagenode/inspector/inspector_test.go
  storagenode/monitor/monitor_test.go
  storagenode/piecestore/endpoint_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1503 audit service won't hang on bad storage node conns
  go.mod
  go.sum
  pkg/audit/newverifier_test.go
  pkg/audit/service.go
  pkg/audit/timeout_test.go
  pkg/audit/verifier.go
  pkg/transport/common.go
  pkg/transport/insecure.go
  pkg/transport/slowtransport.go
  pkg/transport/transport.go
  satellite/peer.go
Labels: Request Code Review, cla-signed

#1492 V3-1319 Add an authorization token field for account creation backend
  cmd/storj-sim/console.go
  cmd/storj-sim/network.go
  satellite/console/consoleweb/consoleql/mutation.go
  satellite/console/consoleweb/consoleql/mutation_test.go
  satellite/console/consoleweb/consoleql/query_test.go
  satellite/console/consoleweb/server.go
  satellite/console/database.go
  satellite/console/registrationtoken.go
  satellite/console/service.go
  satellite/satellitedb/consoledb.go
  satellite/satellitedb/dbx/satellitedb.dbx
  satellite/satellitedb/dbx/satellitedb.dbx.go
  satellite/satellitedb/dbx/satellitedb.dbx.postgres.sql
  satellite/satellitedb/dbx/satellitedb.dbx.sqlite3.sql
  satellite/satellitedb/locked.go
  satellite/satellitedb/migrate.go
  satellite/satellitedb/regtokens.go
  satellite/satellitedb/testdata/postgres.v8.sql
Labels: Request Code Review, cla-signed

#1518 adds pingbackTimeout to kademlia endpoint
  bootstrap/peer.go
  pkg/kademlia/endpoint.go
  pkg/kademlia/kademlia.go
  pkg/kademlia/kademlia_test.go
  satellite/peer.go
  storagenode/orders/db_test.go
  storagenode/peer.go
Labels: Request Code Review, cla-signed

#1434 fix kademlia bootstrap and getting peer identity from context
  pkg/identity/identity.go
  pkg/kademlia/dialer.go
  pkg/kademlia/dialer_test.go
  pkg/kademlia/kademlia.go
Labels: Request Code Review, cla-signed

#1528 adds context timeout to transport.DialAddress
  pkg/transport/transport.go
Labels: Request Code Review, cla-signed

#1529 rearranges code in verifier.go
  pkg/audit/verifier.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1531 V3-1289 API keys fetch bug
  web/satellite/src/components/header/AccountDropdown.vue
  web/satellite/src/store/modules/notifications.ts
  web/satellite/src/store/mutationConstants.ts
  web/satellite/src/utils/constants/actionNames.ts
Labels: cla-signed

#1530 Test that network stalls don't cause indefinite hangs in uplink
  cmd/storj-sim/process.go
  scripts/test-aio.sh
  scripts/test-network-stalls.go
  scripts/test-sim-aws.sh
  scripts/test-sim.sh
  scripts/test-uplink.sh
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1452 Adds Libuplink
  lib/uplink/access.go
  lib/uplink/buckets.go
  lib/uplink/common.go
  lib/uplink/libuplink_test.go
  lib/uplink/main.go
  lib/uplink/objects.go
  lib/uplink/uplink.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1534 Api key name visual reduction
  web/satellite/src/components/apiKeys/ApiKeysItem.vue
  web/satellite/src/components/apiKeys/CopyApiKeyPopup.vue
Labels: cla-signed

#1539 backport of kademlia ping tracking
  cmd/storagenode/dashboard.go
  cmd/storagenode/main.go
  pkg/kademlia/endpoint.go
  pkg/kademlia/kademlia.go
  pkg/pb/inspector.pb.go
  pkg/pb/inspector.proto
  pkg/piecestore/psserver/inspector.go
  proto.lock
Labels: cla-signed

#1536 code review checklist
  .github/pull_request_template.md
Labels: cla-signed

#1522 Move psserver tests
  pkg/piecestore/psserver/server_test.go
  pkg/pointerdb/allocation.go
  pkg/storage/ec/client_planet_test.go
  pkg/storage/segments/store.go
  pkg/storage/segments/store_test.go
  storagenode/pieces/db_test.go
  storagenode/pieces/store.go
  storagenode/piecestore/endpoint.go
  storagenode/piecestore/endpoint_test.go
  storagenode/piecestore/verification.go
  storagenode/piecestore/verification_test.go
  storagenode/storagenodedb/infodb.go
  uplink/metainfo/client.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1542 Print Satellite ID in logs when SettleAgreement fails
  pkg/piecestore/psserver/agreementsender/agreementsender.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1541 Fix docker image tags
  Makefile
Labels: cla-signed

#1535 storage node order sending
  pkg/pb/orders.pb.go
  pkg/pb/orders.proto
  storagenode/orders/db_test.go
  storagenode/orders/sender.go
  storagenode/storagenodedb/orders.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1525 Fix CalcEncryptedSize and CalcPieceSize
  pkg/eestream/encode.go
  pkg/eestream/rs_test.go
  pkg/encryption/encryption.go
  pkg/encryption/encryption_test.go
Labels: cla-signed

#1494 Add repairer tests
  internal/testplanet/uplink.go
  pkg/storage/segments/repairer_test.go
Labels: Request Code Review, cla-signed

#1520 Remove PointerDB client
  cmd/gateway/entrypoint
  cmd/gateway/main.go
  cmd/storj-sim/network.go
  cmd/uplink/cmd/root.go
  cmd/uplink/cmd/setup.go
  examples/pointerdb-client/README.md
  examples/pointerdb-client/main.go
  internal/testcontext/compile_test.go
  internal/testplanet/planet_test.go
  internal/testplanet/uplink.go
  internal/testplanet/uplink_test.go
  lib/uplink/libuplink_test.go
  pkg/cfgstruct/bind.go
  pkg/metainfo/kvmetainfo/buckets_test.go
  pkg/metainfo/kvmetainfo/metainfo.go
  pkg/metainfo/kvmetainfo/objects.go
  pkg/metainfo/kvmetainfo/stream.go
  pkg/miniogw/gateway_test.go
  pkg/miniogw/integration_test.go
  pkg/pointerdb/auth/process_api_key.go
  pkg/pointerdb/pdbclient/client.go
  pkg/pointerdb/pdbclient/client_test.go
  pkg/pointerdb/pdbclient/common.go
  pkg/pointerdb/pdbclient/mocks/mock_client.go
  pkg/pointerdb/pdbclient/pdbclient_mock_test.go
  pkg/pointerdb/pointerdb.go
  uplink/config.go
Labels: cla-signed

#1553 make tests run faster
  .travis.yml
  internal/testplanet/planet.go
  internal/testplanet/uplink_test.go
  lib/uplink/libuplink_test.go
  pkg/audit/newverifier_test.go
  pkg/audit/timeout_test.go
  pkg/audit/verifier.go
  pkg/discovery/service_test.go
  pkg/storage/segments/repairer_test.go
  satellite/satellitedb/dbx/satellitedb.dbx.go
  satellite/satellitedb/locked.go
  scripts/check-dbx-version.sh
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1538 kademlia ping tracking
  cmd/storagenode/dashboard.go
  cmd/storagenode/main.go
  pkg/kademlia/endpoint.go
  pkg/kademlia/kademlia.go
  pkg/pb/inspector.pb.go
  pkg/pb/inspector.proto
  pkg/piecestore/psserver/inspector.go
  proto.lock
  storagenode/inspector/inspector.go
  storagenode/inspector/inspector_test.go
Labels: Request Code Review, cla-signed

#1549 change default to true to enforce sa whitelist
  cmd/storj-sim/network.go
  pkg/piecestore/psserver/config.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1545 adds slow kad dialer tests, adds timeout interceptor to transport
  pkg/kademlia/dialer_test.go
  pkg/kademlia/kademlia_planet_test.go
  pkg/transport/common.go
  pkg/transport/insecure.go
  pkg/transport/timeout.go
  pkg/transport/transport.go
Labels: Request Code Review, cla-signed

#1543 fix path validation with sj:/bucket
  internal/fpath/path.go
  internal/fpath/path_test.go
Labels: cla-signed

#1556 removes pingbackTimeout
  bootstrap/peer.go
  pkg/kademlia/endpoint.go
  pkg/kademlia/kademlia_test.go
  satellite/peer.go
  storagenode/peer.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1558 remove unused bootstrap function from discovery/service.go
  pkg/discovery/service.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1521 remove overlay endpoint
  cmd/overlay/cache.go
  pkg/accounting/tally/tally.go
  pkg/datarepair/checker/checker.go
  pkg/datarepair/checker/checker_test.go
  pkg/datarepair/repairer/config.go
  pkg/datarepair/repairer/repairer.go
  pkg/overlay/cache.go
  pkg/overlay/cache_test.go
  pkg/overlay/mocks/overlay.go
  pkg/overlay/selection_test.go
  pkg/overlay/server.go
  pkg/pb/overlay.pb.go
  pkg/pb/overlay.proto
  pkg/pb/utils.go
  pkg/storage/segments/repairer.go
  pkg/storage/segments/repairer_test.go
  proto.lock
  satellite/metainfo/metainfo.go
  satellite/peer.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1559 SNs should NOT be audited for expired segments
  pkg/audit/cursor.go
  pkg/audit/cursor_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1560 storj-sim network env
  cmd/storj-sim/main.go
  cmd/storj-sim/network.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1552 added LOGIN auth scheme to satellite mail service
  internal/post/login.go
  internal/post/oauth2/auth.go
  internal/testplanet/planet.go
  satellite/mailservice/service.go
  satellite/peer.go
Labels: Request Code Review, cla-signed

#1566 check if the editor exists
  internal/fpath/editor.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1567 Add Simon
  .clabot
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1570 Merge statdb pkg into overlay pkg
  cmd/inspector/main.go
  cmd/overlay/cache.go
  cmd/satellite/usage.go
  pkg/accounting/db.go
  pkg/audit/reporter.go
  pkg/audit/service.go
  pkg/datarepair/checker/checker.go
  pkg/discovery/service.go
  pkg/overlay/cache.go
  pkg/overlay/cache_test.go
  pkg/overlay/inspector.go
  pkg/overlay/selection_test.go
  pkg/overlay/statdb_test.go
  pkg/pb/inspector.pb.go
  pkg/pb/inspector.proto
  pkg/server/server.go
  pkg/statdb/inspector.go
  pkg/statdb/statdb.go
  proto.lock
  satellite/peer.go
  satellite/satellitedb/accounting.go
  satellite/satellitedb/database.go
  satellite/satellitedb/locked.go
  satellite/satellitedb/overlaycache.go
  satellite/satellitedb/statdb.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1563 Move from Unique to Index on SatelliteDB
  satellite/satellitedb/dbx/satellitedb.dbx
  satellite/satellitedb/dbx/satellitedb.dbx.go
  satellite/satellitedb/dbx/satellitedb.dbx.postgres.sql
  satellite/satellitedb/dbx/satellitedb.dbx.sqlite3.sql
  satellite/satellitedb/migrate.go
  satellite/satellitedb/testdata/postgres.v9.sql
Labels: Request Code Review, cla-signed

#1573 pkg/process: indicate if an error is causing program death
  pkg/process/exec_conf.go
Labels: cla-signed

#1571 [V3-1366] Email project name bug
  satellite/console/consoleweb/consoleql/mail.go
  satellite/console/consoleweb/consoleql/mutation.go
  satellite/console/consoleweb/consoleql/mutation_test.go
  satellite/console/consoleweb/consoleql/query_test.go
  satellite/console/consoleweb/consoleql/schema.go
  satellite/console/consoleweb/consoleql/typecreator.go
  satellite/console/consoleweb/server.go
  satellite/console/service.go
  satellite/mailservice/service.go
  satellite/peer.go
  web/satellite/static/emails/Forgot.html
  web/satellite/static/emails/Invite.html
  web/satellite/static/emails/Welcome.html
Labels: Request Code Review, cla-signed

#1577 Rename fonts to make it name more general.
  web/satellite/src/App.vue
  web/satellite/src/components/account/AccountArea.vue
  web/satellite/src/components/account/DeleteAccountPopup.vue
  web/satellite/src/components/apiKeys/AddApiKeyPopup.vue
  web/satellite/src/components/apiKeys/ApiKeysDropdown.vue
  web/satellite/src/components/apiKeys/ApiKeysItem.vue
  web/satellite/src/components/apiKeys/CopyApiKeyPopup.vue
  web/satellite/src/components/apiKeys/footerArea/ApproveDeleteApiKeysArea.vue
  web/satellite/src/components/apiKeys/footerArea/DeleteApiKeysArea.vue
  web/satellite/src/components/apiKeys/headerArea/SearchArea.vue
  web/satellite/src/components/apiKeys/headerArea/SortApiKeysHeader.vue
  web/satellite/src/components/buckets/BucketArea.vue
  web/satellite/src/components/buckets/BucketItem.vue
  web/satellite/src/components/buckets/PaginationArea.vue
  web/satellite/src/components/buckets/SearchArea.vue
  web/satellite/src/components/buckets/SortingHeader.vue
  web/satellite/src/components/common/Button.vue
  web/satellite/src/components/common/EmptyStateArea.vue
  web/satellite/src/components/common/HeaderedInput.vue
  web/satellite/src/components/common/HeaderlessInput.vue
  web/satellite/src/components/common/RegistrationSuccessPopup.vue
  web/satellite/src/components/errors/Page404.vue
  web/satellite/src/components/errors/Page50X.vue
  web/satellite/src/components/header/AccountButton.vue
  web/satellite/src/components/header/AccountDropdown.vue
  web/satellite/src/components/header/NewProjectArea.vue
  web/satellite/src/components/header/projectSelection/ProjectSelectionArea.vue
  web/satellite/src/components/header/projectSelection/ProjectSelectionDropdown.vue
  web/satellite/src/components/navigation/NavigationArea.vue
  web/satellite/src/components/notifications/Notification.vue
  web/satellite/src/components/project/DeleteProjectPopup.vue
  web/satellite/src/components/project/NewProjectPopup.vue
  web/satellite/src/components/project/ProjectCreationSuccessPopup.vue
  web/satellite/src/components/project/ProjectDetailsArea.vue
  web/satellite/src/components/team/AddUserPopup.vue
  web/satellite/src/components/team/TeamArea.vue
  web/satellite/src/components/team/TeamMemberItem.vue
  web/satellite/src/components/team/footerArea/ApproveDeleteUserArea.vue
  web/satellite/src/components/team/footerArea/DeleteUserArea.vue
  web/satellite/src/components/team/headerArea/SearchArea.vue
  web/satellite/src/components/team/headerArea/SortDropdown.vue
  web/satellite/src/components/team/headerArea/SortUsersDropdown.vue
  web/satellite/src/views/Login.vue
  web/satellite/src/views/Register.vue
  web/satellite/static/activation/error.css
  web/satellite/static/activation/error.html
  web/satellite/static/activation/success.css
  web/satellite/static/activation/success.html
  web/satellite/static/emails/Invite.html
  web/satellite/static/emails/Welcome.html
  web/satellite/static/errors/404.css
  web/satellite/static/errors/404.html
  web/satellite/static/fonts/font_bold.ttf
  web/satellite/static/fonts/font_extrabold.ttf
  web/satellite/static/fonts/font_medium.ttf
  web/satellite/static/fonts/font_regular.ttf
  web/satellite/static/fonts/font_semibold.ttf
Labels: cla-signed

#1575 Web header design changes
  web/satellite/src/components/header/Header.vue
  web/satellite/src/components/header/NewProjectArea.vue
  web/satellite/src/components/navigation/NavigationArea.vue
  web/satellite/src/views/Dashboard.vue
  web/satellite/src/views/Login.vue
  web/satellite/src/views/Register.vue
  web/satellite/static/images/Logo.svg
Labels: cla-signed

#1574 adds test for correct download with non-critical amount of nodes offline
  internal/testplanet/uplink_test.go
  pkg/overlay/cache.go
  pkg/overlay/cache_test.go
  satellite/metainfo/metainfo.go
  satellite/satellitedb/overlaycache.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1579 skips TestDownloadWithSomeNodesOffline
  internal/testplanet/uplink_test.go
Labels: cla-signed

#1578 Initial Migration Draft to wipe the network gracefully
  pkg/piecestore/psserver/psdb/psdb.go
  pkg/piecestore/psserver/psdb/testdata/sqlite.v4.sql
Labels: Request Code Review, cla-signed

#1583 devDefaults for easy uplink setup connecting to storj-sim
  uplink/config.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1564 Satellite orders receiving
  internal/testplanet/planet.go
  pkg/pointerdb/allocation.go
  satellite/metainfo/metainfo.go
  satellite/orders/endpoint.go
  satellite/orders/orders_test.go
  satellite/peer.go
  satellite/satellitedb/database.go
  satellite/satellitedb/dbx/satellitedb.dbx.go
  satellite/satellitedb/locked.go
  satellite/satellitedb/orders.go
  storagenode/orders/sender.go
  storagenode/peer.go
  storagenode/piecestore/endpoint.go
Labels: Request Code Review, cla-signed
