Repository storj/storj, pull requests merged in 2019-10, with the labels that each got.

#3145 web/satellite: editing of project description bug fixed
  web/satellite/src/components/project/ProjectDetails.vue
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3067 storagenode/storagenodedb: add SQL receiver logic for graceful exit
  storagenode/peer.go
  storagenode/satellites/satellites.go
  storagenode/storagenodedb/database.go
  storagenode/storagenodedb/satellites.go
  storagenode/storagenodedb/storagenodedbtest/satellites_test.go
  storagenode/storagenodedb/storageusage.go
  storagenode/storagenodedb/testdata/multidbsnapshot.go
  storagenode/storagenodedb/testdata/v25.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3149 satellite/metainfo: add commit interval to prevent long delays between order limit creation and segment commit
  internal/testplanet/satellite.go
  satellite/metainfo/config.go
  satellite/metainfo/metainfo.go
  satellite/metainfo/metainfo_test.go
  satellite/metainfo/validation.go
  satellite/peer.go
  scripts/testdata/satellite-config.yaml.lock
  storagenode/retain/retain.go
Labels: cla-signed

#3133 storagenode/storagenodedb: Vacuum info.db in preparation for dbs plit
  Jenkinsfile.public
  storagenode/storagenodedb/database.go
  storagenode/storagenodedb/testdata/multidbsnapshot.go
  storagenode/storagenodedb/testdata/v22.go
Labels: cla-signed

#3087 satellite/overlay: add UpdateExitStatus and GetExitingNodes
  satellite/gracefulexit/getnodes_test.go
  satellite/overlay/service.go
  satellite/satellitedb/locked.go
  satellite/satellitedb/overlaycache.go
Labels: Request Code Review, cla-signed

#3136 web/satellite: logic removed from template
  web/satellite/src/components/account/AccountArea.vue
  web/satellite/src/components/account/AccountPaymentMethods.vue
  web/satellite/src/components/account/ChangePasswordPopup.vue
  web/satellite/src/components/account/DeleteAccountPopup.vue
  web/satellite/src/components/account/EditProfilePopup.vue
  web/satellite/src/components/account/ProfileArea.vue
  web/satellite/src/components/account/billing/AccountBalance.vue
  web/satellite/src/components/account/billing/DepositAndBilling.vue
  web/satellite/src/components/account/billing/MonthlyBillingSummary.vue
  web/satellite/src/components/apiKeys/ApiKeysArea.vue
  web/satellite/src/components/apiKeys/ApiKeysCopyPopup.vue
  web/satellite/src/components/apiKeys/ApiKeysCreationPopup.vue
  web/satellite/src/components/apiKeys/ApiKeysItem.vue
  web/satellite/src/components/apiKeys/SortingHeader.vue
  web/satellite/src/components/buckets/BucketArea.vue
  web/satellite/src/components/buckets/NoBucketsArea.vue
  web/satellite/src/components/common/EmptyStateArea.vue
  web/satellite/src/components/common/HeaderedInput.vue
  web/satellite/src/components/common/HeaderlessInput.vue
  web/satellite/src/components/common/VHeader.vue
  web/satellite/src/components/common/VInfo.vue
  web/satellite/src/components/common/VList.vue
  web/satellite/src/components/common/VPagination.vue
  web/satellite/src/components/common/VSearch.vue
  web/satellite/src/components/common/VerticalArrows.vue
  web/satellite/src/components/common/registrationSuccessPopup.html
  web/satellite/src/components/common/test/TestList.vue
  web/satellite/src/components/dashboard/DashboardArea.vue
  web/satellite/src/components/header/AccountButton.vue
  web/satellite/src/components/header/AccountDropdown.vue
  web/satellite/src/components/header/headerArea.html
  web/satellite/src/components/header/projectSelection/ProjectSelectionArea.vue
  web/satellite/src/components/navigation/NavigationArea.vue
  web/satellite/src/components/navigation/TabNavigation.vue
  web/satellite/src/components/navigation/navigationArea.html
  web/satellite/src/components/notifications/NotificationArea.vue
  web/satellite/src/components/project/AddStripeCardPopup.vue
  web/satellite/src/components/project/DeleteProjectPopup.vue
  web/satellite/src/components/project/NewProjectPopup.vue
  web/satellite/src/components/project/ProjectCreationSuccessPopup.vue
  web/satellite/src/components/project/ProjectDetails.vue
  web/satellite/src/components/project/ProjectOverviewArea.vue
  web/satellite/src/components/project/UsageReport.vue
  web/satellite/src/components/referral/ReferralStats.vue
  web/satellite/src/components/team/AddUserPopup.vue
  web/satellite/src/components/team/HeaderArea.vue
  web/satellite/src/components/team/ProjectMemberListItem.vue
  web/satellite/src/components/team/ProjectMembersArea.vue
  web/satellite/src/components/team/SortingListHeader.vue
  web/satellite/src/views/DashboardArea.vue
  web/satellite/src/views/forgotPassword/forgotPassword.html
  web/satellite/src/views/login/loginArea.html
  web/satellite/src/views/register/registerArea.html
  web/satellite/tests/unit/components/navigation/__snapshots__/navigationArea.spec.ts.snap
  web/satellite/tests/unit/projectMembers/__snapshots__/SortingListHeader.spec.ts.snap
  web/satellite/tests/unit/views/__snapshots__/DashboardArea.spec.ts.snap
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3138 web/storagenode: logic removed from template
  web/storagenode/src/app/components/BandwidthChart.vue
  web/storagenode/src/app/components/DiskSpaceChart.vue
  web/storagenode/src/app/components/SNOContentFilling.vue
  web/storagenode/src/app/components/SatelliteSelectionDropdown.vue
  web/storagenode/src/app/views/DashboardArea.vue
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3120 web/storagenode: vue style guide applying
  web/storagenode/src/app/components/BandwidthChart.vue
  web/storagenode/src/app/components/BarInfo.vue
  web/storagenode/src/app/components/ChecksArea.vue
  web/storagenode/src/app/components/PayoutArea.vue
  web/storagenode/src/app/components/SNOContentFilling.vue
  web/storagenode/src/app/components/SNOContentTitle.vue
  web/storagenode/src/app/components/SNOFooter.vue
  web/storagenode/src/app/components/SNOHeader.vue
  web/storagenode/src/app/components/SatelliteSelection.vue
  web/storagenode/src/app/components/SatelliteSelectionDropdown.vue
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3153 scripts: ignore .build directory for size checks
  scripts/check-large-files.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3151 Add Repair Threshold Override to allow earlier repair
  satellite/peer.go
  satellite/repair/checker/checker.go
  satellite/repair/repair_test.go
  satellite/repair/repairer/segments.go
  scripts/testdata/satellite-config.yaml.lock
Labels: Request Code Review, Reviewer Can Merge, Sprint Release Goal, cla-signed

#3162 pkg/rpc/rpcstatus: Fix return type
  pkg/rpc/rpcstatus/status_drpc.go
Labels: cla-signed

#3152 split satellite: create separate API process
  satellite/api.go
Labels: Request Code Review, cla-signed

#3168 storagenode/dashboard: update online status
  cmd/storagenode/dashboard.go
  pkg/kademlia/endpoint.go
  storagenode/console/service.go
  storagenode/contact/contact_test.go
  storagenode/contact/endpoint.go
  storagenode/inspector/inspector.go
  storagenode/inspector/inspector_test.go
  storagenode/peer.go
  storagenode/piecestore/endpoint.go
  web/storagenode/src/app/store/modules/node.ts
Labels: Request Code Review, Reviewer Can Merge, Sprint Release Goal, cla-signed

#3170 satellite/console: remove domain prefix from token cookie key
  satellite/console/consoleweb/server.go
  web/satellite/src/utils/authToken.ts
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3165 mobile: build libuplink aar
  .gitignore
  Makefile
  mobile/build.sh
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3155 mobile: API updates
  mobile/apikey.go
  mobile/libuplink_android/app/src/androidTest/java/io/storj/mobile/libuplink/LibuplinkInstrumentedTest.java
  mobile/test-libuplink-android.sh
  mobile/uplink.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3167 satellite/{accounting/tally,repair/checker}: create a valid test pointer
  satellite/accounting/tally/tally_test.go
  satellite/repair/checker/checker_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3173 web/satellite: fix registration popup ref check
  web/satellite/src/views/register/RegisterArea.vue
Labels: cla-signed

#3159 web/satellite: sorting in api keys fixed
  web/satellite/src/types/apiKeys.ts
  web/satellite/tests/unit/store/apiKeys.spec.ts
Labels: cla-signed

#3172 web/satellie: added missing alt attribute to img tags
  satellite/console/consoleweb/consoleql/testdata/Invite.html
  web/marketing/pages/stop-free-credit.html
  web/marketing/pages/stop-partner-offer.html
  web/marketing/pages/stop-referral-offer.html
  web/satellite/src/components/account/AccountPaymentMethods.vue
  web/satellite/src/components/buckets/NoBucketsArea.vue
  web/satellite/src/components/common/HeaderedInput.vue
  web/satellite/src/components/common/HeaderlessInput.vue
  web/satellite/src/components/errors/page40X.html
  web/satellite/src/components/errors/page50X.html
  web/satellite/src/components/header/AccountButton.vue
  web/satellite/src/components/header/projectSelection/ProjectSelectionArea.vue
  web/satellite/src/components/project/CardChoiceItem.vue
  web/satellite/src/components/project/DeleteProjectPopup.vue
  web/satellite/src/components/project/NewProjectPopup.vue
  web/satellite/src/components/team/AddUserPopup.vue
  web/satellite/src/views/DashboardArea.vue
  web/satellite/src/views/forgotPassword/forgotPassword.html
  web/satellite/src/views/login/loginArea.html
  web/satellite/src/views/register/registerArea.html
  web/satellite/static/errors/404.html
  web/satellite/static/resetPassword/resetPassword.html
  web/satellite/tests/unit/common/__snapshots__/HeaderedInput.spec.ts.snap
  web/satellite/tests/unit/views/__snapshots__/DashboardArea.spec.ts.snap
  web/storagenode/src/app/components/ChecksArea.vue
  web/storagenode/src/app/components/SNOContentFilling.vue
  web/storagenode/src/app/components/SatelliteSelection.vue
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3139 internal/testplanet: use postgres for pointerDB
  internal/testplanet/run.go
  satellite/satellitedb/satellitedbtest/run.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3150 uplink/gateway: wizard message update
  cmd/gateway/main.go
  cmd/uplink/cmd/setup.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3186 storagenode/console: use bytes for remaining info
  storagenode/console/bandwidth.go
  storagenode/console/diskspace.go
  storagenode/console/service.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3183 storagenode/console: use bandwidth monthly summary
  storagenode/console/service.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3188 web/storagenode: memory conversions extended
  web/storagenode/src/app/components/BarInfo.vue
  web/storagenode/src/app/utils/chartUtils.ts
  web/storagenode/src/app/utils/converter.ts
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3178 satellite/accounting: refactor code and remove unused fields
  satellite/accounting/bucketstats.go
  satellite/accounting/db_test.go
  satellite/accounting/projectusage.go
  satellite/accounting/projectusage_test.go
  satellite/accounting/tally/common.go
  satellite/accounting/tally/tally.go
  satellite/accounting/tally/tally_test.go
  satellite/console/usagerollups_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3192 satellite/repair: defer close piecestore in downloadAndVerifyPiece
  satellite/repair/repairer/ec.go
Labels: cla-signed

#3193 satellite/repair: remove deprecated error message
  satellite/repair/checker/checker.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3177 mobile: move to lib/uplink-gomobile
  Makefile
  lib/uplink-gomobile/.gitignore
  lib/uplink-gomobile/apikey.go
  lib/uplink-gomobile/bucket.go
  lib/uplink-gomobile/build.sh
  lib/uplink-gomobile/doc.go
  lib/uplink-gomobile/encryption.go
  lib/uplink-gomobile/libuplink_android/.gitignore
  lib/uplink-gomobile/libuplink_android/app/.gitignore
  lib/uplink-gomobile/libuplink_android/app/build.gradle
  lib/uplink-gomobile/libuplink_android/app/proguard-rules.pro
  lib/uplink-gomobile/libuplink_android/app/src/androidTest/java/io/storj/mobile/libuplink/LibuplinkInstrumentedTest.java
  lib/uplink-gomobile/libuplink_android/app/src/main/AndroidManifest.xml
  lib/uplink-gomobile/libuplink_android/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  lib/uplink-gomobile/libuplink_android/app/src/main/res/drawable/ic_launcher_background.xml
  lib/uplink-gomobile/libuplink_android/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  lib/uplink-gomobile/libuplink_android/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  lib/uplink-gomobile/libuplink_android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  lib/uplink-gomobile/libuplink_android/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  lib/uplink-gomobile/libuplink_android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  lib/uplink-gomobile/libuplink_android/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  lib/uplink-gomobile/libuplink_android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  lib/uplink-gomobile/libuplink_android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  lib/uplink-gomobile/libuplink_android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  lib/uplink-gomobile/libuplink_android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  lib/uplink-gomobile/libuplink_android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  lib/uplink-gomobile/libuplink_android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  lib/uplink-gomobile/libuplink_android/app/src/main/res/values/colors.xml
  lib/uplink-gomobile/libuplink_android/app/src/main/res/values/strings.xml
  lib/uplink-gomobile/libuplink_android/app/src/main/res/values/styles.xml
  lib/uplink-gomobile/libuplink_android/build.gradle
  lib/uplink-gomobile/libuplink_android/gradle.properties
  lib/uplink-gomobile/libuplink_android/gradle/wrapper/gradle-wrapper.jar
  lib/uplink-gomobile/libuplink_android/gradle/wrapper/gradle-wrapper.properties
  lib/uplink-gomobile/libuplink_android/gradlew
  lib/uplink-gomobile/libuplink_android/gradlew.bat
  lib/uplink-gomobile/libuplink_android/settings.gradle
  lib/uplink-gomobile/object.go
  lib/uplink-gomobile/scope.go
  lib/uplink-gomobile/test-libuplink-android.sh
  lib/uplink-gomobile/test-sim.sh
  lib/uplink-gomobile/uplink.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3156 satellite/web: Fixed Login Button overlapping.
  web/satellite/src/views/login/loginArea.scss
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3180 web/satellite: Payments methods removed
  web/satellite/src/components/account/AccountArea.vue
  web/satellite/src/components/account/AccountPaymentMethods.vue
  web/satellite/src/components/navigation/NavigationArea.vue
  web/satellite/src/router/index.ts
  web/satellite/src/views/DashboardArea.vue
  web/satellite/tests/unit/components/navigation/__snapshots__/navigationArea.spec.ts.snap
  web/satellite/tests/unit/components/navigation/navigationArea.spec.ts
  web/satellite/tests/unit/views/DashboardArea.spec.ts
Labels: cla-signed

#3065 Add the tempDir as parameter
  lib/uplinkc/testdata/helpers.h
  lib/uplinkc/testdata_test.go
  lib/uplinkc/uplink.go
Labels: Code Review In-Progress, Request Code Review, cla-signed

#3158 web/satellite: units added to buckets table header
  web/satellite/src/components/buckets/SortingHeader.vue
Labels: cla-signed

#3038 docs/blueprints: referral manager v1
  docs/blueprints/archive/marketing-offer-program.md
  docs/blueprints/referral-manager-v1.md
Labels: Design Doc, Request Code Review, Reviewer Can Merge, cla-signed

#3157 web/satellite: DatePicker rework
  web/satellite/src/components/common/VDatePicker.vue
  web/satellite/src/components/project/DatePicker.vue
  web/satellite/src/components/project/UsageReport.vue
  web/satellite/src/utils/datepicker.ts
  web/satellite/tests/unit/common/VDatePicker.spec.ts
  web/satellite/tests/unit/utils/datepicker.spec.ts
  web/satellite/tsconfig.json
  web/satellite/tslint.json
Labels: cla-signed

#3166 web/satellite: scroll added for project description container
  web/satellite/src/components/project/ProjectDetails.vue
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3199 satellite/repairer: move segment age calculation
  satellite/repair/repairer/segments.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3161 satellite/audit: do not fail or contain nodes for audited segments that are not piece-hash-verified
  satellite/audit/reverify_test.go
  satellite/audit/verifier.go
  satellite/audit/verifier_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3174 satellite/gracefulexit: add transfer queue for pieces
  docs/blueprints/storagenode-graceful-exit/pieces.md
  docs/blueprints/storagenode-graceful-exit/protocol.md
  internal/testplanet/satellite.go
  satellite/gracefulexit/chore.go
  satellite/gracefulexit/chore_test.go
  satellite/gracefulexit/pathcollector.go
  satellite/peer.go
  scripts/testdata/satellite-config.yaml.lock
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2992 satellite/accounting: implement tally as an observer
  satellite/accounting/projectusage_test.go
  satellite/accounting/tally/tally.go
  satellite/accounting/tally/tally_test.go
  satellite/peer.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3200 storagenode/console: Changes reported by reviewers
  .gitignore
  Makefile
  cmd/storj-sim/network.go
  internal/testplanet/storagenode.go
  storagenode/console/consoleassets/.gitignore
  storagenode/console/consoleserver/server.go
  storagenode/peer.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3171 Storage Node Dashboard shortcut opens the SNOboard
  installer/windows/Product.wxs
Labels: Request Code Review, cla-signed

#3198 installer/windows: Update links to documentation
  installer/windows/AllocatedBandwidthConfig.wxs
  installer/windows/IdentityDir.wxs
  installer/windows/PublicAddressConfig.wxs
  installer/windows/WalletConfig.wxs
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3164 storagenode: embed the console into the binary and makefile
  Makefile
  cmd/storagenode/Dockerfile
  cmd/storagenode/entrypoint
  storagenode/console/consoleassets/assets.go
  storagenode/console/consoleserver/server.go
  storagenode/peer.go
  web/storagenode/.gitignore
  web/storagenode/package-lock.json
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3204 satellite/audit: Add piece hash verified to log messages
  satellite/audit/verifier.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3194 storagenode/signature: Reject uploads with a timestamp too far in the future
  storagenode/piecestore/verification.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3206 installer/windows: add to private Jenkins build
  Jenkinsfile
  Makefile
  installer/windows/Product.wxs
  installer/windows/build.bat
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3208 Fix jenkins builds of storagenode console.
  Makefile
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3203 satellite/overlay: remove overlay.IsVetted
  satellite/overlay/service.go
  satellite/overlay/service_test.go
  satellite/satellitedb/locked.go
  satellite/satellitedb/overlaycache.go
Labels: Request Code Review, cla-signed

#3201 satellite/gracefulexit: Add protobuf definitions for communication between storage node and satellite
  pkg/pb/gracefulexit.pb.go
  pkg/pb/gracefulexit.proto
  pkg/pb/inspector.pb.go
  pkg/rpc/compat_drpc.go
  pkg/rpc/compat_grpc.go
  proto.lock
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3189 cmd/storagenode: enable migration of configs of different types
  cmd/storagenode/deprecated.go
  cmd/storagenode/main.go
  cmd/storagenode/main_test.go
Labels: Request Code Review, cla-signed

#3211 satellite/overlay: do not include gracefully exiting nodes in node selection
  satellite/overlay/selection_test.go
  satellite/satellitedb/overlaycache.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3214 satellite/audit: add mutex to pieceHashesVerified map
  satellite/audit/verifier.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3184 satellite/console: Removed 'user not found' message on password reset request
  satellite/console/consoleweb/consoleql/query.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3212 installer/windows: checkbox for opening SNOboard after installation
  installer/windows/CustomInstallDir.wxs
  installer/windows/Product.wxs
  installer/windows/windows.wixproj
Labels: Request Code Review, cla-signed

#3217 satellite/audit: fix audit panic
  satellite/audit/disqualification_test.go
  satellite/audit/reporter.go
  satellite/audit/reporter_test.go
  satellite/audit/verifier.go
  satellite/audit/worker.go
Labels: Bug, Request Code Review, Reviewer Can Merge, cla-signed

#3225 cmd/storj-sim: expose GATEWAY_X_API_KEY
  cmd/storj-sim/network.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3219 web/storagenode: charts on first day of the month updated
  web/storagenode/src/app/utils/chartUtils.ts
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3185 satellite/console: Added error for adding api key with existing name attempt.
  satellite/console/apikeys.go
  satellite/console/service.go
  satellite/satellitedb/apikeys.go
  satellite/satellitedb/dbx/satellitedb.dbx
  satellite/satellitedb/dbx/satellitedb.dbx.go
  satellite/satellitedb/locked.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3216 Installer: identity directory defaults to %APPDATA%\Storj\Identity\Storagenode
  installer/windows/Product.wxs
Labels: Request Code Review, cla-signed

#3187 satellite/payments - payment account setup
  go.mod
  go.sum
  satellite/payments/account.go
  satellite/payments/localpayments/local.go
  satellite/payments/service.go
  satellite/payments/stripecoinpayments/customers_test.go
  satellite/payments/stripecoinpayments/database.go
  satellite/payments/stripecoinpayments/service.go
  satellite/payments/stripepayments/stripe.go
  satellite/peer.go
  satellite/satellitedb/customers.go
  satellite/satellitedb/database.go
  satellite/satellitedb/dbx/satellitedb.dbx
  satellite/satellitedb/dbx/satellitedb.dbx.go
  satellite/satellitedb/dbx/satellitedb.dbx.postgres.sql
  satellite/satellitedb/dbx/satellitedb.dbx.sqlite3.sql
  satellite/satellitedb/locked.go
  satellite/satellitedb/migrate.go
  satellite/satellitedb/testdata/postgres.v59.sql
Labels: Request Code Review, cla-signed

#3233 satellite: make PointerDB an argument to satellite.New
  cmd/satellite/main.go
  internal/testplanet/reconfigure.go
  internal/testplanet/run.go
  internal/testplanet/satellite.go
  satellite/peer.go
  storage/postgreskv/client.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3235 Bump drpc version
  go.mod
  go.sum
Labels: cla-signed

#3226 web/satellite: labels and titles style following problems solved
  web/satellite/src/components/account/ChangePasswordPopup.vue
  web/satellite/src/components/account/EditProfilePopup.vue
  web/satellite/src/components/account/ProfileArea.vue
  web/satellite/src/components/account/billing/BillingHistory.vue
  web/satellite/src/components/buckets/NoBucketsArea.vue
  web/satellite/src/components/project/ProjectDetails.vue
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3227 web/satellite: api key validation bug fixed
  web/satellite/src/components/apiKeys/ApiKeysArea.vue
  web/satellite/src/components/apiKeys/ApiKeysCreationPopup.vue
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3221 web/satellite: notification message text breaking fixed
  web/satellite/src/components/notifications/NotificationItem.vue
  web/satellite/tests/unit/notifications/__snapshots__/NotificationArea.spec.ts.snap
  web/satellite/tests/unit/notifications/__snapshots__/NotificationItem.spec.ts.snap
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3202 storagenode/cmd: create start graceful exit CLI
  cmd/storagenode/gracefulexit.go
  cmd/storagenode/main.go
  go.mod
  go.sum
  pkg/pb/gracefulexit.pb.go
  pkg/pb/gracefulexit.proto
  pkg/rpc/compat_drpc.go
  pkg/rpc/compat_grpc.go
  proto.lock
  storagenode/gracefulexit/endpoint.go
  storagenode/gracefulexit/endpoint_test.go
  storagenode/peer.go
Labels: Request Code Review, cla-signed

#3163 CI: test drpc and grpc
  Jenkinsfile.drpc
  Jenkinsfile.public
  pkg/rpc/rpc_test.go
  scripts/test-sim.sh
Labels: Request Code Review, cla-signed

#3242 satellite/payments: account balance
  satellite/payments/account.go
  satellite/payments/stripecoinpayments/customers_test.go
  satellite/payments/stripecoinpayments/database.go
  satellite/payments/stripecoinpayments/service.go
  satellite/peer.go
  satellite/satellitedb/customers.go
  satellite/satellitedb/database.go
  satellite/satellitedb/dbx/satellitedb.dbx
  satellite/satellitedb/dbx/satellitedb.dbx.go
  satellite/satellitedb/locked.go
Labels: Request Code Review, Sprint Release Goal, cla-signed

#3181 satellite/payments: add coinpayments HTTP client
  satellite/payments/coinpayments/client.go
  satellite/payments/coinpayments/transactions.go
Labels: Request Code Review, cla-signed

#3220 web/storagenode: node status updated
  storagenode/console/service.go
  web/storagenode/src/app/components/BandwidthChart.vue
  web/storagenode/src/app/components/BarInfo.vue
  web/storagenode/src/app/components/ChecksArea.vue
  web/storagenode/src/app/components/DiskSpaceChart.vue
  web/storagenode/src/app/components/PayoutArea.vue
  web/storagenode/src/app/components/SNOContentFilling.vue
  web/storagenode/src/app/components/SNOContentTitle.vue
  web/storagenode/src/app/components/SNOFooter.vue
  web/storagenode/src/app/components/SNOHeader.vue
  web/storagenode/src/app/components/SatelliteSelection.vue
  web/storagenode/src/app/components/SatelliteSelectionDropdown.vue
  web/storagenode/src/app/components/VBar.vue
  web/storagenode/src/app/components/VChart.vue
  web/storagenode/src/app/components/VInfo.vue
  web/storagenode/src/app/store/modules/node.ts
  web/storagenode/src/app/utils/chart.ts
  web/storagenode/src/app/utils/date.ts
  web/storagenode/src/app/views/DashboardArea.vue
  web/storagenode/src/storagenode/api/storagenode.ts
  web/storagenode/src/storagenode/dashboard.ts
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3179 web/storagenode: chart y and x axis reworked
  web/storagenode/src/app/components/BandwidthChart.vue
  web/storagenode/src/app/components/DiskSpaceChart.vue
  web/storagenode/src/app/components/PayoutArea.vue
  web/storagenode/src/app/components/VChart.vue
  web/storagenode/src/app/utils/chart.ts
  web/storagenode/tslint.json
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3248 updating term to be accurate; Its held amount.
  docs/blueprints/storagenode-graceful-exit/reports.md
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3243 storagenode/contact: remove random sleep on run
  internal/testplanet/storagenode.go
  storagenode/contact/chore.go
  storagenode/contact/service.go
  storagenode/peer.go
Labels: cla-signed

#3223 satellite/gracefulexit: Implement the 'process' endpoint on the satellite
  internal/testplanet/satellite.go
  pkg/pb/gracefulexit.pb.go
  pkg/pb/gracefulexit.proto
  pkg/pb/orders.pb.go
  pkg/pb/orders.proto
  proto.lock
  satellite/gracefulexit/chore.go
  satellite/gracefulexit/common.go
  satellite/gracefulexit/db.go
  satellite/gracefulexit/db_test.go
  satellite/gracefulexit/endpoint.go
  satellite/gracefulexit/endpoint_test.go
  satellite/gracefulexit/pathcollector.go
  satellite/orders/service.go
  satellite/overlay/service.go
  satellite/overlay/service_test.go
  satellite/peer.go
  satellite/satellitedb/dbx/satellitedb.dbx
  satellite/satellitedb/dbx/satellitedb.dbx.go
  satellite/satellitedb/gracefulexit.go
  satellite/satellitedb/locked.go
  satellite/satellitedb/overlaycache.go
  scripts/testdata/satellite-config.yaml.lock
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3250 storagenode/piecestore: Change test to use ioutil.ReadAll to attempt to reduce test flake
  storagenode/piecestore/verification_test.go
Labels: cla-signed

#3251 satellite/gracefulexit: Fix drpc/grpc interface and EOF check in endpoint tests
  satellite/gracefulexit/endpoint_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3254 cmd/certificates: Change Error Handling to return more clear messages to the user/client
  certificate/endpoint.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3215 pkg/rpc: defeat MITM attacks in most cases
  pkg/peertls/tlsopts/tls.go
  pkg/rpc/dial.go
  pkg/rpc/known_ids.go
  pkg/rpc/known_ids_test.go
  storagenode/piecestore/endpoint.go
  uplink/metainfo/client.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3255 OrderLimit/GracePeriod: Increase time window from 1h to 24h
  satellite/metainfo/config.go
  scripts/testdata/satellite-config.yaml.lock
  storagenode/piecestore/endpoint.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3175 satellite/discovery: remove discovery related code
  cmd/storj-sim/network.go
  internal/testplanet/run.go
  internal/testplanet/satellite.go
  lib/uplinkc/testdata_test.go
  pkg/pb/overlay.pb.go
  pkg/pb/overlay.proto
  pkg/rpc/compat_drpc.go
  pkg/rpc/compat_grpc.go
  pkg/server/config.go
  proto.lock
  satellite/api.go
  satellite/contact/contact_test.go
  satellite/contact/kademlia.go
  satellite/contact/service.go
  satellite/discovery/service.go
  satellite/discovery/service_test.go
  satellite/overlay/service_test.go
  satellite/peer.go
  satellite/repair/repair_test.go
  scripts/testdata/satellite-config.yaml.lock
  storagenode/contact/contact_test.go
  storagenode/contact/kademlia.go
  storagenode/contact/service.go
  storagenode/inspector/inspector_test.go
  storagenode/monitor/monitor_test.go
  storagenode/peer.go
  storagenode/trust/service_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3237 internal/testplanet: add satellite.API to testplanet
  internal/testplanet/planet.go
  internal/testplanet/satellite.go
  satellite/api.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3270 pkg/pb: regen gracefulexit.pb.go
  pkg/pb/gracefulexit.pb.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3261 Update dial.go
  pkg/rpc/dial.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3252 satellite/repair: dont error on deleted segments
  satellite/repair/repair_test.go
  satellite/repair/repairer/segments.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3260 mobile: add EncryptionRestrictions
  lib/uplink-gomobile/apikey.go
  lib/uplink-gomobile/encryption.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3249 satellite/payments: receive credit cards
  satellite/payments/account.go
  satellite/payments/creditcards.go
  satellite/payments/stripecoinpayments/accounts.go
  satellite/payments/stripecoinpayments/creditcards.go
  satellite/payments/stripecoinpayments/service.go
Labels: Code Review In-Progress, Request Code Review, Reviewer Can Merge, Sprint Release Goal, cla-signed

#3239 web/satellite: api keys selection caching added
  web/satellite/src/components/apiKeys/ApiKeysArea.vue
  web/satellite/src/store/modules/apiKeys.ts
  web/satellite/tests/unit/apiKeys/ApiKeysArea.spec.ts
  web/satellite/tests/unit/store/apiKeys.spec.ts
Labels: cla-signed

#3231 web/satellite: project members sorting fixed
  satellite/satellitedb/projectmembers.go
  satellite/satellitedb/projectmembers_test.go
  web/satellite/src/components/apiKeys/SortingHeader.vue
  web/satellite/src/components/team/ProjectMembersArea.vue
  web/satellite/src/components/team/SortingListHeader.vue
  web/satellite/tests/unit/projectMembers/__snapshots__/SortingListHeader.spec.ts.snap
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3238 web/satellite: project members frontend selection caching added
  web/satellite/src/components/team/HeaderArea.vue
  web/satellite/src/components/team/ProjectMembersArea.vue
  web/satellite/src/store/modules/projectMembers.ts
  web/satellite/src/types/projectMembers.ts
  web/satellite/tests/unit/projectMembers/__snapshots__/HeaderArea.spec.ts.snap
  web/satellite/tests/unit/store/projectMembers.spec.ts
Labels: cla-signed

#3246 uplink/piecestore: Check SN piece hash timestamp
  uplink/piecestore/verification.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3279 satellite/payments: add credit card to payment account
  satellite/payments/creditcards.go
  satellite/payments/stripecoinpayments/creditcards.go
Labels: Request Code Review, Reviewer Can Merge, Sprint Release Goal, cla-signed

#3262 storagenode/gracefulexit: Add graceful exit chore and worker.
  internal/testplanet/storagenode.go
  pkg/pb/gracefulexit.proto
  storagenode/gracefulexit/chore.go
  storagenode/gracefulexit/chore_test.go
  storagenode/gracefulexit/worker.go
  storagenode/peer.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3274 storagenode/piecestore: Fix to ignore both gRPC and dRPC EOF errors.
  storagenode/piecestore/endpoint.go
Labels: Reviewer Can Merge, cla-signed

#3114 scripts: add check-monitoring script to detect changes to monkit calls
  Jenkinsfile.public
  Makefile
  monkit.lock
  satellite/accounting/tally/tally.go
  satellite/repair/checker/checker.go
  satellite/satellitedb/overlaycache.go
  scripts/check-monitoring.go
Labels: Request Code Review, cla-signed

#3282 piecestore: fix test flakiness around upload/download usage tracking
  storagenode/piecestore/verification_test.go
Labels: cla-signed

#3281 satellite/payments: dbx scheme renamed, userID placed on Account level
  satellite/payments/account.go
  satellite/payments/creditcards.go
  satellite/payments/stripecoinpayments/accounts.go
  satellite/payments/stripecoinpayments/creditcards.go
  satellite/payments/stripecoinpayments/service.go
  satellite/satellitedb/customers.go
  satellite/satellitedb/dbx/satellitedb.dbx
  satellite/satellitedb/dbx/satellitedb.dbx.go
Labels: Request Code Review, Reviewer Can Merge, Sprint Release Goal, cla-signed

#3284 satellite/gracefulexit: protobuf field name updates
  pkg/pb/gracefulexit.pb.go
  pkg/pb/gracefulexit.proto
  proto.lock
  satellite/gracefulexit/endpoint.go
  satellite/gracefulexit/endpoint_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3264 storagenode/cmd: add exit-status command for graceful exit
  cmd/storagenode/gracefulexit.go
  cmd/storagenode/main.go
  pkg/pb/gracefulexit.pb.go
  pkg/pb/gracefulexit.proto
  proto.lock
  storagenode/gracefulexit/endpoint.go
  storagenode/gracefulexit/endpoint_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3286 piecestore: update usage before completing upload
  storagenode/piecestore/endpoint.go
Labels: cla-signed

#3176 {versioncontrol,internal/version}: add rollout to versioncontrol server
  internal/version/service.go
  internal/version/version.go
  internal/version/version_test.go
  versioncontrol/peer.go
  versioncontrol/peer_test.go
Labels: cla-signed

#3285 satellite/audit: improve logging
  satellite/audit/disqualification_test.go
  satellite/audit/reporter.go
  satellite/audit/reporter_test.go
  satellite/audit/verifier.go
  satellite/audit/worker.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3291 Satellite/PieceHashValidation: Increase time window from 2h to 24h to avoid timezone issues
  satellite/metainfo/metainfo.go
  uplink/piecestore/verification.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3293 add mykola siedov to clabot
  .clabot
Labels: cla-signed

#3287 satellite/repair: improve logging
  satellite/repair/repairer/ec.go
  satellite/repair/repairer/repairer.go
  satellite/repair/repairer/segments.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3213 satellite/accounting: add redis support to live accounting
  cmd/satellite/main.go
  internal/testplanet/satellite.go
  satellite/accounting/db.go
  satellite/accounting/live/cache.go
  satellite/accounting/live/live.go
  satellite/accounting/live/live_test.go
  satellite/accounting/live/memory.go
  satellite/accounting/live/redis.go
  satellite/accounting/projectusage.go
  satellite/accounting/tally/tally.go
  satellite/api.go
  satellite/peer.go
  scripts/testdata/satellite-config.yaml.lock
  storage/redis/client.go
Labels: Request Code Review, cla-signed

#3295 storagenode/gracefulexit: use correct rpc status code
  storagenode/gracefulexit/endpoint.go
  storagenode/gracefulexit/endpoint_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3263 satellite/metrics: create a metrics chore
  internal/testplanet/satellite.go
  satellite/metrics/chore.go
  satellite/metrics/counter.go
  satellite/metrics/counter_test.go
  satellite/peer.go
  scripts/testdata/satellite-config.yaml.lock
Labels: Request Code Review, cla-signed

#3280 cmd/satellite: create API subcommand
  cmd/satellite/main.go
  cmd/storj-sim/network.go
  cmd/storj-sim/process.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3266 examples/scope: small scope exploder command line tool
  examples/scope/main.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3289 jenkins: update to golangci-lint 1.21.0
  .golangci.yml
  Dockerfile.jenkins
  Makefile
  lib/uplinkc/handles.go
  lib/uplinkc/handles_test.go
  lib/uplinkc/testdata_test.go
  lib/uplinkc/universe.go
  lib/uplinkc/universe_test.go
  lib/uplinkc/uplink.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3290 web/satellite: validation added on delete account popup
  web/satellite/src/components/account/DeleteAccountPopup.vue
  web/satellite/src/components/project/ProjectOverviewArea.vue
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3277 web/satellite: styling bugs fixed
  web/satellite/src/components/account/ChangePasswordPopup.vue
  web/satellite/src/components/apiKeys/ApiKeysArea.vue
  web/satellite/src/components/buckets/BucketArea.vue
  web/satellite/src/components/project/UsageReport.vue
  web/satellite/src/components/team/AddUserPopup.vue
  web/satellite/src/components/team/ProjectMembersArea.vue
  web/satellite/src/store/modules/apiKeys.ts
  web/satellite/src/store/modules/projectMembers.ts
  web/satellite/tests/unit/apiKeys/ApiKeysArea.spec.ts
  web/satellite/tests/unit/mock/api/apiKeys.ts
  web/satellite/tests/unit/projectMembers/ProjectMembersArea.spec.ts
  web/satellite/tests/unit/store/apiKeys.spec.ts
  web/satellite/tests/unit/store/projectMembers.spec.ts
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3209 web/satellite: name removed from header
  web/satellite/src/components/header/AccountButton.vue
  web/satellite/static/images/account/BlackArrowExpand.svg
  web/satellite/static/images/account/BlackArrowHide.svg
Labels: cla-signed

#3299 satellite/gracefulexit: use zap.Stringer instead of zap.String
  satellite/gracefulexit/endpoint.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3297 satellite/console: payments api
  cmd/storj-sim/network.go
  satellite/api.go
  satellite/console/consoleweb/consoleapi/payments.go
  satellite/console/consoleweb/consoleql/mutation_test.go
  satellite/console/consoleweb/consoleql/query_test.go
  satellite/console/consoleweb/server.go
  satellite/console/service.go
  satellite/payments/account.go
  satellite/payments/creditcards.go
  satellite/payments/stripecoinpayments/accounts.go
  satellite/payments/stripecoinpayments/creditcards.go
  satellite/payments/stripecoinpayments/service.go
  satellite/payments/stripecoinpayments/tokens.go
  satellite/payments/tokens.go
  satellite/peer.go
  web/satellite/.env
Labels: Request Code Review, Reviewer Can Merge, Sprint Release Goal, cla-signed

#3301 satellite/satellitedb: add exit_status column to nodes table
  satellite/overlay/service.go
  satellite/satellitedb/dbx/satellitedb.dbx
  satellite/satellitedb/dbx/satellitedb.dbx.go
  satellite/satellitedb/dbx/satellitedb.dbx.postgres.sql
  satellite/satellitedb/dbx/satellitedb.dbx.sqlite3.sql
  satellite/satellitedb/migrate.go
  satellite/satellitedb/overlaycache.go
  satellite/satellitedb/testdata/postgres.v61.sql
Labels: cla-signed

#3197 mobile: create release script
  Makefile
  lib/uplink-gomobile/bucket.go
  lib/uplink-gomobile/build.sh
  lib/uplink-gomobile/libuplink_android/app/src/androidTest/java/io/storj/mobile/libuplink/LibuplinkInstrumentedTest.java
  lib/uplink-gomobile/release/AndroidManifest.xml
  lib/uplink-gomobile/release/libuplink-android-gomobile.pom
  lib/uplink-gomobile/release/release.sh
  lib/uplink-gomobile/test-libuplink-android.sh
  lib/uplink-gomobile/test-sim.sh
Labels: Code Review In-Progress, Request Code Review, Reviewer Can Merge, cla-signed

#3303 satellite/console: add REST registration API endpoint
  satellite/console/consoleweb/server.go
Labels: Request Code Review, cla-signed

#3218 upload: Add more info to returned error response & to logs
  satellite/metainfo/metainfo.go
  satellite/metainfo/metainfo_test.go
  satellite/metainfo/validation.go
  uplink/storage/segments/store.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3306 pkg/rpc/rpcstatus: fix drpc grpc compatibilty
  pkg/rpc/rpcstatus/status_grpc.go
Labels: Request Code Review, cla-signed

#3316 Adding cpustejovsky to the CLA
  .clabot
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3302 satellite/repair: reduce timeout
  satellite/repair/repairer/ec.go
  satellite/repair/repairer/repairer.go
  scripts/testdata/satellite-config.yaml.lock
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3317 cmd/storj-sim: make postgres default to STORJ_SIM_POSTGRES
  cmd/storj-sim/main.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3321 Update to go 1.13.3
  Dockerfile.jenkins
  Makefile
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3320 satellite/satellitedb: switch to postgres only
  cmd/satellite/main.go
  internal/testplanet/planet.go
  internal/testplanet/run.go
  internal/testplanet/satellite.go
  satellite/metainfo/metainfo_test.go
  satellite/satellitedb/database.go
  satellite/satellitedb/satellitedbtest/pgschema.go
  satellite/satellitedb/satellitedbtest/run.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3296 satellite/satellitedb: remove sqlite support
  satellite/orders/orders_test.go
  satellite/repair/queue/queue2_test.go
  satellite/satellitedb/attribution.go
  satellite/satellitedb/database.go
  satellite/satellitedb/dbx/gen.go
  satellite/satellitedb/dbx/satellitedb.dbx.go
  satellite/satellitedb/gracefulexit.go
  satellite/satellitedb/locked.go
  satellite/satellitedb/lockedtx.go
  satellite/satellitedb/orders.go
  satellite/satellitedb/overlaycache.go
  satellite/satellitedb/repairqueue.go
  satellite/satellitedb/usercredits.go
  scripts/lockedgen.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3314 Updating Support Link in README
  README.md
Labels: Enhancement, Request Code Review, Reviewer Can Merge, cla-signed

#3253 {versioncontrol,internal/version,cmd/*}: refactor version control
  cmd/gateway/main.go
  cmd/identity/main.go
  cmd/storagenode-updater/main.go
  cmd/uplink/cmd/root.go
  internal/testplanet/satellite.go
  internal/testplanet/versioning.go
  internal/version/checker/client.go
  internal/version/checker/client_test.go
  internal/version/checker/service.go
  internal/version/version.go
  pkg/process/debug.go
  satellite/api.go
  satellite/peer.go
  storagenode/console/service.go
  storagenode/peer.go
  versioncontrol/peer.go
  versioncontrol/peer_test.go
Labels: cla-signed

#3324 README: Replace reference Rocket chat to forum
  README.md
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3276 {internal/version,versioncontrol,cmd/storagenode-updater}: add rollout to storagenode updater
  cmd/storagenode-updater/main.go
  cmd/storagenode-updater/main_test.go
  cmd/storagenode-updater/testdata/fake-ident.cert
  cmd/storagenode-updater/testdata/fake-ident.key
  internal/testplanet/satellite.go
  internal/testplanet/versioning.go
  internal/version/checker/client.go
  internal/version/checker/client_test.go
  internal/version/stats.go
  internal/version/version.go
  internal/version/version_test.go
  pkg/process/exec_conf.go
  satellite/api.go
  satellite/peer.go
  satellite/satellitedb/overlaycache.go
  storagenode/peer.go
  versioncontrol/peer.go
  versioncontrol/peer_test.go
Labels: Code Review In-Progress, Request Code Review, cla-signed

#3308 satellite/console: new passwordChange API endpoint
  satellite/console/consoleweb/consoleapi/auth.go
  satellite/console/consoleweb/server.go
Labels: Request Code Review, cla-signed

#3326 gomobile Reader.Read should take offset and length params
  lib/uplink-gomobile/bucket.go
  lib/uplink-gomobile/libuplink_android/app/src/androidTest/java/io/storj/mobile/libuplink/LibuplinkInstrumentedTest.java
Labels: cla-signed

#3319 cmd/satellite: add API run command to satellite dockerfile entrypoint
  cmd/satellite/entrypoint
Labels: cla-signed

#3327 satellite/console: forgot password, resend email endpoints added, default http route replaced with gorilla mux
  satellite/console/consoleweb/consoleapi/auth.go
  satellite/console/consoleweb/server.go
Labels: Request Code Review, cla-signed

#3328 installer/windows: add config dir flag to windows installer
  installer/windows/Product.wxs
Labels: Code Review In-Progress, Request Code Review, Reviewer Can Merge, cla-signed

#3333 Makefile: handle empty/default $GOPATH
  Makefile
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3334 storagenode/pieces: just a tiny comment update
  storagenode/pieces/store.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3311 satellite/metainfo: pass streamID/segmentID between Batch request/response
  pkg/pb/metainfo.pb.go
  pkg/pb/metainfo.proto
  proto.lock
  satellite/metainfo/batch.go
  satellite/metainfo/metainfo_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3160 web/satellite: project owner status added on team page
  satellite/console/consoleweb/consoleql/project.go
  web/satellite/src/api/projects.ts
  web/satellite/src/components/team/ProjectMemberListItem.vue
  web/satellite/src/store/modules/projects.ts
  web/satellite/src/types/projects.ts
  web/satellite/tests/unit/apiKeys/ApiKeysArea.spec.ts
  web/satellite/tests/unit/projectMembers/ProjectMemberListItem.spec.ts
  web/satellite/tests/unit/projectMembers/ProjectMembersArea.spec.ts
  web/satellite/tests/unit/projectMembers/__snapshots__/ProjectMemberListItem.spec.ts.snap
  web/satellite/tests/unit/store/projects.spec.ts
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3336 Expose range download in gomobile
  lib/uplink-gomobile/bucket.go
  lib/uplink-gomobile/libuplink_android/app/src/androidTest/java/io/storj/mobile/libuplink/LibuplinkInstrumentedTest.java
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3339 web/storagenode: node version bug fixed
  web/storagenode/src/app/components/SNOContentTitle.vue
  web/storagenode/src/storagenode/api/storagenode.ts
  web/storagenode/src/storagenode/dashboard.ts
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3228 installer/windows: custom welcome dialog
  installer/windows/CustomInstallDir.wxs
  installer/windows/StorjWelcomeDlg.wxs
  installer/windows/windows.wixproj
Labels: Request Code Review, cla-signed

#3337 satellite/console: add REST delete API endpoint
  satellite/console/consoleweb/consoleapi/auth.go
  satellite/console/consoleweb/server.go
Labels: Request Code Review, cla-signed

#3322 storagenode/gracefulexit: Implement storage node graceful exit worker - part 1
  pkg/pb/gracefulexit.pb.go
  pkg/pb/gracefulexit.proto
  proto.lock
  satellite/gracefulexit/endpoint.go
  satellite/gracefulexit/endpoint_test.go
  satellite/orders/service.go
  storagenode/gracefulexit/chore.go
  storagenode/gracefulexit/chore_test.go
  storagenode/gracefulexit/endpoint.go
  storagenode/gracefulexit/worker.go
  storagenode/peer.go
  uplink/ecclient/client.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3335 pkg/rpc: remove read/write deadlines as a mechanism for request timeouts
  cmd/gateway/main.go
  cmd/uplink/cmd/root.go
  internal/testplanet/uplink.go
  lib/uplink/uplink.go
  lib/uplink/uplink_test.go
  pkg/rpc/common.go
  pkg/rpc/dial.go
  satellite/audit/reverify_test.go
  storagenode/orders/service.go
  storagenode/peer.go
  uplink/config.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3300 cmd/satellite: add graceful exit reports command to satellite CLI
  cmd/satellite/gracefulexit.go
  cmd/satellite/main.go
  cmd/satellite/usage.go
  satellite/gracefulexit/common.go
  satellite/gracefulexit/getnodes_test.go
  satellite/overlay/service.go
  satellite/overlay/service_test.go
  satellite/satellitedb/gracefulexit.go
  satellite/satellitedb/overlaycache.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3315 uplink/metainfo: cleanup method names
  lib/uplink/project.go
  satellite/metainfo/metainfo_test.go
  uplink/metainfo/client.go
  uplink/metainfo/client_old.go
  uplink/metainfo/kvmetainfo/stream.go
  uplink/storage/segments/store.go
  uplink/storage/streams/store.go
  uplink/storage/streams/store_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3318 satellite/payments: add payments loop, update pending transactions
  satellite/api.go
  satellite/console/consoleweb/consoleql/mutation_test.go
  satellite/console/consoleweb/consoleql/query_test.go
  satellite/payments/clearing.go
  satellite/payments/paymentsconfig/config.go
  satellite/payments/stripecoinpayments/clearing.go
  satellite/payments/stripecoinpayments/service.go
  satellite/payments/stripecoinpayments/tokens.go
  satellite/payments/stripecoinpayments/transactions.go
  satellite/payments/stripecoinpayments/transactions_test.go
  satellite/peer.go
  satellite/satellitedb/coinpaymentstxs.go
  satellite/satellitedb/dbx/satellitedb.dbx
  satellite/satellitedb/dbx/satellitedb.dbx.go
Labels: Request Code Review, cla-signed

#3294 web/satellite: long email bug fixed
  web/satellite/src/components/account/ProfileArea.vue
  web/satellite/src/components/buckets/NoBucketsArea.vue
  web/satellite/src/components/project/ProjectDetails.vue
Labels: Request Code Review, Reviewer Can Merge, cla-signed
