Repository storj/storj, pull requests merged in 2019-02, with the labels that each got.

#1202 Fix identity creation unicorn vomit
  cmd/identity/main.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1181 Test merging planets
  bootstrap/peer.go
  internal/testplanet/planet.go
  pkg/discovery/service_test.go
  pkg/kademlia/config.go
  pkg/kademlia/kademlia.go
  pkg/kademlia/merge_test.go
  satellite/peer.go
  storagenode/peer.go
Labels: Request Code Review, cla-signed

#1206 Fix typo - second edition
  satellite/satellitedb/overlaycache.go
Labels: Request Code Review, cla-signed

#1205 Add top flag to tparse
  .travis.yml
  pkg/kademlia/merge_test.go
Labels: Request Code Review, cla-signed

#1207 Fix audit
  pkg/audit/verifier.go
  pkg/audit/verifier_test.go
Labels: Request Code Review, cla-signed

#1039 Satellite api keys frontend
  package-lock.json
  satellite/console/service.go
  web/satellite/package.json
  web/satellite/src/App.vue
  web/satellite/src/api/apiKeys.ts
  web/satellite/src/components/apiKeys/AddApiKeyPopup.vue
  web/satellite/src/components/apiKeys/ApiKeysArea.vue
  web/satellite/src/components/apiKeys/ApiKeysItem.vue
  web/satellite/src/components/apiKeys/CopyApiKeyPopup.vue
  web/satellite/src/components/apiKeys/footerArea/DeleteApiKeysArea.vue
  web/satellite/src/components/apiKeys/headerArea/HeaderArea.vue
  web/satellite/src/components/common/EmptyStateArea.vue
  web/satellite/src/components/header/projectSelection/ProjectSelectionDropdown.vue
  web/satellite/src/store/index.ts
  web/satellite/src/store/modules/apiKeys.ts
  web/satellite/src/store/modules/appState.ts
  web/satellite/src/store/mutationConstants.ts
  web/satellite/src/utils/constants/actionNames.ts
Labels: Request Code Review, WIP, cla-signed

#1211 improve identity create ux
  pkg/identity/certificate_authority.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1201 Updates transport dialopts to use WithBlock()
  internal/testplanet/node.go
  pkg/node/connection_pool.go
  pkg/transport/transport.go
  pkg/transport/transport_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1213 miniogw: fix buffer size alignment
  pkg/miniogw/config.go
Labels: Reviewer Can Merge, cla-signed

#1209 Fix panic in PointerDB.Get
  pkg/pointerdb/pdbclient/client.go
  pkg/pointerdb/pdbclient/client_test.go
  pkg/pointerdb/pointerdb.go
  pkg/storage/segments/repairer.go
  pkg/storage/segments/store.go
Labels: cla-signed

#1208 Fix EOF error on audits (storage node)
  pkg/piecestore/psserver/retrieve.go
Labels: Request Code Review, cla-signed

#1214 Only run gospace tidy when go.mod or go.sum change
  .travis.yml
  scripts/check-travis-tidy.sh
Labels: Request Code Review, cla-signed

#1203 Cleanup repository a bit
  cmd/pdbinspect/main.go
  docker-compose.yaml
  examples/auth/main.go
  examples/metric-sender/main.go
  pkg/process/metrics.go
  pkg/telemetry/example_test.go
  test/Dockerfile
Labels: Request Code Review, cla-signed

#1166 sql based tally
  cmd/satellite/main.go
  pkg/accounting/db.go
  pkg/accounting/rollup/rollup.go
  pkg/accounting/rollup/rollup_test.go
  pkg/accounting/tally/tally.go
  pkg/accounting/tally/tally_test.go
  pkg/bwagreement/bwagreement_test.go
  pkg/bwagreement/server.go
  pkg/bwagreement/server_test.go
  pkg/piecestore/psserver/agreementsender/agreementsender.go
  satellite/satellitedb/accounting.go
  satellite/satellitedb/bandwidthagreement.go
  satellite/satellitedb/dbx/satellitedb.dbx
  satellite/satellitedb/dbx/satellitedb.dbx.go
  satellite/satellitedb/dbx/satellitedb.dbx.postgres.sql
  satellite/satellitedb/dbx/satellitedb.dbx.sqlite3.sql
  satellite/satellitedb/locked.go
Labels: Request Code Review, cla-signed

#1217 make a map object before inserting into it
  pkg/accounting/tally/tally.go
Labels: cla-signed

#1223 Fix typos in check-travis-tidy.sh
  scripts/check-travis-tidy.sh
Labels: Request Code Review, cla-signed

#1220 Stop storagenode on ctrl+c
  pkg/server/server.go
  scripts/check-travis-tidy.sh
Labels: cla-signed

#1221 testplanet: add capability to stop peers
  internal/testplanet/planet.go
  internal/testplanet/planet_test.go
Labels: Request Code Review, cla-signed

#1026 Divide uplink and gateway params set
  cmd/gateway/Dockerfile
  cmd/gateway/main.go
  cmd/uplink/cmd/cat.go
  cmd/uplink/cmd/cp.go
  cmd/uplink/cmd/ls.go
  cmd/uplink/cmd/mb.go
  cmd/uplink/cmd/mount.go
  cmd/uplink/cmd/put.go
  cmd/uplink/cmd/rb.go
  cmd/uplink/cmd/rm.go
  cmd/uplink/cmd/root.go
  cmd/uplink/cmd/run.go
  cmd/uplink/cmd/setup.go
  cmd/uplink/main.go
  satellite/satellitedb/dbx/satellitedb.dbx.go
Labels: Request Code Review, cla-signed

#1183 Upload/download for testplanet Uplink
  internal/testplanet/node.go
  internal/testplanet/planet.go
  internal/testplanet/uplink.go
  internal/testplanet/uplink_test.go
  pkg/metainfo/kvmetainfo/buckets_test.go
  pkg/metainfo/kvmetainfo/objects.go
  pkg/metainfo/kvmetainfo/objects_test.go
Labels: Request Code Review, cla-signed

#1222 testplanet.Run
  docker-compose.yaml
  internal/testplanet/planet.go
  internal/testplanet/run.go
  internal/testplanet/run_test.go
  pkg/kademlia/merge_test.go
  satellite/peer.go
  satellite/satellitedb/database.go
  satellite/satellitedb/locked.go
  satellite/satellitedb/satellitedbtest/run.go
Labels: Request Code Review, cla-signed

#1186 node graveyard resurrection
  internal/testplanet/planet.go
  pkg/discovery/service.go
Labels: cla-signed

#909 Improve logic for cutting the long tail during upload
  examples/eestream/store/main.go
  go.mod
  go.sum
  pkg/eestream/decode.go
  pkg/eestream/encode.go
  pkg/eestream/mocks/mock_client.go
  pkg/eestream/rs.go
  pkg/eestream/rs_test.go
  pkg/metainfo/kvmetainfo/buckets_test.go
  pkg/metainfo/kvmetainfo/objects_test.go
  pkg/miniogw/gateway_test.go
  pkg/piecestore/psclient/client.go
  pkg/storage/ec/client.go
  pkg/storage/ec/client_test.go
  pkg/storage/segments/store.go
Labels: Request Code Review, cla-signed

#1227 Ensure that tally tests run against postgres
  internal/testplanet/run_test.go
  pkg/accounting/tally/tally_test.go
Labels: Request Code Review, cla-signed

#1235 Fix data race in teeReader
  internal/sync2/tee.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1228 Ensure cursor tests run against postgres
  pkg/audit/cursor_test.go
Labels: Request Code Review, cla-signed

#1229 Ensure checker tests run against postgres
  pkg/datarepair/checker/checker_test.go
  pkg/datarepair/irreparable/irreparable_test.go
Labels: Request Code Review, cla-signed

#1239 Fixes intermitent failures in storage/ec TestPut
  pkg/storage/ec/client_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1230 Ensure discovery tests run against postgres
  pkg/discovery/service_test.go
Labels: Request Code Review, cla-signed

#1143 Add bucket to project relationship on satellite
  cmd/storj-sim/console.go
  cmd/storj-sim/network.go
  internal/testplanet/planet.go
  internal/testplanet/uplink.go
  pkg/metainfo/kvmetainfo/buckets_test.go
  pkg/miniogw/gateway_test.go
  pkg/miniogw/integration_test.go
  pkg/pointerdb/pointerdb.go
  pkg/pointerdb/pointerdb_test.go
  satellite/console/apikeys.go
  satellite/console/buckets.go
  satellite/console/consoleweb/consoleql/mutation_test.go
  satellite/console/consoleweb/consoleql/query_test.go
  satellite/console/database.go
  satellite/console/projects_test.go
  satellite/console/service.go
  satellite/peer.go
  satellite/satellitedb/buckets.go
  satellite/satellitedb/consoledb.go
  satellite/satellitedb/dbx/satellitedb.dbx
  satellite/satellitedb/dbx/satellitedb.dbx.go
  satellite/satellitedb/dbx/satellitedb.dbx.postgres.sql
  satellite/satellitedb/dbx/satellitedb.dbx.sqlite3.sql
  satellite/satellitedb/locked.go
Labels: Backward Incompatible, Request Code Review, cla-signed

#1236 Use lower bcrypt cost for console.Service when running tests and disable flaky tests
  internal/testplanet/planet.go
  pkg/cfgstruct/bind.go
  pkg/kademlia/merge_test.go
  pkg/piecestore/psserver/server_test.go
  satellite/console/consoleweb/consoleql/mutation_test.go
  satellite/console/consoleweb/consoleql/query_test.go
  satellite/console/consoleweb/server.go
  satellite/console/service.go
  satellite/peer.go
Labels: cla-signed

#1226 storage node cert cache
  pkg/accounting/tally/tally_test.go
  pkg/kademlia/dialer.go
  pkg/kademlia/kademlia.go
  pkg/kademlia/kademlia_planet_test.go
  pkg/piecestore/psserver/readerwriter.go
  pkg/piecestore/psserver/server.go
  pkg/piecestore/psserver/server_test.go
Labels: Request Code Review, cla-signed

#1240 restore previous folder layout in travis
  scripts/setup-gopath.sh
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1231 Make testplanet.Run and satellitedbtest.Run parallel by default
  internal/testplanet/planet.go
  internal/testplanet/run.go
  satellite/console/consoleweb/consoleql/mutation_test.go
  satellite/console/consoleweb/consoleql/schema.go
  satellite/console/consoleweb/server.go
  satellite/satellitedb/satellitedbtest/run.go
Labels: Request Code Review, cla-signed

#1218 don't put nil nodes in GetResponse
  pkg/metainfo/kvmetainfo/buckets_test.go
  pkg/metainfo/kvmetainfo/objects_test.go
  pkg/pointerdb/pdbclient/client.go
  pkg/pointerdb/pointerdb.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1238 psserver: swallow io.EOF when getting full content in FileRanger
  pkg/piecestore/psserver/server_test.go
  pkg/ranger/file.go
Labels: Request Code Review, cla-signed

#1219 better batch-generation
  cmd/identity/batch.go
  cmd/identity/keys.go
  go.mod
  go.sum
  internal/cui/example.go
  internal/cui/screen.go
  pkg/identity/generate.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1247 Fix parallel execution sharing
  internal/testplanet/run.go
  satellite/satellitedb/satellitedbtest/run.go
Labels: Request Code Review, cla-signed

#1216 add certificates claims+
  cmd/certificates/claims.go
  cmd/certificates/setup.go
  pkg/certificates/certificates.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1248 Fix discovery busy-spin
  pkg/discovery/service.go
Labels: Request Code Review, cla-signed

#1233 Remove node package and simplify DHT interface
  bootstrap/peer.go
  bootstrap/testing.go
  internal/testplanet/planet.go
  internal/testplanet/planet_test.go
  pkg/dht/dht.go
  pkg/kademlia/dialer_test.go
  pkg/kademlia/endpoint.go
  pkg/kademlia/inspector.go
  pkg/kademlia/kademlia.go
  pkg/kademlia/kademlia_test.go
  pkg/node/client.go
  pkg/node/connection_pool.go
  pkg/node/node.go
  pkg/node/node_test.go
  pkg/node/server.go
  pkg/piecestore/psserver/server.go
  satellite/peer.go
  satellite/testing.go
  storagenode/peer.go
  storagenode/testing.go
Labels: Request Code Review, cla-signed

#1204 Enable ipv6 tests
  cmd/storj-sim/network.go
  scripts/test-sim.sh
Labels: Request Code Review, cla-signed

#1246 Add checker irreparable test
  pkg/datarepair/checker/checker_test.go
  satellite/satellitedb/irreparabledb.go
Labels: Request Code Review, cla-signed

#1249 Proper planet shutdown
  bootstrap/peer.go
  internal/testplanet/planet.go
  pkg/certificates/config.go
  pkg/datarepair/repairer/config.go
  pkg/overlay/client.go
  pkg/pointerdb/pdbclient/client.go
  pkg/server/server.go
  pkg/transport/transport.go
  satellite/console/consoleweb/server.go
  satellite/peer.go
  storagenode/peer.go
Labels: Request Code Review, cla-signed

#1232 Ensure overlay tests run against postgres
  pkg/overlay/cache_test.go
  pkg/overlay/client_test.go
  pkg/overlay/server_test.go
Labels: cla-signed

#1198 go test fail due to consoleql UTC issues
  satellite/console/consoleweb/consoleql/mutation_test.go
  satellite/console/consoleweb/consoleql/query_test.go
Labels: Request Code Review, cla-signed

#1252 storagenode: fix port in entrypoint
  cmd/storagenode/entrypoint
Labels: cla-signed

#1215 identity improvements:
  cmd/certificates/auth.go
  cmd/certificates/main.go
  cmd/certificates/setup.go
  cmd/certificates/sign.go
  cmd/certificates/verify.go
  cmd/identity/certificate_authority.go
  cmd/identity/identity.go
  cmd/identity/main.go
  cmd/identity/revocations.go
  pkg/certificates/config.go
  pkg/identity/certificate_authority.go
  pkg/identity/extensions_test.go
  pkg/identity/identity.go
  pkg/identity/revocations.go
  pkg/identity/revocations_test.go
  pkg/identity/setup.go
  pkg/peertls/extensions.go
  pkg/peertls/peertls.go
  pkg/peertls/peertls_test.go
  pkg/server/config.go
  pkg/server/options.go
  pkg/utils/utils.go
  pkg/utils/utils_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1224 Rollup tests
  pkg/accounting/db.go
  pkg/accounting/rollup/rollup_test.go
  pkg/accounting/tally/tally.go
  pkg/accounting/tally/tally_test.go
  satellite/satellitedb/accounting.go
  satellite/satellitedb/dbx/satellitedb.dbx
  satellite/satellitedb/dbx/satellitedb.dbx.go
  satellite/satellitedb/locked.go
Labels: cla-signed

#1253 Added congratulations page after registration. Implemented Account confirmation argument validation.
  web/satellite/src/App.vue
  web/satellite/src/api/users.ts
  web/satellite/src/components/common/RegistrationSuccessPopup.vue
  web/satellite/src/store/modules/appState.ts
  web/satellite/src/store/modules/users.ts
  web/satellite/src/store/mutationConstants.ts
  web/satellite/src/utils/constants/actionNames.ts
  web/satellite/src/views/Dashboard.vue
  web/satellite/src/views/Register.vue
Labels: cla-signed

#1241 regroup things related to public-key cryptography
  cmd/identity/batch.go
  cmd/identity/main.go
  cmd/storj-sim/inmemory.go
  internal/testpeertls/certificates.go
  pkg/auth/signature.go
  pkg/identity/certificate_authority.go
  pkg/identity/extensions_test.go
  pkg/identity/generate.go
  pkg/identity/identity.go
  pkg/identity/identity_test.go
  pkg/identity/utils.go
  pkg/peertls/extensions.go
  pkg/peertls/peertls.go
  pkg/peertls/peertls_test.go
  pkg/peertls/utils.go
  pkg/pkcrypto/common.go
  pkg/pkcrypto/encoding.go
  pkg/pkcrypto/hashing.go
  pkg/pkcrypto/signing.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1256 Fixes Difficulty Display Difference
  cmd/identity/batch.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1262 web satellite popups changed
  web/satellite/src/components/apiKeys/CopyApiKeyPopup.vue
  web/satellite/src/components/common/RegistrationSuccessPopup.vue
  web/satellite/src/components/project/ProjectCreationSuccessPopup.vue
  web/satellite/src/components/team/AddUserPopup.vue
Labels: cla-signed

#1265 Satellite Web Changed graphQL default port
  web/satellite/src/utils/apolloManager.ts
Labels: cla-signed

#1242 SHA256Hash() and TBSBytes() needn't return error
  cmd/identity/main.go
  pkg/peertls/extensions.go
  pkg/peertls/peertls_test.go
  pkg/pkcrypto/encoding.go
  pkg/pkcrypto/hashing.go
  pkg/pkcrypto/signing.go
Labels: cla-signed

#1264 Disable colors in dashboard by default. --color flag to enable them
  cmd/identity/main.go
  cmd/storagenode/dashboard.go
  cmd/storagenode/main.go
Labels: cla-signed

#1243 Consolidate key/cert/signature encoding and decoding
  cmd/identity/batch.go
  cmd/identity/main.go
  cmd/storj-sim/inmemory.go
  internal/testplanet/gen_identities.go
  pkg/auth/signedMessage.go
  pkg/bwagreement/server_test.go
  pkg/certificates/certificates_test.go
  pkg/identity/certificate_authority.go
  pkg/identity/identity.go
  pkg/identity/identity_test.go
  pkg/identity/utils.go
  pkg/peertls/peertls.go
  pkg/pkcrypto/common.go
  pkg/pkcrypto/encoding.go
  pkg/pkcrypto/signing.go
  pkg/server/options.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1042 Store the uplinks public key on the satellite so that it can verify bandwidth requests in the future
  pkg/accounting/tally/tally_test.go
  pkg/bwagreement/server.go
  pkg/bwagreement/server_test.go
  pkg/bwagreement/testbwagreement/common.go
  pkg/certdb/certdb.go
  pkg/certdb/certdb_test.go
  pkg/pointerdb/allocation.go
  pkg/pointerdb/pointerdb_test.go
  satellite/peer.go
  satellite/satellitedb/certdb.go
  satellite/satellitedb/database.go
  satellite/satellitedb/dbx/satellitedb.dbx
  satellite/satellitedb/dbx/satellitedb.dbx.go
  satellite/satellitedb/dbx/satellitedb.dbx.postgres.sql
  satellite/satellitedb/dbx/satellitedb.dbx.sqlite3.sql
  satellite/satellitedb/locked.go
Labels: Request Code Review, cla-signed

#1267 sync2.Cycle for controllable intervals
  internal/sync2/cycle.go
  internal/sync2/cycle_test.go
Labels: Request Code Review, cla-signed

#1266 Convert Payments to use SQL, for SUM() and Wallet
  pkg/accounting/rollup/rollup_test.go
  satellite/satellitedb/accounting.go
  satellite/satellitedb/dbx/satellitedb.dbx
  satellite/satellitedb/dbx/satellitedb.dbx.go
Labels: Request Code Review, cla-signed

#1244 Unite all cryptographic signing and verifying
  cmd/identity/batch.go
  go.mod
  go.sum
  internal/debugging/certificates.go
  pkg/accounting/tally/tally_test.go
  pkg/auth/signature.go
  pkg/auth/signature_test.go
  pkg/auth/signedMessage.go
  pkg/bwagreement/server.go
  pkg/bwagreement/server_test.go
  pkg/certdb/certdb.go
  pkg/certdb/certdb_test.go
  pkg/certificates/certificates.go
  pkg/identity/certificate_authority.go
  pkg/identity/generate.go
  pkg/identity/identity.go
  pkg/identity/identity_test.go
  pkg/peertls/extensions.go
  pkg/peertls/peertls.go
  pkg/peertls/peertls_test.go
  pkg/peertls/utils.go
  pkg/piecestore/psserver/server.go
  pkg/piecestore/psserver/server_test.go
  pkg/pkcrypto/common.go
  pkg/pkcrypto/encoding.go
  pkg/pkcrypto/signing.go
  pkg/pkcrypto/signing_test.go
  pkg/pointerdb/allocation.go
  pkg/storage/ec/client_test.go
  satellite/satellitedb/certdb.go
  satellite/satellitedb/locked.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1269 add inspector to makefile
  Makefile
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1274 close revocation database in test
  pkg/identity/extensions_test.go
Labels: Request Code Review, cla-signed

#1275 Ensure everyone sees everyone else
  bootstrap/peer.go
  internal/sync2/cycle.go
  internal/testplanet/planet.go
  internal/testplanet/uplink_test.go
  pkg/accounting/rollup/rollup_test.go
  pkg/audit/cursor_test.go
  pkg/discovery/service.go
  pkg/discovery/service_test.go
  pkg/kademlia/dialer_test.go
  pkg/kademlia/kademlia.go
  pkg/kademlia/kademlia_test.go
  pkg/metainfo/kvmetainfo/objects_test.go
  pkg/miniogw/integration_test.go
  pkg/overlay/client_test.go
  pkg/overlay/config.go
  pkg/overlay/server_test.go
  pkg/transport/transport.go
  satellite/peer.go
  storagenode/peer.go
Labels: Request Code Review, cla-signed

#1273 Disable psserver.TestRetrieve
  pkg/piecestore/psserver/server_test.go
Labels: Request Code Review, cla-signed

#1234 Move metainfo config
  cmd/gateway/main.go
  cmd/uplink/cmd/root.go
  cmd/uplink/cmd/setup.go
  internal/testplanet/uplink.go
  pkg/miniogw/config.go
  pkg/miniogw/integration_test.go
  uplink/config.go
Labels: Request Code Review, cla-signed

#1277 Fix randomness in stopping nodes in TestGetObjectStream
  pkg/metainfo/kvmetainfo/objects_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1282 Fix server config usage
  bootstrap/peer.go
  internal/testplanet/planet.go
  pkg/server/server.go
  satellite/peer.go
  storagenode/peer.go
Labels: cla-signed

#1283 disable revocation db for testplanet
  internal/testplanet/planet.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1281 Enable planet Merging test
  internal/testplanet/planet.go
  pkg/kademlia/kademlia.go
  pkg/kademlia/merge_test.go
  pkg/metainfo/kvmetainfo/objects_test.go
  satellite/peer.go
Labels: Request Code Review, cla-signed

#1272 Adds tests to discovery/graveyard
  pkg/discovery/service_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1271 Add test for randomized node selection
  pkg/overlay/cache_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1254 Smtp mail sending library
  internal/mail/message.go
  internal/mail/sender.go
Labels: Request Code Review, WIP, cla-signed

#1251 Updating account activation flow
  cmd/storj-sim/console.go
  satellite/console/consoleweb/consoleql/mutation.go
  satellite/console/consoleweb/consoleql/mutation_test.go
  satellite/console/consoleweb/consoleql/query_test.go
  satellite/console/database.go
  satellite/console/service.go
  satellite/console/users.go
  satellite/console/users_test.go
  satellite/satellitedb/consoledb.go
  satellite/satellitedb/dbx/satellitedb.dbx
  satellite/satellitedb/dbx/satellitedb.dbx.go
  satellite/satellitedb/dbx/satellitedb.dbx.postgres.sql
  satellite/satellitedb/dbx/satellitedb.dbx.sqlite3.sql
  satellite/satellitedb/locked.go
  satellite/satellitedb/users.go
  satellite/satellitedb/users_test.go
  web/satellite/src/api/users.ts
Labels: Request Code Review, cla-signed

#1285 pkg/transport: fail on bad certificates
  internal/testplanet/gen_identities.go
  pkg/transport/transport.go
  satellite/peer.go
Labels: Request Code Review, cla-signed

#1286 pkg/transport: require tls configuration for dialing
  bootstrap/peer.go
  cmd/inspector/main.go
  cmd/storagenode/dashboard.go
  cmd/storj-sim/network.go
  examples/grpc-debug/main.go
  examples/pointerdb-client/main.go
  internal/testplanet/planet.go
  internal/testplanet/uplink.go
  pkg/certificates/certificates.go
  pkg/certificates/certificates_test.go
  pkg/certificates/config.go
  pkg/datarepair/repairer/config.go
  pkg/datarepair/repairer/repairer.go
  pkg/identity/identity.go
  pkg/kademlia/kademlia_test.go
  pkg/metainfo/kvmetainfo/buckets_test.go
  pkg/miniogw/gateway_test.go
  pkg/overlay/client.go
  pkg/peertls/tlsopts/cert.go
  pkg/peertls/tlsopts/config.go
  pkg/peertls/tlsopts/options.go
  pkg/peertls/tlsopts/options_test.go
  pkg/peertls/tlsopts/tls.go
  pkg/piecestore/psserver/agreementsender/agreementsender.go
  pkg/piecestore/psserver/server_test.go
  pkg/pointerdb/pdbclient/client.go
  pkg/server/config.go
  pkg/server/server.go
  pkg/storage/ec/client.go
  pkg/storage/ec/client_test.go
  pkg/transport/transport.go
  pkg/transport/transport_test.go
  satellite/peer.go
  storagenode/peer.go
  uplink/config.go
Labels: Request Code Review, cla-signed

#1290 Better randomized selection test limit
  pkg/overlay/cache_test.go
Labels: Request Code Review, cla-signed

#1260 Gmail auth implementation for SMTP
  internal/mail/gmail/gmailauth.go
Labels: cla-signed

#1295 move node type definition to db level for node selection
  pkg/overlay/cache.go
  pkg/overlay/cache_test.go
  pkg/overlay/server.go
  satellite/satellitedb/overlaycache.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1294 test random selection for new nodes
  pkg/overlay/cache_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1296 Node selection method name change
  pkg/overlay/cache.go
  pkg/overlay/cache_test.go
  satellite/satellitedb/locked.go
  satellite/satellitedb/overlaycache.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1279 Disable Checker subsystem in tests
  pkg/datarepair/checker/checker.go
  pkg/datarepair/checker/checker_test.go
  satellite/peer.go
Labels: Request Code Review, cla-signed

#1261 implement basic migration
  internal/migrate/create_test.go
  internal/migrate/versions.go
  internal/migrate/versions_test.go
Labels: Request Code Review, cla-signed

#1300 Update dbx
  satellite/satellitedb/dbx/satellitedb.dbx.go
Labels: Request Code Review, cla-signed

#1298 Implemented Notification for API key deletion result.
  satellite/console/consoleweb/consoleql/mutation.go
  satellite/console/consoleweb/consoleql/mutation_test.go
  satellite/console/service.go
  web/satellite/src/api/apiKeys.ts
  web/satellite/src/components/apiKeys/footerArea/DeleteApiKeysArea.vue
  web/satellite/src/store/modules/apiKeys.ts
Labels: cla-signed

#1304 pb.Equal fix
  pkg/pb/bandwidth_utils.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1305 create dbutil package for migration testing
  internal/dbutil/dbschema/schema.go
  internal/dbutil/pgutil/query.go
  internal/dbutil/pgutil/query_test.go
  internal/dbutil/pgutil/schema.go
  internal/testplanet/run.go
  satellite/satellitedb/database.go
  satellite/satellitedb/satellitedbtest/run.go
Labels: Request Code Review, cla-signed

#1306 Removed ReverseList from KeyValueStore interfaces
  pkg/kademlia/routing_helpers.go
  pkg/storj/node.go
  storage/boltdb/client.go
  storage/common.go
  storage/postgreskv/client.go
  storage/redis/client.go
  storage/storelogger/logger.go
  storage/teststore/store.go
  storage/testsuite/test.go
  storage/testsuite/test_list.go
Labels: cla-signed

#1310 Add uplink tests
  scripts/test-sim-aws.sh
  scripts/test-sim.sh
  scripts/test-uplink.sh
Labels: cla-signed

#1308 Move SplitConnstr to a nicer place
  internal/dbutil/split.go
  pkg/certificates/config.go
  pkg/identity/revocations.go
  pkg/pointerdb/config.go
  pkg/utils/utils.go
  satellite/satellitedb/database.go
Labels: Request Code Review, cla-signed

#1297 Repair checker is checking the same 1000 elements all the time
  pkg/datarepair/checker/checker.go
  pkg/datarepair/checker/checker_test.go
  storage/boltdb/client.go
  storage/boltdb/common.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1313 Reduce Log Messages on Level Info
  pkg/piecestore/psclient/client.go
  pkg/piecestore/psclient/readerwriter.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1314 Fix invalid config key msg for dashbord
  cmd/storagenode/main.go
  pkg/process/exec_conf.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1312 dbutil add snapshot logic
  internal/dbutil/dbschema/data.go
  internal/dbutil/dbschema/schema.go
  internal/dbutil/dbschema/snapshot.go
  internal/dbutil/pgutil/data.go
  internal/dbutil/pgutil/db.go
  internal/dbutil/pgutil/query.go
  internal/dbutil/pgutil/query_test.go
Labels: Request Code Review, cla-signed

#1315 fix kad refresh bad bucket range
  pkg/kademlia/kademlia.go
  pkg/kademlia/routing.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1316 Fixed Input deletion on Add Team Member Popup.
  web/satellite/src/components/team/AddUserPopup.vue
Labels: cla-signed

#1317 add `certificates claim delete` & refactor
  cmd/certificates/claims.go
  pkg/certificates/certificates.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1301 Satellite migrations
  cmd/overlay/cache.go
  cmd/satellite/main.go
  cmd/satellite/payments.go
  internal/dbutil/dbschema/data.go
  internal/dbutil/dbschema/snapshot.go
  internal/migrate/versions.go
  internal/testplanet/planet.go
  internal/testplanet/run.go
  pkg/pointerdb/pointerdb_test.go
  satellite/satellitedb/database.go
  satellite/satellitedb/migrate.go
  satellite/satellitedb/migrate_postgres_test.go
  satellite/satellitedb/satellitedbtest/run.go
  satellite/satellitedb/testdata/postgres.v0.sql
  satellite/satellitedb/testdata/postgres.v1.sql
  satellite/satellitedb/testdata/postgres.v2.sql
  satellite/satellitedb/testdata/postgres.v3.sql
  satellite/satellitedb/testdata/postgres.v4.sql
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1303 [V3-1113] empty search result area bug fixed
  web/satellite/src/components/common/EmptyStateArea.vue
  web/satellite/src/components/team/TeamArea.vue
Labels: cla-signed

#1311 Create dbutil package for sqlite
  internal/dbutil/pgutil/query.go
  internal/dbutil/sqliteutil/db.go
  internal/dbutil/sqliteutil/query.go
  internal/dbutil/sqliteutil/query_test.go
Labels: Request Code Review, cla-signed

#1320 kad.FindNear fix
  pkg/dht/dht.go
  pkg/kademlia/dialer_test.go
  pkg/kademlia/inspector.go
  pkg/kademlia/kademlia.go
  pkg/kademlia/kademlia_test.go
  pkg/kademlia/routing.go
  pkg/kademlia/routing_test.go
  pkg/piecestore/psserver/server.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1321 Add protolock to build
  .travis.yml
  proto.lock
  scripts/protobuf.go
Labels: cla-signed

#1325 show nicer time in storage node dashboard
  cmd/storagenode/dashboard.go
Labels: Request Code Review, cla-signed

#1299 Storagenode migrations
  cmd/storagenode/main.go
  internal/migrate/versions_test.go
  internal/testcontext/context.go
  internal/testplanet/planet.go
  pkg/piecestore/psserver/psdb/migrate_test.go
  pkg/piecestore/psserver/psdb/psdb.go
  pkg/piecestore/psserver/psdb/psdb_test.go
  pkg/piecestore/psserver/psdb/testdata/sqlite.v0.sql
  pkg/piecestore/psserver/server_test.go
  storagenode/storagenodedb/database.go
Labels: Request Code Review, cla-signed

#1323 handle server termination in kademlia tests
  pkg/kademlia/kademlia_test.go
Labels: Request Code Review, cla-signed

#1326 restrict actions on PayerBandwidthAllocation
  pkg/pointerdb/allocation.go
Labels: Request Code Review, cla-signed

#1258 removes some SignedMessage use
  internal/testplanet/planet_test.go
  pkg/audit/cursor.go
  pkg/audit/verifier.go
  pkg/audit/verifier_test.go
  pkg/auth/signature.go
  pkg/auth/signature_test.go
  pkg/pb/bandwidth_utils.go
  pkg/pb/piecestore.pb.go
  pkg/pb/piecestore.proto
  pkg/piecestore/psclient/client.go
  pkg/piecestore/psclient/pieceranger.go
  pkg/piecestore/psclient/pieceranger_test.go
  pkg/piecestore/psclient/readerwriter.go
  pkg/piecestore/psserver/retrieve.go
  pkg/piecestore/psserver/server.go
  pkg/piecestore/psserver/server_test.go
  pkg/piecestore/psserver/store.go
  pkg/pointerdb/allocation.go
  pkg/pointerdb/pdbclient/client.go
  pkg/pointerdb/pdbclient/mocks/mock_client.go
  pkg/pointerdb/pointerdb.go
  pkg/pointerdb/pointerdb_test.go
  pkg/storage/ec/client.go
  pkg/storage/ec/client_test.go
  pkg/storage/ec/mocks/mock_client.go
  pkg/storage/ec/psclient_mock_test.go
  pkg/storage/ec/transportclient_mock_test.go
  pkg/storage/segments/repairer.go
  pkg/storage/segments/repairer_test.go
  pkg/storage/segments/store.go
  pkg/storage/segments/store_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1329 mark sync2 tests parallel
  internal/sync2/copy_test.go
  internal/sync2/cycle_test.go
  internal/sync2/fence_test.go
  internal/sync2/limiter_test.go
  internal/sync2/pipe_test.go
  internal/sync2/sleep_test.go
  internal/sync2/tee_test.go
  internal/sync2/throttle_test.go
  internal/sync2/workgroup_test.go
Labels: Request Code Review, cla-signed

#1330 Remove all-in-one description, it's no longer valid
  all-in-one.md
Labels: Request Code Review, cla-signed

#1331 linting satellite code
  web/satellite/.gitignore
  web/satellite/src/App.vue
  web/satellite/src/api/apiKeys.ts
  web/satellite/src/api/projectMembers.ts
  web/satellite/src/api/projects.ts
  web/satellite/src/api/users.ts
  web/satellite/src/components/apiKeys/AddApiKeyPopup.vue
  web/satellite/src/components/apiKeys/ApiKeysArea.vue
  web/satellite/src/components/apiKeys/CopyApiKeyPopup.vue
  web/satellite/src/components/apiKeys/footerArea/DeleteApiKeysArea.vue
  web/satellite/src/components/apiKeys/headerArea/HeaderArea.vue
  web/satellite/src/components/common/RegistrationSuccessPopup.vue
  web/satellite/src/components/header/projectSelection/ProjectSelectionDropdown.vue
  web/satellite/src/components/team/AddUserPopup.vue
  web/satellite/src/components/team/TeamArea.vue
  web/satellite/src/components/team/headerArea/SortDropdown.vue
  web/satellite/src/components/team/headerArea/SortUsersDropdown.vue
  web/satellite/src/main.ts
  web/satellite/src/router/index.ts
  web/satellite/src/store/index.ts
  web/satellite/src/store/modules/apiKeys.ts
  web/satellite/src/store/modules/appState.ts
  web/satellite/src/store/modules/notifications.ts
  web/satellite/src/store/modules/projectMembers.ts
  web/satellite/src/store/modules/projects.ts
  web/satellite/src/store/modules/users.ts
  web/satellite/src/store/mutationConstants.ts
  web/satellite/src/types/DelayedNotification.ts
  web/satellite/src/types/fetch.d.ts
  web/satellite/src/types/projects.d.ts
  web/satellite/src/types/register.d.ts
  web/satellite/src/types/response.d.ts
  web/satellite/src/types/tsx.d.ts
  web/satellite/src/types/users.d.ts
  web/satellite/src/types/vue.d.ts
  web/satellite/src/utils/apolloManager.ts
  web/satellite/src/utils/constants/ProjectMemberSortEnum.ts
  web/satellite/src/utils/constants/actionNames.ts
  web/satellite/src/utils/constants/emptyStatesImages.ts
  web/satellite/src/utils/constants/navigationLinks.ts
  web/satellite/src/utils/constants/notification.ts
  web/satellite/src/utils/constants/routerConstants.ts
  web/satellite/src/utils/idGenerator.ts
  web/satellite/src/utils/tokenManager.ts
  web/satellite/src/views/Dashboard.vue
  web/satellite/tests/unit/common/Button.spec.ts
  web/satellite/tests/unit/common/Checkbox.spec.ts
  web/satellite/tests/unit/common/HeaderedInput.spec.ts
  web/satellite/tests/unit/common/HeaderlessInput.spec.ts
  web/satellite/tests/unit/dashboard/account/AccountDropdown.spec.ts
  web/satellite/tests/unit/notifications/Notification.spec.ts
  web/satellite/tests/unit/notifications/NotificationArea.spec.ts
  web/satellite/tests/unit/store/projectMembers.spec.ts
  web/satellite/tests/unit/store/projects.spec.ts
  web/satellite/tests/unit/store/users.spec.ts
  web/satellite/tests/unit/utils/validation.spec.ts
  web/satellite/tslint.json
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1332 use correct return value in tests
  web/satellite/tests/unit/store/projects.spec.ts
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1335 Satellite web unit tests fix
  web/satellite/tests/unit/store/projectMembers.spec.ts
  web/satellite/tests/unit/store/users.spec.ts
Labels: cla-signed

#1334 ensure migrate tests cleanup
  internal/migrate/create_test.go
  internal/migrate/versions_test.go
Labels: Request Code Review, cla-signed

#1336 Added number of overall API Keys.
  web/satellite/src/components/apiKeys/footerArea/DeleteApiKeysArea.vue
  web/satellite/tests/unit/store/projectMembers.spec.ts
  web/satellite/tests/unit/store/users.spec.ts
Labels: cla-signed

#1338 Satellite web create project flow
  web/satellite/src/App.vue
  web/satellite/src/components/project/NewProjectPopup.vue
  web/satellite/src/components/project/ProjectCreationSuccessPopup.vue
  web/satellite/src/router/index.ts
  web/satellite/src/store/modules/appState.ts
  web/satellite/src/store/mutationConstants.ts
  web/satellite/src/utils/constants/actionNames.ts
  web/satellite/src/utils/constants/navigationLinks.ts
  web/satellite/src/utils/constants/routerConstants.ts
  web/satellite/src/views/Dashboard.vue
Labels: cla-signed

#1346 cmd/identity: set default CONFDIR
  cmd/identity/main.go
Labels: cla-signed

#1348 [storj-sim] storage node must wait for satellite start
  cmd/storj-sim/network.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1270 Routing table tests
  pkg/dht/dht.go
  pkg/kademlia/dialer_test.go
  pkg/kademlia/kademlia_test.go
  pkg/kademlia/replacement_cache.go
  pkg/kademlia/replacement_cache_test.go
  pkg/kademlia/routing.go
  pkg/kademlia/routing_helpers.go
  pkg/kademlia/routing_helpers_test.go
  pkg/kademlia/routing_integration_helpers_test.go
  pkg/kademlia/routing_integration_test.go
  pkg/kademlia/routing_test.go
  pkg/kademlia/testrouting/testrouting.go
  pkg/kademlia/testrouting/utils.go
  pkg/kademlia/testrouting/viz.go
  pkg/pb/utils.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1333 BWA aliases
  pkg/accounting/tally/tally_test.go
  pkg/audit/cursor.go
  pkg/audit/verifier.go
  pkg/audit/verifier_test.go
  pkg/bwagreement/bwagreement_test.go
  pkg/bwagreement/server.go
  pkg/bwagreement/server_test.go
  pkg/bwagreement/testbwagreement/common.go
  pkg/pb/bandwidth_utils.go
  pkg/piecestore/psclient/client.go
  pkg/piecestore/psclient/pieceranger.go
  pkg/piecestore/psclient/pieceranger_test.go
  pkg/piecestore/psclient/readerwriter.go
  pkg/piecestore/psserver/psdb/psdb.go
  pkg/piecestore/psserver/psdb/psdb_test.go
  pkg/piecestore/psserver/readerwriter.go
  pkg/piecestore/psserver/retrieve.go
  pkg/piecestore/psserver/server.go
  pkg/piecestore/psserver/server_test.go
  pkg/piecestore/psserver/store.go
  pkg/pointerdb/allocation.go
  pkg/pointerdb/pdbclient/client.go
  pkg/pointerdb/pdbclient/client_test.go
  pkg/pointerdb/pdbclient/mocks/mock_client.go
  pkg/pointerdb/pdbclient/pdbclient_mock_test.go
  pkg/pointerdb/pointerdb.go
  pkg/storage/ec/client.go
  pkg/storage/ec/client_test.go
  pkg/storage/ec/mocks/mock_client.go
  pkg/storage/ec/psclient_mock_test.go
  pkg/storage/segments/store_test.go
  satellite/satellitedb/bandwidthagreement.go
  satellite/satellitedb/certdb.go
  satellite/satellitedb/locked.go
  satellite/satellitedb/migrate.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1347 Storage node hash calculation on upload
  pkg/pb/bandwidth_utils.go
  pkg/pb/piecestore.pb.go
  pkg/pb/piecestore.proto
  pkg/piecestore/psserver/readerwriter.go
  pkg/piecestore/psserver/readerwriter_test.go
  pkg/piecestore/psserver/server.go
  pkg/piecestore/psserver/server_test.go
  pkg/piecestore/psserver/store.go
  storagenode/peer.go
Labels: Request Code Review, cla-signed

#1337 use peer ca whitelist in testplanet
  internal/testplanet/gen_identities.go
  internal/testplanet/identities.go
  internal/testplanet/identities_table.go
  internal/testplanet/planet.go
  internal/testplanet/signed_identities_table.go
  pkg/identity/identity.go
  pkg/peertls/tlsopts/options_test.go
  pkg/pkcrypto/encoding.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1353 Update README.md
  README.md
Labels: cla-signed

#1357 add Patrick Gerbes to cla
  .clabot
Labels: Request Code Review, cla-signed

#1354 Use SignedHash on client/uplink side
  pkg/piecestore/psclient/client.go
  pkg/piecestore/psclient/readerwriter.go
  pkg/storage/ec/client.go
  pkg/storage/ec/client_test.go
  pkg/storage/ec/mocks/mock_client.go
  pkg/storage/ec/psclient_mock_test.go
  pkg/storage/segments/repairer.go
  pkg/storage/segments/repairer_test.go
  pkg/storage/segments/store.go
Labels: Request Code Review, cla-signed

#1355 Endpoint for local node info
  cmd/inspector/main.go
  pkg/kademlia/dialer.go
  pkg/kademlia/endpoint.go
  pkg/kademlia/inspector.go
  pkg/kademlia/kademlia.go
  pkg/kademlia/kademlia_planet_test.go
  pkg/kademlia/kademlia_test.go
  pkg/pb/inspector.pb.go
  pkg/pb/inspector.proto
  pkg/pb/node.pb.go
  pkg/pb/node.proto
  pkg/pb/overlay.pb.go
  pkg/pb/overlay.proto
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1360 fix claims delete config
  cmd/certificates/claims.go
Labels: Request Code Review, cla-signed

#1361 some certificates cmd cleanup:
  cmd/certificates/claims.go
  cmd/certificates/main.go
  pkg/certificates/config.go
  pkg/identity/certificate_authority.go
  pkg/identity/identity.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1362 reorder graphite metric string for easier parsing
  cmd/statreceiver/graphite.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1351 Total file count through Monkit
  pkg/accounting/tally/stats.go
  pkg/accounting/tally/tally.go
  pkg/datarepair/checker/checker.go
Labels: Request Code Review, cla-signed

#1363 update golang.org/x, grpc and their dependencies
  go.mod
  go.sum
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1318 Replace list calls with iterates in kademlia routing table
  pkg/kademlia/kademlia_test.go
  pkg/kademlia/routing.go
  pkg/kademlia/routing_helpers.go
  pkg/kademlia/routing_helpers_test.go
  pkg/kademlia/utils.go
Labels: Request Code Review, cla-signed

#1342 dial node/address with bad server cert
  examples/grpc-debug/main.go
  internal/testplanet/planet.go
  internal/testplanet/reconfigure.go
  pkg/peertls/peertls.go
  pkg/peertls/peertls_test.go
  pkg/peertls/tlsopts/tls.go
  pkg/peertls/utils.go
  pkg/transport/transport.go
  pkg/transport/transport_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1356 add testcontext.Compile
  internal/testcontext/compile.go
  internal/testcontext/compile_norace.go
  internal/testcontext/compile_race.go
  internal/testcontext/compile_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1369 add piecestore.Storage interface
  pkg/piecestore/psserver/readerwriter.go
  pkg/piecestore/psserver/retrieve.go
  pkg/piecestore/psserver/server.go
  pkg/piecestore/psserver/store.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1370 Disable vet for tests
  .travis.yml
Labels: Request Code Review, cla-signed

#1364 Bwagreements not properly deleted
  pkg/piecestore/psserver/agreementsender/agreementsender.go
  pkg/piecestore/psserver/psdb/psdb.go
Labels: Request Code Review, cla-signed

#1378 rename payment command to node usage
  cmd/satellite/main.go
  cmd/satellite/usage.go
Labels: cla-signed

#1359 Validate piece hash on satellite
  pkg/pb/pointerdb.pb.go
  pkg/pb/pointerdb.proto
  pkg/pointerdb/pointerdb.go
  pkg/pointerdb/pointerdb_test.go
  pkg/storage/segments/repairer.go
  pkg/storage/segments/repairer_test.go
  pkg/storage/segments/store.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1379 Jj/payments cleanup
  cmd/satellite/usage.go
  pkg/overlay/cache.go
  satellite/satellitedb/dbx/satellitedb.dbx
  satellite/satellitedb/dbx/satellitedb.dbx.go
  satellite/satellitedb/locked.go
  satellite/satellitedb/overlaycache.go
Labels: Request Code Review, cla-signed

#1365 uplink ttl
  cmd/uplink/cmd/cp.go
  pkg/piecestore/psserver/psdb/psdb.go
Labels: cla-signed

#1328 Adds DumpNodes method to Kademlia Inspector
  pkg/kademlia/inspector.go
  pkg/kademlia/kademlia.go
  pkg/kademlia/routing.go
  pkg/overlay/inspector.go
  pkg/pb/inspector.pb.go
  pkg/pb/inspector.proto
Labels: Request Code Review, Reviewer Can Merge, cla-signed
