Repository storj/storj, pull requests merged in 2019-01, with the labels that each got.

#926 statreceiver nitpicking
  cmd/statreceiver/common.go
  cmd/statreceiver/copy.go
  cmd/statreceiver/db.go
  cmd/statreceiver/file.go
  cmd/statreceiver/filter.go
  cmd/statreceiver/graphite.go
  cmd/statreceiver/luacfg/cfg.go
  cmd/statreceiver/luacfg/cfg_test.go
  cmd/statreceiver/main.go
  cmd/statreceiver/parser.go
  cmd/statreceiver/print.go
  cmd/statreceiver/sanitizer.go
  cmd/statreceiver/udp.go
  examples/luacfg/main.go
Labels: Request Code Review, cla-signed

#953 pkg/provider: split into pkg/server, pkg/identity
  cmd/captplanet/run.go
  cmd/captplanet/setup.go
  cmd/certificates/main.go
  cmd/satellite/main.go
  cmd/storagenode/main.go
  cmd/uplink/cmd/run.go
  pkg/identity/cert_authority_test.go
  pkg/identity/certificate_authority.go
  pkg/identity/common.go
  pkg/identity/identity.go
  pkg/identity/identity_test.go
  pkg/identity/setup.go
  pkg/identity/utils.go
  pkg/miniogw/config.go
  pkg/miniogw/integration_test.go
  pkg/peertls/extensions.go
  pkg/provider/provider.go
  pkg/provider/transition.go
  pkg/server/common.go
  pkg/server/config.go
  pkg/server/interceptors.go
  pkg/server/options.go
  pkg/server/options_test.go
  pkg/server/server.go
Labels: cla-signed

#949 remove farmer references
  cmd/storagenode/main.go
  pkg/kademlia/config.go
  pkg/kademlia/kademlia_test.go
  pkg/overlay/mocks/overlay.go
  pkg/statdb/statdb.go
  satellite/satellitedb/mutex.go
  satellite/satellitedb/statdb.go
Labels: cla-signed

#952 inspector: use existing identity
  pkg/inspector/config.go
Labels: cla-signed

#951 kad: remove a redundant arg
  pkg/kademlia/config.go
  pkg/kademlia/kademlia.go
  pkg/kademlia/kademlia_test.go
Labels: cla-signed

#946 satellite hot minor changes
  web/satellite/src/components/common/Button.vue
  web/satellite/src/components/common/EmptyStateArea.vue
  web/satellite/src/components/common/HeaderedInput.vue
  web/satellite/src/components/common/HeaderlessInput.vue
  web/satellite/src/components/dashboard/DashboardHeader.vue
  web/satellite/src/components/dashboard/account/AccountArea.vue
  web/satellite/src/components/dashboard/account/AccountButton.vue
  web/satellite/src/components/dashboard/projectSelection/ProjectSelectionArea.vue
  web/satellite/src/components/projectDetails/ProjectDetailsArea.vue
  web/satellite/src/components/team/headerArea/SearchArea.vue
  web/satellite/src/components/team/headerArea/SortUsersDropdown.vue
Labels: cla-signed

#915 Fix CA Timeout and show progress to the user
  pkg/identity/certificate_authority.go
  pkg/identity/setup.go
  pkg/identity/utils.go
  pkg/process/exec_conf.go
Labels: Request Code Review, cla-signed

#919 Add config editing via the CLI for storage nodes
  cmd/storagenode/main.go
  internal/fpath/editor.go
  pkg/process/exec_conf.go
Labels: Request Code Review, cla-signed

#939 Fix 'empty queue' error when satellite starts
  pkg/datarepair/queue/queue.go
  pkg/datarepair/repairer/repairer.go
  satellite/satellitedb/repairqueue.go
  storage/common.go
  storage/redis/client_queue.go
  storage/testqueue/queue.go
Labels: Request Code Review, cla-signed

#950 CSR Service (part 2): cert signing rpc
  Makefile
  go.mod
  go.sum
  internal/debugging/certificates.go
  internal/testidentity/identity.go
  internal/testpeertls/certificates.go
  pkg/accounting/tally/tally_test.go
  pkg/audit/cursor_test.go
  pkg/auth/signature_test.go
  pkg/bwagreement/test/server_test.go
  pkg/certificates/certificates.go
  pkg/certificates/certificates_test.go
  pkg/identity/cert_authority_test.go
  pkg/identity/certificate_authority.go
  pkg/identity/identity.go
  pkg/kademlia/kademlia_test.go
  pkg/miniogw/integration_test.go
  pkg/overlay/client_test.go
  pkg/pb/certificate.pb.go
  pkg/pb/certificate.proto
  pkg/peertls/extensions.go
  pkg/peertls/peertls_test.go
  pkg/piecestore/psclient/pieceid_test.go
  pkg/piecestore/psserver/server_test.go
  pkg/pointerdb/pointerdb_test.go
Labels: Request Code Review, cla-signed

#947 Use generated locking database implementation
  go.mod
  go.sum
  pkg/accounting/db.go
  pkg/bwagreement/server.go
  pkg/datarepair/irreparable/irreparable.go
  pkg/datarepair/queue/queue.go
  pkg/statdb/statdb.go
  satellite/db.go
  satellite/satellitedb/database.go
  satellite/satellitedb/dbx/satellitedb.dbx
  satellite/satellitedb/locked.go
  satellite/satellitedb/lockedgen/main.go
  satellite/satellitedb/mutex.go
  storage/common.go
Labels: Request Code Review, cla-signed

#799 storj-sdk base code
  cmd/storj-sdk/cancelable.go
  cmd/storj-sdk/main.go
  cmd/storj-sdk/network.go
  cmd/storj-sdk/prefix.go
  cmd/storj-sdk/process.go
  cmd/storj-sdk/testplanet.go
  internal/fpath/os.go
  internal/fpath/path.go
  internal/testplanet/node.go
  internal/testplanet/planet.go
  pkg/audit/service.go
  pkg/kademlia/peer_discovery.go
  pkg/process/logging.go
Labels: Request Code Review, cla-signed

#873 Proper NodeType Handling
  cmd/captplanet/run.go
  cmd/overlay/main.go
  cmd/satellite/main.go
  cmd/storagenode/main.go
  examples/piecestore-client/main.go
  internal/testplanet/planet.go
  internal/teststorj/node.go
  pkg/accounting/tally/tally_test.go
  pkg/audit/verifier.go
  pkg/kademlia/config.go
  pkg/kademlia/kademlia.go
  pkg/kademlia/kademlia_test.go
  pkg/kademlia/peer_discovery.go
  pkg/kademlia/routing.go
  pkg/kademlia/routing_test.go
  pkg/node/connection_pool.go
  pkg/node/node.go
  pkg/node/node_test.go
  pkg/pb/discovery.pb.go
  pkg/pb/node.pb.go
  pkg/pb/node.proto
  pkg/pb/payments.pb.go
  pkg/pb/pointerdb.pb.go
  pkg/pb/utils.go
  pkg/piecestore/psclient/client.go
  pkg/piecestore/psclient/pieceranger_test.go
  pkg/pointerdb/pdbclient/client.go
  pkg/pointerdb/pdbclient/client_test.go
  pkg/pointerdb/pointerdb.go
  pkg/storage/ec/client.go
  pkg/storage/ec/client_test.go
  pkg/storage/ec/transportclient_mock_test.go
  pkg/storage/segments/repairer.go
  pkg/storage/segments/store.go
  pkg/storage/segments/store_test.go
  pkg/transport/transport.go
  pkg/transport/transport_test.go
Labels: Request Code Review, cla-signed

#958 pkg/kademlia: simplify code
  pkg/kademlia/kademlia_test.go
  pkg/kademlia/peer_discovery.go
  pkg/kademlia/replacement_cache_test.go
  pkg/kademlia/routing.go
  pkg/kademlia/routing_helpers.go
  pkg/kademlia/routing_helpers_test.go
  pkg/kademlia/utils.go
  pkg/kademlia/utils_test.go
Labels: Request Code Review, cla-signed

#962 Web_satellite bug fixing
  web/satellite/src/api/projectMembers.ts
  web/satellite/src/components/apiKeys/PaginationArea.vue
  web/satellite/src/components/apiKeys/headerArea/HeaderArea.vue
  web/satellite/src/components/apiKeys/headerArea/SortApiKeysHeader.vue
  web/satellite/src/components/common/HeaderedInput.vue
  web/satellite/src/components/common/HeaderlessInput.vue
  web/satellite/src/components/common/IEditable.ts
  web/satellite/src/components/dashboard/AddUserPopup.vue
  web/satellite/src/components/dashboard/account/AccountArea.vue
  web/satellite/src/components/dashboard/account/AccountDropdown.vue
  web/satellite/src/components/projectDetails/DeleteProjectPopup.vue
  web/satellite/src/components/projectDetails/ProjectDetailsArea.vue
  web/satellite/src/components/team/TeamMemberItem.vue
  web/satellite/src/components/team/addUserPopup/AddUserPopupArea.vue
  web/satellite/src/components/team/footerArea/DeleteUserArea.vue
  web/satellite/src/components/team/headerArea/SortDropdown.vue
  web/satellite/src/store/modules/projectMembers.ts
  web/satellite/src/store/modules/projects.ts
  web/satellite/src/store/modules/users.ts
  web/satellite/src/store/mutationConstants.ts
Labels: cla-signed

#963 pkg/process: properly quote arguments
  pkg/process/exec_conf.go
Labels: Request Code Review, cla-signed

#964 remove node startup log in piecestore server
  pkg/piecestore/psserver/server.go
Labels: Request Code Review, cla-signed

#900 Test all-in-one
  .dockerignore
  .travis.yml
  Makefile
  cmd/storagenode/entrypoint
  docker-compose.yaml
  pkg/storage/ec/client.go
  scripts/test-aio.sh
Labels: Request Code Review, cla-signed

#966 V3-1029 Update list Project Logic
  pkg/satellite/satellitedb/dbx/satellitedb.dbx
  pkg/satellite/satellitedb/dbx/satellitedb.dbx.go
  pkg/satellite/satellitedb/projects.go
  web/satellite/src/views/Dashboard.vue
Labels: cla-signed

#970 captplanet: use -race flag in script
  .travis.yml
  scripts/test-aio.sh
  scripts/test-captplanet.sh
Labels: Request Code Review, cla-signed

#954 CSR automation in storage node setup
  .travis.yml
  Makefile
  cmd/certificates/main.go
  cmd/storagenode/main.go
  pkg/certificates/certificates.go
  pkg/certificates/certificates_test.go
  pkg/identity/certificate_authority.go
  pkg/identity/identity.go
  pkg/peertls/extensions.go
  scripts/test-certificate-signing.sh
  scripts/utils.sh
Labels: Request Code Review, cla-signed

#976 returns nil if no nodeData present in CalculateAtRestRaw
  pkg/accounting/tally/tally.go
Labels: cla-signed

#960 Verifier should use payer bandwidth alloc from satellite
  pkg/audit/cursor.go
  pkg/audit/service.go
  pkg/audit/verifier.go
  pkg/audit/verifier_test.go
  pkg/piecestore/psserver/readerwriter.go
  pkg/piecestore/psserver/retrieve.go
  pkg/piecestore/psserver/server.go
  pkg/piecestore/psserver/server_test.go
Labels: cla-signed

#982 Fix output message when overwriting storagenode configuration
  cmd/storagenode/main.go
Labels: Request Code Review, cla-signed

#944 Fix ignored setup arguments
  cmd/captplanet/run.go
  cmd/captplanet/setup.go
  cmd/satellite/main.go
  cmd/storagenode/main.go
  cmd/uplink/cmd/run.go
  cmd/uplink/cmd/setup.go
Labels: Request Code Review, cla-signed

#968 Add `setup` tag for config structs
  cmd/captplanet/main.go
  cmd/captplanet/run.go
  cmd/captplanet/setup.go
  cmd/satellite/main.go
  cmd/storagenode/main.go
  cmd/uplink/cmd/setup.go
  pkg/cfgstruct/bind.go
  pkg/process/exec_conf.go
Labels: Request Code Review, cla-signed

#978 Test bwagreement serial number
  pkg/accounting/tally/tally_test.go
  pkg/bwagreement/test/common.go
  pkg/bwagreement/test/server_test.go
Labels: Request Code Review, cla-signed

#979 prepare key generation for launch
  cmd/identity/keys.go
  pkg/identity/certificate_authority.go
  pkg/identity/generate.go
  pkg/identity/identity.go
  pkg/identity/identity_test.go
  pkg/identity/utils.go
  pkg/peertls/peertls.go
  pkg/peertls/peertls_test.go
  pkg/storj/node.go
  pkg/storj/node_test.go
Labels: cla-signed, reviewer can merge

#983 sync2: add Fence and Sleep
  internal/sync2/fence.go
  internal/sync2/fence_test.go
  internal/sync2/sleep.go
  internal/sync2/sleep_test.go
Labels: Request Code Review, cla-signed

#984 Upgrade monkit-hw
  go.mod
  go.sum
Labels: Request Code Review, cla-signed

#904 Process for updating storage node stats in kademlia
  pkg/kademlia/routing.go
  pkg/kademlia/routing_test.go
  pkg/piecestore/psserver/bucket_refresher.go
  pkg/piecestore/psserver/config.go
  pkg/piecestore/psserver/server.go
Labels: Request Code Review, cla-signed

#992 normalize login email
  pkg/satellite/service.go
  pkg/satellite/validation.go
Labels: Request Code Review, cla-signed

#993 Enable import grouping checks
  .travis.yml
  cmd/identity/keys.go
  cmd/statreceiver/main.go
  internal/fpath/editor.go
  pkg/kademlia/kademlia.go
  pkg/satellite/apikeys.go
  pkg/satellite/satellitedb/db.go
  pkg/satellite/satelliteweb/satelliteql/project.go
  pkg/satellite/service.go
  scripts/check-imports.go
Labels: Request Code Review, cla-signed

#967 Satellite api tests
  pkg/satellite/satelliteweb/satelliteql/mutation.go
  pkg/satellite/satelliteweb/satelliteql/mutation_test.go
  pkg/satellite/satelliteweb/satelliteql/query_test.go
Labels: Request Code Review, cla-signed

#948 Satellite Web store test coverage
  web/satellite/jestSetup.ts
  web/satellite/package.json
  web/satellite/src/api/projectMembers.ts
  web/satellite/src/api/projects.ts
  web/satellite/src/store/modules/projectMembers.ts
  web/satellite/src/store/modules/projects.ts
  web/satellite/src/store/modules/users.ts
  web/satellite/src/utils/apolloManager.ts
  web/satellite/tests/unit/store/projectMembers.spec.ts
  web/satellite/tests/unit/store/projects.spec.ts
  web/satellite/tests/unit/store/users.spec.ts
Labels: cla-signed

#991 Fix data-race in UpdateSelf
  pkg/kademlia/kademlia.go
  pkg/kademlia/routing.go
Labels: Request Code Review, cla-signed

#990 Fail integration tests on race
  .travis.yml
  scripts/fail-on-race.go
Labels: Request Code Review, cla-signed

#996 Upgrade monkit-hw
  go.mod
  go.sum
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#994 change default BootstrapAddr
  pkg/kademlia/config.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#998 Add missing satellite arguments
  cmd/storj-sdk/network.go
  pkg/discovery/config.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#995 truncate store value logging
  storage/storelogger/logger.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#973 Added systemd script to service folder at the top level
  examples/service/storagenode.service
Labels: cla-signed

#985 Get satellites to send BW agreements to via KAD
  cmd/captplanet/setup.go
  cmd/storagenode/main.go
  cmd/storj-sdk/network.go
  pkg/piecestore/psserver/agreementsender/agreementsender.go
  pkg/piecestore/psserver/config.go
Labels: Request Code Review, cla-signed

#972 Satellite accepts manipulated paychecks V3-1023
  pkg/accounting/tally/tally_test.go
  pkg/bwagreement/server.go
  pkg/bwagreement/test/common.go
  pkg/bwagreement/test/server_test.go
  pkg/pointerdb/pointerdb.go
  satellite/satellitedb/bandwidthagreement.go
  satellite/satellitedb/dbx/satellitedb.dbx
  satellite/satellitedb/dbx/satellitedb.dbx.go
  satellite/satellitedb/dbx/satellitedb.dbx.postgres.sql
  satellite/satellitedb/dbx/satellitedb.dbx.sqlite3.sql
  satellite/satellitedb/locked.go
Labels: Request Code Review, cla-signed

#1006 Remove unused discovery endpoint
  pkg/discovery/config.go
  pkg/discovery/server.go
  pkg/pb/bandwidth.pb.go
  pkg/pb/certificate.pb.go
  pkg/pb/datarepair.pb.go
  pkg/pb/discovery.pb.go
  pkg/pb/discovery.proto
  pkg/pb/inspector.pb.go
  pkg/pb/meta.pb.go
  pkg/pb/node.pb.go
  pkg/pb/overlay.pb.go
  pkg/pb/payments.pb.go
  pkg/pb/piecestore.pb.go
  pkg/pb/pointerdb.pb.go
  pkg/pb/streams.pb.go
Labels: Request Code Review, cla-signed

#1008 V3-1033 Implement AppState module for DropDown lists
  web/satellite/src/App.vue
  web/satellite/src/components/account/AccountArea.vue
  web/satellite/src/components/account/DeleteAccountPopup.vue
  web/satellite/src/components/dashboard/DashboardArea.vue
  web/satellite/src/components/header/AccountButton.vue
  web/satellite/src/components/header/AccountDropdown.vue
  web/satellite/src/components/header/Header.vue
  web/satellite/src/components/header/NewProjectArea.vue
  web/satellite/src/components/header/projectSelection/ProjectSelectionArea.vue
  web/satellite/src/components/header/projectSelection/ProjectSelectionDropdown.vue
  web/satellite/src/components/navigation/NavigationArea.vue
  web/satellite/src/components/notifications/Notification.vue
  web/satellite/src/components/project/DeleteProjectPopup.vue
  web/satellite/src/components/project/NewProjectPopup.vue
  web/satellite/src/components/project/ProjectDetailsArea.vue
  web/satellite/src/components/team/AddUserPopup.vue
  web/satellite/src/components/team/TeamArea.vue
  web/satellite/src/components/team/footerArea/DeleteUserArea.vue
  web/satellite/src/components/team/headerArea/HeaderArea.vue
  web/satellite/src/router/index.ts
  web/satellite/src/store/modules/appState.ts
  web/satellite/src/store/modules/notifications.ts
  web/satellite/src/store/modules/projects.ts
  web/satellite/src/store/mutationConstants.ts
  web/satellite/src/types/DelayedNotification.ts
  web/satellite/src/types/EmailInput.ts
  web/satellite/src/utils/constants/actionNames.ts
  web/satellite/src/utils/constants/navigationLinks.ts
  web/satellite/src/utils/qraphql/createProjectsQuery.ts
  web/satellite/src/views/Dashboard.vue
  web/satellite/src/views/Login.vue
  web/satellite/src/views/Register.vue
  web/satellite/tests/unit/notifications/NotificationArea.spec.ts
Labels: cla-signed

#1001 cmd/bootstrap: a kademlia-only server
  cmd/bootstrap/Dockerfile
  cmd/bootstrap/entrypoint
  cmd/bootstrap/main.go
  cmd/storj-sdk/network.go
  go.sum
  pkg/kademlia/config.go
  pkg/pb/node.pb.go
  pkg/pb/node.proto
Labels: Reviewer Can Merge, cla-signed

#1014 Fix captplanet race
  cmd/captplanet/run.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1017 Reordering when we set the API_KEY env var in the docker entrypoint
  cmd/satellite/entrypoint
Labels: cla-signed

#965 Differentiate GET and PUT operations in the tally service
  cmd/satellite/main.go
  cmd/storagenode/main.go
  pkg/accounting/common.go
  pkg/accounting/db.go
  pkg/accounting/tally/tally.go
  pkg/accounting/tally/tally_test.go
  pkg/audit/cursor.go
  pkg/pb/piecestore.pb.go
  pkg/pb/piecestore.proto
  pkg/piecestore/psserver/readerwriter.go
  pkg/piecestore/psserver/retrieve.go
  pkg/piecestore/psserver/server.go
  pkg/storage/segments/repairer.go
  pkg/storage/segments/repairer_test.go
  satellite/satellitedb/accounting.go
  satellite/satellitedb/locked.go
Labels: Request Code Review, cla-signed

#1019 Some pointerdb methods don't validate api key
  pkg/pointerdb/pointerdb.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1005 Storage Node Peer
  internal/testplanet/node.go
  internal/testplanet/planet.go
  internal/testplanet/planet_test.go
  pkg/kademlia/kademlia.go
  pkg/kademlia/peer_discovery.go
  pkg/kademlia/routing.go
  pkg/node/node_test.go
  pkg/piecestore/psserver/psdb/psdb.go
  pkg/piecestore/psserver/server.go
  storagenode/peer.go
  storagenode/storagenodedb/database.go
  storagenode/testing.go
Labels: Request Code Review, cla-signed

#1010 Reduce test CA difficulty
  cmd/gateway/entrypoint
  cmd/satellite/entrypoint
  cmd/storagenode/entrypoint
  docker-compose.yaml
  internal/testidentity/identity.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#999 Satellite web Endless scroll and 'Sort by' for Team Members page.
  pkg/satellite/satelliteweb/satelliteql/project.go
  web/satellite/src/App.vue
  web/satellite/src/api/projectMembers.ts
  web/satellite/src/components/header/projectSelection/ProjectSelectionDropdown.vue
  web/satellite/src/components/team/TeamArea.vue
  web/satellite/src/components/team/TeamMemberItem.vue
  web/satellite/src/components/team/headerArea/SearchArea.vue
  web/satellite/src/components/team/headerArea/SortDropdown.vue
  web/satellite/src/components/team/headerArea/SortUsersDropdown.vue
  web/satellite/src/store/modules/appState.ts
  web/satellite/src/store/modules/projectMembers.ts
  web/satellite/src/store/mutationConstants.ts
  web/satellite/src/utils/constants/ProjectMemberSortEnum.ts
  web/satellite/src/utils/constants/actionNames.ts
Labels: cla-signed

#1015 satellites reject expired BWAs
  pkg/accounting/tally/tally_test.go
  pkg/bwagreement/server.go
  pkg/bwagreement/test/common.go
  pkg/bwagreement/test/server_test.go
  pkg/pointerdb/config.go
  pkg/pointerdb/pointerdb.go
  satellite/satellitedb/bandwidthagreement.go
  satellite/satellitedb/dbx/satellitedb.dbx
  satellite/satellitedb/dbx/satellitedb.dbx.go
  satellite/satellitedb/dbx/satellitedb.dbx.postgres.sql
  satellite/satellitedb/dbx/satellitedb.dbx.sqlite3.sql
Labels: Request Code Review, cla-signed

#1027 do not try to dial nil node from audit verifier
  pkg/audit/verifier.go
Labels: Bug, Request Code Review, Reviewer Can Merge, cla-signed

#1007 Empty satellite signature crashing
  pkg/bwagreement/server.go
  pkg/bwagreement/test/server_test.go
Labels: Request Code Review

#1025 V3-978 Create missing unit tests for satellitedb
  pkg/satellite/apikeys.go
  pkg/satellite/satelliteauth/claims_test.go
  pkg/satellite/satelliteauth/token_test.go
  pkg/satellite/satellitedb/apikeys_test.go
  pkg/satellite/satellitedb/db_test.go
  pkg/satellite/satellitedb/projectmembers_test.go
  pkg/satellite/satellitedb/projects_test.go
  pkg/satellite/satellitedb/users_test.go
  pkg/satellite/satellitedb/utils_test.go
  pkg/satellite/service.go
  web/satellite/src/api/projects.ts
Labels: Request Code Review, cla-signed

#1033 Fix unstarted pointerdb responsibility
  cmd/captplanet/run.go
  pkg/accounting/tally/config.go
  pkg/audit/service.go
  pkg/discovery/config.go
Labels: cla-signed

#997 Improve cert signing integration test+:
  cmd/certificates/auth.go
  cmd/certificates/main.go
  cmd/certificates/setup.go
  cmd/certificates/sign.go
  cmd/certificates/verify.go
  cmd/identity/certificate_authority.go
  cmd/identity/identity.go
  cmd/identity/main.go
  cmd/storagenode/main.go
  pkg/certificates/certificates.go
  pkg/certificates/certificates_test.go
  pkg/certificates/config.go
  pkg/identity/certificate_authority.go
  pkg/identity/identity.go
  scripts/test-certificate-signing.sh
  scripts/utils.sh
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1022 Add Tee and cancellable Copy to sync2 pkg
  internal/sync2/copy.go
  internal/sync2/copy_test.go
  internal/sync2/io.go
  internal/sync2/pipe.go
  internal/sync2/pipe_test.go
  internal/sync2/tee.go
  internal/sync2/tee_test.go
Labels: Request Code Review, cla-signed

#1030 Add arguments to lockedgen for using it in other places
  satellite/satellitedb/database.go
  satellite/satellitedb/locked.go
  scripts/dependencies_test.go
  scripts/lockedgen.go
Labels: Request Code Review, cla-signed

#1032 Fail integration tests on panic
  .travis.yml
  cmd/bootstrap/main.go
  cmd/storj-sdk/network.go
  scripts/fail-on-race.go
  scripts/test-storj-sdk.sh
Labels: Request Code Review, cla-signed

#1020 continue agreement sender loop on error
  pkg/bwagreement/server.go
  pkg/bwagreement/test/server_test.go
  pkg/pb/bandwidth.pb.go
  pkg/pb/bandwidth.proto
  pkg/piecestore/psserver/agreementsender/agreementsender.go
Labels: Request Code Review, cla-signed

#1044 agreement sender bug fix
  pkg/piecestore/psserver/agreementsender/agreementsender.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1036 Adding additional required values for satellite configuration
  cmd/gateway/entrypoint
  cmd/satellite/entrypoint
  cmd/storagenode/entrypoint
  cmd/uplink/entrypoint
Labels: cla-signed

#1038 Fix kademlia bootstrap address ignored
  cmd/storagenode/main.go
Labels: cla-signed

#1031 minor web satelite ui bug fixes
  web/satellite/src/App.vue
  web/satellite/src/components/apiKeys/headerArea/SearchArea.vue
  web/satellite/src/components/header/Header.vue
  web/satellite/src/components/team/TeamMemberItem.vue
  web/satellite/src/components/team/headerArea/SearchArea.vue
  web/satellite/src/views/Login.vue
  web/satellite/src/views/Register.vue
Labels: cla-signed

#1040 Remove overwrite flags
  cmd/bootstrap/main.go
  cmd/captplanet/main.go
  cmd/captplanet/setup.go
  cmd/satellite/main.go
  cmd/storagenode/main.go
  cmd/uplink/cmd/setup.go
  scripts/cert-gating.sh
  scripts/test-captplanet.sh
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1029 pkg/inspector: split functionality to be per-service
  cmd/captplanet/main.go
  cmd/captplanet/run.go
  cmd/inspector/main.go
  cmd/satellite/main.go
  pkg/inspector/config.go
  pkg/inspector/server.go
  pkg/kademlia/config.go
  pkg/kademlia/inspector.go
  pkg/overlay/config.go
  pkg/overlay/inspector.go
  pkg/pb/bandwidth.pb.go
  pkg/pb/certificate.pb.go
  pkg/pb/datarepair.pb.go
  pkg/pb/inspector.pb.go
  pkg/pb/inspector.proto
  pkg/pb/meta.pb.go
  pkg/pb/node.pb.go
  pkg/pb/overlay.pb.go
  pkg/pb/payments.pb.go
  pkg/pb/piecestore.pb.go
  pkg/pb/pointerdb.pb.go
  pkg/pb/streams.pb.go
  pkg/statdb/common.go
  pkg/statdb/config.go
  pkg/statdb/inspector.go
Labels: cla-signed

#1013 Clean up Storage node setup
  cmd/storagenode/main.go
  examples/grpc-debug/main.go
  internal/memory/size.go
  internal/memory/size_test.go
  internal/testplanet/planet.go
  pkg/cfgstruct/bind.go
  pkg/cfgstruct/bind_test.go
  pkg/cfgstruct/flags.go
  pkg/datarepair/repairer/config.go
  pkg/miniogw/config.go
  pkg/miniogw/integration_test.go
  pkg/piecestore/psclient/client.go
  pkg/piecestore/psserver/config.go
  pkg/piecestore/psserver/server.go
  pkg/pointerdb/config.go
  pkg/pointerdb/pointerdb.go
Labels: Backward Incompatible, cla-signed

#1046 add more bwagreement unit tests
  pkg/accounting/tally/tally_test.go
  pkg/bwagreement/test/common.go
  pkg/bwagreement/test/server_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1051 Save only user-specific flags to storage node's config.yaml
  cmd/bootstrap/main.go
  cmd/captplanet/setup.go
  cmd/certificates/setup.go
  cmd/satellite/main.go
  cmd/storagenode/main.go
  cmd/uplink/cmd/setup.go
  pkg/cfgstruct/bind.go
  pkg/kademlia/config.go
  pkg/piecestore/psserver/config.go
  pkg/process/exec_conf.go
  pkg/server/config.go
Labels: cla-signed

#1052 use Node ID for metrics ID
  cmd/bootstrap/main.go
  cmd/captplanet/run.go
  cmd/satellite/main.go
  cmd/storagenode/main.go
  cmd/uplink/cmd/mount.go
  cmd/uplink/cmd/run.go
  pkg/identity/identity.go
  pkg/process/exec_conf.go
  pkg/process/metrics.go
  pkg/telemetry/client.go
Labels: cla-signed

#1049 Fix SN overrided params
  cmd/storagenode/entrypoint
  cmd/storagenode/main.go
  pkg/piecestore/psserver/config.go
  pkg/process/exec_conf.go
Labels: cla-signed

#1047 Change overlay cache database interface
  internal/testplanet/node.go
  pkg/audit/cursor_test.go
  pkg/overlay/cache.go
  pkg/overlay/cache_test.go
  pkg/overlay/client_test.go
  pkg/overlay/config.go
  pkg/overlay/config_test.go
  pkg/overlay/server.go
  pkg/overlay/server_test.go
  satellite/db.go
  satellite/satellitedb/database.go
  satellite/satellitedb/dbx/satellitedb.dbx
  satellite/satellitedb/dbx/satellitedb.dbx.go
  satellite/satellitedb/dbx/satellitedb.dbx.postgres.sql
  satellite/satellitedb/dbx/satellitedb.dbx.sqlite3.sql
  satellite/satellitedb/locked.go
  satellite/satellitedb/overlaycache.go
  satellite/satellitedb/satellitedbtest/utils.go
Labels: Request Code Review, cla-signed

#1059 Fix ignored overridden flag in user config
  pkg/process/exec_conf.go
Labels: cla-signed

#1061 adds base 10 memory sizes
  internal/memory/size.go
  internal/memory/size_test.go
Labels: cla-signed

#1065 format timestamps for use in filename
  pkg/payments/server.go
Labels: cla-signed

#1067 payment logs
  cmd/captplanet/main.go
  cmd/payments/main.go
  cmd/satellite/main.go
  pkg/payments/config.go
  pkg/payments/server.go
  pkg/pb/payments.pb.go
  pkg/pb/payments.proto
  satellite/satellitedb/accounting.go
Labels: cla-signed

#1068 Errcheck/errors
  cmd/payments/main.go
  pkg/payments/server.go
Labels: cla-signed

#1064 trivial: log "connection to node failed" at DEBUG level
  pkg/node/server.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1069 add make install-sdk target
  .travis.yml
  Makefile
  scripts/test-sdk-aws.sh
  scripts/test-sdk.sh
Labels: cla-signed

#1071 disable things in Travis
  .travis.yml
Labels: cla-signed

#1056 rollup query
  pkg/accounting/common.go
  pkg/accounting/db.go
  pkg/accounting/rollup/config.go
  pkg/accounting/rollup/rollup.go
  pkg/accounting/tally/config.go
  pkg/accounting/tally/tally.go
  pkg/datarepair/checker/config.go
  pkg/datarepair/repairer/config.go
  satellite/satellitedb/accounting.go
  satellite/satellitedb/dbx/satellitedb.dbx
  satellite/satellitedb/dbx/satellitedb.dbx.go
  satellite/satellitedb/dbx/satellitedb.dbx.postgres.sql
  satellite/satellitedb/dbx/satellitedb.dbx.sqlite3.sql
  satellite/satellitedb/locked.go
Labels: Request Code Review, cla-signed

#1073 remove overlay count from inspector kad count command
  cmd/inspector/main.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1066 ConsoleDB merge and buckets table creation
  satellite/console/apikeys.go
  satellite/console/buckets.go
  satellite/console/consoleweb/config.go
  satellite/console/database.go
  satellite/db.go
  satellite/satellitedb/apikeys.go
  satellite/satellitedb/buckets.go
  satellite/satellitedb/consoledb.go
  satellite/satellitedb/consoledbx/consoledb.dbx
  satellite/satellitedb/consoledbx/consoledb.dbx.go
  satellite/satellitedb/consoledbx/consoledb.dbx.postgres.sql
  satellite/satellitedb/consoledbx/consoledb.dbx.sqlite3.sql
  satellite/satellitedb/consoledbx/gen.go
  satellite/satellitedb/database.go
  satellite/satellitedb/dbx/satellitedb.dbx
  satellite/satellitedb/dbx/satellitedb.dbx.go
  satellite/satellitedb/dbx/satellitedb.dbx.postgres.sql
  satellite/satellitedb/dbx/satellitedb.dbx.sqlite3.sql
  satellite/satellitedb/locked.go
  satellite/satellitedb/lockedtx.go
  satellite/satellitedb/projectmembers.go
  satellite/satellitedb/projects.go
  satellite/satellitedb/projects_test.go
  satellite/satellitedb/users.go
  satellite/satellitedb/users_test.go
Labels: Request Code Review, cla-signed

#1074 adds pretty printing for inspector kad dump-nodes
  cmd/inspector/main.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1063 trivial: log bootstrap node address used to DEBUG
  pkg/kademlia/config.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1058 use _real_ cert-path to get node ID for metrics
  cmd/satellite/main.go
  cmd/storagenode/main.go
  cmd/uplink/cmd/run.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1072 storagenode dashboard is working and passing tests locally
  cmd/storagenode/main.go
  examples/piecestore-client/main.go
  go.mod
  pkg/pb/inspector.pb.go
  pkg/pb/piecestore.pb.go
  pkg/pb/piecestore.pb.mock.go
  pkg/pb/piecestore.proto
  pkg/piecestore/psclient/client.go
  pkg/piecestore/psclient/liteclient.go
  pkg/piecestore/psserver/config.go
  pkg/piecestore/psserver/server.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1076 Add address param for SN dashboard
  cmd/storagenode/main.go
Labels: cla-signed

#1078 Rename storj-sdk to storj-sim
  .travis.yml
  Makefile
  cmd/storj-sim/cancelable.go
  cmd/storj-sim/main.go
  cmd/storj-sim/network.go
  cmd/storj-sim/prefix.go
  cmd/storj-sim/process.go
  cmd/storj-sim/testplanet.go
  scripts/test-sim-aws.sh
  scripts/test-sim.sh
Labels: cla-signed

#1075 Storagenode logs and config improvements
  cmd/storagenode/main.go
  pkg/kademlia/config.go
  pkg/node/server.go
  pkg/piecestore/psserver/config.go
  pkg/process/exec_conf.go
  pkg/server/config.go
Labels: cla-signed

#1070 Remove captplanet
  Makefile
  cmd/captplanet/main.go
  cmd/captplanet/run.go
  cmd/captplanet/setup.go
  cmd/certificates/main.go
  cmd/inspector/main.go
  scripts/test-captplanet.sh
Labels: cla-signed

#1082 pkg/server: include production cert
  pkg/server/cert.go
  pkg/server/config.go
  pkg/server/options.go
  pkg/server/options_test.go
Labels: cla-signed

#1079 Generate Payments Report
  cmd/payments/main.go
  cmd/satellite/main.go
  pkg/accounting/common.go
  pkg/accounting/db.go
  pkg/overlay/cache.go
  pkg/payments/config.go
  pkg/payments/server.go
  pkg/pb/bandwidth.pb.go
  pkg/pb/certificate.pb.go
  pkg/pb/datarepair.pb.go
  pkg/pb/meta.pb.go
  pkg/pb/node.pb.go
  pkg/pb/overlay.pb.go
  pkg/pb/payments.pb.go
  pkg/pb/payments.proto
  pkg/pb/pointerdb.pb.go
  pkg/pb/streams.pb.go
  satellite/satellitedb/accounting.go
  satellite/satellitedb/dbx/satellitedb.dbx
  satellite/satellitedb/dbx/satellitedb.dbx.go
  satellite/satellitedb/locked.go
  satellite/satellitedb/overlaycache.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1081 memory.Size: autoformat sizes based on value entropy
  internal/memory/size.go
  pkg/piecestore/psserver/config.go
Labels: cla-signed

#1085 Jj/bytes
  cmd/satellite/main.go
  pkg/accounting/rollup/config.go
  pkg/accounting/tally/tally.go
  pkg/payments/server.go
Labels: cla-signed

#1086 nonessential edits for storj-sim
  cmd/storj-sim/network.go
Labels: cla-signed

#1084 Closing context doesn't stop storage node
  pkg/piecestore/psserver/bucket_refresher.go
  pkg/piecestore/psserver/config.go
  pkg/piecestore/psserver/server.go
  pkg/server/config.go
Labels: cla-signed

#1088 Fix panic in inspector if ping fails
  cmd/inspector/main.go
Labels: Reviewer Can Merge, cla-signed

#1083 Consolidate identity management to identity cli commands
  .travis.yml
  Makefile
  cmd/bootstrap/main.go
  cmd/certificates/setup.go
  cmd/identity/certificate_authority.go
  cmd/identity/identity.go
  cmd/identity/keys.go
  cmd/identity/main.go
  cmd/satellite/main.go
  cmd/storagenode/main.go
  cmd/storj-sim/network.go
  cmd/storj-sim/process.go
  cmd/uplink/cmd/setup.go
  internal/fpath/os.go
  pkg/certificates/config.go
  pkg/identity/certificate_authority.go
  pkg/identity/utils.go
Labels: cla-signed

#1087 Sno dashboard updates
  cmd/storagenode/main.go
  pkg/piecestore/psserver/server.go
Labels: cla-signed

#1034 Satellite Peer
  internal/testplanet/node.go
  internal/testplanet/planet.go
  pkg/audit/cursor_test.go
  pkg/audit/service.go
  pkg/auth/grpcauth/authentication.go
  pkg/bwagreement/server.go
  pkg/datarepair/checker/checker.go
  pkg/datarepair/checker/checker_test.go
  pkg/datarepair/repairer/config.go
  pkg/datarepair/repairer/repairer.go
  pkg/discovery/service.go
  pkg/discovery/service_test.go
  pkg/kademlia/kademlia.go
  pkg/kademlia/lookup_test.go
  pkg/overlay/cache.go
  pkg/overlay/client_test.go
  pkg/overlay/server.go
  pkg/overlay/server_test.go
  pkg/pointerdb/config.go
  pkg/pointerdb/pointerdb.go
  pkg/pointerdb/pointerdb_test.go
  satellite/db.go
  satellite/peer.go
  satellite/testing.go
  storagenode/peer.go
Labels: Request Code Review, cla-signed

#1092 Kademlia Dialer
  go.mod
  go.sum
  internal/sync2/semaphore.go
  pkg/kademlia/dialer.go
  pkg/kademlia/kademlia.go
  pkg/kademlia/kademlia_test.go
  pkg/kademlia/peer_discovery.go
Labels: cla-signed

#1095 fix some email list parsing in certificates tool
  cmd/certificates/auth.go
Labels: cla-signed

#1094 Coyle/cert inspector
  cmd/inspector/main.go
Labels: cla-signed

#1096 pkg/node: fix connection logging
  pkg/node/server.go
Labels: cla-signed

#1037 Move pointerdb logic to a service
  pkg/accounting/tally/tally_test.go
  pkg/pointerdb/config.go
  pkg/pointerdb/pointerdb.go
  pkg/pointerdb/pointerdb_test.go
  pkg/pointerdb/service.go
  satellite/peer.go
Labels: Request Code Review, cla-signed

#1097 adding identity and certificates to be built and pushed
  Makefile
Labels: cla-signed

#1100 wip testing and timestamp fix
  pkg/accounting/db.go
  pkg/accounting/rollup/rollup.go
  pkg/accounting/rollup/rollup_test.go
  pkg/accounting/tally/tally.go
  satellite/satellitedb/accounting.go
  satellite/satellitedb/bandwidthagreement.go
  satellite/satellitedb/locked.go
Labels: cla-signed

#1098 Don't create identity when running dash
  cmd/storagenode/main.go
  examples/piecestore-client/main.go
  pkg/piecestore/psclient/liteclient.go
Labels: cla-signed

#1103 cla: add tim
  .clabot
Labels: cla-signed

#1104 added targets for binaries to fix master
  Makefile
Labels: cla-signed

#1099 Remove pointerdb.Server from other services
  pkg/accounting/tally/tally.go
  pkg/accounting/tally/tally_test.go
  pkg/audit/cursor.go
  pkg/audit/cursor_test.go
  pkg/audit/service.go
  pkg/datarepair/checker/checker.go
  pkg/pointerdb/allocation.go
  pkg/pointerdb/config.go
  pkg/pointerdb/pointerdb.go
  pkg/pointerdb/pointerdb_test.go
  satellite/peer.go
Labels: cla-signed

#1093 certificates config and --certs-dir fixes
  Makefile
  cmd/bootstrap/main.go
  cmd/certificates/auth.go
  cmd/certificates/main.go
  cmd/certificates/setup.go
  cmd/identity/certificate_authority.go
  cmd/identity/identity.go
  cmd/identity/main.go
  cmd/satellite/main.go
  cmd/storagenode/main.go
  cmd/storj-sim/network.go
  cmd/uplink/cmd/root.go
  cmd/uplink/cmd/run.go
  cmd/uplink/cmd/setup.go
  pkg/cfgstruct/bind.go
  pkg/identity/certificate_authority.go
  pkg/identity/identity.go
  scripts/cert-gating.sh
  scripts/utils.sh
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1110 Fix partial rename of `creds-dirs` to `identity-dirs`
  cmd/bootstrap/main.go
  cmd/certificates/main.go
  cmd/certificates/setup.go
  cmd/identity/certificate_authority.go
  cmd/identity/identity.go
  cmd/identity/main.go
  cmd/satellite/main.go
  cmd/storagenode/main.go
  cmd/uplink/cmd/root.go
  cmd/uplink/cmd/setup.go
  pkg/cfgstruct/bind.go
  pkg/identity/certificate_authority.go
  pkg/identity/identity.go
Labels: cla-signed

#1105 Enable linters
  .golangci.yml
  .travis.yml
  pkg/audit/cursor.go
  pkg/payments/config.go
Labels: Request Code Review, cla-signed

#1111 Fix import grouping
  cmd/uplink/cmd/setup.go
  pkg/metainfo/kvmetainfo/buckets_test.go
  pkg/miniogw/gateway_test.go
  pkg/piecestore/psserver/readerwriter_test.go
  pkg/process/metrics.go
  pkg/storage/ec/client.go
  pkg/telemetry/tm_test.go
  satellite/satellitedb/apikeys_test.go
  storage/postgreskv/schema/migrate.go
Labels: Request Code Review, cla-signed

#1107 Use storagenode.Peer for storagenode
  cmd/storagenode/main.go
  go.mod
  go.sum
  internal/testplanet/planet.go
  pkg/kademlia/config.go
  pkg/kademlia/kademlia.go
  pkg/piecestore/psserver/agreementsender/agreementsender.go
  pkg/piecestore/psserver/bucket_refresher.go
  pkg/piecestore/psserver/config.go
  pkg/piecestore/psserver/psdb/psdb.go
  pkg/piecestore/psserver/server.go
  pkg/piecestore/pstore.go
  pkg/server/config.go
  storagenode/peer.go
  storagenode/storagenodedb/database.go
Labels: Request Code Review, cla-signed

#1112 Don't change linter concurrency
  .golangci.yml
Labels: Request Code Review, cla-signed

#1113 Change default difficulty to 30
  cmd/identity/keys.go
  cmd/identity/main.go
  cmd/storj-sim/network.go
  pkg/certificates/config.go
  pkg/identity/certificate_authority.go
Labels: Request Code Review, cla-signed

#1118 Print successfully connected message every 100 times
  pkg/node/server.go
Labels: Request Code Review, cla-signed

#1089 Try accessing bootstrap node for verification
  bootstrap/bootstrapdb/database.go
  bootstrap/peer.go
  bootstrap/testing.go
  cmd/bootstrap/main.go
  internal/testplanet/planet.go
  pkg/kademlia/config.go
  pkg/kademlia/kademlia.go
Labels: cla-signed

#1116 storagenode approvedSatelliteIDs
  pkg/piecestore/psserver/config.go
  pkg/piecestore/psserver/readerwriter.go
  pkg/piecestore/psserver/server.go
  pkg/piecestore/psserver/server_test.go
Labels: WIP, cla-signed

#1119 Satellite Peer
  cmd/satellite/main.go
  cmd/storagenode/main.go
  cmd/storj-sim/network.go
  internal/testplanet/planet.go
  pkg/accounting/rollup/config.go
  pkg/accounting/rollup/rollup.go
  pkg/accounting/rollup/rollup_test.go
  pkg/accounting/tally/config.go
  pkg/accounting/tally/tally.go
  pkg/accounting/tally/tally_test.go
  pkg/audit/cursor_test.go
  pkg/audit/reporter.go
  pkg/audit/service.go
  pkg/audit/verifier.go
  pkg/audit/verifier_test.go
  pkg/bwagreement/common.go
  pkg/bwagreement/config.go
  pkg/bwagreement/server.go
  pkg/datarepair/checker/checker.go
  pkg/datarepair/checker/common.go
  pkg/datarepair/checker/config.go
  pkg/datarepair/repairer/config.go
  pkg/discovery/config.go
  pkg/discovery/service.go
  pkg/kademlia/config.go
  pkg/overlay/config.go
  pkg/overlay/mocks/overlay.go
  pkg/overlay/server.go
  pkg/payments/config.go
  pkg/payments/server.go
  pkg/piecestore/psclient/client.go
  pkg/pointerdb/config.go
  pkg/statdb/common.go
  pkg/statdb/config.go
  pkg/statdb/statdb.go
  satellite/peer.go
Labels: Request Code Review, cla-signed

#1128 Change identity command
  cmd/identity/certificate_authority.go
  cmd/identity/identity.go
  cmd/identity/keys.go
  cmd/identity/main.go
  cmd/storj-sim/network.go
  pkg/certificates/config.go
Labels: cla-signed

#1121 quick log cleanup for storage node
  go.mod
  go.sum
  pkg/piecestore/psserver/retrieve.go
  pkg/piecestore/psserver/server.go
  pkg/piecestore/psserver/store.go
Labels: cla-signed

#1129 Identity cleanups
  cmd/identity/main.go
Labels: cla-signed

#1122 Making sure payments works
  cmd/payments/main.go
  pkg/accounting/db.go
  pkg/accounting/tally/tally.go
  pkg/payments/server.go
  pkg/pb/payments.pb.go
  pkg/pb/payments.proto
  satellite/peer.go
  satellite/satellitedb/locked.go
Labels: WIP, cla-signed

#1130 Jj/audit
  satellite/peer.go
Labels: cla-signed

#1131 adds logs in rollup and tally run
  pkg/accounting/rollup/rollup.go
  pkg/accounting/tally/tally.go
Labels: cla-signed

#1132 rollup timestamp fix
  pkg/accounting/db.go
  pkg/accounting/rollup/rollup.go
  satellite/satellitedb/accounting.go
  satellite/satellitedb/locked.go
Labels: Reviewer Can Merge, cla-signed

#1124 internal/sync2: fix file handle leak
  internal/sync2/io.go
  pkg/kademlia/routing_helpers_test.go
Labels: Request Code Review, cla-signed

#1127 Make inmemory a separate command
  cmd/storj-sim/inmemory.go
  cmd/storj-sim/main.go
  cmd/storj-sim/process.go
  pkg/process/debug.go
  pkg/process/exec.go
  pkg/process/metrics.go
Labels: Request Code Review, cla-signed

#1035 [V3-1021] added buttons control for cabinet
  web/satellite/src/components/project/NewProjectPopup.vue
  web/satellite/src/components/team/AddUserPopup.vue
  web/satellite/src/views/Login.vue
  web/satellite/src/views/Register.vue
Labels: cla-signed

#1138 Separate identity from server config
  bootstrap/peer.go
  cmd/bootstrap/main.go
  cmd/certificates/main.go
  cmd/satellite/main.go
  cmd/storagenode/main.go
  pkg/server/config.go
  storagenode/peer.go
Labels: Backward Incompatible, Request Code Review, cla-signed

#1141 Explorer instructions
  EXPLORER_RELEASE_SETUP_INSTRUCTIONS.md
Labels: cla-signed

#1134 removes standalone payments service
  cmd/payments/main.go
  internal/testplanet/planet.go
  pkg/payments/server.go
  pkg/pb/bandwidth.pb.go
  pkg/pb/certificate.pb.go
  pkg/pb/datarepair.pb.go
  pkg/pb/inspector.pb.go
  pkg/pb/meta.pb.go
  pkg/pb/node.pb.go
  pkg/pb/overlay.pb.go
  pkg/pb/payments.pb.go
  pkg/pb/payments.proto
  pkg/pb/piecestore.pb.go
  pkg/pb/pointerdb.pb.go
  pkg/pb/streams.pb.go
  satellite/peer.go
  satellite/satellitedb/accounting.go
Labels: Request Code Review, cla-signed

#1142 Improve identity cli ux:
  cmd/identity/main.go
  go.sum
  pkg/identity/certificate_authority.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1144 Storagenode online confirmation ping
  cmd/inspector/main.go
  cmd/storagenode/main.go
  cmd/storagenode/pkg
  go.mod
  go.sum
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1117 Make Bandwidth Agreements Secure / Trustable
  pkg/accounting/tally/tally_test.go
  pkg/auth/signedMessage.go
  pkg/bwagreement/server.go
  pkg/bwagreement/test/common.go
  pkg/bwagreement/test/server_test.go
  pkg/certificates/certificates.go
  pkg/identity/identity.go
  pkg/pb/BandwidthUtils.go
  pkg/pb/piecestore.pb.go
  pkg/pb/piecestore.proto
  pkg/piecestore/psclient/client.go
  pkg/piecestore/psclient/pieceranger_test.go
  pkg/piecestore/psclient/readerwriter.go
  pkg/piecestore/psserver/retrieve.go
  pkg/piecestore/psserver/server.go
  pkg/piecestore/psserver/server_test.go
  pkg/piecestore/pstore.go
  pkg/pointerdb/allocation.go
  pkg/storj/node.go
  satellite/peer.go
Labels: Request Code Review, cla-signed

#1146 removing instructions
  EXPLORER_RELEASE_SETUP_INSTRUCTIONS.md
Labels: cla-signed

#1149 Improve bwagreement tests
  pkg/accounting/tally/tally_test.go
  pkg/bwagreement/server_test.go
  pkg/bwagreement/testbwagreement/common.go
  pkg/piecestore/psserver/server_test.go
Labels: Request Code Review, cla-signed

#1145 identity cleanup
  cmd/identity/certificate_authority.go
  cmd/identity/main.go
  pkg/certificates/certificates_test.go
  pkg/certificates/config.go
  pkg/identity/certificate_authority.go
  pkg/identity/setup.go
  pkg/provider/transition.go
Labels: Help Wanted, Request Code Review, Reviewer Can Merge, cla-signed

#1147 fixing entrypoint script looking for invalid flag
  cmd/gateway/entrypoint
  cmd/satellite/entrypoint
  cmd/storagenode/entrypoint
  docker-compose.yaml
Labels: cla-signed

#1140 storj-sim configs
  cmd/bootstrap/main.go
  cmd/certificates/setup.go
  cmd/satellite/main.go
  cmd/storj-sim/network.go
  cmd/uplink/cmd/mount.go
  cmd/uplink/cmd/run.go
  cmd/uplink/cmd/setup.go
Labels: Request Code Review, cla-signed

#1154 Remove server aliases
  bootstrap/peer.go
  pkg/certificates/certificates_test.go
  pkg/certificates/config.go
  pkg/piecestore/psserver/server_test.go
  pkg/provider/transition.go
  pkg/server/config.go
  pkg/server/server.go
  satellite/peer.go
  storagenode/peer.go
Labels: Request Code Review, cla-signed

#1156 Added Pagination and SearchOptions reset on successfull adding new user to project.
  web/satellite/src/components/team/AddUserPopup.vue
Labels: cla-signed
