Repository storj/storj, pull requests merged in 2019-05, with the labels that each got.

#1871 makes TestBootstrapBackoffReconnect not flaky
  pkg/kademlia/kademlia_planet_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1537 Macaroon Library
  pkg/macaroon/macaroon.go
  pkg/macaroon/macaroon_test.go
  pkg/macaroon/serialize.go
Labels: Request Code Review, cla-signed

#1838 moved invalid/offline back into SQL
  pkg/datarepair/checker/checker.go
  pkg/overlay/cache.go
  pkg/overlay/cache_test.go
  pkg/overlay/selection_test.go
  pkg/overlay/statdb_test.go
  satellite/inspector/inspector.go
  satellite/satellitedb/locked.go
  satellite/satellitedb/overlaycache.go
  storagenode/piecestore/endpoint.go
Labels: Request Code Review, cla-signed

#1873 jenkins: use -race for check-imports and fix dbx check
  Jenkinsfile.public
  satellite/satellitedb/dbx/satellitedb.dbx.go
  scripts/check-dbx-version.sh
  scripts/check-imports.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1876 Add Identity to Version Control Server
  internal/version/version.go
  versioncontrol/peer.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1867 do not return error if no stripe in audit selection
  pkg/audit/cursor.go
  pkg/audit/cursor_test.go
  pkg/audit/newverifier_test.go
  pkg/audit/service.go
  pkg/audit/timeout_test.go
Labels: Request Code Review, cla-signed

#1851 Small design and popup fixes
  web/satellite/src/components/common/registrationSuccessPopup.html
  web/satellite/src/components/project/ProjectCreationSuccessPopup.vue
  web/satellite/src/components/project/UsageReport.vue
  web/satellite/static/resetPassword/resetPassword.css
Labels: cla-signed

#1881 V3-1243 audit all node code and vulnerabilities part 1
  web/satellite/package.json
  web/satellite/src/api/apiKeys.ts
Labels: cla-signed

#1883 Add Build Timeout to Jenkinsfile
  Jenkinsfile.public
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1875 Add image for versioncontrol server
  Makefile
  cmd/versioncontrol/Dockerfile
  cmd/versioncontrol/entrypoint
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1889 Fix Jenkins master builds
  Jenkinsfile
  Makefile
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1899 Update Calculation to include the already used space for the diskspace allocation
  storagenode/monitor/monitor.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1902 Add Yingrong to CLA
  .clabot
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1865 add boltDB batching for Put operation, add benchmark test
  storage/boltdb/client.go
  storage/boltdb/client_test.go
  storage/testsuite/bench.go
  storage/testsuite/test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1905 Adding Jeff Wendling to the CLA list.
  .clabot
Labels: Reviewer Can Merge, cla-signed

#1906 Add barlock and sndrr to CLA List
  .clabot
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1907 Updates release MaxThreshold default to 130
  uplink/config.go
Labels: Code Review In-Progress, Request Code Review, Reviewer Can Merge, cla-signed

#1904 Gateway setup interactive
  cmd/gateway/main.go
  cmd/storj-sim/network.go
  pkg/cfgstruct/utils.go
Labels: Code Review In-Progress, Request Code Review, Reviewer Can Merge, cla-signed

#1888 hopefully sensible satellite defaults
  cmd/satellite/main.go
  pkg/accounting/rollup/rollup.go
  pkg/datarepair/repairer/repairer.go
  pkg/kademlia/config.go
  pkg/overlay/cache.go
  satellite/mailservice/service.go
  satellite/metainfo/config.go
Labels: Request Code Review, cla-signed

#1801 updates the libuplink documentation with examples
  lib/uplink/doc.go
  lib/uplink/example_test.go
  lib/uplink/uplink.go
Labels: Request Code Review, cla-signed

#1882 Easy fix: typo
  cmd/storagenode/main.go
Labels: Reviewer Can Merge, cla-signed

#1909 Add Network Wipe for Storagenodes
  storagenode/storagenodedb/infodb.go
  storagenode/storagenodedb/testdata/sqlite.v1.sql
Labels: Request Code Review, cla-signed

#1891 Direct suggestions to ideas.storj.io
  README.md
Labels: cla-signed

#1894 Uplink CLI link added to popup
  web/satellite/src/components/project/ProjectCreationSuccessPopup.vue
Labels: cla-signed

#1898 v3-1660: Create a test that breaks when satellite config file has changed
  Jenkinsfile.public
  Makefile
  scripts/test-satellite-cfg-change.sh
  scripts/testdata/satellite-config.yaml.lock
  scripts/update-satellite-cfg-lock.sh
Labels: Request Code Review, SRG, cla-signed

#1862 add apikey library on top of macaroons
  pkg/macaroon/apikey.go
  pkg/macaroon/apikey_test.go
  pkg/macaroon/types.pb.go
  pkg/macaroon/types.proto
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1913 storage node collector
  internal/sync2/cycle.go
  internal/sync2/cycle_test.go
  internal/testplanet/planet.go
  internal/testplanet/uplink.go
  storagenode/collector/service.go
  storagenode/collector/service_test.go
  storagenode/monitor/monitor.go
  storagenode/orders/sender.go
  storagenode/peer.go
  storagenode/pieces/db_test.go
  storagenode/pieces/store.go
  storagenode/piecestore/endpoint.go
  storagenode/storagenodedb/infodb.go
  storagenode/storagenodedb/pieceinfo.go
  storagenode/storagenodedb/testdata/sqlite.v2.sql
Labels: Request Code Review, cla-signed

#1920 Uplink CLI should not require identity
  cmd/uplink/cmd/root.go
Labels: cla-signed

#1921 Gateway should not require identity
  cmd/gateway/main.go
  pkg/miniogw/gateway_test.go
  pkg/miniogw/integration_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1879 repair checker resumes iterating where left off
  pkg/datarepair/checker/checker.go
  pkg/datarepair/checker/checker_test.go
  pkg/overlay/cache.go
  pkg/overlay/selection_test.go
  satellite/satellitedb/overlaycache.go
Labels: Request Code Review, cla-signed

#1926 Update golang version used for release builds
  Makefile
Labels: cla-signed

#1911 docs/design: template
  docs/design/TEMPLATE.md
Labels: cla-signed

#1928 Shorten timeout for stalled builds
  Jenkinsfile.public
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1919 cmd/statreceiver: enable lua libraries in lua config
  cmd/statreceiver/luacfg/cfg.go
Labels: cla-signed

#1927 unskip TestIdentifyIrreparableSegments
  pkg/datarepair/checker/checker_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1915 v3-1660: improvement of test-satellite-cfg-change and related things
  Makefile
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1870 skips TestBootstrapBackoffReconnect
  pkg/kademlia/kademlia_planet_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1850 Set connection read/write timeout
  pkg/transport/timeout.go
  pkg/transport/transport.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1932 jenkins: run two satellites in integration tests
  scripts/test-sim.sh
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1923 Fix to issue an error for empty enc key
  pkg/cfgstruct/utils.go
Labels: Request Code Review, cla-signed

#1937 pkg/kademlia: fix timeout test slowness
  pkg/kademlia/dialer_test.go
  pkg/transport/transport.go
Labels: cla-signed

#1936 internal/sync2: Cycle minor impl & docs improvements
  internal/sync2/cycle.go
  internal/sync2/cycle_test.go
  internal/sync2/doc.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1910 real-time tracking of space used per project
  pkg/accounting/live/doc.go
  pkg/accounting/live/live.go
  pkg/accounting/live/live_test.go
  pkg/accounting/tally/tally.go
  satellite/metainfo/metainfo.go
  satellite/peer.go
  scripts/testdata/satellite-config.yaml.lock
Labels: Request Code Review, Reviewer Can Merge, Sprint Release Goal, cla-signed

#1935 Remove UseIdentity and IdentityVersion from libuplink volatile config
  cmd/gateway/main.go
  cmd/storj-sim/network.go
  lib/uplink/uplink.go
Labels: Request Code Review, cla-signed

#1940 transport: separate dial from request timeouts
  internal/testplanet/uplink.go
  pkg/kademlia/dialer_test.go
  pkg/kademlia/kademlia_planet_test.go
  pkg/transport/transport.go
  uplink/config.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1933 jenkins: peer constraints
  Jenkinsfile.public
  scripts/check-peer-constraints.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1897 Refactor accountingdb interface
  cmd/satellite/usage.go
  pkg/accounting/db.go
  pkg/accounting/db_test.go
  pkg/accounting/projectusage_test.go
  pkg/accounting/rollup/rollup.go
  pkg/accounting/rollup/rollup_test.go
  pkg/accounting/tally/tally.go
  pkg/accounting/tally/tally_test.go
  pkg/overlay/cache.go
  satellite/metainfo/metainfo.go
  satellite/peer.go
  satellite/satellitedb/accounting.go
  satellite/satellitedb/database.go
  satellite/satellitedb/dbx/satellitedb.dbx
  satellite/satellitedb/dbx/satellitedb.dbx.go
  satellite/satellitedb/dbx/satellitedb.dbx.postgres.sql
  satellite/satellitedb/dbx/satellitedb.dbx.sqlite3.sql
  satellite/satellitedb/locked.go
  satellite/satellitedb/migrate.go
  satellite/satellitedb/projectaccounting.go
  satellite/satellitedb/storagenodeaccounting.go
  satellite/satellitedb/testdata/postgres.v18.sql
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1951 Add BlackDuck888
  .clabot
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1950 Update readwrite.go
  storagenode/pieces/readwrite.go
Labels: cla-signed

#1952 Empty enc key v3 1717
  cmd/uplink/cmd/setup.go
Labels: cla-signed

#1639 Add additional error handling to email message sending.
  internal/post/message.go
  internal/post/sender.go
Labels: Request Code Review, cla-signed

#1916 ResetPassword Table and all CRUD methods.
  satellite/console/consoleweb/consoleql/mail.go
  satellite/console/consoleweb/consoleql/query.go
  satellite/console/consoleweb/consoleql/query_test.go
  satellite/console/consoleweb/server.go
  satellite/console/database.go
  satellite/console/resetpasswordtoken.go
  satellite/console/resetpasswordtoken_test.go
  satellite/console/service.go
  satellite/satellitedb/consoledb.go
  satellite/satellitedb/dbx/satellitedb.dbx
  satellite/satellitedb/dbx/satellitedb.dbx.go
  satellite/satellitedb/dbx/satellitedb.dbx.postgres.sql
  satellite/satellitedb/dbx/satellitedb.dbx.sqlite3.sql
  satellite/satellitedb/locked.go
  satellite/satellitedb/migrate.go
  satellite/satellitedb/resetpasstokens.go
  satellite/satellitedb/testdata/postgres.v19.sql
  web/satellite/static/emails/Forgot.html
  web/satellite/static/resetPassword/success.css
  web/satellite/static/resetPassword/success.html
Labels: Request Code Review, cla-signed

#1954 Removed redundant logs from satellite.
  satellite/console/consoleweb/server.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1956 check results in verifier test
  pkg/audit/newverifier_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1958 fix node selection
  satellite/satellitedb/overlaycache.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1962 Back to login pop-up issue
  web/satellite/src/store/modules/appState.ts
Labels: cla-signed

#1908 add postgres support to storj-sim
  Jenkinsfile.public
  cmd/storj-sim/main.go
  cmd/storj-sim/network.go
  internal/dbutil/pgutil/schema.go
  satellite/console/consoleweb/server.go
  satellite/metainfo/config.go
  satellite/peer.go
  satellite/satellitedb/database.go
  satellite/satellitedb/migrate.go
  scripts/test-sim.sh
  storage/postgreskv/client.go
  storage/postgreskv/schema/migrate.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1893 headers in team and apiKeys pages aligned
  web/satellite/src/components/apiKeys/ApiKeysArea.vue
  web/satellite/src/components/apiKeys/headerArea/HeaderArea.vue
  web/satellite/src/components/team/TeamArea.vue
  web/satellite/src/components/team/headerArea/HeaderArea.vue
Labels: cla-signed

#1924 uplink share subcommand
  cmd/uplink/cmd/root.go
  cmd/uplink/cmd/share.go
  lib/uplink/apikey.go
  lib/uplink/uplink.go
  pkg/cfgstruct/bind.go
  pkg/cfgstruct/flags.go
  pkg/macaroon/apikey.go
  pkg/macaroon/apikey_test.go
  pkg/macaroon/caveat.go
  pkg/macaroon/macaroon.go
  pkg/macaroon/types.pb.go
  pkg/macaroon/types.proto
  pkg/pb/node.pb.go
  pkg/pb/overlay.pb.go
  pkg/process/exec_conf.go
Labels: cla-signed

#1964 make caveat nonces random
  cmd/uplink/cmd/share.go
  pkg/macaroon/caveat.go
Labels: Reviewer Can Merge, cla-signed

#1929 adds audit system's containment mode design draft
  docs/design/audit-containment.md
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1961 Resend account activation email
  satellite/console/consoleweb/consoleql/mutation.go
  satellite/console/consoleweb/consoleql/project.go
  satellite/console/consoleweb/consoleql/query.go
  satellite/console/consoleweb/consoleql/query_test.go
  satellite/console/service.go
  web/satellite/src/api/users.ts
  web/satellite/src/components/common/RegistrationSuccessPopup.vue
  web/satellite/src/components/common/registrationSuccessPopup.html
  web/satellite/src/utils/consoleLocalStorage.ts
  web/satellite/src/views/register/Register.vue
  web/satellite/src/views/register/register.html
Labels: cla-signed

#1966 Fix download error threshold
  pkg/eestream/decode.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1963 Billing markup and project page rework
  web/satellite/src/components/account/EditProfilePopup.vue
  web/satellite/src/components/buckets/SearchArea.vue
  web/satellite/src/components/project/PaymentMethods.vue
  web/satellite/src/components/project/ProjectDetails.vue
  web/satellite/src/components/project/ProjectDetailsArea.vue
  web/satellite/src/components/project/ProjectNavigation.vue
  web/satellite/src/components/project/ProjectOverviewArea.vue
  web/satellite/src/components/project/UsageReport.vue
  web/satellite/src/components/project/billing/BillingArea.vue
  web/satellite/src/components/project/billing/BillingItem.vue
  web/satellite/src/components/project/billing/PaginationArea.vue
  web/satellite/src/components/project/billing/SortingHeader.vue
  web/satellite/src/router/index.ts
  web/satellite/src/utils/constants/navigationLinks.ts
  web/satellite/src/utils/constants/projectNavigation.ts
  web/satellite/src/utils/constants/routerConstants.ts
  web/satellite/src/views/login/Login.vue
Labels: Reviewer Can Merge, cla-signed

#1847 Console buckets page
  satellite/console/consoleweb/consoleql/project.go
  satellite/console/consoleweb/consoleql/typecreator.go
  satellite/console/service.go
  satellite/console/usagerollups.go
  satellite/console/usagerollups_test.go
  satellite/satellitedb/locked.go
  satellite/satellitedb/usagerollups.go
  web/satellite/src/api/usage.ts
  web/satellite/src/components/buckets/BucketArea.vue
  web/satellite/src/components/buckets/BucketItem.vue
  web/satellite/src/components/buckets/PaginationArea.vue
  web/satellite/src/components/buckets/SearchArea.vue
  web/satellite/src/components/buckets/SortingHeader.vue
  web/satellite/src/components/project/UsageReport.vue
  web/satellite/src/router/index.ts
  web/satellite/src/store/index.ts
  web/satellite/src/store/modules/usage.ts
  web/satellite/src/store/mutationConstants.ts
  web/satellite/src/types/projects.d.ts
  web/satellite/src/types/usage.d.ts
  web/satellite/src/utils/constants/actionNames.ts
  web/satellite/src/utils/constants/navigationLinks.ts
  web/satellite/src/views/Dashboard.vue
Labels: Request Code Review, cla-signed

#1965 pkg/macaroon: fix NewCaveat doc comment
  pkg/macaroon/caveat.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1971 updating words to be accurate on GUI
  web/satellite/src/components/project/UsageReport.vue
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1973 Bd/doc text2
  cmd/gateway/README.md
  cmd/uplink/README.md
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1939 repair segment reassess it missing pieces just before repair
  pkg/datarepair/checker/checker.go
  pkg/datarepair/repairer/repairer.go
  pkg/overlay/cache.go
  pkg/storage/segments/repairer.go
  pkg/storage/segments/repairer_test.go
Labels: Request Code Review, cla-signed

#1970 Create containment mode database table and migrate scripts
  pkg/overlay/cache.go
  satellite/satellitedb/dbx/satellitedb.dbx
  satellite/satellitedb/dbx/satellitedb.dbx.go
  satellite/satellitedb/dbx/satellitedb.dbx.postgres.sql
  satellite/satellitedb/dbx/satellitedb.dbx.sqlite3.sql
  satellite/satellitedb/migrate.go
  satellite/satellitedb/overlaycache.go
  satellite/satellitedb/testdata/postgres.v20.sql
Labels: Request Code Review, cla-signed

#1833 Console rollup period fix
  web/satellite/src/components/buckets/BucketArea.vue
  web/satellite/src/components/header/projectSelection/ProjectSelectionDropdown.vue
  web/satellite/src/components/project/UsageReport.vue
  web/satellite/src/store/modules/usage.ts
  web/satellite/src/store/mutationConstants.ts
  web/satellite/src/utils/constants/actionNames.ts
  web/satellite/src/views/Dashboard.vue
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1943 storage node garbage collection design doc
  docs/design/garbage-collection.md
Labels: Request Code Review, cla-signed

#1982 removes 0 offline nodes assertion from verifier test
  pkg/audit/newverifier_test.go
Labels: cla-signed

#1985 satellite/mailservice: wait for goroutines to finish
  satellite/console/consoleweb/consoleql/mutation.go
  satellite/console/consoleweb/consoleql/mutation_test.go
  satellite/console/consoleweb/consoleql/query.go
  satellite/console/consoleweb/consoleql/query_test.go
  satellite/mailservice/service.go
  satellite/peer.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1986 satellite/console: use require.NoError in tests
  satellite/console/consoleweb/consoleql/mutation_test.go
  satellite/console/consoleweb/consoleql/query_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1987 improve logging
  storagenode/piecestore/endpoint.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1988 storage/postgreskv: use batch size 1000
  storage/postgreskv/client.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1992 Revert "storage/postgreskv: use batch size 1000"
  storage/postgreskv/client.go
Labels: cla-signed

#1960 Rough sketch for Satellite RPC
  docs/design/metainfo-rpc.md
Labels: cla-signed

#1983 remove downloader from verifier
  pkg/audit/common.go
  pkg/audit/service.go
  pkg/audit/verifier.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1974 Bt/repair no nodes
  pkg/datarepair/checker/checker.go
  satellite/metainfo/metainfo.go
  satellite/metainfo/metainfo_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1994 disable flaky TestSegmentStoreRepair
  pkg/storage/segments/repairer_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1993 update dependencies for bug fixes
  go.mod
  go.sum
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1968 Optimize KnownUnreliableOrOffline SQL query
  pkg/overlay/benchmark_test.go
  pkg/storj/node.go
  satellite/satellitedb/overlaycache.go
  satellite/satellitedb/satellitedbtest/run.go
  satellite/satellitedb/utils.go
  satellite/satellitedb/utils_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1999 improve repair logs
  pkg/storage/ec/client.go
  pkg/storage/segments/repairer.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2001 Add 3bl3gamer
  .clabot
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2000 Store repaired Segments and improve Repair Condition
  pkg/storage/ec/client.go
  pkg/storage/segments/repairer.go
Labels: Request Code Review, cla-signed

#2002 v0.11.4 repair fixes
  pkg/datarepair/checker/checker.go
  pkg/datarepair/repairer/repairer.go
  pkg/overlay/cache.go
  pkg/storage/ec/client.go
  pkg/storage/segments/repairer.go
  pkg/storage/segments/repairer_test.go
Labels: cla-signed

#2003 call GetRemotePieces once
  pkg/storage/segments/repairer.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2004 improve repair logging
  pkg/storage/ec/client.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1995 Fixed NodeID and PieceID marshaling from JSON
  pkg/storj/node.go
  pkg/storj/node_test.go
  pkg/storj/pieceid.go
  pkg/storj/pieceid_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2006 better repairer logging
  pkg/datarepair/repairer/repairer.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2012 v0.11.5
  pkg/datarepair/repairer/repairer.go
  pkg/storage/ec/client.go
Labels: cla-signed

#1942 Design Doc for referral & free tier program
  docs/design/marketing-offer-program.md
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1980 cmd/storagenode: pull more things into releaseDefaults
  cmd/storagenode/entrypoint
  pkg/peertls/tlsopts/config.go
  scripts/testdata/satellite-config.yaml.lock
  storagenode/piecestore/endpoint.go
  storagenode/trust/service.go
Labels: cla-signed

#2005 Setup bootstrap image like the rest
  Makefile
  cmd/bootstrap/Dockerfile
  cmd/bootstrap/entrypoint
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2015 Bugfix: Repair increase success counter
  pkg/storage/ec/client.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2016 Mountable Drive design doc
  docs/design/mountable-drive.md
Labels: cla-signed

#2017 v0.11.6 bugfix repair service
  pkg/datarepair/checker/checker.go
  pkg/storage/ec/client.go
  satellite/metainfo/metainfo.go
  satellite/metainfo/metainfo_test.go
Labels: cla-signed

#1991 db: set max idle connections higher to avoid redialing all the time
  internal/dbutil/defaults.go
  internal/dbutil/pgutil/db.go
  satellite/satellitedb/database.go
  storage/postgreskv/client.go
  storagenode/storagenodedb/infodb.go
Labels: Request Code Review, cla-signed

#2010 Clean up version in image tags
  Makefile
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2018 using DB time only
  satellite/satellitedb/repairqueue.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1967 Change where the encryption key is being stored for uplink
  cmd/gateway/main.go
  cmd/storj-sim/network.go
  cmd/uplink/cmd/common.go
  cmd/uplink/cmd/common_test.go
  cmd/uplink/cmd/cp.go
  cmd/uplink/cmd/ls.go
  cmd/uplink/cmd/mb.go
  cmd/uplink/cmd/rb.go
  cmd/uplink/cmd/rm.go
  cmd/uplink/cmd/root.go
  cmd/uplink/cmd/setup.go
  cmd/uplink/cmd/setup_unexported_test.go
  cmd/uplink/cmd/share.go
  pkg/miniogw/integration_test.go
  pkg/pkcrypto/doc.go
  pkg/process/exec_conf.go
  pkg/storj/doc.go
  pkg/storj/encryption.go
  pkg/storj/encryption_test.go
  scripts/test-uplink.sh
  uplink/config.go
  uplink/config_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1972 adds db layer functions for containment
  pkg/audit/containment.go
  pkg/audit/containment_test.go
  satellite/peer.go
  satellite/satellitedb/containment.go
  satellite/satellitedb/database.go
  satellite/satellitedb/locked.go
Labels: Request Code Review, cla-signed

#2026 define satellite-signed vouchers service
  pkg/pb/vouchers.pb.go
  pkg/pb/vouchers.proto
Labels: Request Code Review, cla-signed

#1959 add uplink-contexts design doc
  docs/design/uplink-scopes.md
Labels: cla-signed

#1890 filter duplicate node IPs
  internal/testplanet/planet.go
  pkg/overlay/cache.go
  pkg/overlay/config.go
  pkg/overlay/selection_test.go
  pkg/pb/node.pb.go
  pkg/pb/node.proto
  pkg/transport/transport.go
  proto.lock
  satellite/satellitedb/dbx/satellitedb.dbx
  satellite/satellitedb/dbx/satellitedb.dbx.go
  satellite/satellitedb/dbx/satellitedb.dbx.postgres.sql
  satellite/satellitedb/dbx/satellitedb.dbx.sqlite3.sql
  satellite/satellitedb/migrate.go
  satellite/satellitedb/overlaycache.go
  satellite/satellitedb/testdata/postgres.v21.sql
  scripts/testdata/satellite-config.yaml.lock
Labels: Request Code Review, Sprint Release Goal, cla-signed

#2028 Send durability stats after iterating over all segments
  pkg/datarepair/checker/checker.go
Labels: Request Code Review, cla-signed

#2009 Show all certificate claims
  cmd/certificates/claims.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1975 Create offer table in satellitedb for free credit program
  docs/design/marketing-offer-program.md
  satellite/satellitedb/dbx/satellitedb.dbx
  satellite/satellitedb/dbx/satellitedb.dbx.go
  satellite/satellitedb/dbx/satellitedb.dbx.postgres.sql
  satellite/satellitedb/dbx/satellitedb.dbx.sqlite3.sql
  satellite/satellitedb/migrate.go
  satellite/satellitedb/testdata/postgres.v22.sql
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2019 cmd/statreceiver: allow for packet filtering to packet destinations
  cmd/statreceiver/example.lua
  cmd/statreceiver/filter.go
  cmd/statreceiver/parser.go
Labels: cla-signed

#2030 Send number of files as part of durability stats
  pkg/datarepair/checker/checker.go
Labels: cla-signed

#2035 skips flaky TestProjectUsageBandwidth
  pkg/accounting/projectusage_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2027 remove unnecessary containmentDB wrapper
  pkg/audit/containment.go
  satellite/peer.go
  satellite/satellitedb/database.go
  satellite/satellitedb/locked.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2033 cmd/uplink: Fix error on interactive setup when --config-dir flag is used.
  cmd/uplink/cmd/setup.go
Labels: Bug, Request Code Review, Reviewer Can Merge, cla-signed

#2020 Password based key derivation design
  docs/design/password-key-derivation.md
Labels: cla-signed

#2029 log errors only when an error happens
  satellite/console/consoleweb/consoleql/mutation.go
Labels: Reviewer Can Merge, cla-signed

#2025 Save hash of expected share from missing audited node
  pkg/audit/containment.go
  pkg/audit/containment_test.go
  pkg/audit/reporter.go
  pkg/audit/service.go
  pkg/audit/timeout_test.go
  pkg/audit/verifier.go
  satellite/peer.go
  satellite/satellitedb/containment.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2044 rename audit.RecordAuditsInfo to audit.Report
  pkg/audit/newverifier_test.go
  pkg/audit/reporter.go
  pkg/audit/timeout_test.go
  pkg/audit/verifier.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2034 Satellite order receiver named log
  satellite/orders/endpoint.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1918 Java/Android libuplink bindings
  internal/fpath/temp_data.go
  internal/sync2/tee.go
  internal/sync2/tee_test.go
  lib/uplink/bucket.go
  mobile/.gitignore
  mobile/bucket.go
  mobile/build.sh
  mobile/doc.go
  mobile/libuplink_android/.gitignore
  mobile/libuplink_android/app/.gitignore
  mobile/libuplink_android/app/build.gradle
  mobile/libuplink_android/app/proguard-rules.pro
  mobile/libuplink_android/app/src/androidTest/java/io/storj/mobile/libuplink/LibuplinkInstrumentedTest.java
  mobile/libuplink_android/app/src/main/AndroidManifest.xml
  mobile/libuplink_android/app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  mobile/libuplink_android/app/src/main/res/drawable/ic_launcher_background.xml
  mobile/libuplink_android/app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  mobile/libuplink_android/app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  mobile/libuplink_android/app/src/main/res/mipmap-hdpi/ic_launcher.png
  mobile/libuplink_android/app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  mobile/libuplink_android/app/src/main/res/mipmap-mdpi/ic_launcher.png
  mobile/libuplink_android/app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  mobile/libuplink_android/app/src/main/res/mipmap-xhdpi/ic_launcher.png
  mobile/libuplink_android/app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  mobile/libuplink_android/app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  mobile/libuplink_android/app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  mobile/libuplink_android/app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  mobile/libuplink_android/app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  mobile/libuplink_android/app/src/main/res/values/colors.xml
  mobile/libuplink_android/app/src/main/res/values/strings.xml
  mobile/libuplink_android/app/src/main/res/values/styles.xml
  mobile/libuplink_android/build.gradle
  mobile/libuplink_android/gradle.properties
  mobile/libuplink_android/gradle/wrapper/gradle-wrapper.jar
  mobile/libuplink_android/gradle/wrapper/gradle-wrapper.properties
  mobile/libuplink_android/gradlew
  mobile/libuplink_android/gradlew.bat
  mobile/libuplink_android/settings.gradle
  mobile/object.go
  mobile/scope.go
  mobile/test-libuplink-android.sh
  mobile/test-sim.sh
  mobile/uplink.go
  pkg/eestream/encode.go
Labels: Request Code Review, Sprint Release Goal, cla-signed

#2042 Add warning info to storagenode dashboard when avail BW < 0
  cmd/storagenode/dashboard.go
Labels: Request Code Review, cla-signed

#2052 Add ethanadams to CLA Bot
  .clabot
Labels: Request Code Review, cla-signed

#2048 pkg/audit: Readdress ignored Verifier tests
  pkg/audit/verifier.go
  pkg/audit/verifier_test.go
Labels: Enhancement, Request Code Review, Reviewer Can Merge, cla-signed

#2054 cmd/uplink: Fix a faulty test
  cmd/uplink/cmd/common_test.go
Labels: Bug, Request Code Review, Reviewer Can Merge, cla-signed

#2050 Delete pending audit entries from containment DB when files get deleted
  satellite/metainfo/metainfo.go
  satellite/peer.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2021 add performance benchmarks
  cmd/uplink/cmd/cp_test.go
  internal/s3client/uplink.go
  scripts/test-sim-benchmark.sh
Labels: Code Review In-Progress, Reviewer Can Merge, Sprint Release Goal, cla-signed

#2057 Add ReneSmeekes
  .clabot
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2056 Use absolute size for unit calculation to account for negative numbers
  internal/memory/size.go
  internal/memory/size_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2047 Fix flaky TestProjectUsageBandwidth
  pkg/accounting/projectusage_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2058 size of raw key should be at least storj.KeySize
  uplink/config_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2041 add Reverify to auditing
  pkg/audit/containment_test.go
  pkg/audit/newverifier_test.go
  pkg/audit/reporter.go
  pkg/audit/service.go
  pkg/audit/timeout_test.go
  pkg/audit/verifier.go
  pkg/overlay/cache.go
  satellite/orders/service.go
Labels: Request Code Review, Sprint Release Goal, cla-signed

#2062 Revert Containment Mode from release-alpha12
  pkg/audit/containment.go
  pkg/audit/containment_test.go
  pkg/audit/newverifier_test.go
  pkg/audit/reporter.go
  pkg/audit/service.go
  pkg/audit/timeout_test.go
  pkg/audit/verifier.go
  pkg/audit/verifier_test.go
  satellite/metainfo/metainfo.go
  satellite/peer.go
  satellite/satellitedb/containment.go
  satellite/satellitedb/database.go
  satellite/satellitedb/locked.go
Labels: cla-signed

#2045 add repair monkit stats
  pkg/storage/segments/repairer.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2064 Fixes Auth Issue
  internal/testplanet/planet.go
  satellite/console/consoleweb/server.go
  satellite/peer.go
  scripts/testdata/satellite-config.yaml.lock
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2065 monkit repair stats - address potential divide by 0
  pkg/storage/segments/repairer.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2036 Per-project usage limiting
  pkg/accounting/db.go
  pkg/accounting/projectusage.go
  pkg/accounting/projectusage_test.go
  satellite/console/projects.go
  satellite/metainfo/metainfo.go
  satellite/peer.go
  satellite/satellitedb/dbx/satellitedb.dbx
  satellite/satellitedb/dbx/satellitedb.dbx.go
  satellite/satellitedb/dbx/satellitedb.dbx.postgres.sql
  satellite/satellitedb/dbx/satellitedb.dbx.sqlite3.sql
  satellite/satellitedb/locked.go
  satellite/satellitedb/migrate.go
  satellite/satellitedb/projectaccounting.go
  satellite/satellitedb/projects.go
  satellite/satellitedb/testdata/postgres.v24.sql
Labels: Code Review In-Progress, Reviewer Can Merge, Sprint Release Goal, cla-signed

#2066 Changing 64bit atomics to 32bit for alignment on ARM.
  internal/sync2/cycle.go
Labels: cla-signed

#2060 aws s3 performance tests
  cmd/s3-benchmark/main.go
  cmd/uplink/cmd/cp_test.go
  internal/s3client/common.go
  internal/s3client/uplink.go
  scripts/test-aws-benchmark.sh
  scripts/test-sim-benchmark.sh
Labels: Code Review In-Progress, Reviewer Can Merge, cla-signed

#2069 Remove unused parameter
  satellite/metainfo/metainfo.go
  satellite/peer.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2070 Fix dates source on UsageReport page
  web/satellite/src/components/project/UsageReport.vue
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2051 Enable gocritic linter
  .golangci.yml
  bootstrap/peer.go
  cmd/certificates/auth.go
  cmd/storj-sim/prefix.go
  cmd/uplink/cmd/share.go
  pkg/accounting/live/live.go
  pkg/audit/cursor_test.go
  pkg/auth/grpcauth/authentication.go
  pkg/auth/signedMessage.go
  pkg/discovery/service.go
  pkg/eestream/decode.go
  pkg/encryption/transform.go
  pkg/identity/utils.go
  pkg/kademlia/kademlia.go
  pkg/kademlia/routing_test.go
  pkg/macaroon/serialize.go
  pkg/pkcrypto/encoding.go
  pkg/ranger/http.go
  pkg/storage/segments/repairer.go
  pkg/storj/node.go
  pkg/storj/pieceid.go
  pkg/storj/serialnumber.go
  satellite/console/consoleweb/server.go
  satellite/metainfo/config.go
  satellite/peer.go
  satellite/satellitedb/containment.go
  satellite/satellitedb/database.go
  storage/postgreskv/schema/migrate.go
  storagenode/inspector/inspector.go
  storagenode/pieces/store_test.go
  storagenode/piecestore/endpoint_test.go
  uplink/metainfo/client.go
Labels: Request Code Review, cla-signed

#2049 Enable Scopelint Linter
  .golangci.yml
  cmd/uplink/cmd/cp_test.go
  internal/post/message.go
  internal/testidentity/identity.go
  internal/testpeertls/revocations.go
  internal/testplanet/planet_test.go
  pkg/accounting/projectusage_test.go
  pkg/accounting/tally/tally_test.go
  pkg/audit/cursor_test.go
  pkg/certificates/certificates_test.go
  pkg/eestream/rs_test.go
  pkg/identity/certificate_authority_test.go
  pkg/identity/identity_test.go
  pkg/kademlia/kademlia.go
  pkg/kademlia/kademlia_test.go
  pkg/kademlia/routing_helpers_test.go
  pkg/kademlia/routing_test.go
  pkg/peertls/extensions/extensions_test.go
  pkg/peertls/tlsopts/tls_test.go
  pkg/pkcrypto/signing_test.go
  pkg/storage/segments/store_test.go
  satellite/console/service.go
  satellite/satellitedb/migrate_postgres_test.go
  storage/testsuite/test_parallel.go
Labels: cla-signed

#2032 add payment popup added
  web/satellite/src/App.vue
  web/satellite/src/components/project/AddPaymentMethodPopup.vue
  web/satellite/src/components/project/CardChoiceItem.vue
  web/satellite/src/components/project/NewProjectPopup.vue
Labels: cla-signed

#2074 updating help message on storage node for AllocatedBandwidth
  storagenode/piecestore/endpoint.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2068 Command line flags features and cleanup
  cmd/bootstrap/main.go
  cmd/certificates/main.go
  cmd/gateway/main.go
  cmd/identity/batch.go
  cmd/identity/certificate_authority.go
  cmd/identity/identity.go
  cmd/identity/main.go
  cmd/identity/revocations.go
  cmd/overlay/main.go
  cmd/satellite/main.go
  cmd/statreceiver/main.go
  cmd/storagenode/main.go
  cmd/uplink/cmd/root.go
  cmd/uplink/cmd/setup.go
  cmd/uplink/cmd/share.go
  cmd/versioncontrol/main.go
  go.mod
  go.sum
  pkg/cfgstruct/bind.go
  pkg/cfgstruct/bind_test.go
  pkg/process/exec_conf.go
Labels: Reviewer Can Merge, cla-signed

#1996 Value Attribution design doc
  docs/design/value-attribution.md
Labels: Request Code Review, cla-signed

#1955 Added the irreparable repair functionality
  internal/testplanet/planet.go
  pkg/datarepair/checker/checker.go
  pkg/datarepair/checker/checker_test.go
  satellite/peer.go
  scripts/testdata/satellite-config.yaml.lock
Labels: Code Review In-Progress, Request Code Review, Reviewer Can Merge, cla-signed

#2078 Add monkit stats to piecestore upload/download
  storagenode/piecestore/endpoint.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2061 Relocate IP Lookup to ensure it is always set
  internal/testplanet/planet.go
  internal/testplanet/reconfigure.go
  pkg/overlay/cache.go
  pkg/overlay/cache_test.go
  pkg/overlay/selection_test.go
  pkg/transport/transport.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed
