Repository storj/storj, pull requests merged in 2019-07, with the labels that each got.

#2399 go.mod: enforce go 1.12
  go.mod
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2403 pkg/storage/segments: Abort repaired test unmet requirements
  pkg/storage/segments/repairer_test.go
Labels: Enhancement, Request Code Review, Reviewer Can Merge, cla-signed

#2402 Audit tests cleanup
  pkg/audit/reporter_test.go
  pkg/audit/reverify_test.go
  pkg/audit/verifier_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2374 cmd/internal/assets: package for embedding resources
  .gitignore
  cmd/internal/asset/asset.go
  cmd/internal/asset/asset_test.go
  cmd/internal/asset/code.go
  cmd/internal/asset/generate/main.go
  cmd/internal/asset/inmemory.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2381 internal/testplanet: ensure that metainfo connections get closed
  internal/testplanet/uplink.go
  satellite/metainfo/metainfo_test.go
  storagenode/piecestore/endpoint_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2335 remove flakiness in TestDataRepair and TestSegmentStoreRepair
  internal/testplanet/satellite.go
  pkg/datarepair/datarepair_test.go
  pkg/storage/segments/repairer_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2315 account for disqualified nodes in data repair tests
  pkg/datarepair/datarepair_test.go
  pkg/storage/segments/repairer_test.go
Labels: Request Code Review, cla-signed

#2406 pkg/pb: rename Order2 to Order, OrderLimit2 to OrderLimit
  pkg/auth/signing/encode.go
  pkg/auth/signing/sign.go
  pkg/auth/signing/verify.go
  pkg/pb/metainfo.pb.go
  pkg/pb/metainfo.proto
  pkg/pb/orders.pb.go
  pkg/pb/orders.proto
  pkg/pb/piecestore2.pb.go
  pkg/pb/piecestore2.proto
  pkg/storage/ec/client_planet_test.go
  pkg/storage/ec/client_test.go
  pkg/storage/segments/store.go
  proto.lock
  satellite/metainfo/metainfo_test.go
  satellite/orders/service.go
  storagenode/orders/db_test.go
  storagenode/orders/sender.go
  storagenode/piecestore/endpoint.go
  storagenode/piecestore/endpoint_test.go
  storagenode/piecestore/verification.go
  storagenode/storagenodedb/orders.go
  uplink/metainfo/client.go
  uplink/piecestore/client.go
  uplink/piecestore/download.go
  uplink/piecestore/upload.go
  uplink/piecestore/verification.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2401 pkg/datarepair/checker: Fix doc comments
  pkg/datarepair/checker/checker.go
Labels: Bug, Request Code Review, Reviewer Can Merge, cla-signed

#2408 add testrand back to datarepair test
  pkg/datarepair/datarepair_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2405 fix repair queue
  pkg/storage/segments/repairer.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2162 Fix smtp sender return error on close
  internal/post/sender.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2396 Fixed typo in disqualification.md
  docs/design/disqualification.md
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2384 satellite/rewards: use USD type
  internal/currency/usd.go
  internal/currency/usd_test.go
  satellite/console/usercredits.go
  satellite/marketingweb/form.go
  satellite/marketingweb/server.go
  satellite/marketingweb/server_test.go
  satellite/rewards/rewards.go
  satellite/rewards/rewards_test.go
  satellite/satellitedb/offers.go
  satellite/satellitedb/usercredits.go
  satellite/satellitedb/usercredits_test.go
  web/marketing/pages/free-offers-modal.html
  web/marketing/pages/free-offers.html
  web/marketing/pages/referral-offers-modal.html
  web/marketing/pages/referral-offers.html
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2369 add bucket metadata table in SA masterDB
  satellite/satellitedb/dbx/satellitedb.dbx
  satellite/satellitedb/dbx/satellitedb.dbx.go
  satellite/satellitedb/dbx/satellitedb.dbx.postgres.sql
  satellite/satellitedb/dbx/satellitedb.dbx.sqlite3.sql
  satellite/satellitedb/locked.go
  satellite/satellitedb/migrate.go
  satellite/satellitedb/testdata/postgres.v38.sql
Labels: Code Review In-Progress, Reviewer Can Merge, cla-signed

#2318 Creates Routing Table Antechamber
  bootstrap/bootstrapdb/database.go
  bootstrap/peer.go
  pkg/kademlia/antechamber.go
  pkg/kademlia/antechamber_test.go
  pkg/kademlia/kademlia_test.go
  pkg/kademlia/routing.go
  pkg/kademlia/routing_helpers_test.go
  satellite/peer.go
  storage/boltdb/client.go
  storagenode/peer.go
  storagenode/storagenodedb/database.go
Labels: Request Code Review, Reviewer Can Merge, Sprint Release Goal, cla-signed

#2413 removing Jira in readme
  README.md
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2383 add bucket metainfo rpc
  pkg/pb/encryption.pb.go
  pkg/pb/encryption.proto
  pkg/pb/metainfo.pb.go
  pkg/pb/metainfo.proto
  proto.lock
  satellite/metainfo/metainfo.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2416 reduce vetting requirement
  pkg/overlay/config.go
  scripts/testdata/satellite-config.yaml.lock
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2387 Routing table antechamber should expire old nodes that failed connection
  pkg/kademlia/antechamber.go
  pkg/kademlia/routing.go
  pkg/kademlia/routing_helpers.go
  pkg/kademlia/routing_helpers_test.go
Labels: Request Code Review, Reviewer Can Merge, Sprint Release Goal, cla-signed

#2417 Rollback uptime disqualification
  pkg/overlay/config.go
  satellite/satellitedb/migrate.go
  satellite/satellitedb/testdata/postgres.v39.sql
  scripts/testdata/satellite-config.yaml.lock
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2415 Update Readme to actual needed Go Version
  README.md
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2407 Add storj.StreamID
  internal/testrand/rand.go
  pkg/pb/types.go
  pkg/storj/streamid.go
  pkg/storj/streamid_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2348 Storagenode add daily bandwidth usage query for SNO
  storagenode/console/bandwidth.go
  storagenode/console/service.go
  storagenode/storagenodedb/consoledb.go
Labels: Request Code Review, Sprint Release Goal, cla-signed

#2365 Pass logger into repairer and ecclient
  internal/testplanet/uplink.go
  lib/uplink/project.go
  lib/uplink/uplink.go
  pkg/datarepair/repairer/repairer.go
  pkg/metainfo/kvmetainfo/buckets_test.go
  pkg/miniogw/gateway_test.go
  pkg/storage/ec/client.go
  pkg/storage/ec/client_planet_test.go
  pkg/storage/segments/repairer.go
  pkg/storage/segments/store_test.go
  satellite/metainfo/metainfo_test.go
  satellite/peer.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2361 Add daily node space usage to satellite nodestats endpoint
  pkg/accounting/db.go
  pkg/pb/nodestats.pb.go
  pkg/pb/nodestats.proto
  proto.lock
  satellite/nodestats/endpoint.go
  satellite/peer.go
  satellite/satellitedb/locked.go
  satellite/satellitedb/storagenodeaccounting.go
Labels: Request Code Review, Sprint Release Goal, cla-signed

#2422 Storagenode nodestats client add daily space usage
  storagenode/console/service.go
  storagenode/nodestats/service.go
Labels: Request Code Review, cla-signed

#2341 satellite/console: add get current reward offer to console
  satellite/console/consoleweb/consoleql/mutation_test.go
  satellite/console/consoleweb/consoleql/query.go
  satellite/console/consoleweb/consoleql/query_test.go
  satellite/console/consoleweb/consoleql/reward.go
  satellite/console/consoleweb/consoleql/typecreator.go
  satellite/console/service.go
  satellite/peer.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2419 overlay.UpdateStats removes node from containment mode
  pkg/audit/containment_test.go
  pkg/audit/reporter.go
  satellite/satellitedb/overlaycache.go
Labels: Request Code Review, cla-signed

#2421 Move from allowed range to minimum for Version Control
  internal/testplanet/bootstrap.go
  internal/version/service.go
  internal/version/version.go
  versioncontrol/peer.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2382 libuplink scope type
  lib/uplink/apikey.go
  lib/uplink/encryption.go
  lib/uplink/ex_restrict_test.go
  lib/uplink/examples_test.go
  lib/uplink/scope.go
  pkg/macaroon/apikey.go
  pkg/pb/scope.pb.go
  pkg/pb/scope.proto
  proto.lock
Labels: cla-signed

#2412 OrderLimit creation date time limit
  internal/testplanet/storagenode.go
  pkg/pb/orders.pb.go
  pkg/pb/orders.proto
  pkg/storage/ec/client_planet_test.go
  proto.lock
  satellite/orders/service.go
  storagenode/orders/db_test.go
  storagenode/piecestore/endpoint.go
  storagenode/piecestore/endpoint_test.go
  storagenode/piecestore/verification.go
Labels: cla-signed

#2425 pkg/cfgstruct: add pflag support to bind
  pkg/cfgstruct/bind.go
  pkg/cfgstruct/bind_test.go
  pkg/storj/nodeurl.go
  pkg/storj/nodeurl_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2435 monitor optimal wait fraction
  pkg/storage/ec/client.go
Labels: cla-signed

#2410 V3-1989: Storage node database is locked for several minutes while submiting orders
  storagenode/storagenodedb/bandwidthdb.go
  storagenode/storagenodedb/certdb.go
  storagenode/storagenodedb/consoledb.go
  storagenode/storagenodedb/infodb.go
  storagenode/storagenodedb/orders.go
  storagenode/storagenodedb/pieceinfo.go
  storagenode/storagenodedb/storagenodedbtest/run_test.go
  storagenode/storagenodedb/usedserials.go
  storagenode/storagenodedb/vouchers.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2438 Properly format Log Message for Version Check Failure
  internal/version/service.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2444 go.mod: update grpc to 1.22.0
  Jenkinsfile.gerrit
  Jenkinsfile.public
  go.mod
  go.sum
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2397 storagenode: decline uploads when there are too many live requests
  internal/testplanet/storagenode.go
  storagenode/piecestore/endpoint.go
  storagenode/piecestore/endpoint_test.go
Labels: Request Code Review, Reviewer Can Merge, Sprint Release Goal, cla-signed

#2420 Fix test-sim debug-addr error
  pkg/process/debug.go
  scripts/test-uplink.sh
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2447 Set MinDownloadTimeout to 5s in testplanet
  internal/testplanet/satellite.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2433 Remove long tail timer in ecclient
  pkg/storage/ec/client.go
Labels: Request Code Review, cla-signed

#2198 Add timestamp and piece size to piece hash
  go.mod
  pkg/pb/orders.pb.go
  pkg/pb/orders.proto
  proto.lock
  satellite/metainfo/metainfo.go
  satellite/metainfo/metainfo_test.go
  satellite/metainfo/validation.go
  storagenode/piecestore/endpoint.go
Labels: Backward Incompatible, Request Code Review, cla-signed

#2193 Add pieceNum to PieceID derivation function
  pkg/audit/reverify_test.go
  pkg/audit/verifier.go
  pkg/audit/verifier_test.go
  pkg/storj/pieceid.go
  pkg/storj/pieceid_test.go
  satellite/metainfo/validation.go
  satellite/orders/service.go
Labels: Backward Incompatible, Request Code Review, cla-signed

#2386 design doc: path component encoding
  docs/design/path-component-encoding.md
Labels: Design Doc, Request Code Review, Reviewer Can Merge, cla-signed

#2388 implement storj.NodeURL in trusted satellites
  bootstrap/peer.go
  internal/testplanet/planet.go
  internal/testplanet/storagenode.go
  pkg/cfgstruct/bind_test.go
  satellite/peer.go
  storagenode/peer.go
  storagenode/piecestore/endpoint.go
  storagenode/trust/service.go
  storagenode/trust/service_test.go
Labels: Request Code Review, Reviewer Can Merge, Sprint Release Goal, cla-signed

#2363 Rename/remove EncryptionScheme -> EncryptionParame…
  cmd/gateway/main.go
  cmd/uplink/cmd/cp.go
  cmd/uplink/cmd/mb.go
  examples/eestream/serve-collected/main.go
  examples/eestream/serve/main.go
  examples/eestream/store/main.go
  internal/testplanet/uplink.go
  lib/uplink/bucket.go
  lib/uplink/encryption.go
  lib/uplink/project.go
  lib/uplinkc/convert.go
  mobile/bucket.go
  pkg/accounting/tally/tally_test.go
  pkg/audit/disqualification_test.go
  pkg/eestream/rs_test.go
  pkg/encryption/encryption.go
  pkg/encryption/encryption_test.go
  pkg/encryption/examples_test.go
  pkg/encryption/path.go
  pkg/encryption/path_new.go
  pkg/encryption/path_new_test.go
  pkg/encryption/path_test.go
  pkg/metainfo/kvmetainfo/buckets.go
  pkg/metainfo/kvmetainfo/buckets_test.go
  pkg/metainfo/kvmetainfo/objects.go
  pkg/metainfo/kvmetainfo/objects_test.go
  pkg/metainfo/kvmetainfo/project.go
  pkg/metainfo/kvmetainfo/stream.go
  pkg/metainfo/kvmetainfo/temputils.go
  pkg/miniogw/gateway_test.go
  pkg/miniogw/integration_test.go
  pkg/storage/objects/store.go
  pkg/storage/streams/shim.go
  pkg/storage/streams/store.go
  pkg/storage/streams/store_test.go
  pkg/storj/encryption.go
  pkg/storj/metainfo.go
  pkg/storj/object.go
  satellite/metainfo/metainfo_test.go
  uplink/config.go
Labels: Backward Incompatible, Request Code Review, Reviewer Can Merge, cla-signed

#2449 Enable bucket name validation
  satellite/metainfo/metainfo_test.go
  satellite/metainfo/validation.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2446 storagenode/consoledb: fix daily bandwidth query
  storagenode/storagenodedb/consoledb.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2442 Rename BucketItem into Bucket
  pkg/pb/inspector.pb.go
  pkg/pb/inspector.proto
  pkg/pb/metainfo.pb.go
  pkg/pb/metainfo.proto
  proto.lock
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2452 change bucket table to fix conflict with pointerDB
  satellite/satellitedb/dbx/satellitedb.dbx
  satellite/satellitedb/dbx/satellitedb.dbx.go
  satellite/satellitedb/dbx/satellitedb.dbx.postgres.sql
  satellite/satellitedb/dbx/satellitedb.dbx.sqlite3.sql
  satellite/satellitedb/migrate.go
  satellite/satellitedb/testdata/postgres.v38.sql
  satellite/satellitedb/testdata/postgres.v39.sql
Labels: Reviewer Can Merge, cla-signed

#2443 storagenode/nodestats: connection leak
  storagenode/nodestats/service.go
  storagenode/orders/sender.go
Labels: Request Code Review, cla-signed

#2426 satellite/nodestats: endpoint add audit check
  pkg/pb/encryption.pb.go
  pkg/pb/nodestats.pb.go
  pkg/pb/nodestats.proto
  proto.lock
  satellite/nodestats/endpoint.go
Labels: Request Code Review, cla-signed

#2458 scripts/protobuf: use command-line diff
  scripts/protobuf.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2450 Fix migration failure due to duplicate bucket_bandwidth_rollups entries
  satellite/satellitedb/migrate.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2434 refactor some store encryption stuff
  lib/uplink/encryption.go
  pkg/audit/disqualification_test.go
  pkg/encryption/examples_test.go
  pkg/encryption/path.go
  pkg/encryption/path_new.go
  pkg/encryption/path_new_test.go
  pkg/encryption/path_test.go
  pkg/metainfo/kvmetainfo/objects.go
  pkg/storage/streams/shim.go
  pkg/storage/streams/store.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2428 uplink mobile: add passphrase generation helpers
  mobile/encryption.go
  mobile/uplink.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2457 Satellite console frontend data reload
  web/satellite/src/components/account/Profile.vue
  web/satellite/src/components/apiKeys/ApiKeysArea.vue
  web/satellite/src/components/buckets/BucketArea.vue
  web/satellite/src/components/project/ProjectDetails.vue
  web/satellite/src/components/project/UsageReport.vue
  web/satellite/src/components/team/TeamArea.vue
  web/satellite/src/store/modules/projects.ts
  web/satellite/src/views/Dashboard.vue
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2210 Improve stability of TestDownloadSharesDownloadTimeout
  internal/testblobs/slow.go
  internal/testplanet/reconfigure.go
  internal/testplanet/run.go
  internal/testplanet/storagenode.go
  pkg/audit/verifier_test.go
Labels: Request Code Review, cla-signed

#2440 lib/uplink: ensure tests are compiled separately
  lib/uplink/bucket_attrs_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2461 pkg/datarepair/checker: Fix typo in doc comment
  pkg/datarepair/checker/checker.go
Labels: Bug, Request Code Review, Reviewer Can Merge, cla-signed

#2456 storagenode/dashboard: show console address
  cmd/storagenode/dashboard.go
  go.mod
  go.sum
  pkg/pb/inspector.pb.go
  pkg/pb/inspector.proto
  pkg/pb/metainfo.pb.go
  pkg/pb/orders.pb.go
  proto.lock
  storagenode/inspector/inspector.go
  storagenode/peer.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2308 Fix ordering of protoc includes
  scripts/protobuf.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2441 storagenode/piecestore: add piece_creation field
  storagenode/pieces/db_test.go
  storagenode/pieces/store.go
  storagenode/piecestore/endpoint.go
  storagenode/piecestore/verification_test.go
  storagenode/storagenodedb/infodb.go
  storagenode/storagenodedb/pieceinfo.go
  storagenode/storagenodedb/testdata/sqlite.v6.sql
Labels: Request Code Review, cla-signed

#2467 Rename voucher service to endpoint
  satellite/peer.go
  satellite/vouchers/endpoint.go
Labels: cla-signed

#2462 Add 'Old' suffix to some metainfo methods/messages
  pkg/pb/metainfo.pb.go
  pkg/pb/metainfo.proto
  proto.lock
  satellite/metainfo/metainfo.go
  satellite/metainfo/validation.go
  uplink/metainfo/client.go
Labels: Backward Incompatible, Request Code Review, cla-signed

#2464 Update inspector timestamp to time.time
  cmd/storagenode/dashboard.go
  pkg/pb/inspector.pb.go
  pkg/pb/inspector.proto
  proto.lock
  storagenode/inspector/inspector.go
  storagenode/inspector/inspector_test.go
Labels: Request Code Review, cla-signed

#2451 piecestore: pipeline chunks with orders
  storagenode/piecestore/endpoint.go
  uplink/piecestore/upload.go
Labels: Backward Incompatible, Request Code Review, Reviewer Can Merge, cla-signed

#2455 storagenode/nodestats: combine stats into single RPC call
  pkg/pb/nodestats.pb.go
  pkg/pb/nodestats.proto
  proto.lock
  satellite/nodestats/endpoint.go
  storagenode/console/service.go
  storagenode/nodestats/service.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2471 Add proper Version Handling to Identity, Gateway and Uplink Binary
  cmd/gateway/main.go
  cmd/identity/main.go
  cmd/uplink/cmd/root.go
  pkg/process/exec_conf.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2477 Removing trace of encodedPiece.Read() because it's fast.
  pkg/eestream/encode.go
Labels: Reviewer Can Merge, cla-signed

#2478 Update vouchers to use time.Time instead of timestamp
  pkg/pb/vouchers.pb.go
  pkg/pb/vouchers.proto
  proto.lock
  satellite/vouchers/endpoint.go
  storagenode/storagenodedb/vouchers.go
  storagenode/vouchers/verification.go
  storagenode/vouchers/vouchers_test.go
Labels: Request Code Review, cla-signed

#2476 adding expiration date check on satellite's CreateSegment
  satellite/metainfo/metainfo.go
  satellite/metainfo/metainfo_test.go
Labels: cla-signed

#2482 Update node.proto to use time.Time instead of timestamp
  internal/version/version.go
  pkg/overlay/benchmark_test.go
  pkg/pb/node.pb.go
  pkg/pb/node.proto
  proto.lock
  satellite/satellitedb/overlaycache.go
Labels: Request Code Review, cla-signed

#2432 satellite/rewards: replace iota with hardcoded OfferType value
  satellite/rewards/rewards.go
  satellite/satellitedb/dbx/satellitedb.dbx
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2485 pkg: Align errs Class messages
  pkg/identity/common.go
  pkg/server/common.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1976 satellite/datarepair: use reliability cache
  internal/testplanet/satellite.go
  pkg/datarepair/checker/checker.go
  pkg/datarepair/checker/checker_test.go
  pkg/datarepair/checker/online.go
  pkg/datarepair/datarepair_test.go
  pkg/overlay/cache.go
  satellite/peer.go
  satellite/satellitedb/locked.go
  satellite/satellitedb/overlaycache.go
  scripts/testdata/satellite-config.yaml.lock
Labels: Request Code Review, cla-signed

#2483 Change pointerdb pointer to use time.Time for Creation date
  pkg/accounting/tally/tally_test.go
  pkg/audit/cursor_test.go
  pkg/audit/verifier.go
  pkg/audit/verifier_unit_test.go
  pkg/datarepair/checker/checker.go
  pkg/datarepair/checker/checker_test.go
  pkg/datarepair/irreparable/irreparable_test.go
  pkg/metainfo/kvmetainfo/objects.go
  pkg/pb/pointerdb.pb.go
  pkg/pb/pointerdb.proto
  pkg/storage/segments/store.go
  pkg/storage/segments/store_test.go
  proto.lock
  satellite/metainfo/metainfo_test.go
  satellite/metainfo/service.go
  storagenode/storagenodedb/vouchers.go
Labels: Request Code Review, cla-signed

#2473 Ensure we force a segment size and account storage before committing them
  internal/testplanet/satellite.go
  satellite/metainfo/config.go
  satellite/metainfo/metainfo.go
  satellite/metainfo/validation.go
  scripts/testdata/satellite-config.yaml.lock
Labels: Request Code Review, cla-signed

#2460 satellite/metainfo: add buckets RPC and database
  lib/uplink/project.go
  lib/uplinkc/convert.go
  mobile/bucket.go
  pkg/macaroon/apikey.go
  pkg/metainfo/kvmetainfo/buckets.go
  pkg/pb/encryption.pb.go
  pkg/pb/encryption.proto
  pkg/pb/metainfo.pb.go
  pkg/storj/bucket.go
  pkg/storj/object.go
  proto.lock
  satellite/metainfo/db.go
  satellite/metainfo/db_test.go
  satellite/metainfo/metainfo.go
  satellite/metainfo/service.go
  satellite/peer.go
  satellite/satellitedb/buckets.go
  satellite/satellitedb/dbx/satellitedb.dbx
  satellite/satellitedb/dbx/satellitedb.dbx.go
  satellite/satellitedb/locked.go
Labels: Code Review In-Progress, Reviewer Can Merge, cla-signed

#2469 storagenode: add in-memory tracking for bandwidth and disk usage
  storagenode/bandwidth/db_test.go
  storagenode/bandwidth/usage.go
  storagenode/monitor/monitor.go
  storagenode/pieces/store.go
  storagenode/storagenodedb/bandwidthdb.go
  storagenode/storagenodedb/infodb.go
  storagenode/storagenodedb/pieceinfo.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2491 discovery: use fetch info to ping
  pkg/discovery/service.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2475 error icon changed
  web/satellite/src/utils/constants/notification.ts
  web/satellite/static/images/register/ErrorInfo.svg
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2488 pkg/identity: Use identity error class
  pkg/identity/identity.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2367 Update password based key derivation design doc
  docs/design/password-key-derivation.md
  lib/uplink/project.go
  pkg/encryption/password.go
  pkg/encryption/password_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2495 Web satellite master fix
  web/satellite/src/api/projects.ts
  web/satellite/src/components/common/RegistrationSuccessPopup.vue
  web/satellite/src/components/project/NewProjectPopup.vue
  web/satellite/src/store/modules/projects.ts
  web/satellite/src/types/projects.d.ts
Labels: cla-signed

#2497 frontend template tabs fixed
  web/satellite/src/components/account/AccountArea.vue
  web/satellite/src/components/account/AccountPaymentMethods.vue
  web/satellite/src/components/account/ChangePasswordPopup.vue
  web/satellite/src/components/account/EditProfilePopup.vue
  web/satellite/src/components/account/Profile.vue
  web/satellite/src/components/account/billing/BillingArea.vue
  web/satellite/src/components/account/billing/BillingItem.vue
  web/satellite/src/components/account/billing/PaginationArea.vue
  web/satellite/src/components/account/billing/SortingHeader.vue
  web/satellite/src/components/buckets/BucketArea.vue
  web/satellite/src/components/buckets/SortingHeader.vue
  web/satellite/src/components/common/HeaderedInput.vue
  web/satellite/src/components/common/HeaderlessInput.vue
  web/satellite/src/components/common/registrationSuccessPopup.html
  web/satellite/src/components/errors/page40X.html
  web/satellite/src/components/errors/page50X.html
  web/satellite/src/components/navigation/TabNavigation.vue
  web/satellite/src/components/navigation/navigationArea.html
  web/satellite/src/components/project/AddPaymentMethodPopup.vue
  web/satellite/src/components/project/CardChoiceItem.vue
  web/satellite/src/components/project/DeleteProjectPopup.vue
  web/satellite/src/components/project/ProjectCreationSuccessPopup.vue
  web/satellite/src/components/project/ProjectDetails.vue
  web/satellite/src/components/project/ProjectPaymentMethods.vue
  web/satellite/src/components/project/UsageReport.vue
  web/satellite/src/components/project/billing/BillingArea.vue
  web/satellite/src/components/project/billing/BillingItem.vue
  web/satellite/src/components/project/billing/PaginationArea.vue
  web/satellite/src/components/project/billing/SortingHeader.vue
  web/satellite/src/components/referral/ReferralStats.vue
  web/satellite/src/components/team/AddUserPopup.vue
  web/satellite/src/components/team/TeamArea.vue
  web/satellite/src/views/forgotPassword/forgotPassword.html
  web/satellite/src/views/login/login.html
  web/satellite/src/views/register/register.html
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2360 Link Sharing service design
  docs/design/link-sharing-service.md
Labels: Design Doc, Request Code Review, Reviewer Can Merge, cla-signed

#2493 Update to go 1.12.7
  Dockerfile.jenkins
  Makefile
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2496 satellite/satellitedb: rename order.go to order.pb.go
  satellite/satellitedb/pbold/order.pb.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1957 adds metainfo rpc doc
  docs/design/metainfo-rpc.md
Labels: Design Doc, Request Code Review, cla-signed

#2494 storagenode/bandwidth: rename BandwidthUsed to MonthSummary
  storagenode/bandwidth/db_test.go
  storagenode/bandwidth/usage.go
  storagenode/monitor/monitor.go
  storagenode/storagenodedb/bandwidthdb.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2506 satellite/metainfo: optimize pointerdb size
  satellite/metainfo/metainfo.go
Labels: cla-signed

#2504 storagenode: use minimum time in the order for expiration
  internal/testplanet/storagenode.go
  storagenode/collector/service_test.go
  storagenode/piecestore/verification.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2498 storagenode: remove 'certificates' table
  storagenode/orders/db_test.go
  storagenode/orders/sender.go
  storagenode/peer.go
  storagenode/pieces/db_test.go
  storagenode/piecestore/endpoint.go
  storagenode/storagenodedb/certdb.go
  storagenode/storagenodedb/database.go
  storagenode/storagenodedb/infodb.go
  storagenode/storagenodedb/orders.go
  storagenode/storagenodedb/pieceinfo.go
  storagenode/storagenodedb/storagenodedbtest/run_test.go
  storagenode/storagenodedb/testdata/sqlite.v7.sql
  storagenode/storagenodedb/usedserials.go
  storagenode/trust/certdb.go
  storagenode/trust/certdb_test.go
Labels: cla-signed

#2509 Change protobuf expirations to use time.Time
  pkg/audit/cursor.go
  pkg/audit/cursor_test.go
  pkg/metainfo/kvmetainfo/objects.go
  pkg/pb/metainfo.pb.go
  pkg/pb/metainfo.proto
  pkg/pb/orders.pb.go
  pkg/pb/orders.proto
  pkg/pb/pointerdb.pb.go
  pkg/pb/pointerdb.proto
  pkg/storage/ec/client_planet_test.go
  pkg/storage/segments/repairer.go
  pkg/storage/segments/store.go
  proto.lock
  satellite/metainfo/metainfo.go
  satellite/metainfo/metainfo_test.go
  satellite/metainfo/validation.go
  satellite/orders/endpoint.go
  satellite/orders/service.go
  satellite/satellitedb/pbold/order.pb.go
  storagenode/orders/db_test.go
  storagenode/pieces/db_test.go
  storagenode/pieces/store.go
  storagenode/piecestore/endpoint.go
  storagenode/piecestore/endpoint_test.go
  storagenode/piecestore/verification.go
  storagenode/piecestore/verification_test.go
  storagenode/storagenodedb/orders.go
  storagenode/storagenodedb/storagenodedbtest/run_test.go
  uplink/metainfo/client.go
Labels: Request Code Review, cla-signed

#2490 overlay cache: slight modification of node-is-online rules
  internal/testplanet/reconfigure.go
  internal/testplanet/satellite.go
  pkg/datarepair/datarepair_test.go
  pkg/overlay/cache.go
  satellite/satellitedb/overlaycache.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2479 [Mobile] Method to convert passphrase to EncryptionAccess
  mobile/encryption.go
  mobile/libuplink_android/app/src/androidTest/java/io/storj/mobile/libuplink/LibuplinkInstrumentedTest.java
Labels: cla-signed

#2499 scss beautification
  web/satellite/.gitignore
  web/satellite/src/App.vue
  web/satellite/src/components/account/AccountArea.vue
  web/satellite/src/components/account/AccountPaymentMethods.vue
  web/satellite/src/components/account/ChangePasswordPopup.vue
  web/satellite/src/components/account/DeleteAccountPopup.vue
  web/satellite/src/components/account/EditProfilePopup.vue
  web/satellite/src/components/account/Profile.vue
  web/satellite/src/components/account/billing/BillingArea.vue
  web/satellite/src/components/account/billing/BillingItem.vue
  web/satellite/src/components/account/billing/PaginationArea.vue
  web/satellite/src/components/account/billing/SortingHeader.vue
  web/satellite/src/components/apiKeys/AddApiKeyPopup.vue
  web/satellite/src/components/apiKeys/ApiKeysArea.vue
  web/satellite/src/components/apiKeys/ApiKeysItem.vue
  web/satellite/src/components/apiKeys/CopyApiKeyPopup.vue
  web/satellite/src/components/apiKeys/footerArea/ApproveDeleteApiKeysArea.vue
  web/satellite/src/components/apiKeys/footerArea/DeleteApiKeysArea.vue
  web/satellite/src/components/apiKeys/footerArea/Footer.vue
  web/satellite/src/components/buckets/BucketArea.vue
  web/satellite/src/components/buckets/BucketItem.vue
  web/satellite/src/components/buckets/PaginationArea.vue
  web/satellite/src/components/buckets/SearchArea.vue
  web/satellite/src/components/buckets/SortingHeader.vue
  web/satellite/src/components/common/Button.vue
  web/satellite/src/components/common/EmptyStateArea.vue
  web/satellite/src/components/common/HeaderedInput.vue
  web/satellite/src/components/common/HeaderlessInput.vue
  web/satellite/src/components/errors/Page404.vue
  web/satellite/src/components/errors/Page50X.vue
  web/satellite/src/components/header/AccountButton.vue
  web/satellite/src/components/header/AccountDropdown.vue
  web/satellite/src/components/header/NewProjectArea.vue
  web/satellite/src/components/header/projectSelection/ProjectSelectionDropdown.vue
  web/satellite/src/components/navigation/TabNavigation.vue
  web/satellite/src/components/project/AddPaymentMethodPopup.vue
  web/satellite/src/components/project/CardChoiceItem.vue
  web/satellite/src/components/project/DeleteProjectPopup.vue
  web/satellite/src/components/project/NewProjectPopup.vue
  web/satellite/src/components/project/ProjectCreationSuccessPopup.vue
  web/satellite/src/components/project/ProjectDetails.vue
  web/satellite/src/components/project/ProjectPaymentMethods.vue
  web/satellite/src/components/project/UsageReport.vue
  web/satellite/src/components/project/billing/BillingArea.vue
  web/satellite/src/components/project/billing/BillingItem.vue
  web/satellite/src/components/project/billing/PaginationArea.vue
  web/satellite/src/components/project/billing/SortingHeader.vue
  web/satellite/src/components/referral/ReferralStats.vue
  web/satellite/src/components/team/AddUserPopup.vue
  web/satellite/src/components/team/TeamArea.vue
  web/satellite/src/components/team/TeamMemberItem.vue
  web/satellite/src/components/team/footerArea/ApproveDeleteUserArea.vue
  web/satellite/src/components/team/footerArea/DeleteUserArea.vue
  web/satellite/src/components/team/footerArea/Footer.vue
  web/satellite/src/components/team/headerArea/SortUsersDropdown.vue
  web/satellite/src/views/Dashboard.vue
Labels: Reviewer Can Merge, cla-signed

#2424 garbage collection endpoint on storage node
  storagenode/pieces/store.go
  storagenode/piecestore/endpoint.go
  storagenode/piecestore/endpoint_test.go
  storagenode/storagenodedb/pieceinfo.go
Labels: Request Code Review, cla-signed

#2466 Move kademlia dialer into separate package
  pkg/kademlia/kademlia.go
  pkg/kademlia/kademliaclient/kademliaclient.go
  pkg/kademlia/kademliaclient/kademliaclient_test.go
  pkg/kademlia/peer_discovery.go
Labels: cla-signed

#2512 storagenodedb: use datetime functions in sqlite queries
  storagenode/collector/service_test.go
  storagenode/pieces/db_test.go
  storagenode/piecestore/serials_test.go
  storagenode/storagenodedb/bandwidthdb.go
  storagenode/storagenodedb/pieceinfo.go
  storagenode/storagenodedb/usedserials.go
Labels: Request Code Review, cla-signed

#2392 satellite/marketingweb: allow disabling rewards
  satellite/marketingweb/server.go
  satellite/marketingweb/server_test.go
  web/marketing/css/style.css
  web/marketing/img/warning.png
  web/marketing/pages/free-offers.html
  web/marketing/pages/referral-offers.html
  web/marketing/pages/stop-free-credit.html
  web/marketing/pages/stop-referral-offer.html
Labels: Do Not Merge, Request Code Review, cla-signed

#2518 segments: send in the object path to the initial CreateSegment call
  pkg/storage/segments/store.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2519 mobile: add a way to get an encryption access at some path root
  mobile/apikey.go
  mobile/encryption.go
  mobile/libuplink_android/app/src/androidTest/java/io/storj/mobile/libuplink/LibuplinkInstrumentedTest.java
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2390 satellite/rewards: nicer offers handling
  satellite/marketingweb/server.go
  satellite/marketingweb/server_test.go
  satellite/rewards/rewards.go
  satellite/satellitedb/dbx/satellitedb.dbx.go
  satellite/satellitedb/locked.go
  satellite/satellitedb/offers.go
  web/marketing/css/style.css
  web/marketing/img/warning.png
  web/marketing/pages/free-offers.html
  web/marketing/pages/referral-offers.html
  web/marketing/pages/stop-free-credit.html
  web/marketing/pages/stop-referral-offer.html
Labels: Code Review In-Progress, Request Code Review, Reviewer Can Merge, cla-signed

#2521 Move int64s to top of struct to resolve alignment issue on ARM
  storagenode/storagenodedb/bandwidthdb.go
  storagenode/storagenodedb/infodb.go
  storagenode/storagenodedb/pieceinfo.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2520 7 day validity window for order limits
  internal/testplanet/satellite.go
  satellite/metainfo/config.go
  satellite/orders/service.go
  scripts/testdata/satellite-config.yaml.lock
Labels: Request Code Review, cla-signed

#2487 Add checker metrics
  pkg/datarepair/checker/checker.go
  pkg/datarepair/repairer/repairer.go
  pkg/pb/datarepair.pb.go
  pkg/pb/datarepair.proto
  proto.lock
Labels: Request Code Review, cla-signed

#2500 Higher dial timeout for TestDownloadSharesDownloadTimeout
  pkg/audit/verifier_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2345 Replace base64 encoding for path segments
  pkg/datarepair/checker/checker.go
  pkg/datarepair/checker/checker_test.go
  pkg/datarepair/queue/queue_test.go
  pkg/datarepair/repairer/repairer.go
  pkg/encryption/examples_test.go
  pkg/encryption/path.go
  pkg/encryption/path_test.go
  pkg/pb/datarepair.pb.go
  pkg/pb/datarepair.proto
  proto.lock
  satellite/satellitedb/dbx/satellitedb.dbx
  satellite/satellitedb/dbx/satellitedb.dbx.go
  satellite/satellitedb/dbx/satellitedb.dbx.postgres.sql
  satellite/satellitedb/dbx/satellitedb.dbx.sqlite3.sql
  satellite/satellitedb/migrate.go
  satellite/satellitedb/repairqueue.go
  satellite/satellitedb/testdata/postgres.v41.sql
Labels: Backward Incompatible, Request Code Review, cla-signed

#2527 Address concerns with storagenode Retain endpoint
  internal/testplanet/uplink_test.go
  pkg/pb/gc.pb.go
  pkg/pb/gc.proto
  pkg/pb/piecestore2.pb.go
  pkg/pb/piecestore2.proto
  proto.lock
  storagenode/piecestore/endpoint.go
  storagenode/piecestore/endpoint_test.go
  storagenode/storagenodedb/pieceinfo.go
  uplink/piecestore/client.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2525 protocol: implement new piece signing and verification
  go.sum
  internal/testplanet/uplink.go
  pkg/audit/disqualification_test.go
  pkg/audit/reverify_test.go
  pkg/audit/verifier.go
  pkg/audit/verifier_test.go
  pkg/auth/signing/marshaling_test.go
  pkg/auth/signing/sign.go
  pkg/auth/signing/verify.go
  pkg/pb/metainfo.pb.go
  pkg/pb/metainfo.proto
  pkg/pb/orders.pb.go
  pkg/pb/orders.proto
  pkg/pb/types.go
  pkg/storage/ec/client.go
  pkg/storage/ec/client_planet_test.go
  pkg/storage/segments/repairer.go
  pkg/storage/segments/store.go
  pkg/storj/piecekey.go
  proto.lock
  satellite/metainfo/metainfo.go
  satellite/metainfo/metainfo_test.go
  satellite/orders/endpoint.go
  satellite/orders/service.go
  satellite/peer.go
  storagenode/orders/db_test.go
  storagenode/pieces/db_test.go
  storagenode/pieces/store.go
  storagenode/piecestore/endpoint.go
  storagenode/piecestore/endpoint_test.go
  storagenode/piecestore/verification.go
  storagenode/piecestore/verification_test.go
  storagenode/storagenodedb/infodb.go
  storagenode/storagenodedb/orders.go
  storagenode/storagenodedb/pieceinfo.go
  storagenode/storagenodedb/storagenodedbtest/run_test.go
  storagenode/storagenodedb/testdata/sqlite.v9.sql
  storagenode/trust/service.go
  uplink/metainfo/client.go
  uplink/piecestore/client.go
  uplink/piecestore/download.go
  uplink/piecestore/upload.go
Labels: Backward Incompatible, Request Code Review, Reviewer Can Merge, cla-signed

#2526 Custom types for PiecePublicKey/PiecePrivateKey
  pkg/storj/piecekey_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2423 [V3-1927] Repairer uploads to max threshold instead of success threshold
  internal/testplanet/satellite.go
  pkg/datarepair/datarepair_test.go
  pkg/datarepair/repairer/repairer.go
  pkg/storage/ec/client.go
  pkg/storage/segments/repairer.go
  satellite/orders/service.go
  satellite/peer.go
  scripts/testdata/satellite-config.yaml.lock
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2505 Jg/1967 mv bucket metadata uplink
  cmd/gateway/main.go
  cmd/uplink/cmd/ls.go
  lib/uplink/bucket_attrs_test.go
  lib/uplink/project.go
  lib/uplink/project_test.go
  lib/uplinkc/bucket.go
  mobile/bucket.go
  mobile/uplink.go
  pkg/macaroon/apikey.go
  pkg/metainfo/kvmetainfo/buckets.go
  pkg/metainfo/kvmetainfo/buckets_test.go
  pkg/metainfo/kvmetainfo/project.go
  pkg/metainfo/kvmetainfo/temputils.go
  pkg/miniogw/gateway.go
  pkg/pb/metainfo.pb.go
  pkg/pb/metainfo.proto
  pkg/pb/pointerdb.pb.go
  pkg/pb/pointerdb.proto
  pkg/storage/buckets/store.go
  pkg/storj/bucket.go
  proto.lock
  satellite/metainfo/db.go
  satellite/metainfo/db_test.go
  satellite/metainfo/metainfo.go
  satellite/metainfo/service.go
  satellite/satellitedb/buckets.go
  satellite/satellitedb/dbx/satellitedb.dbx
  satellite/satellitedb/dbx/satellitedb.dbx.go
  satellite/satellitedb/locked.go
  uplink/metainfo/client.go
Labels: Backward Incompatible, Code Review In-Progress, Reviewer Can Merge, cla-signed

#2510 satellite/satellitedb: remove num_redeemed in offers table
  satellite/rewards/rewards.go
  satellite/rewards/rewards_test.go
  satellite/satellitedb/dbx/satellitedb.dbx
  satellite/satellitedb/dbx/satellitedb.dbx.go
  satellite/satellitedb/dbx/satellitedb.dbx.postgres.sql
  satellite/satellitedb/dbx/satellitedb.dbx.sqlite3.sql
  satellite/satellitedb/locked.go
  satellite/satellitedb/migrate.go
  satellite/satellitedb/offers.go
  satellite/satellitedb/testdata/postgres.v42.sql
  web/marketing/pages/free-offers.html
  web/marketing/pages/referral-offers.html
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2523 web/marketing/pages: partner UI table
  satellite/marketingweb/server.go
  web/marketing/css/style.css
  web/marketing/pages/home.html
  web/marketing/pages/partner-offers-modal.html
  web/marketing/pages/partner-offers.html
Labels: cla-signed

#2522 satellite/satellitedb: add default offer for offers table
  satellite/rewards/rewards_test.go
  satellite/satellitedb/dbx/satellitedb.dbx
  satellite/satellitedb/dbx/satellitedb.dbx.go
  satellite/satellitedb/dbx/satellitedb.dbx.postgres.sql
  satellite/satellitedb/dbx/satellitedb.dbx.sqlite3.sql
  satellite/satellitedb/migrate.go
  satellite/satellitedb/offers.go
  satellite/satellitedb/testdata/postgres.v43.sql
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2535 discovery: parallelize refresh
  internal/testplanet/satellite.go
  pkg/discovery/service.go
  pkg/overlay/cache.go
  pkg/overlay/cache_test.go
  satellite/satellitedb/dbx/satellitedb.dbx
  satellite/satellitedb/dbx/satellitedb.dbx.go
  satellite/satellitedb/locked.go
  satellite/satellitedb/overlaycache.go
  scripts/testdata/satellite-config.yaml.lock
Labels: Request Code Review, cla-signed

#2539 update tally to rm bucket count
  pkg/accounting/tally/tally.go
Labels: cla-signed

#2544 Update vouchers.go
  storagenode/storagenodedb/vouchers.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2533 Order by attempted time in injured segments select
  satellite/satellitedb/dbx/satellitedb.dbx
  satellite/satellitedb/dbx/satellitedb.dbx.go
  satellite/satellitedb/dbx/satellitedb.dbx.postgres.sql
  satellite/satellitedb/dbx/satellitedb.dbx.sqlite3.sql
  satellite/satellitedb/migrate.go
  satellite/satellitedb/repairqueue.go
  satellite/satellitedb/repairqueue_test.go
  satellite/satellitedb/testdata/postgres.v44.sql
Labels: Request Code Review, cla-signed

#2516 Add Attribution Columns to appropriate tables for OSPP referral link
  pkg/storj/bucket.go
  satellite/console/apikeys.go
  satellite/console/projects.go
  satellite/console/users.go
  satellite/satellitedb/apikeys.go
  satellite/satellitedb/buckets.go
  satellite/satellitedb/buckets_test.go
  satellite/satellitedb/dbx/satellitedb.dbx
  satellite/satellitedb/dbx/satellitedb.dbx.go
  satellite/satellitedb/dbx/satellitedb.dbx.postgres.sql
  satellite/satellitedb/dbx/satellitedb.dbx.sqlite3.sql
  satellite/satellitedb/migrate.go
  satellite/satellitedb/projects.go
  satellite/satellitedb/testdata/postgres.v45.sql
  satellite/satellitedb/users.go
Labels: Request Code Review, cla-signed

#2548 Quick fix of a test case
  satellite/satellitedb/buckets_test.go
Labels: cla-signed

#2545 storagenodedb: optimize index usage and queries
  internal/dbutil/dbschema/schema.go
  internal/dbutil/sqliteutil/db.go
  internal/dbutil/sqliteutil/query.go
  storagenode/storagenodedb/bandwidthdb.go
  storagenode/storagenodedb/infodb.go
  storagenode/storagenodedb/migrations_test.go
  storagenode/storagenodedb/pieceinfo.go
  storagenode/storagenodedb/testdata/sqlite.v10.sql
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2542 signing: ensure we don't break signatures
  pkg/auth/signing/encode.go
  pkg/auth/signing/marshaling_test.go
  pkg/auth/signing/sign_test.go
  pkg/pb/compatibility_test.go
  pkg/pb/orders.pb.go
  pkg/pb/orders.proto
  proto.lock
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2553 Fix monkit leaking
  storagenode/storagenodedb/pieceinfo.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2555 ensure uplink is sending correct size with PieceHash
  storagenode/piecestore/endpoint.go
  uplink/piecestore/upload.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2558 satellite/gc: Fix data race with last piece counts map
  satellite/gc/piecetracker.go
  satellite/gc/service.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2547 Jg/add tests
  satellite/metainfo/db_test.go
  satellite/metainfo/service_test.go
Labels: Reviewer Can Merge, cla-signed

#2557 storagenode: remove datetime calls in favor of UTC
  storagenode/storagenodedb/bandwidthdb.go
  storagenode/storagenodedb/bandwidthdb_test.go
  storagenode/storagenodedb/consoledb.go
  storagenode/storagenodedb/consoledb_test.go
  storagenode/storagenodedb/infodb.go
  storagenode/storagenodedb/infodb_test.go
  storagenode/storagenodedb/orders.go
  storagenode/storagenodedb/orders_test.go
  storagenode/storagenodedb/pieceinfo.go
  storagenode/storagenodedb/pieceinfo_test.go
  storagenode/storagenodedb/testdata/sqlite.v0.sql
  storagenode/storagenodedb/testdata/sqlite.v1.sql
  storagenode/storagenodedb/testdata/sqlite.v10.sql
  storagenode/storagenodedb/testdata/sqlite.v2.sql
  storagenode/storagenodedb/testdata/sqlite.v3.sql
  storagenode/storagenodedb/testdata/sqlite.v4.sql
  storagenode/storagenodedb/testdata/sqlite.v5.sql
  storagenode/storagenodedb/testdata/sqlite.v6.sql
  storagenode/storagenodedb/testdata/sqlite.v7.sql
  storagenode/storagenodedb/testdata/sqlite.v8.sql
  storagenode/storagenodedb/testdata/sqlite.v9.sql
  storagenode/storagenodedb/usedserials.go
  storagenode/storagenodedb/usedserials_test.go
  storagenode/storagenodedb/utcdb.go
  storagenode/storagenodedb/utcdb_test.go
  storagenode/storagenodedb/vouchers.go
  storagenode/storagenodedb/vouchers_test.go
Labels: Request Code Review, Reviewer Can Merge, Sprint Release Goal, cla-signed

#2561 repair: fix data race in reliability cache
  internal/testcontext/context.go
  pkg/datarepair/checker/online.go
  pkg/datarepair/checker/online_test.go
Labels: Request Code Review, Reviewer Can Merge, Sprint Release Goal, cla-signed

#2559 add vouchers to QueryRequest
  pkg/pb/overlay.pb.go
  pkg/pb/overlay.proto
  proto.lock
Labels: cla-signed

#2484 satellite/console: add redeem reward method
  satellite/console/service.go
  satellite/console/usercredits.go
  satellite/rewards/rewards.go
  satellite/rewards/rewards_test.go
  satellite/satellitedb/locked.go
  satellite/satellitedb/offers.go
  satellite/satellitedb/usercredits.go
  satellite/satellitedb/usercredits_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2565 enable utccheck in all tests by default
  storagenode/storagenodedb/utcdb.go
  storagenode/storagenodedb/utcdb_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2534 Metainfo RPC objects methods
  internal/testrand/rand.go
  pkg/auth/signing/encode.go
  pkg/auth/signing/sign.go
  pkg/auth/signing/verify.go
  pkg/pb/metainfo.pb.go
  pkg/pb/metainfo.proto
  pkg/pb/types.go
  pkg/storj/encryption.go
  pkg/storj/object_list_item.go
  pkg/storj/streamid.go
  pkg/storj/streamid_test.go
  proto.lock
  satellite/metainfo/metainfo.go
  satellite/metainfo/metainfo_test.go
  satellite/peer.go
  uplink/metainfo/client.go
Labels: Request Code Review, cla-signed

#2569 Consider encryption overhead when validating max segment size
  satellite/metainfo/validation.go
Labels: Request Code Review, Reviewer Can Merge, Sprint Release Goal, cla-signed

#2541 SN DB Optimization: Add rollups to bandwidth usage
  storagenode/bandwidth/usage.go
  storagenode/peer.go
  storagenode/storagenodedb/bandwidthdb.go
  storagenode/storagenodedb/infodb.go
  storagenode/storagenodedb/storagenodedbtest/run_test.go
  storagenode/storagenodedb/testdata/sqlite.v11.sql
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2575 reduce risk of deleting tables by changing their names
  storagenode/storagenodedb/infodb.go
  storagenode/storagenodedb/orders.go
  storagenode/storagenodedb/pieceinfo.go
  storagenode/storagenodedb/testdata/sqlite.v12.sql
  storagenode/storagenodedb/testdata/sqlite.v13.sql
  storagenode/storagenodedb/usedserials.go
Labels: cla-signed

#2566 Network Wipe (Pre Beta)
  storage/filestore/dir.go
  storagenode/storagenodedb/infodb.go
  storagenode/storagenodedb/orders.go
  storagenode/storagenodedb/pieceinfo.go
  storagenode/storagenodedb/testdata/sqlite.v12.sql
  storagenode/storagenodedb/testdata/sqlite.v13.sql
  storagenode/storagenodedb/usedserials.go
Labels: Request Code Review, cla-signed

#2556 Speedup metainfo tests
  satellite/metainfo/metainfo.go
  satellite/metainfo/metainfo_test.go
Labels: cla-signed

#2578 remove struct to ensure 64bit alignment for atomics
  storagenode/storagenodedb/bandwidthdb.go
  storagenode/storagenodedb/infodb.go
  storagenode/storagenodedb/pieceinfo.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2579 Disabling Dashboard Link
  cmd/storagenode/dashboard.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2427 SNO Dashboard API
  internal/date/utils.go
  storagenode/console/consoleserver/server.go
  storagenode/console/service.go
  storagenode/storagenodedb/consoledb.go
  web/operator/dist/build.js
  web/operator/dist/index.html
Labels: Do Not Merge, Request Code Review, Sprint Release Goal, cla-signed

#2582 Remove orphaned tmp data from Storagenodes
  storagenode/storagenodedb/infodb.go
  storagenode/storagenodedb/testdata/sqlite.v14.sql
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2580 scripts/atomicalign: check for proper alignment for 64bit atomics
  Jenkinsfile.gerrit
  Jenkinsfile.public
  scripts/atomicalign.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2583 web/satellite popups' close cross button hit radius fixed
  web/satellite/src/components/account/DeleteAccountPopup.vue
  web/satellite/src/components/apiKeys/AddApiKeyPopup.vue
  web/satellite/src/components/apiKeys/CopyApiKeyPopup.vue
  web/satellite/src/components/common/registrationSuccessPopup.html
  web/satellite/src/components/project/DeleteProjectPopup.vue
  web/satellite/src/components/project/NewProjectPopup.vue
  web/satellite/src/components/project/ProjectCreationSuccessPopup.vue
  web/satellite/src/components/team/AddUserPopup.vue
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2584 storagenode/trust: implement fetching peer identity without kademlia and endpoint
  cmd/storj-sim/network.go
  cmd/storj-sim/process.go
  internal/testplanet/storagenode.go
  pkg/transport/fetchidentity.go
  pkg/transport/slowtransport.go
  pkg/transport/transport.go
  storagenode/peer.go
  storagenode/piecestore/endpoint.go
  storagenode/piecestore/endpoint_test.go
  storagenode/trust/service.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2581 Log fatal errors with respective severity
  pkg/process/exec_conf.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2571 v3-2156: Add partner_id on user creation
  satellite/console/consoleweb/consoleql/apikey.go
  satellite/console/consoleweb/consoleql/mutation_test.go
  satellite/console/consoleweb/consoleql/user.go
  satellite/console/service.go
  satellite/console/users.go
  satellite/console/users_test.go
  satellite/satellitedb/apikeys.go
  satellite/satellitedb/users.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed
