Repository storj/storj, pull requests merged in 2019-12, with the labels that each got.

#3591 storage: Improve doc comments delete methods
  storage/filestore/dir.go
  storage/filestore/store.go
  storagenode/piecestore/endpoint.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3676 installer/windows: fix minor typo
  installer/windows/PublicAddressConfig.wxs
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3651 Satellite: log the project information for upload, download, and list activities
  satellite/metainfo/metainfo.go
Labels: cla-signed

#3678 web/satellite: referral links and registration
  web/satellite/src/api/auth.ts
  web/satellite/src/api/referral.ts
  web/satellite/src/components/account/AccountArea.vue
  web/satellite/src/components/account/ProfileArea.vue
  web/satellite/src/components/account/referral/ReferralArea.vue
  web/satellite/src/components/apiKeys/ApiKeysArea.vue
  web/satellite/src/components/common/VBanner.vue
  web/satellite/src/components/project/ProjectDetails.vue
  web/satellite/src/components/project/ProjectOverviewArea.vue
  web/satellite/src/store/modules/referral.ts
  web/satellite/src/types/referral.ts
  web/satellite/src/views/DashboardArea.vue
  web/satellite/src/views/register/RegisterArea.vue
  web/satellite/tests/unit/views/__snapshots__/DashboardArea.spec.ts.snap
Labels: Sprint Release Goal, cla-signed

#3674 satellite/satellitedb/satellitedbtest: flag to run cockroach tests
  satellite/satellitedb/satellitedbtest/run.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3680 satellite/console : remove code for creating user credit in CreateUser, skip TestUserCredits
  satellite/console/service.go
  satellite/console/usercredits_test.go
Labels: cla-signed

#3671 satellite/metainfo: Improve piece hash validation
  satellite/metainfo/metainfo.go
  satellite/metainfo/validation.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3682 satellitedb: fixes for cockroachdb compatibility
  satellite/satellitedb/satellitedbtest/cockroachnamespace.go
  satellite/satellitedb/satellitedbtest/cockroachnamespace_test.go
  satellite/satellitedb/storagenodeaccounting.go
  satellite/satellitedb/testdata/postgres.v70.sql
  satellite/satellitedb/testdata/postgres.v71.sql
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3679 satellite/gracefulexit: Add graceful exit completed/failed receipt verification to satellite CLI
  cmd/satellite/gracefulexit.go
  cmd/satellite/main.go
  storagenode/gracefulexit/worker.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3688 satellitedb/satellitedbtest: fix TestNewCockroach
  satellite/satellitedb/satellitedbtest/cockroachnamespace_test.go
Labels: cla-signed

#3689 uplinkc: basic support for Scope
  lib/uplinkc/access_scope.go
  lib/uplinkc/testdata/access_scope_test.c
  lib/uplinkc/uplink_definitions.h
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3665 satellite/metainfo, satellite/repair: add metric for download failed due to not enough pieces available
  monkit.lock
  satellite/metainfo/metainfo.go
  satellite/orders/service.go
  satellite/repair/repairer/ec.go
  uplink/eestream/stripe.go
Labels: Request Code Review, cla-signed

#3686 satellite/satellitedb: cockroachDB compatible transaction in offersDB.Create
  satellite/rewards/rewards_test.go
  satellite/satellitedb/offers.go
Labels: cla-signed

#3673 web/satellite: usage data converting implemented
  web/satellite/src/api/usage.ts
  web/satellite/src/components/project/UsageReport.vue
  web/satellite/src/types/usage.ts
  web/satellite/src/utils/bytesSize.ts
  web/satellite/tests/unit/store/usage.spec.ts
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3660 segment-reaper: delete command logic
  cmd/segment-reaper/delete.go
  cmd/segment-reaper/delete_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3598 cmd/segment-reaper: add detecting and printing zombie segments
  cmd/segment-reaper/bitmask.go
  cmd/segment-reaper/bitmask_test.go
  cmd/segment-reaper/detect.go
  cmd/segment-reaper/observer.go
  cmd/segment-reaper/observer_test.go
Labels: Code Review In-Progress, cla-signed

#3695 web/satelllite: default cc delete disabling
  web/satellite/src/components/account/billing/paymentMethods/CardComponent.vue
Labels: cla-signed

#3594 satellitedb: bucket search fixed
  satellite/accounting/projectusage_test.go
  satellite/satellitedb/projectaccounting.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3712 error messages fixed
  satellite/console/consoleweb/consoleql/consoleerrors.go
  satellite/console/service.go
  web/satellite/src/api/auth.ts
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3684 web/storagenode: disk space chart's tooltip size fixed
  web/storagenode/src/app/components/DiskSpaceChart.vue
  web/storagenode/vue.config.js
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3709 web/storagenode: blurred checks hint added for all satellites state
  web/storagenode/src/app/components/SNOContentFilling.vue
  web/storagenode/static/images/BlurredChecks.png
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3706 satellite/satellitedb: ensure migration tests run
  satellite/satellitedb/migrate.go
  satellite/satellitedb/migrate_postgres_test.go
  satellite/satellitedb/testdata/postgres.v69.sql
  satellite/satellitedb/testdata/postgres.v70.sql
  satellite/satellitedb/testdata/postgres.v71.sql
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3693 satellite/satellitedb: reset storage node reputations to re-enable disqualification
  satellite/satellitedb/migrate.go
  satellite/satellitedb/testdata/postgres.v72.sql
Labels: Request Code Review, Sprint Release Goal, cla-signed

#3694 uplinkc: add more functions to manage Scope
  lib/uplinkc/access_scope.go
  lib/uplinkc/testdata/access_scope_test.c
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3658 cmd/segment-reaper: Implement unit test for observer
  cmd/segment-reaper/detect.go
  cmd/segment-reaper/observer.go
  cmd/segment-reaper/observer_test.go
Labels: Request Code Review, cla-signed

#3704 uplinkc: add download_range function
  lib/uplinkc/object.go
  lib/uplinkc/testdata/object_test.c
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3717 satellite/accounting: fix project limits migration
  satellite/accounting/db.go
  satellite/accounting/db_test.go
  satellite/accounting/projectusage_test.go
  satellite/satellitedb/dbx/satellitedb.dbx
  satellite/satellitedb/dbx/satellitedb.dbx.go
  satellite/satellitedb/dbx/satellitedb.dbx.postgres.sql
  satellite/satellitedb/migrate.go
  satellite/satellitedb/projectaccounting.go
  satellite/satellitedb/projects.go
  satellite/satellitedb/testdata/postgres.v70.sql
  satellite/satellitedb/testdata/postgres.v71.sql
  satellite/satellitedb/testdata/postgres.v72.sql
Labels: Request Code Review, Reviewer Can Merge, Sprint Release Goal, cla-signed

#3723 jenkins: run storj-sim integration tests with cockraochdb
  Jenkinsfile.public
  scripts/test-sim-aws.sh
  scripts/test-uplink.sh
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3720 uplink: remove dependency to storage/
  uplink/metainfo/client_old.go
  uplink/metainfo/kvmetainfo/buckets.go
  uplink/metainfo/kvmetainfo/metainfo.go
  uplink/storage/objects/store.go
  uplink/storage/streams/store.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3722 satellite/metainfo: don't leak error implementation detail
  satellite/audit/verifier.go
  satellite/metainfo/metainfo.go
  satellite/metainfo/service.go
  satellite/repair/repairer/segments.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3718 projectLimit error message changed
  satellite/console/consoleweb/consoleql/consoleerrors.go
Labels: cla-signed

#3726 adding Igor Gaidaenko our new team member!
  .clabot
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3641 web/satellite: add tracking event for segment.io
  web/satellite/package-lock.json
  web/satellite/package.json
  web/satellite/src/components/account/DeleteAccountPopup.vue
  web/satellite/src/components/account/billing/billingHistory/BillingHistory.vue
  web/satellite/src/components/account/billing/paymentMethods/PaymentMethods.vue
  web/satellite/src/components/apiKeys/ApiKeysArea.vue
  web/satellite/src/components/apiKeys/ApiKeysCreationPopup.vue
  web/satellite/src/components/project/DeleteProjectPopup.vue
  web/satellite/src/components/project/NewProjectPopup.vue
  web/satellite/src/components/project/ProjectDetails.vue
  web/satellite/src/components/project/UsageReport.vue
  web/satellite/src/components/team/AddUserPopup.vue
  web/satellite/src/components/team/ProjectMembersArea.vue
  web/satellite/src/utils/constants/analyticsEventNames.ts
  web/satellite/src/utils/plugins/segment.ts
  web/satellite/src/views/forgotPassword/ForgotPassword.vue
  web/satellite/src/views/login/LoginArea.vue
  web/satellite/src/views/register/RegisterArea.vue
  web/satellite/tests/unit/apiKeys/ApiKeysArea.spec.ts
  web/satellite/tests/unit/apiKeys/ApiKeysCreationPopup.spec.ts
  web/satellite/tests/unit/projectMembers/ProjectMembersArea.spec.ts
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3702 satellite/console: project usage limits api
  satellite/accounting/projectusage.go
  satellite/api.go
  satellite/console/consoleweb/consoleql/mutation_test.go
  satellite/console/consoleweb/consoleql/query_test.go
  satellite/console/consoleweb/server.go
  satellite/console/projectusagelimits.go
  satellite/console/service.go
Labels: Request Code Review, cla-signed

#3696 satellite/payments/tokens: return checkout url on new deposit
  satellite/console/consoleweb/consoleapi/payments.go
  satellite/payments/stripecoinpayments/tokens.go
  satellite/payments/tokens.go
Labels: Request Code Review, cla-signed

#3711 web/satellite: billing page behaviour
  web/satellite/src/components/account/billing/balance/AccountBalance.vue
  web/satellite/src/components/account/billing/monthlySummary/MonthlyBillingSummary.vue
  web/satellite/src/components/account/billing/paymentMethods/TokenDepositSelection.vue
  web/satellite/src/store/modules/appState.ts
Labels: cla-signed

#3729 builds: use Postgres 9.6 for Jenkins builds
  Dockerfile.jenkins
  docker-compose.yaml
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3707 storagenode/notifications: db created
  cmd/satellite/reports/attribution.go
  private/dbutil/uuid.go
  private/dbutil/uuid_test.go
  satellite/attribution/db_test.go
  satellite/metainfo/metainfo.go
  satellite/referrals/service.go
  satellite/satellitedb/apikeys.go
  satellite/satellitedb/attribution.go
  satellite/satellitedb/buckets.go
  satellite/satellitedb/coinpaymentstxs.go
  satellite/satellitedb/coupons.go
  satellite/satellitedb/customers.go
  satellite/satellitedb/invoiceprojectrecords.go
  satellite/satellitedb/projectaccounting.go
  satellite/satellitedb/projectmembers.go
  satellite/satellitedb/projects.go
  satellite/satellitedb/regtokens.go
  satellite/satellitedb/resetpasstokens.go
  satellite/satellitedb/users.go
  satellite/satellitedb/utils.go
  satellite/satellitedb/utils_test.go
  storagenode/notifications/notifications.go
  storagenode/notifications/notifications_test.go
  storagenode/peer.go
  storagenode/storagenodedb/database.go
  storagenode/storagenodedb/notifications.go
  storagenode/storagenodedb/testdata/multidbsnapshot.go
  storagenode/storagenodedb/testdata/v28.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3724 uplinkc: add restrict_scope function
  lib/uplinkc/access_scope.go
  lib/uplinkc/testdata/access_scope_test.c
  lib/uplinkc/testdata/require.h
  lib/uplinkc/uplink_definitions.h
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3547 satellite/audit: do not report offline to overlay
  satellite/audit/reporter.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3734 Work with @VinozzZ to make this work on jenkins
  Jenkinsfile
  scripts/test-sim-versions.sh
Labels: cla-signed

#2855 uplink/paths/encryption: support commandline argument to override path cipher to be urlsafe base64 for lists and deletes
  cmd/uplink/cmd/ls.go
  cmd/uplink/cmd/rm.go
  pkg/encryption/encryption.go
  pkg/encryption/path.go
  pkg/encryption/path_test.go
  pkg/encryption/store.go
  pkg/storj/encryption.go
  uplink/metainfo/kvmetainfo/buckets_test.go
  uplink/metainfo/kvmetainfo/objects.go
  uplink/metainfo/kvmetainfo/objects_test.go
  uplink/storage/streams/store.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3737 Update Coverage URL
  README.md
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3725 storagenode/orders: adding jitter to sending
  private/testplanet/storagenode.go
  storagenode/orders/service.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed
