Repository storj/storj, pull requests merged in 2019-09, with the labels that each got.

#2930 storagenode: Increase order sending request timeout
  storagenode/orders/service.go
  storagenode/peer.go
Labels: cla-signed

#2935 pkg/server: Don't use Sugared logger
  pkg/server/interceptors.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2931 docs/design: Adapt Storage Node Downtime tracking to be a blueprint
  docs/design/storage-node-downtime-tracking.md
Labels: Design Doc, Request Code Review, Reviewer Can Merge, cla-signed

#2939 storagenode: add custom dial timeout for orders sending
  storagenode/orders/service.go
  storagenode/peer.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2945 jenkins: work around git.apache.org failures
  Jenkinsfile.public
  scripts/test-sim-backwards.sh
Labels: cla-signed

#2944 jenkins: work around git.apache.org failures
  go.mod
  go.sum
  scripts/test-sim-backwards.sh
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2947 Add TopperDEL to the CLA list
  .clabot
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2936 satellite/satellitedb: always release savepoint in process orders
  satellite/satellitedb/orders.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2923 storagenode/bandwidth: remove bandwidth concerns from console, add satellite summary
  internal/dbutil/nulltime.go
  storagenode/bandwidth/db_test.go
  storagenode/bandwidth/usage.go
  storagenode/console/bandwidth.go
  storagenode/console/db_test.go
  storagenode/console/service.go
  storagenode/peer.go
  storagenode/storagenodedb/bandwidthdb.go
  storagenode/storagenodedb/consoledb.go
  storagenode/storagenodedb/database.go
Labels: Request Code Review, Sprint Release Goal, cla-signed

#2911 storagenode/storageusage: add summary, rename timestamp to interval_start
  storagenode/nodestats/service.go
  storagenode/storagenodedb/database.go
  storagenode/storagenodedb/storageusage.go
  storagenode/storagenodedb/testdata/sqlite.v20.sql
  storagenode/storageusage/storageusage.go
  storagenode/storageusage/storageusage_test.go
Labels: Request Code Review, Sprint Release Goal, cla-signed

#2928 web/satellite: account billing page initial markup
  web/satellite/src/components/account/AccountArea.vue
  web/satellite/src/components/account/Profile.vue
  web/satellite/src/components/account/billing/AccountBalance.vue
  web/satellite/src/components/account/billing/BillingArea.vue
  web/satellite/src/components/account/billing/BillingItem.vue
  web/satellite/src/components/account/billing/DepositAndBilling.vue
  web/satellite/src/components/account/billing/MonthlyBillingSummary.vue
  web/satellite/src/components/account/billing/SortingHeader.vue
  web/satellite/src/router/index.ts
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2891 web/satellite: Fixed Project Members deletion.
  satellite/console/auth.go
  satellite/console/consoleweb/consoleql/consoleerrors.go
  satellite/console/consoleweb/consoleql/consoleerrors_test.go
  satellite/console/consoleweb/consoleql/mutation.go
  satellite/console/consoleweb/consoleql/project.go
  satellite/console/consoleweb/consoleql/query.go
  satellite/console/consoleweb/consoleql/token.go
  satellite/console/service.go
  web/satellite/src/components/team/ProjectMembersArea.vue
Labels: cla-signed

#2858 satellite/nodestats: return storage usage in Byte*hours
  internal/dbutil/nulltime.go
  satellite/accounting/db_test.go
  satellite/satellitedb/storagenodeaccounting.go
Labels: Request Code Review, Sprint Release Goal, cla-signed

#2934 storagenode/buildscript: Overwrite existing docker manifest file
  scripts/deploy-storagenode.sh
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2948 pk/pb: add initial proto for the new contact endpoints
  pkg/pb/contact.pb.go
  pkg/pb/contact.proto
  proto.lock
Labels: Code Review In-Progress, Reviewer Can Merge, cla-signed

#2940 satellite/vouchers: deprecate voucher endpoint, return 'please upgrade' error
  internal/testplanet/satellite.go
  satellite/peer.go
  satellite/vouchers/endpoint.go
  satellite/vouchers/vouchers_test.go
  scripts/testdata/satellite-config.yaml.lock
Labels: Request Code Review, cla-signed

#2897 cmd/certificates: auth export improvements & certificates test script
  Jenkinsfile.public
  Makefile
  cmd/certificates/auth.go
  cmd/certificates/main.go
  scripts/test-certificate-signing.sh
  scripts/test-certificates.sh
  scripts/utils.sh
Labels: Code Review In-Progress, Reviewer Can Merge, cla-signed

#2941 pkg/contact: bare-bones service and endpoint
  satellite/contact/endpoint.go
  satellite/contact/service.go
  storagenode/contact/endpoint.go
  storagenode/contact/service.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2951 satellite,storagenode,bootstrap: add contact service to peer
  satellite/peer.go
  storagenode/contact/service.go
  storagenode/peer.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2946 Use ListDirection in struct BucketListOptions
  lib/uplinkc/uplink_definitions.h
Labels: cla-signed

#2929 web/satellite: dashboard component refactored, tests added
  web/satellite/src/components/header/Header.vue
  web/satellite/src/views/Dashboard.vue
  web/satellite/tests/unit/views/Dashboard.spec.ts
  web/satellite/tests/unit/views/__snapshots__/Dashboard.spec.ts.snap
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2926 web/satellite: npm modules versions pinned
  web/satellite/package-lock.json
  web/satellite/package.json
Labels: Request Code Review, cla-signed

#2943 uplink: don't stop deleting segments on first error
  internal/testplanet/uplink_test.go
  uplink/storage/streams/store.go
Labels: Request Code Review, cla-signed

#2961 add list direction option to bucket_test.c
  lib/uplinkc/testdata/bucket_test.c
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2963 web/satellite: Usage tests fix
  web/satellite/tests/unit/store/usage.spec.ts
Labels: cla-signed

#2908 jenkins: build web/satellite
  Dockerfile.jenkins
  Jenkinsfile.public
  Makefile
  scripts/check-clean-directory.go
  scripts/check-copyright.go
  scripts/check-large-files.go
  scripts/protobuf.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2932 cmd/certificates: separate subcommand configs
  cmd/certificates/auth.go
  cmd/certificates/main.go
  cmd/certificates/setup.go
Labels: Code Review In-Progress, Reviewer Can Merge, cla-signed

#2938 {cmd,pkg}/certificates: service refactor
  cmd/certificates/auth.go
  cmd/certificates/claims.go
  cmd/certificates/main.go
  cmd/certificates/setup.go
  cmd/identity/main.go
  pkg/certificate/authorization/authorizations.go
  pkg/certificate/authorization/authorizations_test.go
  pkg/certificate/authorization/db.go
  pkg/certificate/authorization/doc.go
  pkg/certificate/certificateclient/client.go
  pkg/certificate/certificateclient/doc.go
  pkg/certificate/doc.go
  pkg/certificate/endpoint.go
  pkg/certificate/peer.go
  pkg/certificate/peer_test.go
  pkg/certificates/certificates.go
  pkg/certificates/config.go
  scripts/test-certificates.sh
Labels: Do Not Merge, cla-signed

#2888 satellite/audit: create the audit queue
  internal/testplanet/satellite.go
  satellite/audit/chore.go
  satellite/audit/integration_test.go
  satellite/audit/pathcollector_test.go
  satellite/audit/queue.go
  satellite/audit/queue_test.go
  satellite/audit/reservoir.go
  satellite/audit/reservoirservice.go
  satellite/audit/service.go
  satellite/audit/worker.go
  satellite/peer.go
  scripts/testdata/satellite-config.yaml.lock
Labels: Request Code Review, cla-signed

#2922 auto-updater: download versions and archive with binary
  cmd/auto-updater/main.go
  internal/version/version.go
  internal/version/version_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2953 jenkins: remove Jenkinsfile.gerrit
  Jenkinsfile.gerrit
  Makefile
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2969 storagenode/console: update api
  storagenode/console/consoleserver/server_test.go
  storagenode/console/service.go
  storagenode/storagenodedb/reputation.go
Labels: Request Code Review, Sprint Release Goal, cla-signed

#2950 satellite/satellitedb: ensure that we process orders in order
  pkg/storj/node.go
  pkg/storj/serialnumber.go
  satellite/satellitedb/orders.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2877 storagenode/contact: create chore for nodes to ping satellites
  internal/testplanet/storagenode.go
  satellite/contact/contact_test.go
  satellite/peer.go
  storagenode/contact/chore.go
  storagenode/contact/contact_test.go
  storagenode/contact/endpoint.go
  storagenode/contact/service.go
  storagenode/peer.go
Labels: Request Code Review, cla-signed

#2925 Repair with hashes
  satellite/peer.go
  satellite/repair/checker/checker.go
  satellite/repair/checker/checker_test.go
  satellite/repair/repair_test.go
  satellite/repair/repairer/ec.go
  satellite/repair/repairer/repairer.go
  satellite/repair/repairer/segments.go
  uplink/ecclient/client.go
  uplink/eestream/unsafe_rs.go
Labels: Request Code Review, cla-signed

#2973 Fix flaky repair tests
  satellite/repair/repair_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2949 web/satellite: notification to buckets page added
  web/satellite/src/components/buckets/BucketArea.vue
  web/satellite/src/store/modules/buckets.ts
  web/satellite/tests/unit/store/buckets.spec.ts
Labels: cla-signed

#2906 web/storagenode: markup and logic for node operator dashboard
  web/storagenode/.gitignore
  web/storagenode/babel.config.js
  web/storagenode/index.html
  web/storagenode/package.json
  web/storagenode/src/app/App.vue
  web/storagenode/src/app/components/BandwidthChart.vue
  web/storagenode/src/app/components/Bar.vue
  web/storagenode/src/app/components/BarInfoContainer.vue
  web/storagenode/src/app/components/Chart.vue
  web/storagenode/src/app/components/ChecksAreaContainer.vue
  web/storagenode/src/app/components/DiskSpaceChart.vue
  web/storagenode/src/app/components/InfoComponent.vue
  web/storagenode/src/app/components/PayoutContainer.vue
  web/storagenode/src/app/components/SNOContentFilling.vue
  web/storagenode/src/app/components/SNOContentTitle.vue
  web/storagenode/src/app/components/SNOFooter.vue
  web/storagenode/src/app/components/SNOHeader.vue
  web/storagenode/src/app/components/SatelliteSelectionContainer.vue
  web/storagenode/src/app/components/SatelliteSelectionDropdown.vue
  web/storagenode/src/app/router/index.ts
  web/storagenode/src/app/store/index.ts
  web/storagenode/src/app/store/modules/appState.ts
  web/storagenode/src/app/store/modules/node.ts
  web/storagenode/src/app/types/chartData.ts
  web/storagenode/src/app/types/navigation.ts
  web/storagenode/src/app/types/vue.d.ts
  web/storagenode/src/app/utils/chartUtils.ts
  web/storagenode/src/app/utils/converter.ts
  web/storagenode/src/app/views/Dashboard.vue
  web/storagenode/src/main.ts
  web/storagenode/src/storagenode/api/storagenode.ts
  web/storagenode/src/storagenode/dashboard.ts
  web/storagenode/src/storagenode/satellite.ts
  web/storagenode/static/fonts/font_bold.ttf
  web/storagenode/static/fonts/font_medium.ttf
  web/storagenode/static/fonts/font_regular.ttf
  web/storagenode/static/images/Message.png
  web/storagenode/tsconfig.json
  web/storagenode/tslint.json
  web/storagenode/vue.config.js
Labels: Request Code Review, cla-signed

#2937 web/satellite: side bar markup updated
  web/satellite/src/components/navigation/NavigationArea.vue
  web/satellite/src/components/navigation/TabNavigation.vue
  web/satellite/src/components/navigation/navigationArea.html
  web/satellite/src/components/navigation/navigationArea.scss
  web/satellite/tests/unit/components/navigation/__snapshots__/navigationArea.spec.ts.snap
  web/satellite/tests/unit/components/navigation/navigationArea.spec.ts
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2977 satellite/accounting: use sync2.Cycle instead of ticker
  satellite/accounting/rollup/rollup.go
  satellite/accounting/tally/tally.go
  satellite/peer.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2978 satellite/server diagnostics and http headers improved
  satellite/console/consoleweb/server.go
  satellite/console/consoleweb/utils.go
Labels: cla-signed

#2976 cmd/storj-sim: allow overriding executables
  cmd/storj-sim/process.go
  scripts/test-backwards.sh
  scripts/test-sim-backwards.sh
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2967 pkg/peertls/tlsopts: use min TLS 1.2 for grpc
  pkg/peertls/tlsopts/tls.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2988 pkg/process: reduce noise in storj-sim
  pkg/process/exec_conf.go
  pkg/process/metrics.go
  pkg/telemetry/client.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2987 cmd/uplink: fix progressbar data race
  cmd/uplink/cmd/cp.go
  go.mod
  go.sum
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2979 cmd: windows log file workaround
  pkg/process/logging.go
Labels: cla-signed

#2982 docs: add reputation documentation
  docs/blueprints/node-selection.md
  docs/datascience/extending ratios to reputation.pdf
  docs/datascience/reputation scoring framework.pdf
Labels: cla-signed

#2990 jenkins: update to go1.13
  Dockerfile.jenkins
  Makefile
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2586 satellite/console: add lowercase to reset password email input
  satellite/console/service.go
  satellite/console/users_test.go
  satellite/console/validation.go
  satellite/satellitedb/dbx/satellitedb.dbx
  satellite/satellitedb/dbx/satellitedb.dbx.go
  satellite/satellitedb/dbx/satellitedb.dbx.postgres.sql
  satellite/satellitedb/dbx/satellitedb.dbx.sqlite3.sql
  satellite/satellitedb/migrate.go
  satellite/satellitedb/testdata/postgres.v55.sql
  satellite/satellitedb/users.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2640 uplink: integrate new Metainfo calls
  lib/uplink/bucket.go
  lib/uplink/project.go
  pkg/miniogw/gateway_test.go
  satellite/metainfo/metainfo_test.go
  uplink/metainfo/client.go
  uplink/metainfo/kvmetainfo/buckets_test.go
  uplink/metainfo/kvmetainfo/objects.go
  uplink/metainfo/kvmetainfo/objects_test.go
  uplink/metainfo/kvmetainfo/paths.go
  uplink/metainfo/kvmetainfo/stream.go
  uplink/metainfo/kvmetainfo/temputils.go
  uplink/storage/segments/store.go
  uplink/storage/segments/store_test.go
  uplink/storage/streams/shim.go
  uplink/storage/streams/store.go
  uplink/storage/streams/store_test.go
Labels: Request Code Review, cla-signed

#2952 implement contact.checkin method
  satellite/contact/client.go
  satellite/contact/contact_test.go
  satellite/contact/endpoint.go
  satellite/contact/service.go
  satellite/satellitedb/overlaycache.go
  storagenode/contact/chore.go
  storagenode/peer.go
Labels: Code Review In-Progress, Reviewer Can Merge, cla-signed

#2996 migrate: Allow work on separate dbs
  internal/migrate/versions.go
  internal/migrate/versions_test.go
  satellite/satellitedb/migrate.go
  satellite/satellitedb/migrate_postgres_test.go
  storagenode/storagenodedb/database.go
  storagenode/storagenodedb/migrations_test.go
Labels: cla-signed

#2971 pkg/certificates: add authorization endpoint and refactor
  cmd/certificates/auth.go
  cmd/certificates/claims.go
  cmd/certificates/main.go
  cmd/certificates/setup.go
  pkg/certificate/authorization/authorizations.go
  pkg/certificate/authorization/authorizations_test.go
  pkg/certificate/authorization/db.go
  pkg/certificate/authorization/endpoint.go
  pkg/certificate/authorization/endpoint_test.go
  pkg/certificate/authorization/service.go
  pkg/certificate/authorization/service_test.go
  pkg/certificate/peer.go
  pkg/certificate/peer_test.go
  pkg/pb/certificate.proto
  scripts/test-certificates.sh
Labels: Reviewer Can Merge, cla-signed

#2993 web/satellite: markup for billing history page
  web/satellite/src/components/account/billing/BillingHistory.vue
  web/satellite/src/components/account/billing/BillingItem.vue
  web/satellite/src/components/account/billing/DepositAndBilling.vue
  web/satellite/src/components/account/billing/PaginationArea.vue
  web/satellite/src/components/account/billing/SortingHeader.vue
  web/satellite/src/components/navigation/NavigationArea.vue
  web/satellite/src/components/navigation/navigationArea.scss
  web/satellite/src/router/index.ts
  web/satellite/tests/unit/components/navigation/__snapshots__/navigationArea.spec.ts.snap
  web/satellite/tests/unit/components/navigation/navigationArea.spec.ts
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2866 docs/design: Graceful Exit
  docs/blueprints/storagenode-graceful-exit.md
  docs/blueprints/storagenode-graceful-exit/images/transfer-sequence.svg
  docs/blueprints/storagenode-graceful-exit/overview.md
  docs/blueprints/storagenode-graceful-exit/pieces.md
  docs/blueprints/storagenode-graceful-exit/protocol.md
  docs/blueprints/storagenode-graceful-exit/reports.md
  docs/blueprints/storagenode-graceful-exit/ui.md
Labels: Design Doc, Request Code Review, Reviewer Can Merge, cla-signed

#2995 satellite/repair: fix repairer log
  satellite/repair/repairer/repairer.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3000 internal/migrate: remove duplicate logging
  internal/migrate/versions.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2991 versioncontrol: add new version schema
  cmd/auto-updater/main.go
  internal/version/version.go
  versioncontrol/peer.go
Labels: Request Code Review, cla-signed

#3005 storagenode/storagenodedb: prepare for multiple databases
  storagenode/storagenodedb/database.go
  storagenode/storagenodedb/migrations_test.go
  storagenode/storagenodedb/testdata/multidbsnapshot.go
  storagenode/storagenodedb/testdata/sqlite.v0.sql
  storagenode/storagenodedb/testdata/sqlite.v1.sql
  storagenode/storagenodedb/testdata/sqlite.v10.sql
  storagenode/storagenodedb/testdata/sqlite.v11.sql
  storagenode/storagenodedb/testdata/sqlite.v12.sql
  storagenode/storagenodedb/testdata/sqlite.v13.sql
  storagenode/storagenodedb/testdata/sqlite.v14.sql
  storagenode/storagenodedb/testdata/sqlite.v15.sql
  storagenode/storagenodedb/testdata/sqlite.v16.sql
  storagenode/storagenodedb/testdata/sqlite.v17.sql
  storagenode/storagenodedb/testdata/sqlite.v18.sql
  storagenode/storagenodedb/testdata/sqlite.v19.sql
  storagenode/storagenodedb/testdata/sqlite.v2.sql
  storagenode/storagenodedb/testdata/sqlite.v20.sql
  storagenode/storagenodedb/testdata/sqlite.v3.sql
  storagenode/storagenodedb/testdata/sqlite.v4.sql
  storagenode/storagenodedb/testdata/sqlite.v5.sql
  storagenode/storagenodedb/testdata/sqlite.v6.sql
  storagenode/storagenodedb/testdata/sqlite.v7.sql
  storagenode/storagenodedb/testdata/sqlite.v8.sql
  storagenode/storagenodedb/testdata/sqlite.v9.sql
  storagenode/storagenodedb/testdata/v0.go
  storagenode/storagenodedb/testdata/v1.go
  storagenode/storagenodedb/testdata/v10.go
  storagenode/storagenodedb/testdata/v11.go
  storagenode/storagenodedb/testdata/v12.go
  storagenode/storagenodedb/testdata/v13.go
  storagenode/storagenodedb/testdata/v14.go
  storagenode/storagenodedb/testdata/v15.go
  storagenode/storagenodedb/testdata/v16.go
  storagenode/storagenodedb/testdata/v17.go
  storagenode/storagenodedb/testdata/v18.go
  storagenode/storagenodedb/testdata/v19.go
  storagenode/storagenodedb/testdata/v2.go
  storagenode/storagenodedb/testdata/v20.go
  storagenode/storagenodedb/testdata/v3.go
  storagenode/storagenodedb/testdata/v4.go
  storagenode/storagenodedb/testdata/v5.go
  storagenode/storagenodedb/testdata/v6.go
  storagenode/storagenodedb/testdata/v7.go
  storagenode/storagenodedb/testdata/v8.go
  storagenode/storagenodedb/testdata/v9.go
Labels: cla-signed

#3007 storagenode/dashboard: change disqualification text
  web/storagenode/src/app/components/SNOContentFilling.vue
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3001 satellite/overlay: avoid large statement for piece counts
  satellite/overlay/piececount_test.go
  satellite/satellitedb/overlaycache.go
  satellite/satellitedb/overlaycache_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3009 internal/testplanet: reduce coalesce duration
  internal/testplanet/satellite.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2965 satellite/audit: worker now verifies and reverifies
  internal/testplanet/satellite.go
  satellite/audit/cryptosource.go
  satellite/audit/cursor.go
  satellite/audit/cursor_test.go
  satellite/audit/disqualification_test.go
  satellite/audit/integration_test.go
  satellite/audit/pathcollector_test.go
  satellite/audit/reporter_test.go
  satellite/audit/reverify_test.go
  satellite/audit/service.go
  satellite/audit/verifier.go
  satellite/audit/verifier_test.go
  satellite/audit/verifier_unit_test.go
  satellite/audit/worker.go
  satellite/orders/orders_test.go
  satellite/overlay/service_test.go
  satellite/peer.go
  satellite/repair/repair_test.go
  scripts/testdata/satellite-config.yaml.lock
  storagenode/orders/service_test.go
Labels: Request Code Review, cla-signed

#3008 storagenode/storagenodedb: add new tables for graceful exit
  docs/blueprints/storagenode-graceful-exit/overview.md
  storagenode/storagenodedb/database.go
  storagenode/storagenodedb/testdata/multidbsnapshot.go
  storagenode/storagenodedb/testdata/v21.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3027 web/satellite: analytics removed, buckets header foreground improved
  web/satellite/.env
  web/satellite/index.html
  web/satellite/src/components/buckets/SortingHeader.vue
  web/satellite/src/main.ts
  web/satellite/src/plugins/analytics.ts
  web/satellite/src/views/forgotPassword/ForgotPassword.vue
  web/satellite/src/views/login/Login.vue
  web/satellite/src/views/register/Register.vue
Labels: Reviewer Can Merge, cla-signed

#3043 web/satellite: linter updated, analytics artifacts removed
  web/satellite/src/App.vue
  web/satellite/src/api/apiKeys.ts
  web/satellite/src/api/auth.ts
  web/satellite/src/api/buckets.ts
  web/satellite/src/api/paymentMethods.ts
  web/satellite/src/api/projectMembers.ts
  web/satellite/src/components/apiKeys/ApiKeysCreationPopup.vue
  web/satellite/src/components/apiKeys/SortingHeader.vue
  web/satellite/src/components/buckets/BucketItem.vue
  web/satellite/src/components/common/Button.vue
  web/satellite/src/components/common/Checkbox.vue
  web/satellite/src/components/common/EmptyStateArea.vue
  web/satellite/src/components/common/HeaderComponent.vue
  web/satellite/src/components/common/HeaderedInput.vue
  web/satellite/src/components/project/DeleteProjectPopup.vue
  web/satellite/src/components/team/HeaderArea.vue
  web/satellite/src/components/team/ProjectMembersArea.vue
  web/satellite/src/utils/authToken.ts
  web/satellite/src/utils/constants/analyticsEventNames.ts
  web/satellite/src/utils/doNotTrack.ts
  web/satellite/src/utils/time.ts
  web/satellite/src/views/forgotPassword/ForgotPassword.vue
  web/satellite/src/views/login/Login.vue
  web/satellite/src/views/register/Register.vue
  web/satellite/tests/unit/store/projects.spec.ts
  web/satellite/tests/unit/utils/validation.spec.ts
  web/satellite/tslint.json
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3037 uplink/ecclient: Report success in debug level
  uplink/ecclient/client.go
Labels: Enhancement, Request Code Review, Reviewer Can Merge, cla-signed

#3020 web/satellite: notification height fixed
  web/satellite/src/components/notifications/Notification.vue
Labels: Reviewer Can Merge, cla-signed

#3036 uplink/ecclient: Remove unneeded atomic operation
  uplink/ecclient/client.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3039 storagenode/contact: test node info is updated
  storagenode/contact/chore.go
  storagenode/contact/contact_test.go
Labels: cla-signed

#3042 storagenode/orders: fix data race in settle
  storagenode/orders/service.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3041 satellite: remove remote/inline file from BucketTally
  satellite/accounting/bucketstats.go
  satellite/accounting/bucketusage.go
  satellite/accounting/db_test.go
  satellite/accounting/tally/tally.go
  satellite/accounting/tally/tally_test.go
  satellite/attribution/db_test.go
  satellite/audit/pathcollector.go
  satellite/console/usagerollups_test.go
  satellite/gc/piecetracker.go
  satellite/metainfo/loop.go
  satellite/metainfo/loop_test.go
  satellite/repair/checker/checker.go
  satellite/satellitedb/projectaccounting.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3047 satellite/console/server: fix usage rollup report
  satellite/console/consoleweb/server.go
Labels: Request Code Review, cla-signed

#3046 web/storagenode: error processing added
  web/storagenode/src/app/components/SNOContentTitle.vue
  web/storagenode/src/app/components/SNOHeader.vue
  web/storagenode/src/app/components/SatelliteSelectionDropdown.vue
  web/storagenode/src/storagenode/api/storagenode.ts
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2997 satellite/repair/repairer: update audit status as failed after failing piece hash verification
  satellite/repair/repair_test.go
  satellite/repair/repairer/ec.go
  satellite/repair/repairer/segments.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3033 satellite/satellitedb: add new graceful exit tables and add graceful exit fields to nodes
  docs/blueprints/storagenode-graceful-exit/overview.md
  docs/blueprints/storagenode-graceful-exit/pieces.md
  satellite/satellitedb/dbx/satellitedb.dbx
  satellite/satellitedb/dbx/satellitedb.dbx.go
  satellite/satellitedb/dbx/satellitedb.dbx.postgres.sql
  satellite/satellitedb/dbx/satellitedb.dbx.sqlite3.sql
  satellite/satellitedb/migrate.go
  satellite/satellitedb/testdata/postgres.v56.sql
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2981 Uplink "import" command
  cmd/uplink/cmd/common.go
  cmd/uplink/cmd/import.go
  cmd/uplink/cmd/root.go
  cmd/uplink/cmd/share.go
  pkg/cfgstruct/bind.go
  pkg/cfgstruct/bind_test.go
  pkg/process/config.go
  scripts/testdata/satellite-config.yaml.lock
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3040 uplink/storage/streams: Add test for interrupted deletes
  uplink/storage/streams/store_test.go
Labels: cla-signed

#3048 pkg/pb: minor changes to contact.proto
  pkg/pb/contact.pb.go
  pkg/pb/contact.proto
  proto.lock
  satellite/contact/client.go
  satellite/contact/contact_test.go
  satellite/contact/endpoint.go
  storagenode/contact/chore.go
Labels: Code Review In-Progress, Reviewer Can Merge, cla-signed

#3024 storagenode/container: Enable storagenode console in container images
  cmd/satellite/Dockerfile
  cmd/storagenode/Dockerfile
  cmd/storagenode/entrypoint
Labels: Request Code Review, Reviewer Can Merge, Sprint Release Goal, cla-signed

#3050 satellite/metainfo: make piece hashes nil before storing pointer in metainfo.UpdatePieces()
  satellite/metainfo/service.go
  satellite/repair/repair_test.go
Labels: Bug, Request Code Review, Reviewer Can Merge, cla-signed

#3051 satellite/repair: delete pieces that failed piece hashes verification from pointer
  satellite/repair/repair_test.go
  satellite/repair/repairer/ec.go
  satellite/repair/repairer/segments.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3055 Add satellites database business objects.
  storagenode/storagenodedb/database.go
  storagenode/storagenodedb/satellites.go
Labels: cla-signed

#3035 pkg/miniogw: Add a missed stack trace error
  pkg/miniogw/gateway.go
Labels: Enhancement, Request Code Review, Reviewer Can Merge, cla-signed

#3058 satellite/audit: set devDefaults for ChoreInterval and QueueInterval to 1m
  satellite/audit/worker.go
Labels: Request Code Review, cla-signed

#2968 auto-updater: unpack/check binary, restart service
  cmd/auto-updater/main.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3059 scripts/protobuf.go: update drpc version
  scripts/protobuf.go
Labels: Request Code Review, cla-signed

#3056 satellite/repair: add metric trackers for segment age before repair
  pkg/pb/pointerdb.pb.go
  pkg/pb/pointerdb.proto
  proto.lock
  satellite/metainfo/service.go
  satellite/repair/checker/checker.go
  satellite/repair/repairer/segments.go
Labels: Request Code Review, cla-signed

#3066 add satelliteSystem to testplanet and update tests
  internal/testplanet/planet.go
  internal/testplanet/satellite.go
  internal/testplanet/uplink.go
  pkg/kademlia/merge_test.go
  satellite/audit/disqualification_test.go
  satellite/gc/gc_test.go
  satellite/repair/repair_test.go
  uplink/ecclient/client_planet_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3064 internal/dbutil/sqliteutil: add MigrateTablesToDatabase
  internal/dbutil/sqliteutil/migrator.go
  internal/dbutil/sqliteutil/migrator_test.go
Labels: cla-signed

#2985 satellite/metainfo: Verify storagenode signature on satellite upload
  pkg/pb/metainfo.pb.go
  pkg/pb/metainfo.proto
  pkg/pb/pointerdb.pb.go
  pkg/pb/pointerdb.proto
  proto.lock
  satellite/metainfo/metainfo.go
  satellite/metainfo/metainfo_test.go
  satellite/metainfo/validation.go
  satellite/overlay/peeridentities_test.go
  satellite/peer.go
Labels: Request Code Review, cla-signed

#3075 pkg/transport: set default timeout to 10 minutes
  pkg/transport/common.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3082 update NodeSelectionConfig.OnlineWindow to 4hr default
  satellite/overlay/config.go
  scripts/testdata/satellite-config.yaml.lock
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3083 rm noisy debug logs that we dont need
  pkg/kademlia/endpoint.go
Labels: cla-signed

#3084 satellite/contact: close grpc client connections
  satellite/contact/endpoint.go
Labels: cla-signed

#3062 uplink/satellite: fix for case when inline segment is last one
  satellite/metainfo/loop.go
  satellite/metainfo/metainfo.go
  satellite/repair/checker/checker.go
  satellite/repair/checker/checker_test.go
  scripts/test-backwards.sh
  scripts/test-uplink.sh
  uplink/storage/segments/store.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3085 satellite/audit: fix containment mode
  satellite/audit/reverify_test.go
  satellite/audit/verifier.go
Labels: Bug, Request Code Review, Reviewer Can Merge, Sprint Release Goal, cla-signed

#3086 return status codes for contact endpoint
  satellite/contact/endpoint.go
Labels: Reviewer Can Merge, cla-signed

#3088 satellite/metainfo: fix GetObject method
  satellite/metainfo/metainfo.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3089 cmd: rename auto-updater to storagenode-updater
  cmd/storagenode-updater/main.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3077 auto-updater: respond to Windows Service events
  cmd/storagenode-updater/main.go
  cmd/storagenode-updater/windows.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3079 web/storagenode: UI node ID container fixed
  web/storagenode/src/app/components/SNOHeader.vue
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3076 add auto-updater to Makefile
  Makefile
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3072 go.mod: update to grpc 1.23.1 and update golang.org/x
  go.mod
  go.sum
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3080 web/satellite: copy api key popup title changed
  web/satellite/src/components/apiKeys/ApiKeysCopyPopup.vue
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3092 satellite/audit: Fix flakiness in TestReverifyDifferentShare
  satellite/audit/reverify_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3069 metainfo: move api keys to part of the request
  internal/testplanet/uplink.go
  internal/testplanet/uplink_test.go
  lib/uplink/bucket_attrs_test.go
  lib/uplink/examples_test.go
  lib/uplink/list_test.go
  lib/uplink/uplink.go
  lib/uplinkc/testdata_test.go
  linksharing/handler_test.go
  pkg/auth/grpcauth/apikey.go
  pkg/auth/grpcauth/apikey_test.go
  pkg/macaroon/serialize.go
  pkg/miniogw/gateway_test.go
  pkg/pb/metainfo.pb.go
  pkg/pb/metainfo.proto
  proto.lock
  satellite/metainfo/batch.go
  satellite/metainfo/metainfo.go
  satellite/metainfo/metainfo_test.go
  satellite/metainfo/validation.go
  uplink/metainfo/client.go
  uplink/metainfo/kvmetainfo/buckets_test.go
  uplink/storage/streams/store_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3025 storagenode/process: respond to Windows Service events
  cmd/bootstrap/main.go
  cmd/certificates/auth.go
  cmd/certificates/claims.go
  cmd/certificates/main.go
  cmd/gateway/main.go
  cmd/identity/batch.go
  cmd/identity/certificate_authority.go
  cmd/identity/main.go
  cmd/identity/revocations.go
  cmd/linksharing/main.go
  cmd/satellite/main.go
  cmd/storagenode/dashboard.go
  cmd/storagenode/main.go
  cmd/storagenode/windows.go
  cmd/uplink/cmd/cat.go
  cmd/uplink/cmd/cp.go
  cmd/uplink/cmd/ls.go
  cmd/uplink/cmd/mb.go
  cmd/uplink/cmd/put.go
  cmd/uplink/cmd/rb.go
  cmd/uplink/cmd/rm.go
  cmd/uplink/cmd/setup.go
  cmd/versioncontrol/main.go
  examples/metric-receiver/main.go
  pkg/process/exec_conf.go
Labels: Request Code Review, cla-signed

#2999 remove kademlia: create upsert query to update uptime
  internal/testplanet/uplink_test.go
  pkg/pb/contact.pb.go
  pkg/pb/contact.proto
  proto.lock
  satellite/audit/disqualification_test.go
  satellite/contact/benchmark_test.go
  satellite/contact/contact_test.go
  satellite/contact/endpoint.go
  satellite/overlay/service.go
  satellite/overlay/service_test.go
  satellite/overlay/statdb_test.go
  satellite/satellitedb/locked.go
  satellite/satellitedb/migrate.go
  satellite/satellitedb/overlaycache.go
  satellite/satellitedb/testdata/postgres.v57.sql
  storagenode/contact/chore.go
Labels: Request Code Review, cla-signed

#2966 Remove Kademlia dependencies from Satellite and Storagenode
  README.md
  cmd/inspector/main.go
  cmd/storagenode/entrypoint
  cmd/storagenode/main.go
  cmd/storj-sim/network.go
  internal/testplanet/planet.go
  internal/testplanet/planet_test.go
  internal/testplanet/satellite.go
  internal/testplanet/storagenode.go
  internal/testplanet/uplink_test.go
  pkg/kademlia/kademlia_planet_test.go
  pkg/kademlia/kademliaclient/kademliaclient_test.go
  pkg/kademlia/lookup_test.go
  pkg/kademlia/merge_test.go
  pkg/pb/contact.proto
  satellite/audit/verifier_test.go
  satellite/contact/contact_test.go
  satellite/contact/kademlia.go
  satellite/contact/service.go
  satellite/discovery/service.go
  satellite/discovery/service_test.go
  satellite/peer.go
  satellite/repair/repair_test.go
  scripts/test-sim-backwards.sh
  scripts/testdata/satellite-config.yaml.lock
  storagenode/console/service.go
  storagenode/contact/chore.go
  storagenode/contact/contact_test.go
  storagenode/contact/kademlia.go
  storagenode/contact/service.go
  storagenode/inspector/inspector.go
  storagenode/inspector/inspector_test.go
  storagenode/monitor/monitor.go
  storagenode/monitor/monitor_test.go
  storagenode/operator.go
  storagenode/peer.go
  storagenode/storagenodedb/database.go
  storagenode/storagenodedb/migrations_test.go
  storagenode/storagenodedb/storagenodedbtest/run.go
  storagenode/storagenodedb/storagenodedbtest/run_test.go
Labels: Request Code Review, cla-signed

#2989 satellite/overlay: don't use transport observers
  satellite/overlay/service.go
Labels: Request Code Review, cla-signed

#3078 internal/dbutil/sqliteutil: Fix error handling, ensure connections are closed
  internal/dbutil/sqliteutil/migrator.go
  internal/dbutil/sqliteutil/migrator_test.go
Labels: cla-signed

#2338 internal/testplanet: enable TestUplinksParallel
  internal/testplanet/uplink_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3091 web/satellite: eye icon fits lastpass
  web/satellite/src/components/common/HeaderlessInput.vue
  web/satellite/tests/unit/common/__snapshots__/HeaderlessInput.spec.ts.snap
Labels: cla-signed

#3093 web/satellite: new navigation area adaptation implemented
  web/satellite/src/components/account/AccountArea.vue
  web/satellite/src/components/apiKeys/ApiKeysArea.vue
  web/satellite/src/components/buckets/BucketArea.vue
  web/satellite/src/components/buckets/NoBucketsArea.vue
  web/satellite/src/components/header/AccountButton.vue
  web/satellite/src/components/header/Header.vue
  web/satellite/src/components/header/NewProjectArea.vue
  web/satellite/src/components/header/header.html
  web/satellite/src/components/header/header.scss
  web/satellite/src/components/header/projectSelection/ProjectSelectionArea.vue
  web/satellite/src/components/header/projectSelection/ProjectSelectionDropdown.vue
  web/satellite/src/components/navigation/NavigationArea.vue
  web/satellite/src/components/navigation/navigationArea.html
  web/satellite/src/components/navigation/navigationArea.scss
  web/satellite/src/components/project/ProjectDetails.vue
  web/satellite/src/components/project/ProjectOverviewArea.vue
  web/satellite/src/components/team/ProjectMembersArea.vue
  web/satellite/src/views/Dashboard.vue
  web/satellite/tests/unit/components/navigation/__snapshots__/navigationArea.spec.ts.snap
  web/satellite/tests/unit/views/__snapshots__/Dashboard.spec.ts.snap
Labels: Request Code Review, cla-signed

#3063 autoupdater: use blang/semver
  cmd/storagenode-updater/main.go
  cmd/storagenode-updater/main_test.go
  cmd/storagenode-updater/testdata/fake-storagenode
  cmd/storagenode-updater/testdata/fake-storagenode.zip
  go.mod
  go.sum
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3096 Jenkins: increase timeouts, so master with coverage has time to complete
  Dockerfile.jenkins
  Jenkinsfile.public
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3071 internal/migrate: make rebind optional
  internal/migrate/create.go
  internal/migrate/db.go
  internal/migrate/versions.go
  internal/migrate/versions_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3045 satellite/console: GraphQL input length limitation.
  satellite/console/consoleweb/server.go
  satellite/console/consoleweb/utils.go
Labels: cla-signed

#3094 Adds tests for kad replacement and restores kad operator configs
  cmd/storagenode/entrypoint
  cmd/storj-sim/network.go
  internal/testplanet/planet_test.go
  internal/testplanet/storagenode.go
  scripts/test-sim-backwards.sh
  storagenode/contact/contact_test.go
  storagenode/operator.go
  storagenode/peer.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3095 satellite/overlay: move CheckIn benchmark to overlay
  satellite/contact/benchmark_test.go
  satellite/overlay/benchmark_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3030 web: using kebab notation for props names in html
  web/satellite/src/App.vue
  web/satellite/src/components/account/AccountPaymentMethods.vue
  web/satellite/src/components/account/ChangePasswordPopup.vue
  web/satellite/src/components/account/DeleteAccountPopup.vue
  web/satellite/src/components/account/EditProfilePopup.vue
  web/satellite/src/components/account/Profile.vue
  web/satellite/src/components/account/billing/AccountBalance.vue
  web/satellite/src/components/account/billing/BillingHistory.vue
  web/satellite/src/components/apiKeys/ApiKeysArea.vue
  web/satellite/src/components/apiKeys/ApiKeysCreationPopup.vue
  web/satellite/src/components/buckets/BucketArea.vue
  web/satellite/src/components/common/Button.vue
  web/satellite/src/components/common/Checkbox.vue
  web/satellite/src/components/common/EmptyStateArea.vue
  web/satellite/src/components/common/HeaderComponent.vue
  web/satellite/src/components/common/HeaderedInput.vue
  web/satellite/src/components/common/List.vue
  web/satellite/src/components/common/PagesBlock.vue
  web/satellite/src/components/common/Pagination.vue
  web/satellite/src/components/common/SearchComponent.vue
  web/satellite/src/components/common/registrationSuccessPopup.html
  web/satellite/src/components/common/test/TestList.vue
  web/satellite/src/components/dashboard/DashboardArea.vue
  web/satellite/src/components/header/AccountButton.vue
  web/satellite/src/components/header/AccountDropdown.vue
  web/satellite/src/components/header/projectSelection/ProjectSelectionDropdown.vue
  web/satellite/src/components/navigation/navigationArea.html
  web/satellite/src/components/project/DeleteProjectPopup.vue
  web/satellite/src/components/project/NewProjectPopup.vue
  web/satellite/src/components/project/ProjectCreationSuccessPopup.vue
  web/satellite/src/components/project/ProjectDetails.vue
  web/satellite/src/components/project/ProjectOverviewArea.vue
  web/satellite/src/components/project/ProjectPaymentMethods.vue
  web/satellite/src/components/team/AddUserPopup.vue
  web/satellite/src/components/team/HeaderArea.vue
  web/satellite/src/components/team/ProjectMembersArea.vue
  web/satellite/src/components/team/SortingListHeader.vue
  web/satellite/src/views/forgotPassword/forgotPassword.html
  web/satellite/src/views/login/login.html
  web/satellite/src/views/register/register.html
  web/satellite/tests/unit/common/HeaderComponent.spec.ts
  web/satellite/tests/unit/common/PagesBlock.spec.ts
  web/satellite/tests/unit/common/SearchComponent.spec.ts
  web/satellite/tests/unit/common/__snapshots__/Pagination.spec.ts.snap
  web/storagenode/src/app/components/BandwidthChart.vue
  web/storagenode/src/app/components/ChecksAreaContainer.vue
  web/storagenode/src/app/components/DiskSpaceChart.vue
  web/storagenode/src/app/components/SNOContentFilling.vue
  web/storagenode/src/app/components/SNOContentTitle.vue
  web/storagenode/src/app/components/SatelliteSelectionDropdown.vue
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3106 Adding our new employees
  .clabot
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3100 satellite/metainfo: close loop separately to avoid logical races
  satellite/metainfo/loop.go
  satellite/metainfo/loop_test.go
  satellite/peer.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2921 Windows installer for storage nodes
  .gitignore
  installer/windows/.gitignore
  installer/windows/AllocatedBandwidthConfig.wxs
  installer/windows/AllocatedStorageConfig.wxs
  installer/windows/CustomInstallDir.wxs
  installer/windows/EmailConfig.wxs
  installer/windows/IdentityDir.wxs
  installer/windows/InstallDirConfig.wxs
  installer/windows/Product.wxs
  installer/windows/PublicAddressConfig.wxs
  installer/windows/StorageDirConfig.wxs
  installer/windows/Storj/CustomAction.config
  installer/windows/Storj/CustomAction.cs
  installer/windows/Storj/Properties/AssemblyInfo.cs
  installer/windows/Storj/Storj.csproj
  installer/windows/ValidationError.wxs
  installer/windows/WalletConfig.wxs
  installer/windows/agpl-3.0.rtf
  installer/windows/banner.bmp
  installer/windows/dialog.bmp
  installer/windows/storj.ico
  installer/windows/windows.sln
  installer/windows/windows.wixproj
Labels: Request Code Review, cla-signed

#3104 metainfo: move FinishDeleteSegment logic to BeginDeleteSegment
  satellite/metainfo/metainfo.go
  uplink/storage/segments/store.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3108 pkg/certificates: run certificate authorization endpoint
  pkg/certificate/peer.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3101 satellite/repair/checker: set erasure share size in tests
  satellite/repair/checker/checker_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3110 fix certificates auth export command
  cmd/certificates/auth.go
  scripts/test-certificates.sh
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3098 storagenode/winsvc: avoid the 15s sleep when stopping the service
  cmd/storagenode/windows.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3111 jenkins: disable flaky test-certificates
  Jenkinsfile.public
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3123 satellite/accounting/tally: ensure we have a root piece id
  satellite/accounting/tally/tally_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3119 jenkins: update golangci to v1.19.1
  .golangci.yml
  Dockerfile.jenkins
  Makefile
  cmd/storagenode-updater/windows.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3122 satellite/accounting/rollup: pause in tests
  satellite/accounting/rollup/rollup_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3126 internal/version: Change default endpoint to query
  internal/version/service.go
  scripts/testdata/satellite-config.yaml.lock
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3129 satellite/satellitedb: update node version columns in UpdateCheckIn
  satellite/overlay/service_test.go
  satellite/satellitedb/overlaycache.go
Labels: cla-signed

#3125 Make binaries smaller
  Makefile
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3124 internal/testplanet: ensure monitor chore is finished before contacting satellite
  internal/testplanet/planet.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3130 Bump go version to 1.13.1
  Dockerfile.jenkins
  Makefile
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3107 pkg/certificates: move certificate package to root
  certificate/authorization/authorizations.go
  certificate/authorization/authorizations_test.go
  certificate/authorization/db.go
  certificate/authorization/doc.go
  certificate/authorization/endpoint.go
  certificate/authorization/endpoint_test.go
  certificate/authorization/service.go
  certificate/authorization/service_test.go
  certificate/certificateclient/client.go
  certificate/certificateclient/doc.go
  certificate/doc.go
  certificate/endpoint.go
  certificate/peer.go
  certificate/peer_test.go
  cmd/certificates/auth.go
  cmd/certificates/claims.go
  cmd/certificates/main.go
  cmd/certificates/setup.go
  cmd/identity/main.go
  scripts/check-peer-constraints.go
Labels: Code Review In-Progress, Request Code Review, cla-signed

#3074 satellite/console: remove payments
  satellite/console/consoleweb/consoleql/mutation.go
  satellite/console/consoleweb/consoleql/mutation_test.go
  satellite/console/consoleweb/consoleql/project.go
  satellite/console/consoleweb/consoleql/query_test.go
  satellite/console/consoleweb/consoleql/typecreator.go
  satellite/console/database.go
  satellite/console/projectinvoicestamps.go
  satellite/console/projectinvoicestamps_test.go
  satellite/console/projectpayments.go
  satellite/console/projectpayments_test.go
  satellite/console/service.go
  satellite/console/userpayments.go
  satellite/console/userpayments_test.go
  satellite/peer.go
  satellite/satellitedb/consoledb.go
  satellite/satellitedb/locked.go
  satellite/satellitedb/projectinvoicestamps.go
  satellite/satellitedb/projectpaymentinfos.go
  satellite/satellitedb/userpayments.go
Labels: Request Code Review, cla-signed

#3113 web/satellite routing updated, tests added
  web/satellite/package.json
  web/satellite/src/router/index.ts
  web/satellite/src/store/modules/usage.ts
  web/satellite/src/views/DashboardArea.vue
  web/satellite/tests/unit/components/navigation/navigationArea.spec.ts
  web/satellite/tests/unit/mock/api/apiKeys.ts
  web/satellite/tests/unit/mock/api/buckets.ts
  web/satellite/tests/unit/mock/api/projects.ts
  web/satellite/tests/unit/mock/api/usage.ts
  web/satellite/tests/unit/views/DashboardArea.spec.ts
Labels: Request Code Review, cla-signed

#3135 Fix go build -s -w
  Makefile
  scripts/release.sh
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3132 internal/testplanet: fix conn leak
  internal/testplanet/planet_test.go
  pkg/kademlia/kademliaclient/kademliaclient_test.go
  storagenode/contact/contact_test.go
  storagenode/contact/service.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3090 satellite/console: Added support URLs and other fields to config file
  satellite/console/consoleweb/consoleql/mail.go
  satellite/console/consoleweb/consoleql/mutation.go
  satellite/console/consoleweb/consoleql/mutation_test.go
  satellite/console/consoleweb/consoleql/query.go
  satellite/console/consoleweb/consoleql/query_test.go
  satellite/console/consoleweb/server.go
  scripts/testdata/satellite-config.yaml.lock
  web/satellite/static/emails/Forgot.html
  web/satellite/static/emails/Invite.html
  web/satellite/static/emails/Welcome.html
Labels: Request Code Review, cla-signed

#3054 web/satellite: payment methods markup
  web/satellite/src/App.vue
  web/satellite/src/components/account/billing/BillingArea.vue
  web/satellite/src/components/account/billing/CardComponent.vue
  web/satellite/src/components/account/billing/CardDialog.vue
  web/satellite/src/components/account/billing/PaymentMethods.vue
  web/satellite/src/components/account/billing/StorjInput.vue
  web/satellite/src/components/account/billing/StripeInput.vue
  web/satellite/src/components/project/DatePicker.vue
  web/satellite/src/store/modules/appState.ts
  web/satellite/src/store/mutationConstants.ts
  web/satellite/src/types/payments.ts
  web/satellite/src/utils/constants/actionNames.ts
  web/satellite/src/utils/constants/billingEnums.ts
  web/satellite/static/images/payments/Dialog.svg
Labels: cla-signed

#3131 storagenode/dashboard: change etherscan link to open ERC-20 transactions
  web/storagenode/src/app/components/PayoutContainer.vue
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3116 build: add support for FreeBSD on AMD64
  Makefile
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3115 satellite/audit: delete nodes from containment when segment has changed
  satellite/audit/reverify_test.go
  satellite/audit/verifier.go
  satellite/metainfo/metainfo.go
  satellite/peer.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3141 Add AlexeyALeonov to CLA list
  .clabot
Labels: Request Code Review, Reviewer Can Merge, cla-signed
