Repository storj/storj, pull requests merged in 2019-04, with the labels that each got.

#1622 Don't crash on audit and repair failures
  pkg/audit/service.go
  pkg/datarepair/checker/checker.go
Labels: cla-signed

#1623 Add Fadila to CLA list
  .clabot
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1624 Moved templates and styles for Login, Register and Navigation
  web/satellite/src/components/header/AccountDropdown.vue
  web/satellite/src/components/header/Header.vue
  web/satellite/src/components/navigation/NavigationArea.vue
  web/satellite/src/components/navigation/navigationArea.html
  web/satellite/src/components/navigation/navigationArea.scss
  web/satellite/src/router/index.ts
  web/satellite/src/views/Login.vue
  web/satellite/src/views/Register.vue
  web/satellite/src/views/login/Login.vue
  web/satellite/src/views/login/login.html
  web/satellite/src/views/login/login.scss
  web/satellite/src/views/register/Register.vue
  web/satellite/src/views/register/register.html
  web/satellite/src/views/register/register.scss
Labels: cla-signed

#1595 record bucket data into bucket_storage_tally table
  pkg/accounting/bucketstats.go
  pkg/accounting/db.go
  pkg/accounting/tally/tally.go
  satellite/satellitedb/accounting.go
  satellite/satellitedb/dbx/satellitedb.dbx
  satellite/satellitedb/dbx/satellitedb.dbx.go
  satellite/satellitedb/locked.go
Labels: Request Code Review, cla-signed

#1632 Set last_contact_success when a node is initially added to overlay cache
  satellite/satellitedb/dbx/satellitedb.dbx
  satellite/satellitedb/dbx/satellitedb.dbx.go
  satellite/satellitedb/overlaycache.go
Labels: cla-signed

#1633 adds defer close for node conn in audit verifier
  pkg/audit/verifier.go
Labels: cla-signed

#1617 fixes infinite loop in audit TestVerifierHappyPath
  pkg/audit/cursor_test.go
  pkg/audit/newverifier_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1612 Add Semantic Versioning and refuses outdated Software from Startup
  Makefile
  bootstrap/peer.go
  cmd/bootstrap/main.go
  cmd/gateway/main.go
  cmd/release/main.go
  cmd/satellite/main.go
  cmd/storagenode/dashboard.go
  cmd/storagenode/main.go
  cmd/storj-sim/network.go
  cmd/uplink/cmd/mount.go
  cmd/version-control/config.json.example
  cmd/version-control/main.go
  cmd/versioncontrol/main.go
  cmd/versioncontrol/version-control.service
  internal/testplanet/planet.go
  internal/version/client.go
  internal/version/service.go
  internal/version/version.go
  pkg/certificates/certificates_test.go
  pkg/kademlia/kademlia_test.go
  pkg/process/debug.go
  pkg/process/exec.go
  pkg/transport/slowtransport.go
  pkg/transport/transport.go
  satellite/peer.go
  storagenode/peer.go
  uplink/config.go
  versioncontrol/peer.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1628 migration tests for storagenodedb infodb
  storagenode/storagenodedb/bandwidthdb.go
  storagenode/storagenodedb/certdb.go
  storagenode/storagenodedb/database.go
  storagenode/storagenodedb/infodb.go
  storagenode/storagenodedb/migrations_test.go
  storagenode/storagenodedb/orders.go
  storagenode/storagenodedb/pieceinfo.go
  storagenode/storagenodedb/testdata/sqlite.v0.sql
  storagenode/storagenodedb/usedserials.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1635 skips flaky TestGetShareTimeout
  pkg/audit/timeout_test.go
Labels: cla-signed

#1627 Web forgot password flow markup
  web/satellite/src/router/index.ts
  web/satellite/src/utils/constants/routerConstants.ts
  web/satellite/src/views/forgotPassword/ForgotPassword.vue
  web/satellite/src/views/forgotPassword/forgotPassword.html
  web/satellite/src/views/forgotPassword/forgotPassword.scss
  web/satellite/static/emails/Forgot.html
  web/satellite/static/resetPassword/resetPassword.css
  web/satellite/static/resetPassword/resetPassword.html
Labels: cla-signed

#1636 Adding Travis CI build status icon to the README.
  README.md
Labels: Request Code Review, cla-signed

#1546 API endpoint checking object and segment health from the satellite
  cmd/inspector/main.go
  go.mod
  go.sum
  pkg/pb/inspector.pb.go
  pkg/pb/inspector.proto
  satellite/inspector/inspector.go
  satellite/inspector/inspector_test.go
  satellite/metainfo/metainfo.go
  satellite/peer.go
Labels: Request Code Review, cla-signed

#1589 Change crypto/rand to use math/rand in pgutil
  internal/dbutil/pgutil/db.go
  internal/dbutil/pgutil/schema.go
  internal/migrate/create_test.go
  internal/migrate/versions_test.go
  internal/testplanet/run.go
  satellite/satellitedb/migrate_postgres_test.go
  satellite/satellitedb/satellitedbtest/run.go
Labels: Request Code Review, cla-signed

#1645 skips flaky verifier happy path test
  pkg/audit/newverifier_test.go
Labels: cla-signed

#1606 libuplink: OpenObject, UploadObject, DownloadRange
  lib/uplink/bucket.go
  lib/uplink/object.go
Labels: cla-signed

#1561 project usage limiting
  internal/testplanet/planet.go
  pkg/accounting/bucketusage.go
  pkg/accounting/db.go
  pkg/accounting/projectusage.go
  pkg/accounting/projectusage_test.go
  pkg/accounting/rollup/rollup.go
  satellite/metainfo/metainfo.go
  satellite/orders/endpoint.go
  satellite/orders/orders_test.go
  satellite/peer.go
  satellite/satellitedb/accounting.go
  satellite/satellitedb/dbx/satellitedb.dbx
  satellite/satellitedb/dbx/satellitedb.dbx.go
  satellite/satellitedb/dbx/satellitedb.dbx.postgres.sql
  satellite/satellitedb/dbx/satellitedb.dbx.sqlite3.sql
  satellite/satellitedb/locked.go
  satellite/satellitedb/migrate.go
  satellite/satellitedb/orders.go
  satellite/satellitedb/testdata/postgres.v13.sql
Labels: Code Review In-Progress, Reviewer Can Merge, cla-signed

#1644 update some packages so we don't depend on launchpad
  go.mod
  go.sum
Labels: cla-signed

#1409 Web usage report markup
  web/bootstrap/src/App.vue
  web/bootstrap/src/views/Failure.vue
  web/bootstrap/src/views/Loading.vue
  web/bootstrap/src/views/Search.vue
  web/bootstrap/src/views/Success.vue
  web/satellite/package.json
  web/satellite/src/components/project/DatePicker.vue
  web/satellite/src/components/project/ProjectDetailsArea.vue
  web/satellite/src/components/project/ReportTable.vue
  web/satellite/src/components/project/UsageReport.vue
  web/satellite/src/router/index.ts
  web/satellite/src/utils/constants/routerConstants.ts
  web/satellite/static/images/projectDetails/UsageReport.svg
  web/satellite/webpack.config.dev.js
Labels: cla-signed

#1638 plumb EncryptionScheme, RedundancyScheme through to buckets
  pkg/metainfo/kvmetainfo/buckets.go
  pkg/metainfo/kvmetainfo/objects.go
  pkg/storage/buckets/store.go
  pkg/storage/objects/store.go
  pkg/storage/segments/store.go
  pkg/storage/streams/store.go
  pkg/storage/streams/store_test.go
  pkg/storj/object.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1646 Delete accounting raws after rollup
  pkg/accounting/rollup/rollup.go
  pkg/accounting/rollup/rollup_test.go
  pkg/accounting/tally/tally_test.go
Labels: cla-signed

#1568 libuplink changes for public usage
  lib/uplink/access.go
  lib/uplink/apikey.go
  lib/uplink/bucket.go
  lib/uplink/buckets.go
  lib/uplink/common.go
  lib/uplink/doc.go
  lib/uplink/encryption.go
  lib/uplink/libuplink_test.go
  lib/uplink/main.go
  lib/uplink/object.go
  lib/uplink/objects.go
  lib/uplink/project.go
  lib/uplink/uplink.go
  pkg/metainfo/kvmetainfo/buckets.go
  pkg/metainfo/kvmetainfo/metainfo.go
  pkg/metainfo/kvmetainfo/project.go
  pkg/storj/encryption.go
  pkg/storj/redundancy.go
Labels: Reviewer Can Merge, cla-signed

#1650 Fix repair order limit creation
  satellite/orders/service.go
Labels: Bug, Request Code Review, cla-signed

#1634 adds defer close for node conn in audit verifier
  pkg/audit/verifier.go
Labels: cla-signed

#1554 extension serialization
  cmd/identity/batch.go
  cmd/identity/certificate_authority.go
  cmd/identity/identity.go
  cmd/identity/revocations.go
  internal/testidentity/identity.go
  internal/testpeertls/certificates.go
  internal/testpeertls/revocations.go
  pkg/identity/cert_authority_test.go
  pkg/identity/certificate_authority.go
  pkg/identity/identity.go
  pkg/identity/identity_test.go
  pkg/peertls/extensions/extensions.go
  pkg/peertls/extensions/extensions_test.go
  pkg/peertls/extensions/revocations.go
  pkg/peertls/extensions/revocations_test.go
  pkg/peertls/peertls.go
  pkg/peertls/peertls_test.go
  pkg/peertls/tlsopts/options.go
  pkg/peertls/tlsopts/tls_test.go
  pkg/peertls/utils.go
  pkg/pkcrypto/encoding.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1655 Storj branding changes
  web/satellite/src/components/navigation/navigationArea.html
  web/satellite/src/views/forgotPassword/forgotPassword.html
  web/satellite/src/views/forgotPassword/forgotPassword.scss
  web/satellite/src/views/login/login.html
  web/satellite/src/views/login/login.scss
  web/satellite/src/views/register/register.html
  web/satellite/src/views/register/register.scss
  web/satellite/static/images/AuthImage.svg
  web/satellite/static/images/Logo.svg
  web/satellite/static/images/Mars.png
  web/satellite/static/resetPassword/resetPassword.css
  web/satellite/static/resetPassword/resetPassword.html
Labels: cla-signed

#1653 Add ca-certificates to satellite docker-image so mail works
  cmd/satellite/Dockerfile
Labels: cla-signed

#1590 Forward port Bill and Stefan's changes to master
  pkg/audit/verifier.go
  pkg/piecestore/psserver/psdb/psdb.go
  pkg/piecestore/psserver/psdb/testdata/sqlite.v4.sql
Labels: WIP, cla-signed

#1576 Add Versioning Server
  Makefile
  bootstrap/peer.go
  cmd/bootstrap/main.go
  cmd/gateway/main.go
  cmd/satellite/main.go
  cmd/storagenode/dashboard.go
  cmd/storagenode/main.go
  cmd/storj-sim/network.go
  cmd/uplink/cmd/mount.go
  cmd/versioncontrol/main.go
  cmd/versioncontrol/version-control.service
  internal/testplanet/planet.go
  internal/version/service.go
  internal/version/version.go
  pkg/certificates/certificates_test.go
  pkg/kademlia/kademlia_test.go
  pkg/process/debug.go
  pkg/process/exec.go
  pkg/transport/slowtransport.go
  pkg/transport/transport.go
  satellite/peer.go
  scripts/release.sh
  storagenode/peer.go
  uplink/config.go
  versioncontrol/peer.go
Labels: Request Code Review, cla-signed

#1544 Adds the AMD64 and ARM Storagenode Dockerfiles and setup scripts
  cmd/storagenode/alpha/amd64.Dockerfile
  cmd/storagenode/alpha/arm.Dockerfile
  cmd/storagenode/alpha/dashboard.sh
  cmd/storagenode/alpha/entrypoint.sh
  cmd/storagenode/alpha/setup.sh
Labels: cla-signed

#1557 Fix repairer unit test
  pkg/storage/segments/repairer_test.go
Labels: Do Not Merge, Request Code Review, cla-signed

#1607 Cert creation clarity
  cmd/identity/batch.go
  internal/testpeertls/certificates.go
  pkg/identity/certificate_authority.go
  pkg/identity/identity.go
  pkg/identity/identity_test.go
  pkg/peertls/peertls.go
  pkg/peertls/peertls_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1656 Use sha256-simd for hashing
  go.mod
  go.sum
  pkg/pkcrypto/hashing.go
Labels: cla-signed

#1651 Add since date label in dashboard
  cmd/storagenode/dashboard.go
Labels: cla-signed

#1663 Fix UseSerialNumber panic
  internal/dbutil/pgutil/db.go
  internal/dbutil/sqliteutil/db.go
  satellite/orders/endpoint.go
  satellite/satellitedb/orders.go
  satellite/satellitedb/orders_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1664 Console usage rollup api
  bootstrap/bootstrapweb/bootstrapserver/bootstrapql/schema.go
  go.mod
  go.sum
  internal/storjql/schema.go
  satellite/console/consoleweb/consoleql/apikey.go
  satellite/console/consoleweb/consoleql/mutation.go
  satellite/console/consoleweb/consoleql/project.go
  satellite/console/consoleweb/consoleql/projectmember.go
  satellite/console/consoleweb/consoleql/query.go
  satellite/console/consoleweb/consoleql/schema.go
  satellite/console/consoleweb/consoleql/token.go
  satellite/console/consoleweb/consoleql/typecreator.go
  satellite/console/consoleweb/consoleql/user.go
  satellite/console/database.go
  satellite/console/service.go
  satellite/console/usagerollups.go
  satellite/console/usagerollups_test.go
  satellite/satellitedb/accounting.go
  satellite/satellitedb/consoledb.go
  satellite/satellitedb/dbx/satellitedb.dbx
  satellite/satellitedb/dbx/satellitedb.dbx.go
  satellite/satellitedb/locked.go
  satellite/satellitedb/usagerollups.go
Labels: Request Code Review, cla-signed

#1618 Remove bw from tally service + query bandwidth in rollup service
  pkg/accounting/db.go
  pkg/accounting/projectusage_test.go
  pkg/accounting/rollup/rollup.go
  pkg/accounting/rollup/rollup_test.go
  pkg/accounting/tally/tally.go
  pkg/accounting/tally/tally_test.go
  satellite/orders/endpoint.go
  satellite/orders/service.go
  satellite/peer.go
  satellite/satellitedb/accounting.go
  satellite/satellitedb/dbx/satellitedb.dbx
  satellite/satellitedb/dbx/satellitedb.dbx.go
  satellite/satellitedb/locked.go
  satellite/satellitedb/orders.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1666 internal/version: do version checks much earlier in the process initialization, take 2
  bootstrap/peer.go
  cmd/bootstrap/main.go
  cmd/identity/main.go
  cmd/satellite/main.go
  cmd/storagenode/main.go
  internal/version/service.go
  satellite/peer.go
  storagenode/peer.go
Labels: cla-signed

#1657 update ProjectStorageTotals func to get all records for project
  pkg/accounting/projectusage_test.go
  satellite/satellitedb/accounting.go
Labels: WIP, cla-signed

#1626 Introduce NodeDossier type and cleanup overlay.DB interface
  cmd/satellite/usage.go
  internal/testplanet/uplink_test.go
  pkg/audit/newverifier_test.go
  pkg/audit/timeout_test.go
  pkg/discovery/service.go
  pkg/discovery/service_test.go
  pkg/metainfo/kvmetainfo/objects_test.go
  pkg/overlay/cache.go
  pkg/overlay/cache_test.go
  pkg/overlay/inspector.go
  pkg/overlay/statdb_test.go
  pkg/pb/node.pb.go
  pkg/pb/node.proto
  pkg/storage/segments/repairer_test.go
  pkg/storj/node.go
  satellite/satellitedb/locked.go
  satellite/satellitedb/overlaycache.go
Labels: cla-signed

#1667 fixed test on windows
  storagenode/piecestore/endpoint_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1649 Filehealth cli
  cmd/inspector/main.go
  pkg/pb/inspector.pb.go
  pkg/pb/inspector.proto
  satellite/inspector/inspector.go
  satellite/inspector/inspector_test.go
Labels: Request Code Review, cla-signed

#1580 Enable uplink TestDownloadWithSomeNodesOffline
  internal/testplanet/uplink_test.go
Labels: Do Not Merge, WIP, cla-signed

#1668 Add Version Information into KAD Network and SatelliteDB & Change Selection Process (release-alpha8)
  .travis.yml
  bootstrap/peer.go
  internal/testplanet/planet.go
  internal/version/version.go
  pkg/overlay/cache.go
  pkg/overlay/config.go
  pkg/overlay/inspector.go
  pkg/pb/node.pb.go
  pkg/pb/node.proto
  pkg/pb/overlay.pb.go
  pkg/pb/overlay.proto
  satellite/peer.go
  satellite/satellitedb/dbx/satellitedb.dbx
  satellite/satellitedb/dbx/satellitedb.dbx.go
  satellite/satellitedb/dbx/satellitedb.dbx.postgres.sql
  satellite/satellitedb/dbx/satellitedb.dbx.sqlite3.sql
  satellite/satellitedb/migrate.go
  satellite/satellitedb/overlaycache.go
  satellite/satellitedb/testdata/postgres.v14.sql
  scripts/release.sh
  storagenode/peer.go
Labels: cla-signed

#1673 Add Version Information for NodeStats Updates
  satellite/satellitedb/overlaycache.go
Labels: cla-signed

#1677 Add a log message that records the debug listening address and port.
  pkg/process/debug.go
Labels: Request Code Review, cla-signed

#1619 Store inline bandiwdth
  satellite/metainfo/metainfo.go
  satellite/orders/service.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1679 Fix "Number of valid pieces is lower then success threshold"
  satellite/metainfo/metainfo.go
Labels: cla-signed

#1669 add project usage to web app
  web/satellite/src/api/usage.ts
  web/satellite/src/components/project/UsageReport.vue
  web/satellite/src/store/index.ts
  web/satellite/src/store/modules/usage.ts
  web/satellite/src/store/mutationConstants.ts
  web/satellite/src/types/projects.d.ts
  web/satellite/src/utils/constants/actionNames.ts
  web/satellite/src/views/Dashboard.vue
Labels: Request Code Review, cla-signed

#1678 Replace 'localhost' with '127.0.0.1' in defaults
  cmd/bootstrap/main.go
  cmd/gateway/main.go
  pkg/miniogw/config.go
  pkg/process/debug.go
  uplink/config.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1682 Satellite frontned empty states
  satellite/console/service.go
  web/satellite/src/api/apiKeys.ts
  web/satellite/src/api/projectMembers.ts
  web/satellite/src/api/projects.ts
  web/satellite/src/api/users.ts
  web/satellite/src/components/account/DeleteAccountPopup.vue
  web/satellite/src/components/apiKeys/AddApiKeyPopup.vue
  web/satellite/src/components/header/NewProjectArea.vue
  web/satellite/src/components/header/projectSelection/ProjectSelectionArea.vue
  web/satellite/src/components/navigation/NavigationArea.vue
  web/satellite/src/components/navigation/navigationArea.html
  web/satellite/src/components/navigation/navigationArea.scss
  web/satellite/src/components/project/DatePicker.vue
  web/satellite/src/components/project/DeleteProjectPopup.vue
  web/satellite/src/components/project/NewProjectPopup.vue
  web/satellite/src/components/project/ProjectDetailsArea.vue
  web/satellite/src/components/team/AddUserPopup.vue
  web/satellite/src/components/team/headerArea/SearchArea.vue
  web/satellite/src/router/index.ts
  web/satellite/src/store/modules/appState.ts
  web/satellite/src/store/modules/notifications.ts
  web/satellite/src/store/modules/projectMembers.ts
  web/satellite/src/store/modules/projects.ts
  web/satellite/src/store/mutationConstants.ts
  web/satellite/src/utils/apolloManager.ts
  web/satellite/src/utils/constants/actionNames.ts
  web/satellite/src/utils/constants/appStateEnum.ts
  web/satellite/src/utils/constants/navigationLinks.ts
  web/satellite/src/views/Dashboard.vue
  web/satellite/src/views/login/Login.vue
  web/satellite/static/images/register/Loading.gif
  web/satellite/tsconfig.json
  web/satellite/tslint.json
Labels: Request Code Review, WIP, cla-signed

#1695 Use go 1.12.1 for compiling in Travis
  .travis.yml
Labels: cla-signed

#1693 Adding Ivan to the CLA bot
  .clabot
Labels: cla-signed

#1692 dashboard change last contact never into offline
  cmd/storagenode/dashboard.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1694 web interface small word fixes
  web/satellite/src/components/apiKeys/CopyApiKeyPopup.vue
  web/satellite/src/components/header/AccountDropdown.vue
Labels: cla-signed

#1688 Add LE CA to satellite and storagenode images
  cmd/satellite/Dockerfile
  cmd/storagenode/Dockerfile
  resources/certs.pem
Labels: Request Code Review, cla-signed

#1696 Fixed initial team members fetch on login.
  web/satellite/src/views/Dashboard.vue
Labels: cla-signed

#1698 returns an error if tx.Get_Node_By_Id returns nil node
  satellite/satellitedb/overlaycache.go
Labels: cla-signed

#1389 Identity versioning
  cmd/identity/batch.go
  cmd/identity/main.go
  internal/debugging/certificates.go
  internal/testidentity/V1_identities_table.go
  internal/testidentity/V1_signed_identities_table.go
  internal/testidentity/gen_identities.go
  internal/testidentity/identities.go
  internal/testidentity/identity.go
  internal/testidentity/pregenerated_identities_test.go
  internal/testpeertls/certificates.go
  internal/testpeertls/certificates_test.go
  internal/testpeertls/revocations.go
  internal/testplanet/identities_table.go
  internal/testplanet/planet.go
  internal/testplanet/planet_test.go
  internal/testplanet/signed_identities_table.go
  internal/testplanet/uplink.go
  pkg/auth/signedMessage.go
  pkg/bwagreement/server_test.go
  pkg/certificates/certificates.go
  pkg/certificates/certificates_test.go
  pkg/identity/certificate_authority.go
  pkg/identity/certificate_authority_test.go
  pkg/identity/generate.go
  pkg/identity/identity.go
  pkg/identity/identity_test.go
  pkg/identity/revocation_db.go
  pkg/identity/revocation_db_test.go
  pkg/kademlia/kademlia_test.go
  pkg/peertls/extensions/extensions.go
  pkg/peertls/extensions/extensions_test.go
  pkg/peertls/extensions/revocations_test.go
  pkg/peertls/peertls.go
  pkg/peertls/peertls_test.go
  pkg/peertls/tlsopts/config.go
  pkg/peertls/tlsopts/options.go
  pkg/peertls/tlsopts/options_test.go
  pkg/peertls/tlsopts/tls.go
  pkg/peertls/tlsopts/tls_test.go
  pkg/storj/identity_version.go
  pkg/storj/identity_version_test.go
  pkg/storj/node.go
  pkg/storj/node_test.go
  pkg/storj/pieceid_test.go
  pkg/transport/transport_test.go
  storagenode/bandwidth/db_test.go
  storagenode/orders/db_test.go
  storagenode/pieces/db_test.go
  storagenode/pieces/store_test.go
  storagenode/piecestore/serials_test.go
  storagenode/piecestore/verification_test.go
  storagenode/storagenodedb/certdb.go
  storagenode/trust/certdb_test.go
Labels: Request Code Review, cla-signed

#1701 adds what and why prompts to pr template
  .github/pull_request_template.md
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1705 Fix data repair checker missing pieces list
  pkg/datarepair/checker/checker.go
  pkg/datarepair/datarepair_test.go
Labels: Request Code Review, cla-signed

#1686 Build multiarch ARM32v6 and AMD64 images
  .dockerignore
  Makefile
  cmd/storagenode/Dockerfile
  cmd/storagenode/entrypoint
Labels: Request Code Review, cla-signed

#1699 Don't cancel fetching peer identity context when request is cancelled
  storagenode/trust/service.go
  storagenode/trust/service_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1702 Satellite inspector should show online node count, no overlay size
  satellite/inspector/inspector.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1700 use allocated instead of settled
  pkg/accounting/db.go
  pkg/accounting/projectusage.go
  pkg/accounting/projectusage_test.go
  satellite/metainfo/metainfo.go
  satellite/satellitedb/accounting.go
  satellite/satellitedb/locked.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1712 logs dbx constraint violation error
  satellite/satellitedb/dbx/gen.go
Labels: cla-signed

#1684 Copyrights and design changes, search inputs changed
  web/satellite/src/components/account/DeleteAccountPopup.vue
  web/satellite/src/components/apiKeys/AddApiKeyPopup.vue
  web/satellite/src/components/apiKeys/ApiKeysArea.vue
  web/satellite/src/components/apiKeys/CopyApiKeyPopup.vue
  web/satellite/src/components/apiKeys/headerArea/SearchArea.vue
  web/satellite/src/components/common/Button.vue
  web/satellite/src/components/common/EmptyStateArea.vue
  web/satellite/src/components/common/RegistrationSuccessPopup.vue
  web/satellite/src/components/header/AccountDropdown.vue
  web/satellite/src/components/header/NewProjectArea.vue
  web/satellite/src/components/notifications/NotificationArea.vue
  web/satellite/src/components/project/DeleteProjectPopup.vue
  web/satellite/src/components/project/NewProjectPopup.vue
  web/satellite/src/components/project/ProjectDetailsArea.vue
  web/satellite/src/components/project/UsageReport.vue
  web/satellite/src/components/team/AddUserPopup.vue
  web/satellite/src/components/team/TeamArea.vue
  web/satellite/src/components/team/headerArea/SearchArea.vue
  web/satellite/src/components/team/headerArea/SortDropdown.vue
  web/satellite/src/utils/constants/classConstants.ts
  web/satellite/src/views/login/Login.vue
  web/satellite/src/views/login/login.html
  web/satellite/src/views/login/login.scss
  web/satellite/src/views/register/register.html
  web/satellite/src/views/register/register.scss
  web/satellite/static/activation/success.html
  web/satellite/static/images/LogoWhite.svg
Labels: cla-signed

#1704 upload, download and delete success message on log level info
  storagenode/piecestore/endpoint.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1647 Added error logging to account activation handler
  satellite/console/consoleweb/consoleql/mutation.go
  satellite/console/consoleweb/server.go
Labels: cla-signed

#1721 Identity versioning fix
  cmd/identity/certificate_authority.go
  internal/testidentity/V0_identities_table.go
  internal/testidentity/V0_signed_identities_table.go
  internal/testidentity/V1_identities_table.go
  internal/testidentity/V1_signed_identities_table.go
  internal/testidentity/identities.go
  internal/testidentity/identity.go
  internal/testplanet/planet.go
  internal/testplanet/uplink.go
  lib/uplink/uplink.go
  pkg/certificates/certificates_test.go
  pkg/identity/identity.go
  pkg/identity/identity_test.go
  pkg/kademlia/kademlia_test.go
  pkg/peertls/tlsopts/options_test.go
  pkg/peertls/tlsopts/tls_test.go
  pkg/storj/identity_version.go
  pkg/storj/identity_version_test.go
  pkg/storj/node.go
  pkg/storj/node_test.go
  pkg/transport/transport_test.go
Labels: Request Code Review, cla-signed

#1719 fix createBucketID bug in repair
  pkg/storage/segments/repairer.go
Labels: cla-signed

#1708 convert times to UTC before entering as utimestamp
  pkg/accounting/projectusage_test.go
  pkg/accounting/rollup/rollup.go
  pkg/accounting/tally/tally.go
  satellite/orders/endpoint.go
  satellite/orders/orders_test.go
  satellite/orders/service.go
  satellite/satellitedb/orders_test.go
Labels: cla-signed

#1722 add error in ec client Repair() if not enough successful nodes by end
  pkg/storage/ec/client.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1706 Console add bucket usage report
  satellite/console/consoleweb/consoleql/project.go
  satellite/console/consoleweb/server.go
  satellite/console/service.go
  satellite/console/usagerollups.go
  satellite/satellitedb/locked.go
  satellite/satellitedb/usagerollups.go
  web/satellite/src/api/usage.ts
  web/satellite/src/components/project/ReportTable.vue
  web/satellite/src/components/project/UsageReport.vue
  web/satellite/src/router/index.ts
  web/satellite/src/store/modules/usage.ts
  web/satellite/src/types/projects.d.ts
  web/satellite/src/utils/constants/routerConstants.ts
  web/satellite/static/reports/UsageReport.html
Labels: Request Code Review, cla-signed

#1715 V3-1399 Error messages
  satellite/console/apikeys.go
  satellite/console/auth.go
  satellite/console/service.go
  satellite/console/validation.go
  web/satellite/src/components/apiKeys/footerArea/DeleteApiKeysArea.vue
  web/satellite/src/components/project/DeleteProjectPopup.vue
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1720 storj-sim: add option to print a single variable
  cmd/storj-sim/main.go
  cmd/storj-sim/network.go
Labels: cla-signed

#1727 disable datarepair test for now
  pkg/datarepair/datarepair_test.go
Labels: cla-signed

#1726 Forward-port release-alpha8 build script issues
  .dockerignore
  cmd/storagenode/alpha/amd64.Dockerfile
  scripts/release.sh
Labels: cla-signed

#1728 skip more data repair tests :(
  pkg/datarepair/checker/checker_test.go
Labels: cla-signed

#1648 Add Version Information into KAD Network and SatelliteDB & Change Selection Process
  bootstrap/peer.go
  internal/testplanet/planet.go
  internal/version/version.go
  pkg/discovery/service.go
  pkg/kademlia/endpoint.go
  pkg/kademlia/inspector.go
  pkg/overlay/cache.go
  pkg/overlay/config.go
  pkg/overlay/statdb_test.go
  pkg/pb/inspector.pb.go
  pkg/pb/inspector.proto
  pkg/pb/node.pb.go
  pkg/pb/node.proto
  pkg/pb/overlay.pb.go
  pkg/pb/overlay.proto
  satellite/peer.go
  satellite/satellitedb/dbx/satellitedb.dbx
  satellite/satellitedb/dbx/satellitedb.dbx.go
  satellite/satellitedb/dbx/satellitedb.dbx.postgres.sql
  satellite/satellitedb/dbx/satellitedb.dbx.sqlite3.sql
  satellite/satellitedb/locked.go
  satellite/satellitedb/migrate.go
  satellite/satellitedb/overlaycache.go
  satellite/satellitedb/testdata/postgres.v14.sql
  scripts/release.sh
  storagenode/peer.go
Labels: Request Code Review, cla-signed

#1685 add ability to inspect version to all binaries
  internal/version/service.go
  internal/version/stats.go
  internal/version/version.go
  pkg/process/debug.go
  pkg/process/exec_conf.go
  pkg/process/metrics.go
  scripts/release.sh
Labels: cla-signed

#1718 fix potential truncation of int64
  cmd/uplink/cmd/cp.go
  internal/memory/size.go
  internal/testcontext/context.go
  lib/uplink/uplink.go
Labels: cla-signed

#1725 use one testplanet where we can
  internal/testplanet/uplink_test.go
  pkg/kademlia/dialer_test.go
Labels: cla-signed

#1515 tlsopts: fix helper
  pkg/peertls/tlsopts/options.go
  pkg/peertls/tlsopts/options_internal_test.go
Labels: cla-signed

#1707 Uplink CLI setup wizard
  cmd/uplink/cmd/root.go
  cmd/uplink/cmd/setup.go
Labels: Request Code Review, cla-signed

#1709 remove limits from certificate auth info and export subcommands
  pkg/certificates/certificates.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1730 add custom tparse that doesn't stall
  .travis.yml
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1733 remove fmt print statements
  pkg/peertls/tlsopts/tls.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1734 optimizes deleting obsolete paths
  pkg/piecestore/psserver/psdb/psdb.go
Labels: cla-signed

#1736 no longer includes totalUsedSpaceOld when calculating storagenode used space
  storagenode/inspector/inspector.go
Labels: cla-signed

#1723 Added smarter logic to uplink CLI to add defaults to satellite-addr
  cmd/uplink/cmd/setup.go
  cmd/uplink/cmd/setup_test.go
  uplink/config.go
Labels: Request Code Review, cla-signed

#1662 Tests for upload/download in parallel
  internal/testplanet/uplink_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1665 Implemented password reset on satellite console web.
  satellite/console/consoleweb/consoleql/mail.go
  satellite/console/consoleweb/consoleql/query.go
  satellite/console/consoleweb/consoleql/query_test.go
  satellite/console/consoleweb/consoleql/typecreator.go
  satellite/console/consoleweb/server.go
  satellite/console/service.go
  web/satellite/src/api/users.ts
  web/satellite/src/components/team/TeamArea.vue
  web/satellite/src/store/modules/projectMembers.ts
  web/satellite/src/views/forgotPassword/ForgotPassword.vue
  web/satellite/src/views/forgotPassword/forgotPassword.html
  web/satellite/src/views/login/Login.vue
  web/satellite/src/views/login/login.html
  web/satellite/static/emails/Forgot.html
  web/satellite/static/resetPassword/resetPassword.css
  web/satellite/static/resetPassword/resetPassword.html
Labels: Request Code Review, cla-signed

#1658 use SerializableMeta to store bucket attributes
  lib/uplink/bucket.go
  lib/uplink/bucket_attrs_test.go
  lib/uplink/object.go
  lib/uplink/project.go
  lib/uplink/uplink.go
  pkg/metainfo/kvmetainfo/buckets.go
  pkg/metainfo/kvmetainfo/buckets_test.go
  pkg/metainfo/kvmetainfo/metainfo.go
  pkg/metainfo/kvmetainfo/objects.go
  pkg/metainfo/kvmetainfo/project.go
  pkg/miniogw/gateway_test.go
  pkg/storage/buckets/store.go
  pkg/storage/ec/client.go
  pkg/storage/objects/store.go
  pkg/storage/segments/store.go
  pkg/storage/streams/store.go
  pkg/storage/streams/store_test.go
  pkg/storj/object.go
  uplink/config.go
Labels: cla-signed

#1731 Web minor fixes for deploy
  web/satellite/index.html
  web/satellite/src/App.vue
  web/satellite/src/components/apiKeys/ApiKeysArea.vue
  web/satellite/src/components/common/EmptyStateArea.vue
  web/satellite/src/components/common/RegistrationSuccessPopup.vue
  web/satellite/src/components/common/registrationSuccessPopup.html
  web/satellite/src/components/errors/Page404.vue
  web/satellite/src/components/errors/Page50X.vue
  web/satellite/src/components/errors/page40X.html
  web/satellite/src/components/errors/page50X.html
  web/satellite/src/components/header/AccountDropdown.vue
  web/satellite/src/components/header/Header.vue
  web/satellite/src/components/header/NewProjectArea.vue
  web/satellite/src/components/navigation/navigationArea.html
  web/satellite/src/components/project/DatePicker.vue
  web/satellite/src/components/project/NewProjectPopup.vue
  web/satellite/src/components/project/UsageReport.vue
  web/satellite/src/utils/constants/navigationLinks.ts
  web/satellite/src/views/Dashboard.vue
  web/satellite/src/views/forgotPassword/ForgotPassword.vue
  web/satellite/src/views/forgotPassword/forgotPassword.html
  web/satellite/src/views/login/login.html
  web/satellite/src/views/register/register.html
Labels: cla-signed

#1741 update linter to v1.16
  .travis.yml
  Makefile
  internal/dbutil/pgutil/query.go
  pkg/certificates/certificates.go
  satellite/satellitedb/certdb.go
  storage/common.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1744 Allow the satellite to connect to other mail servers
  cmd/satellite/Dockerfile
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1747 Remove GIF from Template that does not work correctly
  .github/pull_request_template.md
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1746 Set Default Node Type to invalid, to avoid cache issues
  satellite/satellitedb/migrate.go
  satellite/satellitedb/testdata/postgres.v15.sql
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1745 don't cache failed satellite certificate fetch attempt
  storagenode/piecestore/verification.go
  storagenode/trust/service.go
  storagenode/trust/service_test.go
Labels: cla-signed

#1676 Build with the release script
  Makefile
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1751 Fixing upload and build binaries
  Makefile
  scripts/release.sh
Labels: cla-signed

#1753 Fix download when missing piece
  pkg/eestream/decode.go
Labels: Request Code Review, cla-signed

#1754 tparse: switch back to tracking main branch
  .travis.yml
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1527 Piecestore space and bandwidth allocation check
  internal/testplanet/planet.go
  storagenode/bandwidth/usage.go
  storagenode/inspector/inspector.go
  storagenode/monitor/monitor.go
  storagenode/peer.go
  storagenode/piecestore/endpoint.go
  storagenode/piecestore/verification_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1758 Make tracked branch feature work with multi-arch manifests
  Makefile
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1759 Fix :latest tag, again
  Makefile
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1760 Fixing :latest tag, part iii
  Makefile
Labels: cla-signed

#1652 Migrate Minio Gateway to libuplink
  cmd/gateway/main.go
  cmd/storj-sim/network.go
  pkg/miniogw/gateway.go
  pkg/miniogw/gateway_test.go
  pkg/miniogw/integration_test.go
  pkg/miniogw/multipart.go
Labels: Request Code Review, cla-signed

#1762 uplink setup wizard uses default port, checks errors
  cmd/uplink/cmd/setup.go
  cmd/uplink/cmd/setup_test.go
Labels: cla-signed

#1761 libuplink: remove encryption key from project opening
  cmd/gateway/main.go
  lib/uplink/bucket_attrs_test.go
  lib/uplink/uplink.go
  pkg/miniogw/gateway_test.go
  pkg/miniogw/integration_test.go
Labels: cla-signed

#1766 removed commented code, removed unnecessary pointer
  pkg/datarepair/queue/queue_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1768 Clean up satellite image
  Makefile
  cmd/satellite/Dockerfile
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1752 Check context cancellation more nicely
  bootstrap/peer.go
  internal/errs2/ignore.go
  internal/sync2/limiter_test.go
  satellite/peer.go
  storagenode/peer.go
  storagenode/piecestore/endpoint.go
  versioncontrol/peer.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1770 Fix RSConfig calculation in testplanet.Uplink.GetConfig
  internal/testplanet/uplink.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1771 Move collect to a more appropriate package
  internal/errs2/collect.go
  internal/errs2/collect_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1777 Moving failure for putting pieces to Debug as this is expected behavior
  pkg/storage/ec/client.go
Labels: cla-signed

#1780 Implemented send email for support from static email.
  satellite/console/consoleweb/consoleql/mail.go
  web/satellite/src/views/login/Login.vue
  web/satellite/static/emails/Forgot.html
Labels: cla-signed

#1790 Disable pointer db logging
  satellite/peer.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1788 pkg/process: add --debug.trace-out option to binaries
  pkg/process/exec_conf.go
Labels: cla-signed

#1775 hardcode debug ports for storj-sim
  cmd/storj-sim/network.go
Labels: Request Code Review, cla-signed

#1787 pkg/cfgstruct: tie defaults to releases
  cmd/bootstrap/main.go
  cmd/certificates/main.go
  cmd/gateway/main.go
  cmd/identity/batch.go
  cmd/identity/certificate_authority.go
  cmd/identity/identity.go
  cmd/identity/main.go
  cmd/identity/revocations.go
  cmd/overlay/main.go
  cmd/satellite/main.go
  cmd/statreceiver/main.go
  cmd/storagenode/main.go
  cmd/uplink/cmd/root.go
  cmd/uplink/cmd/setup.go
  cmd/versioncontrol/main.go
  examples/grpc-debug/main.go
  internal/testplanet/uplink.go
  pkg/accounting/rollup/rollup.go
  pkg/accounting/tally/tally.go
  pkg/cfgstruct/bind.go
  pkg/cfgstruct/bind_test.go
  pkg/miniogw/integration_test.go
  pkg/piecestore/psserver/config.go
  uplink/config.go
Labels: cla-signed

#1774 Enable TestGetShareTimeout
  pkg/audit/timeout_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1732 Inspector draw routing table
  cmd/inspector/main.go
  pkg/kademlia/inspector.go
  pkg/kademlia/kademlia.go
  pkg/kademlia/routinggraph/routinggraph.go
  pkg/pb/inspector.pb.go
  pkg/pb/inspector.proto
  pkg/pb/overlay.pb.go
Labels: Request Code Review, cla-signed

#1785 Refactor pb.Node protobuf
  bootstrap/peer.go
  cmd/overlay/main.go
  internal/testplanet/planet.go
  internal/testplanet/planet_test.go
  internal/testplanet/run.go
  internal/testplanet/uplink.go
  internal/testplanet/uplink_test.go
  internal/teststorj/node.go
  lib/uplink/bucket_attrs_test.go
  pkg/audit/verifier.go
  pkg/dht/dht.go
  pkg/discovery/service.go
  pkg/kademlia/config.go
  pkg/kademlia/dialer_test.go
  pkg/kademlia/endpoint.go
  pkg/kademlia/inspector.go
  pkg/kademlia/kademlia.go
  pkg/kademlia/kademlia_planet_test.go
  pkg/kademlia/kademlia_test.go
  pkg/kademlia/peer_discovery.go
  pkg/kademlia/routing.go
  pkg/kademlia/routing_helpers_test.go
  pkg/kademlia/routing_test.go
  pkg/kademlia/testrouting/testrouting.go
  pkg/metainfo/kvmetainfo/buckets_test.go
  pkg/overlay/cache.go
  pkg/overlay/cache_test.go
  pkg/overlay/inspector.go
  pkg/overlay/selection_test.go
  pkg/overlay/statdb_test.go
  pkg/pb/node.pb.go
  pkg/pb/node.proto
  pkg/pb/utils.go
  pkg/peertls/tlsopts/options_test.go
  pkg/storage/ec/client.go
  pkg/storage/segments/store.go
  pkg/transport/transport.go
  pkg/transport/transport_test.go
  satellite/inspector/inspector_test.go
  satellite/metainfo/metainfo_test.go
  satellite/orders/orders_test.go
  satellite/orders/service.go
  satellite/peer.go
  satellite/satellitedb/locked.go
  satellite/satellitedb/overlaycache.go
  storagenode/inspector/inspector_test.go
  storagenode/monitor/monitor.go
  storagenode/monitor/monitor_test.go
  storagenode/peer.go
  storagenode/piecestore/endpoint_test.go
Labels: Request Code Review, cla-signed

#1783 removes unused queue code, moves repair queue tests to satellitedb directory
  pkg/datarepair/queue/queue.go
  satellite/satellitedb/repairqueue_test.go
  storage/common.go
  storage/redis/client_queue.go
  storage/redis/queue_test.go
  storage/testsuite/test_queue.go
Labels: cla-signed

#1776 expose identity version flag on relevant identity cli commands
  cmd/identity/main.go
  pkg/identity/certificate_authority.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1793 Skip verifier tests early
  pkg/audit/newverifier_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1779 Public Jenkins
  Dockerfile.jenkins
  Jenkinsfile.public
  scripts/test-sim.sh
  scripts/xunit.go
  storage/postgreskv/alternateclient_test.go
  storage/postgreskv/client_test.go
Labels: Request Code Review, cla-signed

#1716 repair until queue is empty
  pkg/datarepair/repairer/common.go
  pkg/datarepair/repairer/config.go
  pkg/datarepair/repairer/repairer.go
Labels: Request Code Review, cla-signed

#1798 disable other overlay services that might update online in graveyard test
  pkg/discovery/service_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1781 deletes duplicates from existing injuredsegments table
  satellite/satellitedb/migrate.go
  satellite/satellitedb/repairqueue_test.go
  satellite/satellitedb/testdata/postgres.v15.sql
Labels: cla-signed

#1799 Preserve identation in xunit output
  scripts/xunit.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1803 fix non-unique path for injured segments
  satellite/satellitedb/migrate.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1800 Updates rollup default interval to 24 hr
  pkg/accounting/rollup/rollup.go
Labels: Request Code Review, cla-signed

#1806 skips TestUploadDownloadOneUplinksInParallel and TestParallel
  internal/testplanet/uplink_test.go
  satellite/satellitedb/repairqueue_test.go
Labels: cla-signed

#1794 interface tests belong to the interface, not the implementation
  pkg/datarepair/queue/queue_test.go
  satellite/orders/serials_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1802 save raw output and output both stderr/stdin
  Jenkinsfile.public
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1796 Expose actual error from dbx
  internal/dbutil/pgutil/db.go
  internal/dbutil/sqliteutil/db.go
  internal/errs2/ignore.go
  internal/sync2/throttle_test.go
  pkg/bwagreement/server.go
  satellite/satellitedb/dbx/gen.go
  satellite/satellitedb/repairqueue.go
  storagenode/storagenodedb/certdb.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1810 remove storj-sim inmemory
  cmd/storj-sim/inmemory.go
  cmd/storj-sim/main.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1809 use postgres 11 for tests
  Dockerfile.jenkins
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1757 Change time params to UNIX timestamp in console usage-report query
  satellite/console/consoleweb/server.go
  web/satellite/src/components/project/UsageReport.vue
  web/satellite/src/utils/time.ts
Labels: Request Code Review, cla-signed

#1813 api keys change encoding to base32
  satellite/console/apikeys.go
  satellite/metainfo/metainfo.go
Labels: Backward Incompatible, Request Code Review, cla-signed

#1643 Search input and button swapped
  web/satellite/src/components/apiKeys/headerArea/HeaderArea.vue
  web/satellite/src/components/apiKeys/headerArea/SearchArea.vue
  web/satellite/src/components/team/headerArea/HeaderArea.vue
  web/satellite/src/components/team/headerArea/SearchArea.vue
  web/satellite/src/components/team/headerArea/SortUsersDropdown.vue
Labels: cla-signed

#1680 Selecting non-reputable nodes should not result in excessive selection
  pkg/overlay/cache.go
Labels: cla-signed

#1817 Merge alpha storagenode directory with main storagenode directory
  cmd/storagenode/Dockerfile
  cmd/storagenode/alpha/amd64.Dockerfile
  cmd/storagenode/alpha/arm.Dockerfile
  cmd/storagenode/alpha/entrypoint.sh
  cmd/storagenode/alpha/setup.sh
  cmd/storagenode/dashboard.sh
  cmd/storagenode/entrypoint
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1739 rollup interval fixes
  internal/testplanet/planet.go
  pkg/accounting/rollup/rollup.go
  pkg/accounting/rollup/rollup_test.go
  satellite/peer.go
Labels: Request Code Review, cla-signed

#1797 fix saving uplink public key on satellite
  internal/testplanet/uplink_test.go
  satellite/satellitedb/certdb.go
  satellite/satellitedb/dbx/gen.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#1814 updated audit configs
  internal/testplanet/planet.go
  pkg/overlay/cache.go
  pkg/overlay/cache_test.go
  pkg/overlay/config.go
  pkg/overlay/selection_test.go
  satellite/satellitedb/locked.go
  satellite/satellitedb/overlaycache.go
Labels: Request Code Review, cla-signed

#1812 Checker: invalid and offline nodes search update
  pkg/datarepair/checker/checker.go
  pkg/overlay/cache.go
  pkg/overlay/selection_test.go
  pkg/overlay/statdb_test.go
  satellite/satellitedb/locked.go
  satellite/satellitedb/overlaycache.go
Labels: cla-signed
