Repository storj/storj, pull requests merged in 2019-08, with the labels that each got.

#2682 Integrate new Metainfo calls (server side)
  pkg/pb/metainfo.pb.go
  pkg/pb/metainfo.proto
  pkg/storj/object.go
  pkg/storj/object_list_item.go
  pkg/storj/segment.go
  proto.lock
  satellite/metainfo/metainfo.go
  satellite/metainfo/metainfo_test.go
  uplink/eestream/encode.go
  uplink/metainfo/client.go
Labels: Request Code Review, cla-signed

#2676 lib/uplink: ensure it's silent by default
  cmd/gateway/main.go
  cmd/uplink/cmd/root.go
  internal/testplanet/uplink.go
  lib/uplink/bucket_attrs_test.go
  lib/uplink/ex_create_bucket_test.go
  lib/uplink/examples_test.go
  lib/uplink/list_test.go
  lib/uplink/project_test.go
  lib/uplink/uplink.go
  lib/uplinkc/project.go
  lib/uplinkc/uplink.go
  linksharing/handler_test.go
  mobile/uplink.go
  pkg/miniogw/gateway_test.go
  pkg/miniogw/integration_test.go
Labels: Request Code Review, cla-signed

#2650 Enable architectural constraints
  Jenkinsfile.public
  scripts/check-peer-constraints.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2685 internal/sync2: Fix typo in doc comment
  internal/sync2/cycle.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2684 Fix TestCachedBandwidthMonthRollover test
  storagenode/bandwidth/db_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2664 satellite/satellitedb: get active offer for partners
  internal/dbutil/pgutil/query.go
  satellite/console/consoleweb/consoleql/mutation_test.go
  satellite/console/service.go
  satellite/console/usercredits.go
  satellite/rewards/partners.go
  satellite/rewards/rewards.go
  satellite/rewards/rewards_test.go
  satellite/satellitedb/dbx/satellitedb.dbx
  satellite/satellitedb/dbx/satellitedb.dbx.go
  satellite/satellitedb/dbx/satellitedb.dbx.postgres.sql
  satellite/satellitedb/dbx/satellitedb.dbx.sqlite3.sql
  satellite/satellitedb/locked.go
  satellite/satellitedb/migrate.go
  satellite/satellitedb/offers.go
  satellite/satellitedb/testdata/postgres.v49.sql
  satellite/satellitedb/usercredits.go
  satellite/satellitedb/usercredits_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2620 Implement checker observer
  satellite/peer.go
  satellite/repair/checker/checker.go
  satellite/repair/checker/checker_test.go
Labels: Request Code Review, cla-signed

#2687 uplink/storage: don't import mock in production code
  go.mod
  go.sum
  lib/uplinkc/uplink_definitions.h
  uplink/storage/segments/mock_store.go
  uplink/storage/streams/store_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2693 docs/design: Remove "Title" word from title header
  docs/design/TEMPLATE.md
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2668 Adding more info the error logs in bootstrap
  pkg/kademlia/kademlia.go
Labels: Request Code Review, cla-signed

#2698 Add 24 hours to account for the entire rest of the end day when do accounting exports
  cmd/satellite/main.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2696 web/satellite common search component created
  web/satellite/package.json
  web/satellite/src/components/common/SearchComponent.vue
  web/satellite/tests/unit/common/SearchComponent.spec.ts
  web/satellite/tests/unit/common/__snapshots__/SearchComponent.spec.ts.snap
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2692 Updating the certdb to support storage of multiple public keys for same node ID
  satellite/certdb/certdb.go
  satellite/certdb/certdb_test.go
  satellite/satellitedb/certdb.go
  satellite/satellitedb/dbx/satellitedb.dbx
  satellite/satellitedb/dbx/satellitedb.dbx.go
  satellite/satellitedb/dbx/satellitedb.dbx.postgres.sql
  satellite/satellitedb/dbx/satellitedb.dbx.sqlite3.sql
  satellite/satellitedb/locked.go
  satellite/satellitedb/migrate.go
  satellite/satellitedb/testdata/postgres.v50.sql
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2699 storagenode: more live request tracking
  pkg/process/error.go
  storagenode/piecestore/endpoint.go
Labels: cla-signed

#2697 web/satellite color pallet of buttons on create/login account updated
  web/satellite/src/views/login/login.scss
  web/satellite/src/views/register/register.scss
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2683 Make one implementation for SetAttribution/SetBucketAttribution
  pkg/pb/metainfo.pb.go
  pkg/pb/metainfo.proto
  proto.lock
  satellite/metainfo/metainfo.go
  satellite/metainfo/metainfo_test.go
  uplink/metainfo/client.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2709 Web/satellite search component test build fix
  web/satellite/src/components/common/SearchComponent.vue
  web/satellite/tests/unit/common/SearchComponent.spec.ts
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2710 C require macros improvements
  lib/uplinkc/testdata/require.h
Labels: Code Review In-Progress, Request Code Review, Reviewer Can Merge, cla-signed

#2701 Add more monkit for segment piece info
  internal/errs2/ignore.go
  uplink/ecclient/client.go
Labels: Reviewer Can Merge, cla-signed

#2702 satellite/repair: add shouldDelete
  satellite/repair/repairer/repairer.go
  satellite/repair/repairer/segments.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2695 graphql query escaping
  web/satellite/src/api/apiKeys.ts
  web/satellite/src/api/paymentMethods.ts
  web/satellite/src/api/projectMembers.ts
  web/satellite/src/api/projects.ts
  web/satellite/src/api/usage.ts
  web/satellite/src/api/users.ts
Labels: Request Code Review, cla-signed

#2501 cmd/uplink: use scopes to open
  cmd/bootstrap/main.go
  cmd/certificates/setup.go
  cmd/gateway/main.go
  cmd/linksharing/main.go
  cmd/satellite/main.go
  cmd/storagenode/main.go
  cmd/storj-sim/network.go
  cmd/uplink/cmd/cp.go
  cmd/uplink/cmd/ls.go
  cmd/uplink/cmd/rb.go
  cmd/uplink/cmd/rm.go
  cmd/uplink/cmd/root.go
  cmd/uplink/cmd/setup.go
  cmd/uplink/cmd/setup_test.go
  cmd/uplink/cmd/share.go
  cmd/versioncontrol/main.go
  go.mod
  go.sum
  internal/testplanet/uplink.go
  lib/uplink/project_test.go
  pkg/cfgstruct/bind.go
  pkg/miniogw/integration_test.go
  pkg/process/config.go
  pkg/process/exec_conf.go
  pkg/process/exec_conf_test.go
  scripts/testdata/satellite-config.yaml.lock
  uplink/config.go
  uplink/setup/encryption_key.go
  uplink/setup/encryption_key_test.go
  uplink/setup/setup.go
  uplink/setup/setup_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2713 pkg/process: support json trace output
  pkg/process/exec_conf.go
Labels: cla-signed

#2714 libuplink: Add size to `ObjectInfo`
  lib/uplinkc/convert.go
  lib/uplinkc/object.go
  lib/uplinkc/testdata/object_test.c
  lib/uplinkc/uplink_definitions.h
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2720 Add Karl Mozurkewich
  .clabot
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2705 satellite/marketingweb: make display order consistent
  satellite/rewards/display.go
  web/marketing/pages/referral-offers-modal.html
  web/marketing/pages/referral-offers.html
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2694 metainfo: Batch request
  pkg/pb/metainfo.pb.go
  pkg/pb/metainfo.proto
  proto.lock
  satellite/metainfo/batch.go
  satellite/metainfo/metainfo_test.go
  uplink/metainfo/batch.go
  uplink/metainfo/client.go
  uplink/storage/buckets/store.go
Labels: Request Code Review, cla-signed

#2717 satellite/overlay: rename overlay.Cache to overlay.Service
  cmd/inspector/main.go
  docs/design/disqualification.md
  internal/testplanet/uplink_test.go
  satellite/accounting/tally/tally.go
  satellite/audit/reporter.go
  satellite/audit/service.go
  satellite/audit/testplanet_helpers_test.go
  satellite/audit/verifier.go
  satellite/discovery/service.go
  satellite/discovery/service_test.go
  satellite/inspector/inspector.go
  satellite/metainfo/metainfo.go
  satellite/orders/service.go
  satellite/overlay/config.go
  satellite/overlay/inspector.go
  satellite/overlay/selection_test.go
  satellite/overlay/service.go
  satellite/overlay/service_test.go
  satellite/peer.go
  satellite/repair/checker/checker.go
  satellite/repair/checker/online.go
  satellite/repair/checker/online_test.go
  satellite/repair/repair_test.go
  satellite/repair/repairer/repairer.go
  satellite/repair/repairer/segments.go
  satellite/vouchers/endpoint.go
  scripts/testdata/satellite-config.yaml.lock
  storage/redis/client.go
  uplink/metainfo/kvmetainfo/objects_test.go
Labels: Request Code Review, cla-signed

#2724 Fix retain request iteration in debug mode
  storagenode/pieces/store.go
  storagenode/piecestore/endpoint.go
  storagenode/piecestore/endpoint_test.go
  storagenode/storagenodedb/pieceinfo.go
  storagenode/storagenodedb/pieceinfo_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2681 satellite/overlay: reduce calls to UpdateAddress
  satellite/overlay/combinedcache.go
  satellite/overlay/keylock.go
  satellite/overlay/keylock_test.go
  satellite/overlay/service.go
  satellite/overlay/statdb_test.go
  satellite/peer.go
Labels: cla-signed

#2656 Jg/1622 add backwards compatibility test
  Makefile
  scripts/test-backwards.sh
  scripts/test-sim-backwards.sh
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2727 codeowners: setup automatic reviewer assignment
  .github/CODEOWNERS
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2729 codeowners: use proxy team for assignment
  .github/CODEOWNERS
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2725 libuplink upload/download err handling improvements
  internal/errs2/ignore_test.go
  lib/uplinkc/object.go
  lib/uplinkc/testdata/object_test.c
Labels: Code Review In-Progress, Reviewer Can Merge, cla-signed

#2726 Remove the use of in memory SQLite3 tables for storage nodes.
  internal/testplanet/storagenode.go
Labels: cla-signed

#2735 architecture-owner codeowners for design docs
  .github/CODEOWNERS
Labels: cla-signed

#2629 move piece info into files
  internal/testblobs/slow.go
  pkg/pb/piecestore2.pb.go
  pkg/pb/piecestore2.proto
  proto.lock
  satellite/gc/gc_test.go
  storage/blob.go
  storage/filestore/blob.go
  storage/filestore/dir.go
  storage/filestore/store.go
  storage/filestore/store_test.go
  storagenode/collector/service.go
  storagenode/collector/service_test.go
  storagenode/console/service.go
  storagenode/inspector/inspector.go
  storagenode/monitor/monitor.go
  storagenode/peer.go
  storagenode/pieces/db_test.go
  storagenode/pieces/pieceexpiration_test.go
  storagenode/pieces/readwrite.go
  storagenode/pieces/readwrite_test.go
  storagenode/pieces/store.go
  storagenode/pieces/store_test.go
  storagenode/piecestore/endpoint.go
  storagenode/piecestore/endpoint_test.go
  storagenode/piecestore/verification_test.go
  storagenode/storagenodedb/database.go
  storagenode/storagenodedb/infodb.go
  storagenode/storagenodedb/pieceexpiration.go
  storagenode/storagenodedb/pieceinfo.go
  storagenode/storagenodedb/pieceinfo_test.go
  storagenode/storagenodedb/testdata/sqlite.v15.sql
Labels: Request Code Review, cla-signed

#2665 Satellite console server gzip compression
  satellite/console/consoleweb/server.go
  web/satellite/package.json
  web/satellite/vue.config.js
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2738 Uplink setup: respect tls args in libuplink config
  cmd/uplink/cmd/setup.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2543 storagenode/nodestats: cache node stats
  internal/date/utils.go
  internal/date/utils_test.go
  internal/dbutil/nulltime.go
  internal/testplanet/storagenode.go
  internal/testrand/rand.go
  pkg/pb/nodestats.pb.go
  pkg/pb/nodestats.proto
  proto.lock
  satellite/accounting/db.go
  satellite/accounting/db_test.go
  satellite/nodestats/endpoint.go
  satellite/satellitedb/locked.go
  satellite/satellitedb/storagenodeaccounting.go
  storagenode/console/bandwidth.go
  storagenode/console/consoleserver/server.go
  storagenode/console/db_test.go
  storagenode/console/service.go
  storagenode/nodestats/cache.go
  storagenode/nodestats/service.go
  storagenode/peer.go
  storagenode/reputation/reputation.go
  storagenode/storagenodedb/consoledb.go
  storagenode/storagenodedb/infodb.go
  storagenode/storagenodedb/reputation.go
  storagenode/storagenodedb/storageusage.go
  storagenode/storagenodedb/testdata/sqlite.v16.sql
  storagenode/storageusage/storageusage.go
Labels: Request Code Review, cla-signed

#2739 go.mod: use custom grpc that doesn't have tracing support
  go.mod
  go.sum
Labels: Reviewer Can Merge, cla-signed

#2741 go.mod: use pseudo version
  go.mod
  go.sum
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2703 docs/design: auditing 2.0
  docs/design/audit-v2.md
Labels: cla-signed

#2723 docs/design: use piece hashes for repair
  docs/design/repair-with-hashes.md
Labels: Request Code Review, cla-signed

#2737 Restrict node info only for trusted satellites
  bootstrap/peer.go
  pkg/kademlia/endpoint.go
  pkg/kademlia/kademlia.go
  pkg/kademlia/kademlia_planet_test.go
  pkg/kademlia/kademlia_test.go
  satellite/peer.go
  storagenode/monitor/monitor_test.go
  storagenode/peer.go
Labels: cla-signed

#2748 storagenode/nodestats: fix test duration
  go.sum
  internal/testplanet/storagenode.go
  storagenode/nodestats/cache.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2740 web/satellite: team area header updated
  web/satellite/src/components/common/HeaderComponent.vue
  web/satellite/src/components/common/SearchComponent.vue
  web/satellite/src/components/team/TeamArea.vue
  web/satellite/src/components/team/headerArea/HeaderArea.vue
  web/satellite/tests/unit/common/HeaderComponent.spec.ts
  web/satellite/tests/unit/common/SearchComponent.spec.ts
  web/satellite/tests/unit/common/__snapshots__/HeaderComponent.spec.ts.snap
  web/satellite/tests/unit/common/__snapshots__/SearchComponent.spec.ts.snap
  web/satellite/tests/unit/team/headerArea/HeaderArea.spec.ts
  web/satellite/tests/unit/team/headerArea/__snapshots__/HeaderArea.spec.ts.snap
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2712 web/satellite Generic List component
  web/satellite/src/components/common/List.vue
  web/satellite/src/components/common/test/TestList.vue
  web/satellite/src/components/common/test/TestListItem.vue
  web/satellite/tests/unit/common/TestList.spec.ts
Labels: Request Code Review, cla-signed

#2722 web/satellite: pagination component implemented
  web/satellite/src/components/common/PagesBlock.vue
  web/satellite/src/components/common/Pagination.vue
  web/satellite/src/types/fetch.d.ts
  web/satellite/src/types/pagination.ts
  web/satellite/tests/unit/common/PagesBlock.spec.ts
  web/satellite/tests/unit/common/Pagination.spec.ts
  web/satellite/tests/unit/common/__snapshots__/PagesBlock.spec.ts.snap
  web/satellite/tests/unit/common/__snapshots__/Pagination.spec.ts.snap
Labels: Request Code Review, cla-signed

#2749 web/satellite: title removed from header component
  web/satellite/src/components/common/HeaderComponent.vue
  web/satellite/src/components/team/headerArea/HeaderArea.vue
  web/satellite/tests/unit/common/HeaderComponent.spec.ts
  web/satellite/tests/unit/common/__snapshots__/HeaderComponent.spec.ts.snap
  web/satellite/tests/unit/team/headerArea/__snapshots__/HeaderArea.spec.ts.snap
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2711 uplink/ecclient: read concurrently with dials during download
  uplink/ecclient/client.go
  uplink/eestream/decode.go
  uplink/piecestore/download.go
Labels: cla-signed

#2754 Updates the pkg/identity support encode and decode functionality of Peer Identity information
  pkg/identity/identity.go
  pkg/identity/identity_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2756 Update repair-with-hashes.md
  docs/design/repair-with-hashes.md
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2752 satellite/console: project members refactoring
  satellite/console/consoleweb/consoleql/mutation_test.go
  satellite/console/consoleweb/consoleql/project.go
  satellite/console/consoleweb/consoleql/projectmember.go
  satellite/console/consoleweb/consoleql/query_test.go
  satellite/console/consoleweb/consoleql/typecreator.go
  satellite/console/projectmembers.go
  satellite/console/projectmembers_test.go
  satellite/console/service.go
  satellite/satellitedb/locked.go
  satellite/satellitedb/projectmembers.go
Labels: cla-signed

#2761 cmd/uplink: remove identity setup instructions
  cmd/uplink/README.md
Labels: cla-signed

#2760 satellite/certdb: remove certdb that was used to store uplink certificates
  pkg/identity/identity.go
  satellite/certdb/certdb.go
  satellite/certdb/certdb_test.go
  satellite/orders/endpoint.go
  satellite/peer.go
  satellite/satellitedb/certdb.go
  satellite/satellitedb/database.go
  satellite/satellitedb/dbx/satellitedb.dbx
  satellite/satellitedb/dbx/satellitedb.dbx.go
  satellite/satellitedb/dbx/satellitedb.dbx.postgres.sql
  satellite/satellitedb/dbx/satellitedb.dbx.sqlite3.sql
  satellite/satellitedb/locked.go
  satellite/satellitedb/migrate.go
  satellite/satellitedb/testdata/postgres.v52.sql
Labels: cla-signed

#2765 satellie/gc: enable garbage collection on the satellite
  satellite/gc/service.go
  scripts/testdata/satellite-config.yaml.lock
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2766 Revert #2748, #2543 and #2629
  go.sum
  internal/date/utils.go
  internal/date/utils_test.go
  internal/dbutil/nulltime.go
  internal/testblobs/slow.go
  internal/testplanet/storagenode.go
  internal/testrand/rand.go
  pkg/pb/nodestats.pb.go
  pkg/pb/nodestats.proto
  pkg/pb/piecestore2.pb.go
  pkg/pb/piecestore2.proto
  proto.lock
  satellite/accounting/db.go
  satellite/accounting/db_test.go
  satellite/gc/gc_test.go
  satellite/nodestats/endpoint.go
  satellite/satellitedb/locked.go
  satellite/satellitedb/storagenodeaccounting.go
  storage/blob.go
  storage/filestore/blob.go
  storage/filestore/dir.go
  storage/filestore/store.go
  storage/filestore/store_test.go
  storagenode/collector/service.go
  storagenode/collector/service_test.go
  storagenode/console/bandwidth.go
  storagenode/console/consoleserver/server.go
  storagenode/console/db_test.go
  storagenode/console/service.go
  storagenode/inspector/inspector.go
  storagenode/monitor/monitor.go
  storagenode/nodestats/cache.go
  storagenode/nodestats/service.go
  storagenode/peer.go
  storagenode/pieces/db_test.go
  storagenode/pieces/pieceexpiration_test.go
  storagenode/pieces/readwrite.go
  storagenode/pieces/readwrite_test.go
  storagenode/pieces/store.go
  storagenode/pieces/store_test.go
  storagenode/piecestore/endpoint.go
  storagenode/piecestore/endpoint_test.go
  storagenode/piecestore/verification_test.go
  storagenode/reputation/reputation.go
  storagenode/storagenodedb/consoledb.go
  storagenode/storagenodedb/database.go
  storagenode/storagenodedb/infodb.go
  storagenode/storagenodedb/pieceexpiration.go
  storagenode/storagenodedb/pieceinfo.go
  storagenode/storagenodedb/pieceinfo_test.go
  storagenode/storagenodedb/reputation.go
  storagenode/storagenodedb/storageusage.go
  storagenode/storagenodedb/testdata/sqlite.v15.sql
  storagenode/storagenodedb/testdata/sqlite.v16.sql
  storagenode/storageusage/storageusage.go
Labels: cla-signed

#2743 satellite/console: store partner id on api key and project creation
  satellite/console/consoleweb/consoleql/mutation_test.go
  satellite/console/service.go
  satellite/satellitedb/projects.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2753 storagenode: add space used cache for pieces
  cmd/storagenode/main.go
  internal/testplanet/storagenode.go
  storage/filestore/store.go
  storage/filestore/store_test.go
  storagenode/peer.go
  storagenode/pieces/cache.go
  storagenode/pieces/cache_test.go
  storagenode/pieces/readwrite.go
  storagenode/pieces/readwrite_test.go
  storagenode/pieces/store.go
  storagenode/pieces/store_test.go
  storagenode/piecestore/endpoint.go
  storagenode/piecestore/endpoint_test.go
  storagenode/piecestore/verification_test.go
  storagenode/storagenodedb/infodb.go
  storagenode/storagenodedb/piecespaceused.go
  storagenode/storagenodedb/testdata/sqlite.v17.sql
Labels: Code Review In-Progress, Reviewer Can Merge, Sprint Release Goal, cla-signed

#2730 lib/uplinkc: make .so smaller
  Makefile
Labels: Request Code Review, cla-signed

#2750 satellite/console/server: parse html files as templates
  satellite/console/consoleweb/server.go
  web/satellite/static/activation/activated.css
  web/satellite/static/activation/activated.html
  web/satellite/static/activation/error.css
  web/satellite/static/activation/error.html
  web/satellite/static/reports/usageReport.html
Labels: Request Code Review, cla-signed

#2767 storagenode/pieces: Remove duplicated orders test
  storagenode/pieces/db_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2769 storagenode/pieces: skip flaky TestCacheCreateMultipleSatellites
  storagenode/pieces/cache_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2669 docs/design: update kademlia audit gating
  docs/design/kademlia-audit-gating.md
Labels: Design Doc, cla-signed

#2768 lib/uplink: remove Seek method
  internal/testplanet/uplink.go
  lib/uplink/bucket.go
  lib/uplink/list_test.go
  lib/uplink/object.go
  lib/uplinkc/object.go
  mobile/bucket.go
  storagenode/piecestore/endpoint_test.go
  uplink/stream/download.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2772 storagenode: Add more test assertions
  storagenode/orders/db_test.go
  storagenode/piecestore/endpoint_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2758 satellite/satellitedb: save tallies in single transaction
  satellite/satellitedb/projectaccounting.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2771 uplink/piecestore: handle Download errors better
  satellite/orders/orders_test.go
  uplink/piecestore/download.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2777 go.mod: update grpc-go and go
  Dockerfile.jenkins
  Makefile
  go.mod
  go.sum
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2751 storagenode/console: refactor service and api
  storagenode/console/bandwidth.go
  storagenode/console/consoleserver/server.go
  storagenode/console/diskspace.go
  storagenode/console/service.go
  storagenode/peer.go
  storagenode/reputation/reputation.go
  storagenode/storageusage/storageusage.go
Labels: Request Code Review, cla-signed

#2776 satellite/rewards: hardcoded partner ids
  satellite/console/consoleweb/consoleql/mutation_test.go
  satellite/rewards/partners.go
Labels: cla-signed

#2757 uplink/ecclient: performance - close connections faster
  uplink/ecclient/client.go
  uplink/eestream/decode.go
  uplink/eestream/rs_test.go
  uplink/piecestore/download.go
Labels: Request Code Review, Sprint Release Goal, cla-signed

#2779 cmd/certificates: ensure we can bind config values
  cmd/certificates/main.go
  pkg/cfgstruct/bind.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2736 satellite/console: bypass activation token logic for open source partner referral link
  satellite/console/consoleweb/consoleql/mutation_test.go
  satellite/console/service.go
  satellite/rewards/partners.go
  web/marketing/pages/partner-offers-modal.html
  web/satellite/src/views/register/Register.vue
Labels: Code Review In-Progress, Reviewer Can Merge, cla-signed

#2774 jenkins: add backwards compatibility test
  Jenkinsfile.public
  scripts/test-sim-backwards.sh
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2782 design doc for design doc process
  docs/design/design-doc-process
Labels: Design Doc, Reviewer Can Merge, cla-signed

#2788 satellite/overlaycache: add missing audit and uptime success count
  satellite/satellitedb/overlaycache.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2787 web/satellite user api simplification
  web/satellite/src/api/auth.ts
  web/satellite/src/api/baseGql.ts
  web/satellite/src/api/users.ts
  web/satellite/src/components/account/ChangePasswordPopup.vue
  web/satellite/src/components/account/DeleteAccountPopup.vue
  web/satellite/src/components/account/EditProfilePopup.vue
  web/satellite/src/components/common/RegistrationSuccessPopup.vue
  web/satellite/src/store/index.ts
  web/satellite/src/store/modules/users.ts
  web/satellite/src/store/mutationConstants.ts
  web/satellite/src/types/users.ts
  web/satellite/src/utils/consoleLocalStorage.ts
  web/satellite/src/utils/constants/actionNames.ts
  web/satellite/src/views/Dashboard.vue
  web/satellite/src/views/forgotPassword/ForgotPassword.vue
  web/satellite/src/views/login/Login.vue
  web/satellite/src/views/register/Register.vue
  web/satellite/tests/unit/store/users.spec.ts
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2778 go.mod: update grpc-go
  go.mod
  go.sum
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2790 Start building binary for the link sharing service
  Makefile
Labels: Reviewer Can Merge, cla-signed

#2773 satellite/repair: monkit improvements
  uplink/ecclient/client.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2745 satellite/rewards: update current reward to be finished once redemption cap has reached
  satellite/console/consoleweb/consoleql/mutation_test.go
  satellite/console/service.go
  satellite/console/usercredits.go
  satellite/rewards/rewards.go
  satellite/satellitedb/locked.go
  satellite/satellitedb/usercredits.go
  satellite/satellitedb/usercredits_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2784 pkg/process: only propagate missing keys to flags
  pkg/process/exec_conf.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2791 lib/uplinkc: fix flaky download test
  lib/uplinkc/testdata/object_test.c
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2759 satellite/metainfo: fix storing enc key/nonce
  satellite/metainfo/metainfo.go
  scripts/test-uplink.sh
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2780 docs/design: windows installer
  docs/design/storage-node-windows-installer.md
Labels: Design Doc, Request Code Review, cla-signed

#2786 uplink/piecestore: Change where ignore cancel happens
  uplink/eestream/decode.go
  uplink/piecestore/download.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2797 docs/design: referral manager
  docs/design/referral-manager.md
Labels: cla-signed

#2796 storagenode/orders: add ordersDB method CleanArchive
  storagenode/orders/db_test.go
  storagenode/orders/sender.go
  storagenode/storagenodedb/orders.go
Labels: Request Code Review, cla-signed

#2770 web/satellite: api key header updated, redundant components removed
  web/satellite/src/components/apiKeys/AddApiKeyPopup.vue
  web/satellite/src/components/apiKeys/ApiKeysArea.vue
  web/satellite/src/components/apiKeys/ApiKeysCopyPopup.vue
  web/satellite/src/components/apiKeys/ApiKeysCreationPopup.vue
  web/satellite/src/components/apiKeys/ApiKeysItem.vue
  web/satellite/src/components/apiKeys/CopyApiKeyPopup.vue
  web/satellite/src/components/apiKeys/footerArea/ApproveDeleteApiKeysArea.vue
  web/satellite/src/components/apiKeys/footerArea/DeleteApiKeysArea.vue
  web/satellite/src/components/apiKeys/footerArea/Footer.vue
  web/satellite/src/components/apiKeys/headerArea/HeaderArea.vue
  web/satellite/src/components/apiKeys/headerArea/SearchArea.vue
  web/satellite/src/components/common/HeaderComponent.vue
  web/satellite/src/components/common/SearchComponent.vue
  web/satellite/src/components/project/NewProjectPopup.vue
  web/satellite/src/components/project/ProjectCreationSuccessPopup.vue
  web/satellite/src/store/index.ts
  web/satellite/src/store/modules/apiKeys.ts
  web/satellite/src/store/modules/appState.ts
  web/satellite/src/store/modules/projects.ts
  web/satellite/src/store/mutationConstants.ts
  web/satellite/src/utils/constants/actionNames.ts
  web/satellite/tests/unit/apiKeys/ApiKeysArea.spec.ts
  web/satellite/tests/unit/apiKeys/ApiKeysCopyPopup.spec.ts
  web/satellite/tests/unit/apiKeys/ApiKeysCreationPopup.spec.ts
  web/satellite/tests/unit/apiKeys/__snapshots__/ApiKeysArea.spec.ts.snap
  web/satellite/tests/unit/apiKeys/__snapshots__/ApiKeysCopyPopup.spec.ts.snap
  web/satellite/tests/unit/apiKeys/__snapshots__/ApiKeysCreationPopup.spec.ts.snap
  web/satellite/tests/unit/common/SearchComponent.spec.ts
  web/satellite/tests/unit/store/projects.spec.ts
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2762 Update satellite settlement endpoint to batch order processing into transactions.
  satellite/orders/endpoint.go
  satellite/orders/orders_test.go
  satellite/orders/service.go
  satellite/peer.go
  satellite/satellitedb/locked.go
  satellite/satellitedb/orders.go
  scripts/testdata/satellite-config.yaml.lock
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2763 web/satellite: Buckets page rework
  web/satellite/src/components/buckets/BucketArea.vue
  web/satellite/src/components/buckets/BucketItem.vue
  web/satellite/src/components/buckets/PaginationArea.vue
  web/satellite/src/components/buckets/SearchArea.vue
  web/satellite/src/components/buckets/SortingHeader.vue
  web/satellite/src/store/modules/usage.ts
Labels: cla-signed

#2794 web/satellite: add team member placeholder changed
  web/satellite/src/components/team/AddUserPopup.vue
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2801 storagenode: Don't exit with fatal error when unsent orders aren't found
  pkg/process/exec_conf.go
  satellite/orders/endpoint.go
  storagenode/orders/db_test.go
  storagenode/orders/sender.go
  storagenode/storagenodedb/orders.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2804 storagenode/orders: An invalid one don't have to stop all
  storagenode/orders/sender.go
  storagenode/storagenodedb/orders.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2809 uplink/storage/segments: seed download permutation with timestamp
  uplink/storage/segments/store.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2810 jenkins: Backwards Compatibility use Postgres
  Jenkinsfile.public
  scripts/test-sim-backwards.sh
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2814 build: update to go 1.12.9, build everything for aarch64
  Dockerfile.jenkins
  Makefile
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2807 web/satellite: projects api key refactored
  web/satellite/src/api/apiKeys.ts
  web/satellite/src/components/apiKeys/ApiKeysArea.vue
  web/satellite/src/components/apiKeys/ApiKeysCreationPopup.vue
  web/satellite/src/store/index.ts
  web/satellite/src/store/modules/apiKeys.ts
  web/satellite/src/store/mutationConstants.ts
  web/satellite/src/types/apiKeys.ts
  web/satellite/src/utils/constants/actionNames.ts
  web/satellite/src/views/Dashboard.vue
  web/satellite/tests/unit/apiKeys/ApiKeysArea.spec.ts
  web/satellite/tests/unit/apiKeys/ApiKeysCopyPopup.spec.ts
  web/satellite/tests/unit/apiKeys/ApiKeysCreationPopup.spec.ts
  web/satellite/tests/unit/store/apiKeys.spec.ts
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2795 satellite/satellitedb: Add piece count column to nodes table
  satellite/overlay/service.go
  satellite/satellitedb/dbx/satellitedb.dbx
  satellite/satellitedb/dbx/satellitedb.dbx.go
  satellite/satellitedb/dbx/satellitedb.dbx.postgres.sql
  satellite/satellitedb/dbx/satellitedb.dbx.sqlite3.sql
  satellite/satellitedb/migrate.go
  satellite/satellitedb/overlaycache.go
  satellite/satellitedb/testdata/postgres.v53.sql
Labels: Code Review In-Progress, cla-signed

#2813 satellite/orders: document protocol and fix typos
  pkg/pb/orders.pb.go
  pkg/pb/orders.proto
  satellite/orders/endpoint.go
  satellite/orders/service.go
  satellite/peer.go
  satellite/satellitedb/locked.go
  satellite/satellitedb/orders.go
  scripts/testdata/satellite-config.yaml.lock
Labels: Request Code Review, cla-signed

#2811 web/satellite/credits: api/store/component and tests refactored
  web/satellite/src/api/credits.ts
  web/satellite/src/api/usage.ts
  web/satellite/src/components/account/EditProfilePopup.vue
  web/satellite/src/components/account/Profile.vue
  web/satellite/src/components/buckets/BucketArea.vue
  web/satellite/src/components/header/AccountDropdown.vue
  web/satellite/src/components/referral/ReferralStats.vue
  web/satellite/src/store/index.ts
  web/satellite/src/store/modules/credits.ts
  web/satellite/src/store/modules/usage.ts
  web/satellite/src/store/modules/users.ts
  web/satellite/src/store/mutationConstants.ts
  web/satellite/src/types/credits.ts
  web/satellite/src/types/usage.d.ts
  web/satellite/src/utils/constants/actionNames.ts
  web/satellite/src/views/Dashboard.vue
  web/satellite/tests/unit/common/__snapshots__/TestList.spec.ts.snap
  web/satellite/tests/unit/projectMembers/__snapshots__/ProjectMemberListItem.spec.ts.snap
  web/satellite/tests/unit/referralStats/__snapshots__/referralStats.spec.ts.snap
  web/satellite/tests/unit/referralStats/referralStats.spec.ts
  web/satellite/tests/unit/store/credits.spec.ts
  web/satellite/tests/unit/store/users.spec.ts
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2785 storagenode/piecestore: Storagenode should not block garbage collection on satellite
  internal/testplanet/storagenode.go
  satellite/gc/gc_test.go
  storagenode/peer.go
  storagenode/piecestore/endpoint.go
  storagenode/piecestore/endpoint_test.go
  storagenode/retain/retain.go
  storagenode/retain/retain_test.go
Labels: Request Code Review, cla-signed

#2816 scripts/test-sim-backwards: usability improvements
  scripts/test-sim-backwards.sh
Labels: Code Review In-Progress, cla-signed

#2823 docs/audit-v2: formatting fix
  docs/design/audit-v2.md
Labels: Request Code Review, cla-signed

#2812 lib/uplink: remove redis and bolt dependencies
  bootstrap/peer.go
  cmd/bootstrap/main.go
  cmd/certificates/main.go
  cmd/identity/certificate_authority.go
  cmd/identity/main.go
  cmd/identity/revocations.go
  cmd/satellite/main.go
  cmd/storagenode/main.go
  examples/grpc-debug/main.go
  internal/testplanet/bootstrap.go
  internal/testplanet/satellite.go
  internal/testplanet/storagenode.go
  internal/testplanet/uplink.go
  internal/testplanet/uplink_test.go
  internal/testrevocation/revocation_db.go
  lib/uplink/uplink.go
  pkg/certificates/certificates_test.go
  pkg/certificates/config.go
  pkg/kademlia/kademlia_planet_test.go
  pkg/kademlia/kademlia_test.go
  pkg/kademlia/kademliaclient/kademliaclient_test.go
  pkg/peertls/extensions/revocations_test.go
  pkg/peertls/tlsopts/options.go
  pkg/peertls/tlsopts/options_test.go
  pkg/peertls/tlsopts/tls_test.go
  pkg/revocation/revocation_db.go
  pkg/revocation/revocation_db_test.go
  pkg/server/config.go
  pkg/transport/transport_test.go
  satellite/audit/reverify_test.go
  satellite/audit/verifier_test.go
  satellite/peer.go
  storagenode/peer.go
Labels: cla-signed

#2826 satellite/nodestats: use proper error codes
  satellite/nodestats/endpoint.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2824 pkg/kademlia: clearer error message
  pkg/kademlia/endpoint.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2818 storagenode/storagenodedb: initialize used space table with sum over pieceinfo
  storagenode/pieces/cache_test.go
  storagenode/storagenodedb/infodb.go
  storagenode/storagenodedb/testdata/sqlite.v16.sql
  storagenode/storagenodedb/testdata/sqlite.v17.sql
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2820 web/satellite: ProjectMembers store and graphQL queries refactoring
  web/satellite/src/api/projectMembers.ts
  web/satellite/src/components/header/projectSelection/ProjectSelectionDropdown.vue
  web/satellite/src/components/team/AddUserPopup.vue
  web/satellite/src/components/team/HeaderArea.vue
  web/satellite/src/components/team/ProjectMembersArea.vue
  web/satellite/src/store/index.ts
  web/satellite/src/store/modules/projectMembers.ts
  web/satellite/src/store/mutationConstants.ts
  web/satellite/src/types/projectMembers.ts
  web/satellite/src/views/Dashboard.vue
  web/satellite/tests/unit/projectMembers/HeaderArea.spec.ts
  web/satellite/tests/unit/projectMembers/ProjectMemberListItem.spec.ts
  web/satellite/tests/unit/projectMembers/ProjectMembersArea.spec.ts
  web/satellite/tests/unit/projectMembers/SortingListHeader.spec.ts
  web/satellite/tests/unit/store/projectMembers.spec.ts
Labels: Request Code Review, cla-signed

#2827 satellite/metainfo: use status.Error and fix error codes
  satellite/metainfo/metainfo.go
  satellite/metainfo/validation.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2832 web/satellite: Moved endpoint url to config file.
  web/satellite/.env
  web/satellite/src/api/baseGql.ts
  web/satellite/src/api/paymentMethods.ts
  web/satellite/src/api/projects.ts
  web/satellite/src/api/usage.ts
  web/satellite/src/utils/apollo.ts
Labels: cla-signed

#2831 pkg/peertls: extension handling refactor
  pkg/peertls/extensions/extensions.go
  pkg/peertls/extensions/extensions_test.go
  pkg/peertls/extensions/revocations.go
  pkg/peertls/extensions/revocations_test.go
  pkg/peertls/tlsopts/options.go
  pkg/peertls/tlsopts/tls_test.go
  pkg/storj/identity_version.go
  pkg/storj/identity_version_test.go
Labels: Request Code Review, cla-signed

#2829 satellite/audit: Improve comments in verifier
  satellite/audit/verifier.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2833 satellite/repair: fix data race in tests
  satellite/repair/repair_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2825 pkg/revocation: ensure we close revocation databases
  cmd/bootstrap/main.go
  cmd/certificates/main.go
  cmd/identity/main.go
  cmd/satellite/main.go
  cmd/storagenode/main.go
  internal/testplanet/bootstrap.go
  internal/testplanet/satellite.go
  internal/testplanet/storagenode.go
  internal/testplanet/uplink_test.go
  internal/testrevocation/db.go
  internal/testrevocation/revocation_db.go
  pkg/certificates/certificates_test.go
  pkg/peertls/extensions/extensions.go
  pkg/peertls/extensions/revocations.go
  pkg/peertls/extensions/revocations_test.go
  pkg/peertls/tlsopts/options.go
  pkg/peertls/tlsopts/options_test.go
  pkg/peertls/tlsopts/tls_test.go
  pkg/revocation/common.go
  pkg/revocation/db.go
  pkg/revocation/db_test.go
  pkg/server/config.go
  satellite/peer.go
  storagenode/peer.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2834 web/satellite: tab navigation component unit tests added
  web/satellite/src/components/account/AccountArea.vue
  web/satellite/src/components/navigation/TabNavigation.vue
  web/satellite/src/components/project/ProjectOverviewArea.vue
  web/satellite/src/types/navigation.ts
  web/satellite/src/utils/constants/ProjectMemberSortEnum.ts
  web/satellite/src/utils/constants/tabNavigation.ts
  web/satellite/tests/unit/components/navigation/TabNavigation.spec.ts
  web/satellite/tests/unit/components/navigation/__snapshots__/TabNavigation.spec.ts.snap
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2686 docs/design: Kademlia Removal Design Proposal
  docs/design/kademlia-removal.md
Labels: Design Doc, Request Code Review, cla-signed

#2781 web/satellite: Notification rework
  web/satellite/src/components/notifications/Notification.vue
  web/satellite/src/components/notifications/NotificationArea.vue
  web/satellite/src/store/index.ts
  web/satellite/src/store/modules/notifications.ts
  web/satellite/src/types/DelayedNotification.ts
  web/satellite/src/utils/constants/actionNames.ts
  web/satellite/src/utils/constants/notification.ts
  web/satellite/tests/unit/notifications/Notification.spec.ts
  web/satellite/tests/unit/notifications/NotificationArea.spec.ts
  web/satellite/tests/unit/notifications/__snapshots__/Notification.spec.ts.snap
  web/satellite/tests/unit/notifications/__snapshots__/NotificationArea.spec.ts.snap
Labels: Reviewer Can Merge, cla-signed

#2830 web/satellite: buckets api and store refactored
  web/satellite/src/api/buckets.ts
  web/satellite/src/api/usage.ts
  web/satellite/src/components/buckets/BucketArea.vue
  web/satellite/src/components/buckets/BucketItem.vue
  web/satellite/src/components/common/List.vue
  web/satellite/src/components/header/AccountDropdown.vue
  web/satellite/src/components/header/projectSelection/ProjectSelectionDropdown.vue
  web/satellite/src/components/project/NewProjectPopup.vue
  web/satellite/src/store/index.ts
  web/satellite/src/store/modules/buckets.ts
  web/satellite/src/store/modules/usage.ts
  web/satellite/src/store/mutationConstants.ts
  web/satellite/src/types/buckets.ts
  web/satellite/src/types/usage.d.ts
  web/satellite/src/utils/constants/actionNames.ts
  web/satellite/src/views/Dashboard.vue
  web/satellite/tests/unit/store/buckets.spec.ts
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2732 storagenode/storagenodedb: refactor SQLite3 database connection initialization.
  storagenode/storagenodedb/bandwidthdb.go
  storagenode/storagenodedb/consoledb.go
  storagenode/storagenodedb/database.go
  storagenode/storagenodedb/infodb.go
  storagenode/storagenodedb/migrations_test.go
  storagenode/storagenodedb/orders.go
  storagenode/storagenodedb/pieceexpiration.go
  storagenode/storagenodedb/pieceinfo.go
  storagenode/storagenodedb/piecespaceused.go
  storagenode/storagenodedb/reputation.go
  storagenode/storagenodedb/storageusage.go
  storagenode/storagenodedb/usedserials.go
  storagenode/storagenodedb/versions.go
  storagenode/storagenodedb/vouchers.go
Labels: Request Code Review, cla-signed

#2744 satellite/audit: implement reservoir struct and RemoteSegment observer method
  satellite/audit/pathcollector.go
  satellite/audit/pathcollector_test.go
  satellite/audit/reservoir.go
  satellite/audit/service.go
  satellite/peer.go
  scripts/testdata/satellite-config.yaml.lock
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2840 all: fix Error.New formatting
  satellite/audit/containment_test.go
  satellite/audit/verifier.go
  satellite/orders/service.go
  satellite/satellitedb/attribution.go
  satellite/satellitedb/containment.go
  satellite/satellitedb/overlaycache.go
  storage/boltdb/client.go
  storage/postgreskv/client.go
  storage/redis/client.go
  storage/teststore/store.go
  storagenode/storagenodedb/orders.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2841 storagenode/nodestats: fix issue on 32 bit platforms
  storagenode/nodestats/cache.go
  storagenode/nodestats/cache_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2848 Rename design-doc-process.md to README.md
  docs/design/README.md
Labels: cla-signed

#2850 satellite/marketingweb: WriteHeader should only be called once
  satellite/marketingweb/server.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2846 web/satellite: router refactoring
  web/satellite/src/components/account/AccountArea.vue
  web/satellite/src/components/account/DeleteAccountPopup.vue
  web/satellite/src/components/common/RegistrationSuccessPopup.vue
  web/satellite/src/components/header/AccountDropdown.vue
  web/satellite/src/components/navigation/NavigationArea.vue
  web/satellite/src/components/navigation/navigationArea.html
  web/satellite/src/components/project/ProjectCreationSuccessPopup.vue
  web/satellite/src/components/project/ProjectDetails.vue
  web/satellite/src/components/project/ProjectOverviewArea.vue
  web/satellite/src/components/project/UsageReport.vue
  web/satellite/src/components/project/billing/BillingArea.vue
  web/satellite/src/components/project/billing/BillingItem.vue
  web/satellite/src/components/project/billing/PaginationArea.vue
  web/satellite/src/components/project/billing/SortingHeader.vue
  web/satellite/src/components/project/paymentMethods/CardComponent.vue
  web/satellite/src/components/project/paymentMethods/DeletePaymentMethodDialog.vue
  web/satellite/src/components/project/paymentMethods/MakeDefaultPaymentMethodDialog.vue
  web/satellite/src/components/project/paymentMethods/NewPaymentMethodComponent.vue
  web/satellite/src/components/team/AddUserPopup.vue
  web/satellite/src/router/index.ts
  web/satellite/src/types/navigation.ts
  web/satellite/src/utils/constants/navigationLinks.ts
  web/satellite/src/utils/constants/routerConstants.ts
  web/satellite/src/views/Dashboard.vue
  web/satellite/src/views/forgotPassword/ForgotPassword.vue
  web/satellite/src/views/login/Login.vue
  web/satellite/src/views/login/login.html
  web/satellite/src/views/register/Register.vue
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2849 all: enable staticcheck
  .golangci.yml
  bootstrap/bootstrapweb/bootstrapserver/server.go
  cmd/identity/certificate_authority.go
  go.sum
  internal/testplanet/bootstrap.go
  internal/testplanet/satellite.go
  internal/testplanet/storagenode.go
  mobile/apikey.go
  pkg/auth/grpcauth/apikey_test.go
  pkg/encryption/path_test.go
  pkg/identity/identity.go
  pkg/kademlia/kademliaclient/kademliaclient_test.go
  pkg/kademlia/testrouting/utils.go
  pkg/macaroon/serialize.go
  pkg/pb/utils.go
  pkg/ranger/content_test.go
  pkg/storj/nodeurl.go
  satellite/accounting/tally/tally.go
  satellite/audit/disqualification_test.go
  satellite/console/consoleweb/server.go
  satellite/mailservice/simulate/linkclicker.go
  satellite/marketingweb/server.go
  satellite/marketingweb/server_test.go
  satellite/metainfo/metainfo_test.go
  satellite/metainfo/validation.go
  satellite/overlay/service.go
  satellite/repair/checker/checker.go
  satellite/repair/checker/checker_test.go
  satellite/repair/repair_test.go
  satellite/satellitedb/attribution.go
  satellite/satellitedb/offers.go
  satellite/satellitedb/overlaycache.go
  satellite/satellitedb/storagenodeaccounting.go
  scripts/dependencies_test.go
  storage/boltdb/client_test.go
  storage/filestore/dir_windows.go
  storage/filestore/store_test.go
  storage/testsuite/bench.go
  storage/testsuite/test.go
  storagenode/console/consoleserver/server.go
  storagenode/storagenodedb/consoledb.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2838 satellite/audit: Improve code comment in reporter
  satellite/audit/reporter.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2821 storagenode/orders: add archive cleanup to orders service
  internal/testplanet/storagenode.go
  satellite/orders/orders_test.go
  storagenode/collector/service_test.go
  storagenode/orders/db_test.go
  storagenode/orders/service.go
  storagenode/orders/service_test.go
  storagenode/peer.go
  storagenode/piecestore/endpoint.go
  storagenode/storagenodedb/orders.go
Labels: Request Code Review, cla-signed

#2844 web/satellite: Projects api refactoring
  web/satellite/src/api/projects.ts
  web/satellite/src/components/header/AccountDropdown.vue
  web/satellite/src/components/header/projectSelection/ProjectSelectionArea.vue
  web/satellite/src/components/header/projectSelection/ProjectSelectionDropdown.vue
  web/satellite/src/components/notifications/Notification.vue
  web/satellite/src/components/notifications/NotificationArea.vue
  web/satellite/src/components/project/DeleteProjectPopup.vue
  web/satellite/src/components/project/NewProjectPopup.vue
  web/satellite/src/components/project/ProjectDetails.vue
  web/satellite/src/components/project/UsageReport.vue
  web/satellite/src/store/index.ts
  web/satellite/src/store/modules/projects.ts
  web/satellite/src/store/mutationConstants.ts
  web/satellite/src/types/projects.ts
  web/satellite/src/utils/constants/actionNames.ts
  web/satellite/src/views/Dashboard.vue
  web/satellite/tests/unit/apiKeys/ApiKeysCreationPopup.spec.ts
  web/satellite/tests/unit/common/__snapshots__/HeaderComponent.spec.ts.snap
  web/satellite/tests/unit/common/__snapshots__/HeaderedInput.spec.ts.snap
  web/satellite/tests/unit/common/__snapshots__/Pagination.spec.ts.snap
  web/satellite/tests/unit/dashboard/account/AccountDropdown.spec.ts
  web/satellite/tests/unit/store/apiKeys.spec.ts
  web/satellite/tests/unit/store/buckets.spec.ts
  web/satellite/tests/unit/store/projectMembers.spec.ts
  web/satellite/tests/unit/store/projects.spec.ts
  web/satellite/tests/unit/utils/validation.spec.ts
Labels: cla-signed

#2854 web/satellite: projects tests fixed
  web/satellite/tests/unit/store/projects.spec.ts
Labels: cla-signed

#2859 streams: don't encrypt segment count
  pkg/pb/streams.pb.go
  pkg/pb/streams.proto
  proto.lock
  satellite/accounting/tally/tally_test.go
  uplink/metainfo/kvmetainfo/objects.go
  uplink/storage/streams/store.go
Labels: cla-signed

#2856 satellite/nodestats: add disqualified flag
  pkg/pb/nodestats.pb.go
  pkg/pb/nodestats.proto
  proto.lock
  satellite/nodestats/endpoint.go
Labels: Request Code Review, Sprint Release Goal, cla-signed

#2822 storagenode/piecestore: ignore canceled errors on download
  storagenode/piecestore/endpoint.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2853 satellite/marketingweb: fix broken pipe error
  satellite/marketingweb/server.go
  satellite/marketingweb/server_test.go
  web/marketing/pages/partner-offers-modal.html
  web/marketing/pages/referral-offers-modal.html
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2863 satellite/satellitedb: move tests near the interface
  satellite/console/usercredits_test.go
  satellite/repair/queue/queue2_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2800 satellite/rewards: add mongodb into partner info
  satellite/rewards/partners.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2837 design/docs: add successful pingback to kademlia removal document
  docs/design/kademlia-removal.md
Labels: Design Doc, Request Code Review, cla-signed

#2835 lib/uplinkc: ensure it compiles on 32bit arch
  lib/uplinkc/bucket.go
  lib/uplinkc/object.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2789 docs/design: automatic updater
  docs/design/storage-node-automatic-updater.md
Labels: Design Doc, Request Code Review, cla-signed

#2873 storagenode/vouchers: remove storagenode vouchers
  internal/testplanet/storagenode.go
  storagenode/peer.go
  storagenode/storagenodedb/database.go
  storagenode/storagenodedb/testdata/sqlite.v18.sql
  storagenode/storagenodedb/vouchers.go
  storagenode/vouchers/service.go
  storagenode/vouchers/verification.go
  storagenode/vouchers/vouchers_test.go
Labels: cla-signed

#2764 satellitedb/overlay: add database for storing peer identities
  satellite/overlay/peeridentities.go
  satellite/overlay/peeridentities_test.go
  satellite/peer.go
  satellite/satellitedb/database.go
  satellite/satellitedb/dbx/satellitedb.dbx
  satellite/satellitedb/dbx/satellitedb.dbx.go
  satellite/satellitedb/dbx/satellitedb.dbx.postgres.sql
  satellite/satellitedb/dbx/satellitedb.dbx.sqlite3.sql
  satellite/satellitedb/locked.go
  satellite/satellitedb/migrate.go
  satellite/satellitedb/peeridentities.go
  satellite/satellitedb/testdata/postgres.v54.sql
Labels: Request Code Review, cla-signed

#2876 cmd/*: Change loglevel from error to warn
  cmd/bootstrap/main.go
  cmd/gateway/main.go
  cmd/satellite/main.go
  cmd/storagenode/main.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2803 satellite/satellitedb: persist piece counts to/from db
  satellite/gc/piecetracker.go
  satellite/gc/service.go
  satellite/overlay/service.go
  satellite/satellitedb/dbx/satellitedb.dbx
  satellite/satellitedb/dbx/satellitedb.dbx.go
  satellite/satellitedb/locked.go
  satellite/satellitedb/overlaycache.go
  satellite/satellitedb/overlaycache_test.go
Labels: cla-signed

#2851 docs/design: Use WiX toolset directly instead of go-msi for Windows installer
  docs/design/storage-node-windows-installer.md
Labels: Design Doc, Request Code Review, cla-signed

#2881 lint: add linting for errs package
  Jenkinsfile.gerrit
  Jenkinsfile.public
  internal/post/oauth2/auth.go
  pkg/identity/identity.go
  scripts/check-errs.go
  uplink/ecclient/client.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#2884 design/docs: improvements to downtime doc
  docs/design/storagenode-downtime-tracking.md
Labels: cla-signed

#2887 satellite/gc: Service run must call mon.Task
  satellite/gc/service.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed
