Repository storj/storj, pull requests merged in 2019-11, with the labels that each got.

#3415 installer/windows: custom upgrade validation dialog
  installer/windows/CustomInstallDir.wxs
  installer/windows/StorjValidateUpgradeDlg.wxs
  installer/windows/StorjWelcomeDlg.wxs
  installer/windows/windows.wixproj
Labels: Request Code Review, cla-signed

#3437 satellite/gracefulexit: add flag for enabling/disabling graceful exit on the satellite
  internal/testplanet/satellite.go
  satellite/api.go
  satellite/gracefulexit/common.go
  satellite/gracefulexit/endpoint_test.go
  satellite/peer.go
  scripts/testdata/satellite-config.yaml.lock
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3447 storagenode/contact: fix panic in ping satellites
  storagenode/contact/chore.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3421 mobile: build gomobile in .build on Jenkins
  Jenkinsfile.public
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3424 web/satellite: text selection on specific elements disabled
  web/satellite/src/components/account/AccountArea.vue
  web/satellite/src/components/apiKeys/ApiKeysArea.vue
  web/satellite/src/components/apiKeys/ApiKeysCopyPopup.vue
  web/satellite/src/components/apiKeys/ApiKeysCreationPopup.vue
  web/satellite/src/components/apiKeys/SortingHeader.vue
  web/satellite/src/components/buckets/BucketArea.vue
  web/satellite/src/components/buckets/SortingHeader.vue
  web/satellite/src/components/common/EmptyStateArea.vue
  web/satellite/src/components/common/HeaderedInput.vue
  web/satellite/src/components/common/PagesBlock.vue
  web/satellite/src/components/common/RegistrationSuccessPopup.vue
  web/satellite/src/components/common/VButton.vue
  web/satellite/src/components/common/VDatePicker.vue
  web/satellite/src/components/header/headerArea.scss
  web/satellite/src/components/navigation/TabNavigation.vue
  web/satellite/src/components/navigation/navigationArea.scss
  web/satellite/src/components/project/ProjectDetails.vue
  web/satellite/src/components/project/UsageReport.vue
  web/satellite/src/components/team/AddUserPopup.vue
  web/satellite/src/components/team/HeaderArea.vue
  web/satellite/src/components/team/SortingListHeader.vue
  web/satellite/tests/unit/common/__snapshots__/VButton.spec.ts.snap
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3443 installer/windows: change the dialog image
  installer/windows/Product.wxs
  installer/windows/dialog.bmp
  installer/windows/dialog.png
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3446 satellite/satellitedb: update nodes in sorted order
  satellite/satellitedb/overlaycache.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3259 cmd/identity: allow using redis for RevocationDB
  cmd/identity/revocations.go
  cmd/storj-sim/main.go
  cmd/storj-sim/network.go
  pkg/revocation/common.go
  pkg/revocation/db_test.go
  scripts/test-sim-backwards.sh
  storage/redis/client.go
Labels: Request Code Review, cla-signed

#3451 cmd/storj-sim: add --redis flag
  cmd/storj-sim/main.go
  cmd/storj-sim/network.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3455 satellite/gracefulexit: check for unkown error in graceful exit disable test
  satellite/gracefulexit/endpoint_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3452 drpc: enable by default
  internal/testcontext/compile_drpc.go
  internal/testcontext/compile_nodrpc.go
  pkg/rpc/common_drpc.go
  pkg/rpc/common_grpc.go
  pkg/rpc/compat_drpc.go
  pkg/rpc/compat_grpc.go
  pkg/rpc/dial_drpc.go
  pkg/rpc/dial_grpc.go
  pkg/rpc/rpcpeer/peer_drpc.go
  pkg/rpc/rpcpeer/peer_grpc.go
  pkg/rpc/rpcstatus/status_drpc.go
  pkg/rpc/rpcstatus/status_grpc.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3457 satellite: make outgoing connections with grpc
  Makefile
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3436 satellitedb: separate migration into subcommand
  cmd/satellite/api.go
  cmd/satellite/entrypoint
  cmd/satellite/main.go
  cmd/satellite/repairer.go
  cmd/storj-sim/network.go
  cmd/storj-sim/process.go
  go.mod
  go.sum
  internal/migrate/versions.go
  satellite/peer.go
  satellite/satellitedb/migrate.go
  storage/postgreskv/schema/migrate.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3459 storagenode/updater: disable self-autoupdate
  cmd/storagenode-updater/main.go
  cmd/storagenode-updater/main_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3440 storagenode/updater: fix error when storagenode-updater service is stopped
  cmd/storagenode-updater/main.go
  cmd/storagenode-updater/windows.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3438 certificate: set max clock offset to 5 min instead of 15 sec
  certificate/authorization/authorizations.go
  certificate/authorization/authorizations_test.go
  certificate/authorization/db.go
  certificate/peer_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3448 satellite/payments: mock payment service created, api calls from frontend returned
  satellite/api.go
  satellite/payments/mockpayments/mockpayments.go
  satellite/payments/stripecoinpayments/service.go
  satellite/peer.go
  web/satellite/src/components/account/billing/AccountBalance.vue
  web/satellite/src/components/account/billing/CardDialog.vue
  web/satellite/src/components/account/billing/PaymentMethods.vue
  web/satellite/src/views/DashboardArea.vue
Labels: Request Code Review, Reviewer Can Merge, Sprint Release Goal, cla-signed

#3464 satellite/payments: archview comments updated
  satellite/payments/stripecoinpayments/customers.go
  satellite/payments/stripecoinpayments/service.go
  satellite/satellitedb/customers.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3458 cmd/storj-sim: allow user to designate which redis db they want to start at
  cmd/storj-sim/main.go
  cmd/storj-sim/network.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3465 satellite/satellitedb: console tables archview comments updated
  satellite/accounting/bucketusage.go
  satellite/accounting/bucketusage_test.go
  satellite/console/database.go
  satellite/satellitedb/apikeys.go
  satellite/satellitedb/bucketusage.go
  satellite/satellitedb/consoledb.go
  satellite/satellitedb/customers.go
  satellite/satellitedb/dbx/satellitedb.dbx
  satellite/satellitedb/dbx/satellitedb.dbx.go
  satellite/satellitedb/dbx/satellitedb.dbx.postgres.sql
  satellite/satellitedb/migrate.go
  satellite/satellitedb/projectmembers.go
  satellite/satellitedb/projects.go
  satellite/satellitedb/regtokens.go
  satellite/satellitedb/resetpasstokens.go
  satellite/satellitedb/testdata/postgres.v64.sql
  satellite/satellitedb/usagerollups.go
  satellite/satellitedb/usercredits.go
  satellite/satellitedb/users.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3401 storagenode/pieces: Add migration from v0 piece to v1 piece
  internal/testblobs/slow.go
  storage/blob.go
  storage/filestore/dir.go
  storage/filestore/store.go
  storagenode/pieces/store.go
  storagenode/pieces/store_test.go
Labels: cla-signed

#3450 Bump go version to 1.13.4
  Dockerfile.jenkins
  Makefile
Labels: cla-signed

#3474 update to the CLA file adding Rafael Gomes
  .clabot
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3472 satellite: change the Peer name to Core
  cmd/satellite/main.go
  cmd/storj-sim/network.go
  docs/blueprints/storage-node-downtime-tracking.md
  internal/testplanet/satellite.go
  satellite/core.go
  satellite/peer.go
  scripts/test-sim-backwards.sh
  storagenode/peer.go
Labels: cla-signed

#3439 certificates: move db test to separate file
  certificate/authorization/authorizations.go
  certificate/authorization/authorizations_test.go
  certificate/authorization/db.go
  certificate/authorization/db_test.go
  certificate/peer_test.go
Labels: Code Review In-Progress, Reviewer Can Merge, cla-signed

#3372 storagenode/contact: exponential backoff retries for pinging Satellites
  internal/testplanet/planet.go
  storagenode/contact/chore.go
  storagenode/contact/contact_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3477 storagenode/contact: change dev default for contact chore interval to 30s
  storagenode/contact/service.go
Labels: cla-signed

#3460 satellite/metainfo: don't allow uplink to commit same piece multiple times
  satellite/metainfo/metainfo_test.go
  satellite/metainfo/validation.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3480 satellite/audit: increase timeout to 5 minutes
  satellite/audit/worker.go
  scripts/testdata/satellite-config.yaml.lock
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3467 web/satellite: Pages lazy loading added
  web/satellite/src/router/index.ts
  web/satellite/vue.config.js
Labels: cla-signed

#3473 web/satellite: datepicker tests issue resolved
  web/satellite/src/components/common/VDatePicker.vue
  web/satellite/tests/unit/common/VDatePicker.spec.ts
Labels: cla-signed

#3462 web/satellite: added functionality to remove yourself from someone else's project
  web/satellite/src/components/team/HeaderArea.vue
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3444 web/satellite: removed redundant functionality from billing page
  web/satellite/src/components/account/billing/AccountBalance.vue
  web/satellite/src/components/account/billing/DepositAndBilling.vue
  web/satellite/src/components/account/billing/MonthlyBillingSummary.vue
  web/satellite/src/components/account/billing/PaymentMethods.vue
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3445 web/satellite: api keys copied state removed
  web/satellite/src/components/apiKeys/ApiKeysCopyPopup.vue
  web/satellite/tests/unit/apiKeys/ApiKeysCopyPopup.spec.ts
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3442 web/satellite scrollbars to navigation and billing page added
  web/satellite/src/components/account/AccountArea.vue
  web/satellite/src/components/account/ProfileArea.vue
  web/satellite/src/components/account/billing/AccountBalance.vue
  web/satellite/src/components/account/billing/BillingArea.vue
  web/satellite/src/components/account/billing/DepositAndBilling.vue
  web/satellite/src/components/navigation/navigationArea.scss
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3432 web/satellite: blinking before fetching PMs, APIkeys, buckets removed
  web/satellite/src/components/apiKeys/ApiKeysArea.vue
  web/satellite/src/components/buckets/BucketArea.vue
  web/satellite/src/components/team/HeaderArea.vue
  web/satellite/src/components/team/ProjectMemberListItem.vue
  web/satellite/src/components/team/ProjectMembersArea.vue
  web/satellite/tests/unit/projectMembers/__snapshots__/ProjectMemberListItem.spec.ts.snap
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3426 web/satellite: auth error messages fixed
  satellite/console/auth.go
  satellite/console/consoleweb/consoleapi/auth.go
  satellite/console/consoleweb/server.go
  web/satellite/src/api/auth.ts
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3449 web/satellite: info button added on PM page
  web/satellite/src/components/team/HeaderArea.vue
  web/satellite/static/images/team/infoTooltip.svg
  web/satellite/tests/unit/projectMembers/__snapshots__/HeaderArea.spec.ts.snap
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3275 satellite/rewards: ensure that partner information is asked from a service
  satellite/api.go
  satellite/console/consoleweb/consoleql/mutation_test.go
  satellite/console/consoleweb/consoleql/query_test.go
  satellite/console/service.go
  satellite/marketingweb/offers.go
  satellite/marketingweb/server.go
  satellite/rewards/partner.go
  satellite/rewards/partners.go
  satellite/rewards/partners_db_test.go
  satellite/rewards/partners_service.go
  satellite/rewards/partners_staticdb.go
  satellite/rewards/rewards.go
  satellite/rewards/rewards_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3468 satellite/payments: invoice creation
  cmd/inspector/main.go
  pkg/pb/payments.pb.go
  pkg/pb/payments.proto
  pkg/rpc/compat_drpc.go
  pkg/rpc/compat_grpc.go
  proto.lock
  satellite/api.go
  satellite/console/consoleweb/consoleql/mutation_test.go
  satellite/console/consoleweb/consoleql/query_test.go
  satellite/console/projects.go
  satellite/core.go
  satellite/payments/clearing.go
  satellite/payments/stripecoinpayments/accounts.go
  satellite/payments/stripecoinpayments/creditcards.go
  satellite/payments/stripecoinpayments/customers.go
  satellite/payments/stripecoinpayments/customers_test.go
  satellite/payments/stripecoinpayments/db.go
  satellite/payments/stripecoinpayments/endpoint.go
  satellite/payments/stripecoinpayments/invoices.go
  satellite/payments/stripecoinpayments/projectrecords.go
  satellite/payments/stripecoinpayments/projectrecords_test.go
  satellite/payments/stripecoinpayments/service.go
  satellite/payments/stripecoinpayments/tokens.go
  satellite/payments/stripecoinpayments/transactions_test.go
  satellite/peer.go
  satellite/satellitedb/coinpaymentstxs.go
  satellite/satellitedb/customers.go
  satellite/satellitedb/database.go
  satellite/satellitedb/dbx/satellitedb.dbx
  satellite/satellitedb/dbx/satellitedb.dbx.go
  satellite/satellitedb/dbx/satellitedb.dbx.postgres.sql
  satellite/satellitedb/invoiceprojectrecords.go
  satellite/satellitedb/migrate.go
  satellite/satellitedb/projects.go
  satellite/satellitedb/stripecoinpaymentsdb.go
  satellite/satellitedb/testdata/postgres.v65.sql
Labels: Request Code Review, Sprint Release Goal, cla-signed

#3469 cli: tools should exit with non-zero code in case of invalid flags
  pkg/process/exec_conf.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3482 installer/windows: change "Ethereum wallet address" label to "STORJ payout address"
  installer/windows/Storj/CustomAction.cs
  installer/windows/WalletConfig.wxs
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3483 installer/windows: fix hyperlink's background color on Welcome dialog
  installer/windows/StorjWelcomeDlg.wxs
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3456 satellite/gracefulexit: handle piece not found messages from storagenode
  satellite/gracefulexit/endpoint.go
  satellite/gracefulexit/endpoint_test.go
Labels: Request Code Review, cla-signed

#3478 storagenode/gracefulexit: allow storagenodes to concurrently transfer pieces for graceful exit
  internal/testplanet/storagenode.go
  storagenode/gracefulexit/chore.go
  storagenode/gracefulexit/common.go
  storagenode/gracefulexit/endpoint.go
  storagenode/gracefulexit/worker.go
Labels: Request Code Review, cla-signed

#3492 web/storagenode: text selection on specific elements disabled
  web/storagenode/src/app/components/BarInfo.vue
  web/storagenode/src/app/components/ChecksArea.vue
  web/storagenode/src/app/components/PayoutArea.vue
  web/storagenode/src/app/components/SNOContentFilling.vue
  web/storagenode/src/app/components/SNOContentTitle.vue
  web/storagenode/src/app/components/SNOFooter.vue
  web/storagenode/src/app/components/SNOHeader.vue
  web/storagenode/src/app/components/SatelliteSelection.vue
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3494 web/satellite: project description enhanced
  web/satellite/src/components/project/ProjectDetails.vue
  web/satellite/src/components/project/UsageReport.vue
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3502 Rebuild faster by removing weird make calls
  Makefile
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3434 satellite/gracefulexit: Check if node already has a piece in the pointer
  satellite/gracefulexit/endpoint.go
  satellite/gracefulexit/endpoint_test.go
  satellite/metainfo/metainfo.go
  satellite/metainfo/service.go
  satellite/metainfo/service_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3497 satellite/audit: do not audit expired segments
  satellite/audit/reverify_test.go
  satellite/audit/verifier.go
  satellite/audit/verifier_test.go
Labels: Bug, Request Code Review, cla-signed

#3501 makefile: add goversioninfo to build-dev-deps
  Makefile
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3488 satellite/peer: add payments config
  satellite/api.go
  satellite/console/consoleweb/server.go
  satellite/core.go
  satellite/peer.go
  scripts/testdata/satellite-config.yaml.lock
Labels: Request Code Review, Reviewer Can Merge, Sprint Release Goal, cla-signed

#3503 release: opt more binaries in to grpc
  Makefile
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3491 logging: unify logging around satellite ID, node ID and piece ID
  certificate/endpoint.go
  cmd/storagenode/gracefulexit.go
  satellite/contact/endpoint.go
  satellite/gc/service.go
  satellite/gracefulexit/endpoint.go
  satellite/gracefulexit/pathcollector.go
  satellite/metainfo/metainfo.go
  satellite/repair/repairer/ec.go
  storagenode/collector/service.go
  storagenode/contact/chore.go
  storagenode/gracefulexit/chore.go
  storagenode/gracefulexit/endpoint.go
  storagenode/gracefulexit/worker.go
  storagenode/pieces/store.go
  storagenode/piecestore/endpoint.go
  storagenode/retain/retain.go
  uplink/ecclient/client.go
  uplink/storage/streams/store.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3505 release: use /usr/bin/env echo
  Makefile
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3353 Storage Node Satellite Selection design
  docs/blueprints/storage-node-satellite-selection.md
Labels: Design Doc, Request Code Review, cla-signed

#3509 test/backwards-compatibility: fix port change
  scripts/test-sim-backwards.sh
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3510 internal/dbutil/pgutil: retry create schema on a concurrent call
  internal/dbutil/pgutil/schema.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3496 web/satellite: tabs title change
  satellite/console/consoleweb/server.go
  web/satellite/index.html
  web/satellite/src/App.vue
  web/satellite/src/api/auth.ts
  web/satellite/src/router/index.ts
  web/satellite/src/store/index.ts
  web/satellite/src/store/modules/apiKeys.ts
  web/satellite/src/store/modules/appState.ts
  web/satellite/src/store/modules/buckets.ts
  web/satellite/src/store/modules/notifications.ts
  web/satellite/src/store/modules/payments.ts
  web/satellite/src/store/modules/projectMembers.ts
  web/satellite/src/store/modules/projects.ts
  web/satellite/src/store/modules/usage.ts
  web/satellite/src/store/mutationConstants.ts
  web/satellite/src/utils/constants/actionNames.ts
Labels: cla-signed

#3490 web/storagenode: satellite dropdown enhanced
  web/storagenode/src/app/App.vue
  web/storagenode/src/app/components/SatelliteSelection.vue
  web/storagenode/src/app/components/SatelliteSelectionDropdown.vue
  web/storagenode/src/app/store/modules/appState.ts
  web/storagenode/src/main.ts
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3484 web/satellite: menu closing on small windows
  web/satellite/src/components/header/headerArea.html
Labels: cla-signed

#3097 jenkins: use lower segment size for back comp test
  scripts/test-backwards.sh
  scripts/test-sim-backwards.sh
  scripts/test-sim.sh
  scripts/test-uplink.sh
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3508 storj-sim: add rollout seed to avoid warnings
  cmd/storj-sim/network.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3514 web/satellite: token error status code fixed
  web/satellite/src/api/auth.ts
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3310 cmd/uplink: add metadata access
  cmd/uplink/cmd/cp.go
  cmd/uplink/cmd/meta.go
  cmd/uplink/cmd/meta_get.go
  cmd/uplink/cmd/meta_test.go
  internal/testrand/rand.go
Labels: Request Code Review, cla-signed

#3513 satellite/metainfo: fix some uses of metainfo.Delete
  satellite/audit/reverify_test.go
  satellite/audit/verifier.go
  satellite/audit/verifier_test.go
  satellite/gc/gc_test.go
  satellite/gracefulexit/endpoint_test.go
  satellite/metainfo/metainfo.go
  satellite/metainfo/service.go
  satellite/repair/checker/checker_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3516 web/satellite: gzip bug fixed
  web/satellite/vue.config.js
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3495 satellite/rewards: fixes from review comments
  satellite/console/consoleweb/consoleql/mutation_test.go
  satellite/console/service.go
  satellite/marketingweb/offers.go
  satellite/rewards/partner.go
  satellite/rewards/partners_service.go
  satellite/rewards/partners_staticdb.go
  satellite/rewards/rewards.go
  satellite/satellitedb/offers.go
  satellite/satellitedb/usercredits.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3506 makefile: bump drpc and build storj-sim binaries like release
  Makefile
  go.mod
  go.sum
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3435 satellite/gracefulexit: select new node filtered by IP
  internal/testplanet/reconfigure.go
  internal/testplanet/storagenode.go
  satellite/gracefulexit/endpoint.go
  satellite/overlay/selection_test.go
  satellite/overlay/service.go
  satellite/satellitedb/overlaycache.go
Labels: Request Code Review, cla-signed

#3517 pkg/rpc: fix grpc dial timeouts
  pkg/rpc/dial_grpc.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3486 cmd/storagenode-updater: TODO cleanup
  cmd/storagenode-updater/main_test.go
Labels: Code Review In-Progress, Reviewer Can Merge, cla-signed

#3511 uplink: Suppress one metainfo call on delete
  lib/uplink/bucket.go
  pkg/miniogw/gateway_test.go
  pkg/storj/metainfo.go
  uplink/metainfo/kvmetainfo/objects.go
  uplink/metainfo/kvmetainfo/objects_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3493 satellite/gracefulexit: not allow disqualified node to graceful exit
  satellite/gracefulexit/endpoint.go
  satellite/gracefulexit/endpoint_test.go
  satellite/satellitedb/overlaycache.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3527 web/satellite: credit cards icons selection added
  web/satellite/.env.example
  web/satellite/src/components/account/billing/CardComponent.vue
  web/satellite/static/images/payments/cardIcons/americanexpress.svg
  web/satellite/static/images/payments/cardIcons/default.svg
  web/satellite/static/images/payments/cardIcons/dinersclub.svg
  web/satellite/static/images/payments/cardIcons/discover.svg
  web/satellite/static/images/payments/cardIcons/jcb.svg
  web/satellite/static/images/payments/cardIcons/mastercard.svg
  web/satellite/static/images/payments/cardIcons/unionpay.svg
  web/satellite/static/images/payments/cardIcons/visa.svg
Labels: cla-signed

#3518 web/satellite: usage report date selected date range formatted
  web/satellite/src/components/project/UsageReport.vue
  web/satellite/src/utils/datepicker.ts
  web/satellite/tests/unit/utils/datepicker.spec.ts
Labels: cla-signed

#3515 web/satellite: name hint
  web/satellite/src/components/apiKeys/ApiKeysItem.vue
  web/satellite/src/components/buckets/BucketItem.vue
  web/satellite/src/components/team/ProjectMemberListItem.vue
  web/satellite/src/types/projectMembers.ts
  web/satellite/tests/unit/apiKeys/__snapshots__/ApiKeysItem.spec.ts.snap
  web/satellite/tests/unit/projectMembers/__snapshots__/ProjectMemberListItem.spec.ts.snap
Labels: cla-signed

#3476 satellite/gracefulexit: separate functional code
  monkit.lock
  satellite/gracefulexit/common.go
  satellite/gracefulexit/endpoint.go
  satellite/gracefulexit/validation.go
Labels: Request Code Review, cla-signed

#3521 installer/windows: unit tests for C# custom actions (part 1)
  installer/windows/.gitignore
  installer/windows/Storj/CustomAction.cs
  installer/windows/StorjTests/ExpectedExceptionWithMessage.cs
  installer/windows/StorjTests/ExtractInstallDirTests.cs
  installer/windows/StorjTests/Properties/AssemblyInfo.cs
  installer/windows/StorjTests/StorjTests.csproj
  installer/windows/StorjTests/ValidateBandwidthTests.cs
  installer/windows/StorjTests/ValidateIdentityDirTests.cs
  installer/windows/StorjTests/ValidateStorageDirTests.cs
  installer/windows/StorjTests/ValidateStorageTests.cs
  installer/windows/StorjTests/ValidateWalletTests.cs
  installer/windows/StorjTests/packages.config
  installer/windows/build.bat
  installer/windows/unittests.bat
  installer/windows/windows.sln
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3535 certificate/signing: increase min required difficulty to 36
  certificate/peer.go
  cmd/identity/batch.go
  pkg/identity/certificate_authority.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3528 web/satellite: detailed usage charges info markup
  web/satellite/src/components/account/billing/BillingArea.vue
  web/satellite/src/components/account/billing/balance/AccountBalance.vue
  web/satellite/src/components/account/billing/depositAndBilling/BillingHistory.vue
  web/satellite/src/components/account/billing/depositAndBilling/BillingItem.vue
  web/satellite/src/components/account/billing/depositAndBilling/DepositAndBilling.vue
  web/satellite/src/components/account/billing/depositAndBilling/SortingHeader.vue
  web/satellite/src/components/account/billing/monthlySummary/MonthlyBillingSummary.vue
  web/satellite/src/components/account/billing/monthlySummary/UsageChargeItem.vue
  web/satellite/src/components/account/billing/paymentMethods/CardComponent.vue
  web/satellite/src/components/account/billing/paymentMethods/CardDialog.vue
  web/satellite/src/components/account/billing/paymentMethods/PaymentMethods.vue
  web/satellite/src/components/account/billing/paymentMethods/StorjInput.vue
  web/satellite/src/components/account/billing/paymentMethods/StripeInput.vue
  web/satellite/src/router/index.ts
Labels: Reviewer Can Merge, cla-signed

#3537 web/satellite: api keys sorting header styles fixed
  web/satellite/src/components/apiKeys/SortingHeader.vue
Labels: cla-signed

#3525 lib/uplinkc: add clarifying comments to download_read
  lib/uplinkc/object.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3539 internal/testplanet: better error message when postgres is not defined
  internal/testplanet/planet.go
  satellite/satellitedb/satellitedbtest/pgschema.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3429 uplink/storage/streams: Upload loop operations reorganization
  uplink/storage/streams/store.go
Labels: Request Code Review, cla-signed

#3461 docs/design: zombie segments cleaner
  docs/blueprints/zombie-segments-cleaner.md
Labels: Design Doc, Request Code Review, cla-signed

#3500 satellite/console: add token deposit API, populate billing history with transactions
  satellite/console/billinghistoryitem.go
  satellite/console/consoleweb/consoleapi/payments.go
  satellite/console/consoleweb/server.go
  satellite/console/service.go
  satellite/core.go
  satellite/payments/coinpayments/amount.go
  satellite/payments/coinpayments/transactions.go
  satellite/payments/coinpayments/urls.go
  satellite/payments/coinpayments/urls_test.go
  satellite/payments/mockpayments/mockpayments.go
  satellite/payments/stripecoinpayments/tokens.go
  satellite/payments/stripecoinpayments/transactions.go
  satellite/payments/tokens.go
  satellite/satellitedb/coinpaymentstxs.go
  satellite/satellitedb/dbx/satellitedb.dbx
  satellite/satellitedb/dbx/satellitedb.dbx.go
Labels: Request Code Review, cla-signed

#3498 pkg/{cfgstruct,identity}: replace seperator in default values when path tag set
  pkg/cfgstruct/bind.go
  pkg/identity/identity.go
Labels: Code Review In-Progress, Request Code Review, Reviewer Can Merge, cla-signed

#3540 satellite/console: auth API error handling refactored
  satellite/console/consoleweb/consoleapi/auth.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3519 web/storagenode: date and data formating fixed
  web/storagenode/src/app/components/BandwidthChart.vue
  web/storagenode/src/app/components/DiskSpaceChart.vue
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3470 web/satellite: saving selected project in local storage implemented
  web/satellite/src/components/common/RegistrationSuccessPopup.vue
  web/satellite/src/components/header/AccountDropdown.vue
  web/satellite/src/components/header/projectSelection/ProjectSelectionDropdown.vue
  web/satellite/src/components/project/ProjectDetails.vue
  web/satellite/src/utils/consoleLocalStorage.ts
  web/satellite/src/utils/localData.ts
  web/satellite/src/views/DashboardArea.vue
  web/satellite/src/views/register/RegisterArea.vue
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3487 cmd/storagenode-updater: simplify and reorder update sqeuence
  cmd/storagenode-updater/main.go
  internal/version/checker/client.go
  internal/version/checker/client_test.go
Labels: Code Review In-Progress, Reviewer Can Merge, cla-signed

#3419 web/satellite no buckets page reworked
  web/satellite/src/components/buckets/NoBucketsArea.vue
  web/satellite/static/images/buckets/noBucketState/arrow.svg
  web/satellite/static/images/buckets/noBucketState/button.svg
  web/satellite/static/images/buckets/noBucketState/dots.svg
  web/satellite/static/images/buckets/noBucketState/folder.svg
  web/satellite/static/images/buckets/noBucketState/one.svg
  web/satellite/static/images/buckets/noBucketState/three.svg
  web/satellite/static/images/buckets/noBucketState/two.svg
  web/satellite/static/images/buckets/noBucketState/uplink.svg
  web/satellite/static/images/buckets/noBucketState/usage.svg
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3489 satellite: adding proper headers to api responses
  satellite/console/consoleweb/consoleapi/auth.go
  satellite/console/consoleweb/consoleapi/payments.go
  satellite/console/consoleweb/server.go
Labels: cla-signed

#3538 satellite/console: service error types added, error handling fixed
  satellite/console/consoleweb/consoleql/consoleerrors.go
  satellite/console/consoleweb/consoleql/consoleerrors_test.go
  satellite/console/service.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3522 satellite/rewards: use base32 instead of base64+json
  satellite/rewards/partners_service.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3526 lib/uplinkc: add additional fields to UplinkConfig
  lib/uplinkc/uplink.go
  lib/uplinkc/uplink_definitions.h
Labels: cla-signed

#3552 Initialize math/rand default source
  pkg/process/rand.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3554 Add stage name to slack error message
  Jenkinsfile
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3553 Unhook jenkins from the staging (dev) cluster
  Jenkinsfile
  Makefile
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3507 storage/filestore: monkit event for delete queuing
  storage/filestore/dir.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3556 pkg/rpc: generate drpc/grpc tags correctly
  pkg/rpc/gen.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3475 {certificates,pkg/rpcstatus}: improve error logging
  certificate/authorization/authorizations.go
  certificate/authorization/db.go
  certificate/authorization/db_test.go
  certificate/authorization/service.go
  certificate/authorization/service_test.go
  certificate/endpoint.go
  cmd/identity/main.go
  internal/errs2/sanatizer.go
  internal/errs2/sanitizer_test.go
Labels: Code Review In-Progress, Request Code Review, Reviewer Can Merge, cla-signed

#3544 satellite/gracefulexit: add count for order limits sent from satellite to exiting node
  internal/testplanet/satellite.go
  satellite/gracefulexit/common.go
  satellite/gracefulexit/db.go
  satellite/gracefulexit/db_test.go
  satellite/gracefulexit/endpoint.go
  satellite/gracefulexit/endpoint_test.go
  satellite/satellitedb/dbx/satellitedb.dbx
  satellite/satellitedb/dbx/satellitedb.dbx.go
  satellite/satellitedb/dbx/satellitedb.dbx.postgres.sql
  satellite/satellitedb/gracefulexit.go
  satellite/satellitedb/migrate.go
  satellite/satellitedb/testdata/postgres.v67.sql
  scripts/testdata/satellite-config.yaml.lock
Labels: Request Code Review, cla-signed

#3559 certificate: close authDB in tests
  certificate/authorization/endpoint_test.go
  certificate/authorization/service_test.go
  certificate/peer_test.go
  versioncontrol/peer_test.go
Labels: Code Review In-Progress, Reviewer Can Merge, cla-signed

#3557 storagenode/gracefulexit: get hash and limit using original piece ID
  storagenode/gracefulexit/worker.go
Labels: Request Code Review, cla-signed

#3364 Keep v0pieceinfo database isolated
  internal/testblobs/slow.go
  storage/blob.go
  storage/filestore/blob.go
  storage/filestore/store.go
  storage/filestore/store_test.go
  storagenode/gracefulexit/worker.go
  storagenode/pieces/store.go
  storagenode/piecestore/endpoint.go
  storagenode/retain/retain_test.go
  storagenode/storagenodedb/database.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3564 storage/postgreskv: fix ultra-slow nonrecursive list
  storage/postgreskv/client_test.go
  storage/postgreskv/schema/2019111301_fix_seq_scans_in_list.down.sql
  storage/postgreskv/schema/2019111301_fix_seq_scans_in_list.up.sql
  storage/postgreskv/schema/data.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3569 lint: add staticcheck as a separate step
  Dockerfile.jenkins
  Jenkinsfile.public
  certificate/authorization/authorizations_test.go
  cmd/statreceiver/luacfg/cfg.go
  cmd/storagenode-updater/windows.go
  cmd/storagenode/windows.go
  cmd/uplink/cmd/cat.go
  cmd/uplink/cmd/cp.go
  cmd/uplink/cmd/ls.go
  cmd/uplink/cmd/mb.go
  cmd/uplink/cmd/meta_get.go
  cmd/uplink/cmd/put.go
  cmd/uplink/cmd/rb.go
  cmd/uplink/cmd/rm.go
  cmd/uplink/cmd/root.go
  internal/dbutil/split.go
  internal/fpath/editor.go
  internal/fpath/os.go
  internal/testcontext/compile.go
  lib/uplink/project_test.go
  satellite/accounting/live/memory.go
  satellite/console/consoleweb/server.go
  satellite/console/users_test.go
  satellite/metainfo/validation.go
  satellite/overlay/selection_test.go
  satellite/satellitedb/dbx/gen.go
  satellite/satellitedb/dbx/satellitedb.dbx.go
  storage/postgreskv/schema/data.go
  storage/postgreskv/schema/migrate.go
  storage/teststore/store.go
  storagenode/gracefulexit/worker.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3543 installer/windows: unit test mocking file system
  installer/windows/Storj/CustomAction.cs
  installer/windows/Storj/Storj.csproj
  installer/windows/Storj/packages.config
  installer/windows/StorjTests/ExtractInstallDirTests.cs
  installer/windows/StorjTests/MockHelpers.cs
  installer/windows/StorjTests/StorjTests.csproj
  installer/windows/StorjTests/ValidateBandwidthTests.cs
  installer/windows/StorjTests/ValidateIdentityDirTests.cs
  installer/windows/StorjTests/ValidateStorageDirTests.cs
  installer/windows/StorjTests/ValidateStorageTests.cs
  installer/windows/StorjTests/ValidateWalletTests.cs
  installer/windows/StorjTests/packages.config
  installer/windows/unittests.bat
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3542 cmd/storagenode-updater: make updater test windows compatible
  cmd/storagenode-updater/main.go
  cmd/storagenode-updater/main_test.go
  cmd/storagenode-updater/restart.go
  cmd/storagenode-updater/restart_mock.go
  cmd/storagenode-updater/windows.go
  internal/testcontext/compile.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3570 scripts: add script to update tools
  Dockerfile.jenkins
  scripts/update-tools.sh
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3571 storagenode/storagenodedb: don't log opening of each database
  storagenode/storagenodedb/database.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3562 cmd: skeleton for segment-reaper detect command
  cmd/segment-reaper/detect.go
  cmd/segment-reaper/main.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3561 pkg/pb: add referral manager protobuf definition
  pkg/pb/referralmanager.pb.go
  pkg/pb/referralmanager.proto
  pkg/rpc/compat_drpc.go
  pkg/rpc/compat_grpc.go
  proto.lock
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3549 web/satellite: static pages styling fixed
  web/satellite/static/activation/activated.css
  web/satellite/static/activation/activated.html
  web/satellite/static/errors/404.css
  web/satellite/static/errors/404.html
  web/satellite/static/errors/500.css
  web/satellite/static/errors/500.html
  web/satellite/static/resetPassword/resetPassword.css
  web/satellite/static/resetPassword/resetPassword.html
  web/satellite/static/resetPassword/success.css
  web/satellite/static/resetPassword/success.html
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3529 storage/filestore: Add Trash and RestoreTrash to Blobs
  private/testblobs/slow.go
  storage/blob.go
  storage/filestore/dir.go
  storage/filestore/store.go
  storage/filestore/store_test.go
Labels: cla-signed

#3555 uplink/storage/streams: Fix upload error clean up
  uplink/storage/streams/store.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3568 libuplink: remove additional GetBucket for upload/download
  lib/uplink/bucket.go
  lib/uplink/object.go
  pkg/miniogw/gateway_test.go
  pkg/storj/metainfo.go
  uplink/metainfo/kvmetainfo/objects.go
  uplink/metainfo/kvmetainfo/objects_test.go
Labels: Request Code Review, cla-signed

#3577 SNOboard/console: router changed for gorillaMux, caching added
  storagenode/console/consoleserver/server.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3579 satellite/metainfo: avoid large conditional block
  satellite/metainfo/metainfo.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3512 satellite/payments: project usage charges
  private/testplanet/satellite.go
  satellite/accounting/db.go
  satellite/accounting/projectusage.go
  satellite/accounting/projectusage_test.go
  satellite/api.go
  satellite/console/consoleweb/consoleapi/payments.go
  satellite/console/consoleweb/consoleql/mutation_test.go
  satellite/console/consoleweb/consoleql/project.go
  satellite/console/consoleweb/consoleql/query_test.go
  satellite/console/consoleweb/server.go
  satellite/console/database.go
  satellite/console/projects.go
  satellite/console/service.go
  satellite/console/usagerollups.go
  satellite/console/usagerollups_test.go
  satellite/core.go
  satellite/metainfo/metainfo.go
  satellite/payments/account.go
  satellite/payments/mockpayments/mockpayments.go
  satellite/payments/paymentsconfig/config.go
  satellite/payments/projectchardges.go
  satellite/payments/stripecoinpayments/accounts.go
  satellite/payments/stripecoinpayments/service.go
  satellite/satellitedb/consoledb.go
  satellite/satellitedb/dbx/satellitedb.dbx
  satellite/satellitedb/dbx/satellitedb.dbx.go
  satellite/satellitedb/projectaccounting.go
  satellite/satellitedb/projects.go
  satellite/satellitedb/usagerollups.go
  scripts/testdata/satellite-config.yaml.lock
  web/satellite/.env
  web/satellite/src/api/payments.ts
  web/satellite/src/components/project/UsageReport.vue
  web/satellite/src/types/payments.ts
  web/satellite/src/types/usage.ts
  web/satellite/src/views/DashboardArea.vue
Labels: Request Code Review, Reviewer Can Merge, Sprint Release Goal, cla-signed

#3425 storagenode/updater: recover command in Service Manager
  cmd/storagenode-updater/main.go
  cmd/storagenode-updater/windows.go
  installer/windows/Product.wxs
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3530 satellite/payments: add API for retrieving conversion ratio, convert tokens to USD before applying to balance
  satellite/api.go
  satellite/payments/coinpayments/client.go
  satellite/payments/coinpayments/conversionrates.go
  satellite/payments/coinpayments/currency.go
  satellite/payments/coinpayments/transactions.go
  satellite/payments/stripecoinpayments/service.go
  satellite/payments/stripecoinpayments/tokens.go
  satellite/payments/stripecoinpayments/transactions.go
  satellite/payments/stripecoinpayments/transactions_test.go
  satellite/payments/stripecoinpayments/version.go
  satellite/payments/tokens.go
  satellite/satellitedb/coinpaymentstxs.go
  satellite/satellitedb/dbx/satellitedb.dbx
  satellite/satellitedb/dbx/satellitedb.dbx.go
  satellite/satellitedb/dbx/satellitedb.dbx.postgres.sql
  satellite/satellitedb/migrate.go
  satellite/satellitedb/testdata/postgres.v68.sql
  satellite/satellitedb/testdata/postgres.v69.sql
  scripts/testdata/satellite-config.yaml.lock
Labels: Request Code Review, cla-signed

#3582 satellite/payments: switch to using STORJ tokens
  satellite/payments/stripecoinpayments/tokens.go
Labels: Request Code Review, Sprint Release Goal, cla-signed

#3550 web/satellite: redirecting condition for universal login page added
  web/satellite/src/views/login/LoginArea.vue
Labels: Request Code Review, cla-signed

#3585 pkg/pb: remove unneeded proto imports
  pkg/pb/certificate.pb.go
  pkg/pb/certificate.proto
  pkg/pb/encryption_access.pb.go
  pkg/pb/encryption_access.proto
  pkg/pb/overlay.pb.go
  pkg/pb/overlay.proto
  pkg/pb/pointerdb.pb.go
  pkg/pb/pointerdb.proto
  pkg/pb/referralmanager.pb.go
  pkg/pb/referralmanager.proto
  pkg/pb/scope.pb.go
  pkg/pb/scope.proto
  proto.lock
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3567 satellite/nodeselection: don't select nodes that haven't checked in for a while
  private/testplanet/satellite.go
  private/testplanet/uplink_test.go
  satellite/audit/disqualification_test.go
  satellite/contact/endpoint.go
  satellite/overlay/benchmark_test.go
  satellite/overlay/service.go
  satellite/overlay/service_test.go
  satellite/overlay/statdb_test.go
  satellite/repair/repair_test.go
  satellite/satellitedb/overlaycache.go
  uplink/storage/segments/store.go
Labels: Help Wanted, cla-signed

#3588 storagenode-updater: re-enable auto-update storagenode-updater
  cmd/storagenode-updater/main.go
  cmd/storagenode-updater/main_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3560 satellite: added ability to inject stripe public key post build
  satellite/api.go
  satellite/console/consoleweb/server.go
  satellite/console/service.go
  satellite/payments/stripecoinpayments/service.go
  scripts/testdata/satellite-config.yaml.lock
  web/satellite/.env
  web/satellite/index.html
  web/satellite/src/App.vue
  web/satellite/src/api/auth.ts
  web/satellite/src/components/account/billing/paymentMethods/StripeInput.vue
  web/satellite/src/utils/meta.ts
  web/satellite/src/views/DashboardArea.vue
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3584 web/satellite: short name field removed from registration page
  web/satellite/src/views/register/RegisterArea.vue
  web/satellite/src/views/register/registerArea.html
Labels: cla-signed

#3578 metainfo/loop: refactor iterator to be reusable
  satellite/metainfo/loop.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3576 cmd/segment-reaper: add iteration over DB
  cmd/segment-reaper/detect.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3597 satellite/repair: reduce upload timeout
  satellite/repair/repairer/repairer.go
  scripts/testdata/satellite-config.yaml.lock
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3593 pkg/pb/referralmanager: update RedeemTokenRequest, rm ReserveToken
  pkg/pb/referralmanager.pb.go
  pkg/pb/referralmanager.proto
  proto.lock
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3520 docs/blueprints: Deletion performance
  docs/blueprints/deletion-performance.md
Labels: Design Doc, Request Code Review, Reviewer Can Merge, cla-signed

#3602 storagenode/console: show satellite url in satellite selection
  satellite/console/consoleweb/server.go
  storagenode/console/service.go
  web/storagenode/src/app/components/SatelliteSelection.vue
  web/storagenode/src/app/components/SatelliteSelectionDropdown.vue
  web/storagenode/src/storagenode/api/storagenode.ts
  web/storagenode/src/storagenode/dashboard.ts
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3596 uplink/metainfo: remove GetObject from download Batch
  pkg/storj/object.go
  uplink/metainfo/client.go
  uplink/metainfo/kvmetainfo/objects.go
  uplink/metainfo/kvmetainfo/prefixed.go
  uplink/storage/objects/store.go
  uplink/storage/streams/shim.go
  uplink/storage/streams/store.go
  uplink/storage/streams/store_test.go
  uplink/stream/download.go
Labels: Request Code Review, cla-signed

#3601 docs/blueprints: Change adapt endpoint by creating
  docs/blueprints/deletion-performance.md
Labels: Design Doc, Request Code Review, Reviewer Can Merge, cla-signed

#3604 piecestore: Fix invalid comment and typos
  storagenode/piecestore/endpoint_test.go
  uplink/piecestore/client.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3592 satellite/audit: do not contain nodes for unknown errors
  monkit.lock
  private/testblobs/bad.go
  satellite/audit/reporter.go
  satellite/audit/reverify_test.go
  satellite/audit/verifier.go
  satellite/audit/verifier_test.go
  satellite/audit/worker.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3603 satellite/payments: stripe client use satellite logger, give credits when applying transaction to balance
  satellite/console/service.go
  satellite/payments/stripecoinpayments/service.go
Labels: Request Code Review, cla-signed

#3610 storagenode: add new metric satellite.request
  monkit.lock
  storagenode/contact/chore.go
  storagenode/gracefulexit/chore.go
Labels: cla-signed

#3605 web/satellite: project selection dropdown bug fixed
  web/satellite/src/components/header/projectSelection/ProjectSelectionDropdown.vue
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3611 web/satellite: project charges
  satellite/console/consoleweb/consoleapi/payments.go
  satellite/payments/projectchardges.go
  satellite/payments/stripecoinpayments/accounts.go
  web/satellite/src/api/payments.ts
  web/satellite/src/components/account/billing/monthlySummary/MonthlyBillingSummary.vue
  web/satellite/src/components/account/billing/monthlySummary/UsageChargeItem.vue
  web/satellite/src/main.ts
  web/satellite/src/store/modules/payments.ts
  web/satellite/src/types/payments.ts
  web/satellite/src/views/DashboardArea.vue
Labels: Request Code Review, Reviewer Can Merge, Sprint Release Goal, cla-signed

#3612 web/satellite: successful reset password page styling bug fixed
  web/satellite/static/resetPassword/success.html
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3572 scripts: make update-tools.sh more verbose
  scripts/update-tools.sh
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3613 storagenode/collect: delete pieces 24 hours after expiration
  storagenode/collector/service.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3575 storagenode/pieces: Add Trash and RestoreTrash to piecestore
  pkg/pb/piecestore2.pb.go
  pkg/pb/piecestore2.proto
  private/testplanet/uplink_test.go
  proto.lock
  storagenode/pieces/store.go
  storagenode/pieces/store_test.go
  storagenode/piecestore/endpoint.go
  storagenode/retain/retain.go
  storagenode/retain/retain_test.go
  storagenode/storagenodedb/database.go
  storagenode/storagenodedb/pieceexpiration.go
  storagenode/storagenodedb/testdata/multidbsnapshot.go
  storagenode/storagenodedb/testdata/v26.go
Labels: cla-signed

#3616 satellite/metainfo: Don't return error in loop when path has less than 4 parts
  satellite/metainfo/loop.go
Labels: Bug, cla-signed
