Repository storj/storj, pull requests merged in 2020-11, with the labels that each got.

#3959 chore: fix typos in the documentation
  docs/blueprints/access-revocation.md
  docs/blueprints/cache-node-selection.md
  docs/blueprints/linux-setup.md
  docs/blueprints/password-key-derivation.md
  docs/blueprints/repair-with-hashes.md
  docs/blueprints/satellite-billing-system.md
  docs/blueprints/storage-node-satellite-selection.md
  docs/blueprints/storagenode-graceful-exit/overview.md
  docs/blueprints/storagenode-graceful-exit/protocol.md
  web/satellite/README.md
Labels: cla-signed

#3964 .clabot: clarify the cla message
  .clabot
Labels: Reviewer Can Merge, cla-signed

#3967 update partners to include MAXN per our teams request
  satellite/rewards/partners.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3968 build: use go v1.15.4
  Jenkinsfile
  Makefile
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3966 web/satellite: access grant routing
  web/satellite/src/components/accessGrants/AccessGrants.vue
  web/satellite/src/components/accessGrants/ProgressBar.vue
  web/satellite/src/components/accessGrants/steps/CreateAccessNameStep.vue
  web/satellite/src/components/accessGrants/steps/CreateAccessPassphraseStep.vue
  web/satellite/src/components/accessGrants/steps/CreateAccessPermissionsStep.vue
  web/satellite/src/components/accessGrants/steps/CreateAccessUplinkStep.vue
  web/satellite/src/router/index.ts
Labels: cla-signed

#3970 web/satellite:access grant empty state
  web/satellite/src/components/accessGrants/AccessGrants.vue
  web/satellite/src/components/accessGrants/EmptyState.vue
  web/satellite/static/images/accessGrants/access-grants-bg.png
  web/satellite/static/images/accessGrants/key.svg
Labels: cla-signed

#3971 jenkins/rollingupgrade: sleep 5 seconds between old api startup and database migration
  scripts/tests/rollingupgrade/test-sim-rolling-upgrade.sh
Labels: cla-signed

#3972 web/satellite:access grant date picker
  web/satellite/package-lock.json
  web/satellite/package.json
  web/satellite/src/components/accessGrants/permissions/DurationPicker.vue
  web/satellite/src/components/accessGrants/permissions/DurationSelection.vue
  web/satellite/src/components/accessGrants/steps/PermissionsStep.vue
Labels: cla-signed

#3978 web/satellite: create acces grant: duration selection logic
  web/satellite/src/components/accessGrants/permissions/DurationPicker.vue
  web/satellite/src/components/accessGrants/permissions/DurationSelection.vue
  web/satellite/src/components/accessGrants/steps/PermissionsStep.vue
Labels: cla-signed

#3977 Fixed typos in downtime tracking with audits doc
  docs/blueprints/storage-node-downtime-tracking-with-audits.md
Labels: cla-signed
