Repository storj/storj, pull requests merged in 2020-12, with the labels that each got.

#3983 Allow for DB application names per process.
  cmd/satellite/admin.go
  cmd/satellite/api.go
  cmd/satellite/billing.go
  cmd/satellite/compensation.go
  cmd/satellite/gc.go
  cmd/satellite/gracefulexit.go
  cmd/satellite/main.go
  cmd/satellite/repairer.go
  cmd/satellite/reports/attribution.go
  cmd/satellite/usage.go
  cmd/segment-reaper/delete.go
  cmd/segment-reaper/detect.go
  multinode/multinodedb/database.go
  private/dbutil/pgutil/db.go
  satellite/metainfo/config.go
  satellite/satellitedb/database.go
  satellite/satellitedb/migrate_test.go
  satellite/satellitedb/satellitedbtest/run.go
  storage/cockroachkv/client.go
  storage/postgreskv/client.go
  storage/postgreskv/client_test.go
Labels: Request Code Review, cla-signed

#3984 Allow for DB application names per process. (#3983)
  cmd/satellite/admin.go
  cmd/satellite/api.go
  cmd/satellite/billing.go
  cmd/satellite/compensation.go
  cmd/satellite/gc.go
  cmd/satellite/gracefulexit.go
  cmd/satellite/main.go
  cmd/satellite/repairer.go
  cmd/satellite/reports/attribution.go
  cmd/satellite/usage.go
  cmd/segment-reaper/delete.go
  cmd/segment-reaper/detect.go
  multinode/multinodedb/database.go
  private/dbutil/pgutil/db.go
  satellite/metainfo/config.go
  satellite/satellitedb/database.go
  satellite/satellitedb/migrate_test.go
  satellite/satellitedb/satellitedbtest/run.go
  storage/cockroachkv/client.go
  storage/postgreskv/client.go
  storage/postgreskv/client_test.go
Labels: Request Code Review, cla-signed

#3986 cmd: add ca-certificates to Docker images
  cmd/satellite/Dockerfile
  cmd/storagenode/Dockerfile
  cmd/uplink/Dockerfile
  resources/certs.pem
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3982 web/satellite: dashboard lag message tooltip
  web/satellite/src/components/project/ProjectDashboard.vue
  web/satellite/static/images/common/infoTooltipSm.svg
  web/satellite/static/images/tooltipMessageBg.png
  web/satellite/tests/unit/project/__snapshots__/ProjectDashboard.spec.ts.snap
Labels: cla-signed

#3989 .clabot: adding Doom4535 to approved list
  .clabot
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3987 Changed ChecksArea.vue audits/checks precision
  web/storagenode/src/app/components/ChecksArea.vue
Labels: cla-signed

#3992 build: add wasm bits to Dockerfile and bump to go v1.15.6
  Makefile
  cmd/satellite/Dockerfile
  satellite/console/wasm/README.md
  scripts/build-wasm.sh
Labels: Request Code Review, cla-signed

#3993 Jenkinsfile: update to go v1.15.6
  Jenkinsfile
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3994 Adding Fastly
  satellite/rewards/partners.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3995 Update Jenkinsfile.tests
  Jenkinsfile.tests
Labels: Reviewer Can Merge, cla-signed

#3998 satellite/console/wasm: fix issue from merge
  satellite/console/wasm/access.go
Labels: cla-signed

#3999 Update test-sim-UITests.sh
  scripts/test-sim-UITests.sh
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#4001 satellite/accounting: default project limits
  satellite/metainfo/config.go
  scripts/testdata/satellite-config.yaml.lock
Labels: cla-signed

#4002 satellite/access-grants: default auth service url
  satellite/console/consoleweb/server.go
  scripts/testdata/satellite-config.yaml.lock
Labels: cla-signed

#4005 Makefile: build wasm files only once
  Makefile
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#4006 cmd: ensure proper arch is used for docker container
  cmd/storagenode/Dockerfile
  cmd/uplink/Dockerfile
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#4007 build: update node to v14.15.3
  Makefile
  cmd/satellite/Dockerfile
  web/satellite/Dockerfile
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#4008 Makefile,scripts: move from aarch64 to arm64v8
  Makefile
  scripts/deploy-storagenode.sh
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#4009 satellite/accounting: Performance improvements to getNodeIds used by GetBandwidthSince
  satellite/satellitedb/dbx/satellitedb.dbx
  satellite/satellitedb/dbx/satellitedb.dbx.go
  satellite/satellitedb/dbx/satellitedb.dbx.pgx.sql
  satellite/satellitedb/dbx/satellitedb.dbx.pgxcockroach.sql
  satellite/satellitedb/migrate.go
  satellite/satellitedb/storagenodeaccounting.go
  satellite/satellitedb/testdata/postgres.v135.sql
Labels: Request Code Review, cla-signed

#4010 satellite/accounting: Add index for project_id on bucket_storage_tallies
  satellite/satellitedb/dbx/satellitedb.dbx
  satellite/satellitedb/dbx/satellitedb.dbx.go
  satellite/satellitedb/dbx/satellitedb.dbx.pgx.sql
  satellite/satellitedb/dbx/satellitedb.dbx.pgxcockroach.sql
  satellite/satellitedb/migrate.go
  satellite/satellitedb/testdata/postgres.v136.sql
Labels: cla-signed

#4012 satellite/overlay: Add index on nodes table
  satellite/satellitedb/dbx/satellitedb.dbx
  satellite/satellitedb/dbx/satellitedb.dbx.go
  satellite/satellitedb/dbx/satellitedb.dbx.pgx.sql
  satellite/satellitedb/dbx/satellitedb.dbx.pgxcockroach.sql
  satellite/satellitedb/migrate.go
  satellite/satellitedb/testdata/postgres.v137.sql
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#4011 v1.19.4 point release
  Makefile
  scripts/deploy-storagenode.sh
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#4013 satellite/overlay: Use AS OF SYSTEM TIME on CRDB when finding nodes for upload
  satellite/api.go
  satellite/core.go
  satellite/overlay/benchmark_test.go
  satellite/overlay/config.go
  satellite/overlay/service.go
  satellite/overlay/service_test.go
  satellite/repair/checker/online_test.go
  satellite/repairer.go
  satellite/satellitedb/database.go
  satellite/satellitedb/nodeselection.go
  satellite/satellitedb/overlaycache.go
  scripts/testdata/satellite-config.yaml.lock
Labels: Request Code Review, cla-signed

#4014 Jenkinsfile.public: specify main branch for docker build
  Jenkinsfile.public
Labels: Request Code Review, Reviewer Can Merge, cla-signed
