Repository storj/storj, pull requests merged in 2020-05, with the labels that each got.

#3873 satellite/metainfo: move logging to debug for piece deletion
  satellite/metainfo/piecedeletion/dialer.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3838 docs/blueprints: blueprint nodes cache
  docs/blueprints/cache-node-selection.md
Labels: Enhancement, Proposal, cla-signed

#3874 cmd/satellite: Enable admin service like other services, also sort environment variables
  cmd/satellite/entrypoint
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3877 satellite: Change Default Project Limits and minimum STORJ Payment
  satellite/accounting/rollup/rollup.go
  satellite/payments/paymentsconfig/config.go
  scripts/testdata/satellite-config.yaml.lock
  web/satellite/src/components/account/billing/paymentMethods/AddStorjForm.vue
  web/satellite/src/components/account/billing/paymentMethods/PaymentsBonus.vue
  web/satellite/src/components/account/billing/paymentMethods/TokenDepositSelection.vue
  web/satellite/src/components/onboardingTour/steps/AddPaymentStep.vue
  web/satellite/src/components/onboardingTour/steps/paymentStates/AddStorjState.vue
  web/satellite/src/components/onboardingTour/steps/paymentStates/tokenSubSteps/PayingStep.vue
  web/satellite/tests/unit/account/billing/paymentMethods/AddStorjForm.spec.ts
  web/satellite/tests/unit/account/billing/paymentMethods/__snapshots__/AddStorjForm.spec.ts.snap
  web/satellite/tests/unit/account/billing/paymentMethods/__snapshots__/PaymentMethods.spec.ts.snap
  web/satellite/tests/unit/onboardingTour/steps/__snapshots__/AddPaymentStep.spec.ts.snap
  web/satellite/tests/unit/onboardingTour/steps/paymentStates/__snapshots__/AddStorjState.spec.ts.snap
  web/satellite/tests/unit/onboardingTour/steps/paymentStates/tokenSubSteps/PayingStep.spec.ts
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3878 satellite/accounting: separate usage and bandwidth limit
  private/testplanet/satellite.go
  satellite/accounting/db.go
  satellite/accounting/db_test.go
  satellite/accounting/projectusage.go
  satellite/accounting/projectusage_test.go
  satellite/accounting/rollup/rollup.go
  satellite/admin/project.go
  satellite/admin/project_test.go
  satellite/api.go
  satellite/console/consoleweb/consoleql/mutation_test.go
  satellite/console/consoleweb/consoleql/query_test.go
  satellite/core.go
  satellite/satellitedb/dbx/satellitedb.dbx
  satellite/satellitedb/dbx/satellitedb.dbx.cockroach.sql
  satellite/satellitedb/dbx/satellitedb.dbx.go
  satellite/satellitedb/dbx/satellitedb.dbx.postgres.sql
  satellite/satellitedb/migrate.go
  satellite/satellitedb/projectaccounting.go
  satellite/satellitedb/testdata/postgres.v107.sql
  satellite/satellitedb/testdata/postgres.v108.sql
  scripts/testdata/satellite-config.yaml.lock
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3882 satellite/admin: obvious project name in documentation
  satellite/admin/README.md
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3884 cmd/satellite: ensure we only create stripe customers for activated users
  cmd/satellite/stripe.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3881 storagenode/piecestore: move queue size defaults
  private/testplanet/storagenode.go
  storagenode/pieces/deleter.go
  storagenode/pieces/deleter_test.go
  storagenode/piecestore/endpoint.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3888 satellite/admin: add delete project endpoint
  satellite/admin/README.md
  satellite/admin/project.go
  satellite/admin/project_test.go
  satellite/admin/server.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3876 satellite/metainfo: remove deprecated error validation
  satellite/metainfo/metainfo.go
  satellite/metainfo/metainfo_old_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3890 cmd/storj-admin: initial commit of new tool
  cmd/storj-admin/main.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3889 satellite/admin: add user creation endpoint
  satellite/admin/README.md
  satellite/admin/project.go
  satellite/admin/project_test.go
  satellite/admin/server.go
  satellite/admin/user.go
  satellite/admin/user_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3891 satellite/admin: add coupon creation and listing
  satellite/admin/README.md
  satellite/admin/server.go
  satellite/admin/user.go
  satellite/admin/user_test.go
  satellite/payments/coupons.go
  satellite/payments/stripecoinpayments/coupons.go
  satellite/payments/stripecoinpayments/coupons_test.go
  satellite/payments/stripecoinpayments/service.go
  satellite/satellitedb/coupons.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3893 satellite/admin: add coupon deletion
  satellite/admin/README.md
  satellite/admin/coupon.go
  satellite/admin/coupon_test.go
  satellite/admin/server.go
  satellite/admin/user.go
  satellite/admin/user_test.go
  satellite/payments/stripecoinpayments/coupons.go
  satellite/satellitedb/coupons.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3894 satellite/contact: rm unhelpful verbose logging
  satellite/contact/service.go
Labels: cla-signed

#3895 satellite/overlay: enable node selection cache on all satellites
  satellite/overlay/nodeselectioncache.go
  scripts/testdata/satellite-config.yaml.lock
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3896 satellite/admin: add user update endpoint
  satellite/admin/README.md
  satellite/admin/server.go
  satellite/admin/user.go
  satellite/admin/user_test.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3899 cmd/satellite: Install curl per default to docker image
  cmd/satellite/Dockerfile
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3898 nodeselection: Increase minimum free space to 500MB
  satellite/overlay/config.go
  scripts/testdata/satellite-config.yaml.lock
  storagenode/piecestore/endpoint.go
Labels: cla-signed

#3900 satellite/admin: Add the proper documentation for bandwidth limits
  satellite/admin/README.md
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3834 docs/blueprints: tracking downtime with audits
  docs/blueprints/archive/storage-node-downtime-tracking-deprecated.md
  docs/blueprints/storage-node-downtime-tracking-with-audits.md
Labels: Enhancement, Proposal, cla-signed

#3897 satellite/coinpayments: Reduce update interval to 2 minutes
  satellite/payments/stripecoinpayments/service.go
  scripts/testdata/satellite-config.yaml.lock
Labels: Request Code Review, Reviewer Can Merge, cla-signed
