Repository storj/storj, pull requests merged in 2020-04, with the labels that each got.

#3842 cmd/satellite: add gc to entrypoint
  cmd/satellite/entrypoint
Labels: cla-signed

#3820 Remove VOLUME /root/.local/share/storj/storagenode
  cmd/storagenode/Dockerfile
Labels: cla-signed

#3844 storagenode/storagenodedb: Improve preflight schema error message
  storagenode/storagenodedb/database.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3819 cmd/identity: Improve CA key message
  cmd/identity/main.go
Labels: cla-signed

#3780 satellite/metainfo: descellate some errors
  satellite/metainfo/metainfo.go
Labels: cla-signed

#3847 installer/windows: don't require ca.key file
  installer/windows/Storj/CustomAction.cs
  installer/windows/StorjTests/ValidateIdentityDirTests.cs
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3831 satellite/overlay: combine SelectStorageNodes and SelectNewStorageNodes
  satellite/overlay/benchmark_test.go
  satellite/overlay/service.go
  satellite/overlay/service_test.go
  satellite/satellitedb/nodeselection.go
  satellite/satellitedb/overlaycache.go
Labels: Request Code Review, cla-signed

#3846 satellite/overlay: add selected node cache
  satellite/overlay/nodeselectioncache.go
  satellite/overlay/nodeselectioncache_test.go
  satellite/overlay/service.go
  satellite/satellitedb/overlaycache.go
Labels: Code Review In-Progress, cla-signed

#3826 docs/blueprints: slow down and retry
  docs/blueprints/slow-down-and-retry.md
Labels: Enhancement, Proposal, cla-signed

#3851 satellite: update log levels
  private/version/checker/service.go
  satellite/api.go
  satellite/core.go
  satellite/gc.go
  satellite/gracefulexit/endpoint.go
  satellite/repair/repairer/ec.go
  satellite/repairer.go
  storagenode/piecestore/endpoint.go
Labels: Code Review In-Progress, cla-signed

#3857 storagenode/piecestore: fix annoying info log for upload canceled
  storagenode/piecestore/endpoint.go
Labels: Request Code Review, cla-signed

#3858 scripts/deploy-storagenode: tag docker image as latest
  scripts/deploy-storagenode.sh
Labels: cla-signed

#3855 Add container image for segment-reaper
  Makefile
  cmd/segment-reaper/Dockerfile
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3860 Call the right make target for the segment-reaper
  Makefile
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3861 storagenode/piecestore: add missing log message about audit errors
  storagenode/piecestore/endpoint.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed

#3862 satellite/overlay: add changes to selected node benchmarks
  satellite/overlay/benchmark_test.go
Labels: cla-signed

#3859 satellite/overlay: use node selection cache for uploads
  private/testplanet/satellite.go
  satellite/audit/disqualification_test.go
  satellite/overlay/benchmark_test.go
  satellite/overlay/config.go
  satellite/overlay/nodeselectioncache.go
  satellite/overlay/nodeselectioncache_test.go
  satellite/overlay/selection_test.go
  satellite/overlay/service.go
  satellite/repair/repairer/segments.go
  scripts/testdata/satellite-config.yaml.lock
Labels: Request Code Review, cla-signed

#3863 satellite/satellitedb: Ensure we just return bucket usage for buckets that exist
  satellite/accounting/projectusage_test.go
  satellite/satellitedb/projectaccounting.go
Labels: Request Code Review, Reviewer Can Merge, cla-signed
