Repository storj/storj, pull requests merged in 2021-12, with the labels that each got.

#4305 web/satellite: fix delete bucket issue
  web/satellite/src/components/objects/BucketItem.vue
  web/satellite/src/components/objects/BucketsView.vue
Labels: cla-signed

#4304 scripts: making clear if builing a production or development version
  scripts/release.sh
Labels: cla-signed

#4307 Golangci lint v1.43.0 changes
  cmd/storagenode-updater/loop.go
  cmd/storagenode-updater/main.go
  cmd/storagenode-updater/restart.go
  cmd/storagenode/service_nonwindows.go
  cmd/uplinkng/cmd_share_test.go
  storage/filestore/dir_unix.go
Labels: cla-signed, Request Code Review

#4300 Track user events through HubSpot events API
  satellite/analytics/hubspot.go
  satellite/analytics/service.go
  satellite/api.go
  satellite/console/consoleweb/consoleapi/analytics.go
  satellite/console/service.go
  scripts/testdata/satellite-config.yaml.lock
Labels: cla-signed

#4308 Track user events through HubSpot events API (#4300)
  satellite/analytics/hubspot.go
  satellite/analytics/service.go
  satellite/api.go
  satellite/console/consoleweb/consoleapi/analytics.go
  satellite/console/service.go
  scripts/testdata/satellite-config.yaml.lock
Labels: cla-signed

#4311 point release v1.45.3
  Jenkinsfile
  Makefile
Labels: cla-signed

#4309 storagenode/reputation: fix missing space in suspension message
  storagenode/reputation/service.go
Labels: cla-signed

#4285 web/satellite: Fix subtitle in disable 2FA
  web/satellite/src/components/account/mfa/DisableMFAPopup.vue
Labels: cla-signed

#4306 docs: Adding a testplan folder with a README and TEMPLATE for testplan
  docs/testplan/README.md
  docs/testplan/TEMPLATE.md
Labels: cla-signed

#4301 testsuite/ui/multinode: adding more UI tests
  testsuite/ui/multinode/add_node_test.go
  testsuite/ui/multinode/node_more_options_test.go
  web/multinode/package-lock.json
Labels: cla-signed

#4319 Makefile: fix variable used to trigger release drafting
  Makefile
Labels: cla-signed, Request Code Review, Reviewer Can Merge

#4320 Update README.md
  README.md
Labels: cla-signed

#4321 web/satellite: Fix social media sharing links
  web/satellite/src/components/browser/FileShareModal.vue
Labels: cla-signed
