Repository storj/storj, pull requests merged in 2022-03, with the labels that each got.

#4456 Maintainers: update release instructions
  MAINTAINERS.md
Labels: cla-signed

#4403 docs/testplan: Adding a testplan for Access Grants Page
  docs/testplan/access-grants-page-testplan.md
Labels: cla-signed, Tracked in Jira, Testplan

#4599 Maintainers: remove link
  MAINTAINERS.md
Labels: cla-signed

#4600 satellite/repairer: handle excluded countries
  private/testplanet/reconfigure.go
  satellite/audit/verifier_test.go
  satellite/nodeselection/uploadselection/criteria.go
  satellite/orders/service.go
  satellite/overlay/service.go
  satellite/overlay/service_test.go
  satellite/repair/checker/checker_test.go
  satellite/repair/repair_test.go
  satellite/repair/repairer/segments.go
  satellite/satellitedb/overlaycache.go
Labels: cla-signed

#4602 web/multinode: UI clarification to also add port
  web/multinode/src/app/components/modals/AddNewNode.vue
  web/multinode/src/app/views/AddFirstNode.vue
Labels: cla-signed

#4465 docs/testplan: Adding a testplan for new Billing Page
  docs/testplan/billing-page-testplan.md
Labels: cla-signed, Testplan

#4628 satellite/payment: enable segment fee
  satellite/payments/paymentsconfig/config.go
  scripts/testdata/satellite-config.yaml.lock
Labels: cla-signed

#4647 scripts/draft-release: add sleep to avoid race condition on uploading the binaries
  scripts/draft-release.sh
Labels: cla-signed, Request Code Review, Reviewer Can Merge

#4658 Modified event names
  satellite/analytics/hubspot.go
  satellite/analytics/service.go
Labels: cla-signed

#4317 docs/testplan: Adding a testplan for Server Side Copy
  docs/testplan/server-side-copy-testplan.md
Labels: cla-signed, Request Code Review, Testplan

#4665 Added "email" in segment track calls
  satellite/analytics/service.go
Labels: cla-signed
