Repository storj/storj, pull requests merged in 2022-01, with the labels that each got.

#4318 docs/testplan: Adding a testplan for Project Dashboard
  docs/testplan/project-dashboard-testplan.md
Labels: cla-signed, Testplan

#4341 web/satellite: fix FileModal Share Link
  web/satellite/src/components/browser/FileModal.vue
Labels: cla-signed, Request Code Review, Reviewer Can Merge

#4390 Revert "storagenode: display quic status on SNO dashboard"
  private/server/server.go
  storagenode/console/service.go
  storagenode/peer.go
  web/storagenode/src/app/components/SNOContentTitle.vue
  web/storagenode/src/app/store/modules/node.ts
  web/storagenode/src/storagenode/api/storagenode.ts
  web/storagenode/src/storagenode/sno/sno.ts
  web/storagenode/tests/unit/components/DiskStatChart.spec.ts
  web/storagenode/tests/unit/components/payments/EstimationPeriodDropdown.spec.ts
  web/storagenode/tests/unit/store/node.spec.ts
Labels: cla-signed

#4393 satellite/contact: add PingMe endpoint
  go.mod
  go.sum
  satellite/contact/contact_test.go
  satellite/contact/endpoint.go
  testsuite/go.mod
  testsuite/go.sum
Labels: cla-signed

#4404 satellite/metainfo: reduce default user rate limit to 100
  satellite/metainfo/config.go
  scripts/testdata/satellite-config.yaml.lock
Labels: cla-signed

#4449 mod: use vendored base58
  certificate/authorization/authorizations.go
  certificate/authorization/authorizations_test.go
  cmd/storj-sim/network.go
  cmd/uplink/cmd/access.go
  cmd/uplink/cmd/import.go
  cmd/uplinkng/cmd_access_inspect.go
  go.mod
  go.sum
  satellite/gc/gc_test.go
  satellite/inspector/inspector_test.go
  scripts/update-access.go
  testsuite/go.mod
  testsuite/go.sum
Labels: cla-signed
