Repository storj/storj, pull requests merged in 2022-08, with the labels that each got.

#5049 web/satellite: Fix documentation URL
  web/satellite/src/components/accessGrants/CreateAccessModal.vue
Labels: cla-signed, Satellite UI, Community

#4977 web/satellite: Added token transaction history to new payment methods flow
  web/satellite/src/components/account/billing/depositAndBillingHistory/SortingHeader2.vue
  web/satellite/src/components/account/billing/paymentMethods/TokenTransactionItem.vue
  web/satellite/src/components/common/VerticalArrows.vue
  web/satellite/tests/unit/common/__snapshots__/VerticalArrows.spec.ts.snap
  web/satellite/tests/unit/projectMembers/__snapshots__/SortingListHeader.spec.ts.snap
Labels: cla-signed

#5024 storagenode/pieces: allow to configure initial piece scan
  storagenode/peer.go
  storagenode/pieces/cache.go
  storagenode/pieces/cache_test.go
  storagenode/piecestore/endpoint.go
Labels: cla-signed, SNO, Community

#5009 satellite/analytics: Added track calls for user behavioral events
  satellite/analytics/service.go
  satellite/console/service.go
  web/satellite/src/components/accessGrants/AccessGrants.vue
  web/satellite/src/components/accessGrants/CreateAccessModal.vue
  web/satellite/src/components/browser/FileBrowser.vue
  web/satellite/src/utils/constants/analyticsEventNames.ts
Labels: cla-signed

#5015 Web/satellite: Create Access Flow Modal Refactor
  web/satellite/src/components/accessGrants/CreateAccessModal.vue
  web/satellite/src/components/accessGrants/modals/CreateFormModal.vue
  web/satellite/src/components/accessGrants/modals/EncryptFormModal.vue
  web/satellite/src/components/accessGrants/modals/GrantCreatedModal.vue
  web/satellite/src/components/accessGrants/permissions/DurationSelection.vue
Labels: cla-signed

#5065 Web/satellite: Add responsiveness to onboarding flow
  web/satellite/src/components/objects/BucketCreation.vue
  web/satellite/src/components/objects/BucketCreationGeneratePassphrase.vue
  web/satellite/src/components/objects/BucketCreationNameStep.vue
  web/satellite/src/components/objects/BucketCreationProgress.vue
  web/satellite/src/components/onboardingTour/OnboardingTourArea.vue
  web/satellite/src/components/onboardingTour/steps/OverviewStep.vue
  web/satellite/src/components/onboardingTour/steps/common/OverviewContainer.vue
Labels: cla-signed

#5050 web/satellite Billing screen bug fixes
  web/satellite/src/components/account/billing/billingTabs/BillingHistory.vue
  web/satellite/src/components/account/billing/billingTabs/Coupons.vue
  web/satellite/src/components/account/billing/billingTabs/Overview.vue
  web/satellite/src/components/account/billing/billingTabs/PaymentMethods.vue
  web/satellite/src/components/account/billing/estimatedCostsAndCredits/UsageAndChargesItem2.vue
  web/satellite/src/components/navigation/NavigationArea.vue
Labels: cla-signed

#5093 satellite/metabase: revert non-recursive listing optimization
  satellite/metabase/iterator.go
Labels: cla-signed

#5101 storagenode/storagenodedb: fix null at_rest_total values for storage usage
  storagenode/storagenodedb/storageusage.go
  storagenode/storageusage/storageusage_test.go
Labels: cla-signed

#5117 Point release v1.62.4 listing optimization and access grant fix
  satellite/metabase/iterator.go
  satellite/metabase/iterator_test.go
  web/satellite/src/components/accessGrants/CreateAccessModal.vue
  web/satellite/src/components/accessGrants/modals/CreateFormModal.vue
  web/satellite/src/components/accessGrants/modals/EncryptFormModal.vue
  web/satellite/src/components/accessGrants/modals/GrantCreatedModal.vue
Labels: cla-signed
