Repository storj/storj, pull requests merged in 2022-12, with the labels that each got.

#5362 Expose LOG_LEVEL env variable via Dockerfile for storagenode
  cmd/storagenode/Dockerfile
  cmd/storagenode/docker/entrypoint
Labels: cla-signed, Request Code Review, Proposal, Reviewer Can Merge

#5338 docs/testplan: Testplan for Storage-node Email Notification
  docs/testplan/storagenode-email-notification.md
Labels: cla-signed, Testplan

#5020 web/storagenode: fix bandwidth graph
  web/storagenode/src/app/components/BaseChart.vue
Labels: cla-signed, SNO, Community

#5334 satellite/metabase/rangedloop: minimal loop
  satellite/metabase/rangedloop/provider.go
  satellite/metabase/rangedloop/rangedlooptest/countobserver.go
  satellite/metabase/rangedloop/rangedlooptest/providermock.go
  satellite/metabase/rangedloop/service.go
  satellite/metabase/rangedloop/service_test.go
  satellite/rangedloop.go
  scripts/testdata/satellite-config.yaml.lock
Labels: cla-signed

#5337 satellite/metabase/rangedloop: database abstraction
  satellite/metabase/rangedloop/provider.go
  satellite/metabase/rangedloop/providerdb.go
  satellite/metabase/rangedloop/providerdb_test.go
Labels: cla-signed

#5400 ci: removed ui artifacts
  Jenkinsfile.premerge
  Jenkinsfile.public
  Jenkinsfile.verify
Labels: cla-signed, Request Code Review, Reviewer Can Merge

#5336 docs/testplan: Testplan for Automatic Account Freeze-Unfreeze
  docs/testplan/automatic-account-freeze-unfreeze.md
Labels: cla-signed, Testplan

#5350 satellite/metabase/rangedloop: measure observer duration
  satellite/metabase/rangedloop/rangedlooptest/sleepobserver.go
  satellite/metabase/rangedloop/service.go
  satellite/metabase/rangedloop/service_test.go
  satellite/metrics/observer_test.go
Labels: cla-signed
