Repository storj/storj, pull requests merged in 2024-06, with the labels that each got.

#6990 web/satellite: ui updates
  web/satellite/src/components/AccessTableComponent.vue
  web/satellite/src/components/AddCreditCardComponent.vue
  web/satellite/src/components/ApplicationItem.vue
  web/satellite/src/components/BrowserCardViewComponent.vue
  web/satellite/src/components/BrowserRowActions.vue
  web/satellite/src/components/BrowserTableComponent.vue
  web/satellite/src/components/BucketsDataTable.vue
  web/satellite/src/components/CreditCardComponent.vue
  web/satellite/src/components/FileCard.vue
  web/satellite/src/components/ProjectCard.vue
  web/satellite/src/components/ProjectsTableComponent.vue
  web/satellite/src/components/StorjTokenCardComponent.vue
  web/satellite/src/components/TeamTableComponent.vue
  web/satellite/src/components/billing/UsageAndChargesItemComponent.vue
  web/satellite/src/components/dialogs/AccessSetupDialog.vue
  web/satellite/src/components/dialogs/AccountSetupDialog.vue
  web/satellite/src/components/dialogs/BucketDetailsDialog.vue
  web/satellite/src/components/dialogs/FilePreviewDialog.vue
  web/satellite/src/components/dialogs/accessSetupSteps/AccessCreatedStep.vue
  web/satellite/src/components/dialogs/accessSetupSteps/ChooseAccessStep.vue
  web/satellite/src/components/dialogs/accessSetupSteps/ChooseFlowStep.vue
  web/satellite/src/components/dialogs/accessSetupSteps/ChoosePermissionsStep.vue
  web/satellite/src/components/dialogs/accessSetupSteps/OptionalExpirationStep.vue
  web/satellite/src/components/dialogs/accessSetupSteps/SelectBucketsStep.vue
  web/satellite/src/components/dialogs/accountSetupSteps/BusinessStep.vue
  web/satellite/src/components/dialogs/accountSetupSteps/PersonalStep.vue
  web/satellite/src/layouts/default/AccountNav.vue
  web/satellite/src/layouts/default/AppBar.vue
  web/satellite/src/layouts/default/NavigationItem.vue
  web/satellite/src/layouts/default/ProjectNav.vue
  web/satellite/src/plugins/vuetify.ts
  web/satellite/src/styles/styles.scss
  web/satellite/src/views/AccountSettings.vue
  web/satellite/src/views/Applications.vue
  web/satellite/src/views/Billing.vue
  web/satellite/src/views/Bucket.vue
  web/satellite/src/views/ProjectSettings.vue
Labels: cla-signed

#7018 cherry pick v1.107.2
  satellite/console/accountfreezes.go
  satellite/console/accountfreezes_test.go
  satellite/console/projectusagelimits.go
Labels: cla-signed

#6974 web/multinode: implement table sorting
  web/multinode/src/app/components/myNodes/tables/NodesTable.vue
  web/multinode/src/app/components/payouts/tables/payoutSummary/PayoutsSummaryTable.vue
  web/multinode/src/app/components/wallets/tables/walletsSummary/WalletsTable.vue
Labels: cla-signed, Community

#7023 web/satellite: update managed passphrase step
  web/satellite/src/components/dialogs/accountSetupSteps/ManagedPassphraseOptInSelector.vue
Labels: cla-signed

#7022 web/satellite: ui improvements
  web/satellite/src/components/AccessTableComponent.vue
  web/satellite/src/components/BrowserTableComponent.vue
  web/satellite/src/components/BucketsDataTable.vue
  web/satellite/src/components/CreditCardComponent.vue
  web/satellite/src/components/StorjTokenCardComponent.vue
  web/satellite/src/components/TeamTableComponent.vue
  web/satellite/src/components/dialogs/AccessSetupDialog.vue
  web/satellite/src/components/dialogs/AccountDeleteDialog.vue
  web/satellite/src/components/dialogs/AccountEmailChangeDialog.vue
  web/satellite/src/components/dialogs/ApplyCouponCodeDialog.vue
  web/satellite/src/components/dialogs/BrowserNewFolderDialog.vue
  web/satellite/src/components/dialogs/BucketDetailsDialog.vue
  web/satellite/src/components/dialogs/ChangeMemberRoleDialog.vue
  web/satellite/src/components/dialogs/ChangeNameDialog.vue
  web/satellite/src/components/dialogs/ChangePasswordDialog.vue
  web/satellite/src/components/dialogs/CreateAccessDialog.vue
  web/satellite/src/components/dialogs/CreateBucketDialog.vue
  web/satellite/src/components/dialogs/DeleteAccessDialog.vue
  web/satellite/src/components/dialogs/DeleteBucketDialog.vue
  web/satellite/src/components/dialogs/DeleteFileDialog.vue
  web/satellite/src/components/dialogs/DetailedUsageReportDialog.vue
  web/satellite/src/components/dialogs/DisableMFADialog.vue
  web/satellite/src/components/dialogs/EditDefaultCreditCardDialog.vue
  web/satellite/src/components/dialogs/EditProjectDetailsDialog.vue
  web/satellite/src/components/dialogs/EditProjectLimitDialog.vue
  web/satellite/src/components/dialogs/EmissionsDialog.vue
  web/satellite/src/components/dialogs/EnableMFADialog.vue
  web/satellite/src/components/dialogs/EnterBucketPassphraseDialog.vue
  web/satellite/src/components/dialogs/EnterProjectPassphraseDialog.vue
  web/satellite/src/components/dialogs/GeographicDistributionDialog.vue
  web/satellite/src/components/dialogs/InactivityDialog.vue
  web/satellite/src/components/dialogs/JoinProjectDialog.vue
  web/satellite/src/components/dialogs/MFACodesDialog.vue
  web/satellite/src/components/dialogs/RemoveCreditCardDialog.vue
  web/satellite/src/components/dialogs/RemoveProjectMemberDialog.vue
  web/satellite/src/components/dialogs/SessionExpiredDialog.vue
  web/satellite/src/components/dialogs/SetPassphrasePromptDialog.vue
  web/satellite/src/components/dialogs/SetSessionTimeoutDialog.vue
  web/satellite/src/components/dialogs/ShareDialog.vue
  web/satellite/src/components/dialogs/ToggleVersioningDialog.vue
  web/satellite/src/components/dialogs/TrialExpirationDialog.vue
  web/satellite/src/components/dialogs/UpdateSessionTimeoutPromptDialog.vue
  web/satellite/src/components/dialogs/UploadOverwriteWarningDialog.vue
  web/satellite/src/components/dialogs/VersioningBetaDialog.vue
  web/satellite/src/components/dialogs/accessSetupSteps/ChooseFlowStep.vue
  web/satellite/src/components/dialogs/accessSetupSteps/ChoosePermissionsStep.vue
  web/satellite/src/components/dialogs/accessSetupSteps/OptionalExpirationStep.vue
  web/satellite/src/components/dialogs/accessSetupSteps/SelectBucketsStep.vue
  web/satellite/src/components/dialogs/commonPassphraseSteps/SaveButtons.vue
  web/satellite/src/components/dialogs/createAccessSteps/TextOutputArea.vue
  web/satellite/src/components/dialogs/managePassphraseSteps/ManageOptionsStep.vue
  web/satellite/src/layouts/default/AppBar.vue
  web/satellite/src/styles/styles.scss
  web/satellite/src/views/AccountSettings.vue
  web/satellite/src/views/Applications.vue
  web/satellite/src/views/Billing.vue
  web/satellite/src/views/Dashboard.vue
  web/satellite/src/views/ProjectSettings.vue
Labels: cla-signed, Satellite UI
