Repository storj/storj, pull requests merged in 2025-03, with the labels that each got.

#7387 web/satellite: ui and ux updates
  web/satellite/src/components/AccessTableComponent.vue
  web/satellite/src/components/BrowserCardViewComponent.vue
  web/satellite/src/components/BrowserRowActions.vue
  web/satellite/src/components/BrowserSnackbarComponent.vue
  web/satellite/src/components/BrowserTableComponent.vue
  web/satellite/src/components/BrowserVersionsTableComponent.vue
  web/satellite/src/components/BucketsDataTable.vue
  web/satellite/src/components/DomainsTableComponent.vue
  web/satellite/src/components/ProjectCard.vue
  web/satellite/src/components/ProjectsTableComponent.vue
  web/satellite/src/components/TeamTableComponent.vue
  web/satellite/src/components/TokenTransactionsTableComponent.vue
  web/satellite/src/components/UploadItem.vue
  web/satellite/src/components/billing/BillingHistoryTab.vue
  web/satellite/src/components/billing/UsageAndChargesItemComponent.vue
  web/satellite/src/components/dialogs/CreateProjectDialog.vue
  web/satellite/src/components/dialogs/EditDefaultCreditCardDialog.vue
  web/satellite/src/components/dialogs/EditProjectDetailsDialog.vue
  web/satellite/src/components/dialogs/EditProjectLimitDialog.vue
  web/satellite/src/components/dialogs/RemoveCreditCardDialog.vue
  web/satellite/src/components/dialogs/UploadOverwriteWarningDialog.vue
  web/satellite/src/components/dialogs/accessSetupSteps/AccessCreatedStep.vue
  web/satellite/src/components/onboarding/OnboardingStepperComponent.vue
  web/satellite/src/layouts/default/AppBar.vue
  web/satellite/src/layouts/default/AuthBar.vue
  web/satellite/src/plugins/vuetify.ts
  web/satellite/src/styles/styles.scss
  web/satellite/src/views/Access.vue
  web/satellite/src/views/Applications.vue
  web/satellite/src/views/Bucket.vue
  web/satellite/src/views/Buckets.vue
  web/satellite/src/views/CunoFS.vue
  web/satellite/src/views/Dashboard.vue
  web/satellite/src/views/Domains.vue
  web/satellite/src/views/Projects.vue
  web/satellite/src/views/Team.vue
Labels: cla-signed, Satellite UI

#7390 make;docker/jobq: Add docker image to build for jobq
  Makefile
  cmd/jobq/Dockerfile
Labels: cla-signed, Request Code Review, Reviewer Can Merge

#7391 Cherry-pick jobq commits into release-v1.124
  Makefile
  cmd/jobq/Dockerfile
  satellite/internalpb/jobqueue.pb.go
  satellite/internalpb/jobqueue.proto
  satellite/internalpb/jobqueue_drpc.pb.go
  satellite/jobq/client.go
  satellite/jobq/clientserver_test.go
  satellite/jobq/job.go
  satellite/jobq/jobqueue/jobqueue.go
  satellite/jobq/jobqueue/jobqueue_sync_test.go
  satellite/jobq/jobqueue/jobqueue_test.go
  satellite/jobq/server/endpoint.go
Labels: cla-signed, Request Code Review, Reviewer Can Merge

#7394 cherry pick v1.124.2
  storagenode/hashstore/tbl.go
Labels: cla-signed

#7397 cherry-pick v1.124.3
  satellite/metabase/list_objects.go
Labels: cla-signed

#7403 Point release v1.124.5
  private/testplanet/satellite.go
  satellite/metabase/adapter_spanner.go
  satellite/metabase/adapter_spanner_test.go
  satellite/metabase/db.go
  satellite/metainfo/config.go
  satellite/satellite-config.yaml.lock
Labels: cla-signed

#7404 web/satellite: improve the share dialogs
  web/satellite/src/components/InputCopyButton.vue
  web/satellite/src/components/dialogs/ShareDialog.vue
Labels: cla-signed, Satellite UI

#7406 Point release v1.124.6
  storagenode/blobstore/statcache/statcache.go
Labels: cla-signed

#7417 Cherry picks for v1.125 release
  cmd/storagenode/service_windows.go
  cmd/tools/metabase-listing-performance/main.go
  private/server/fastopen_windows.go
  satellite/admin/user.go
  satellite/analytics/hubspot.go
  satellite/analytics/service.go
  satellite/console/accountfreezes.go
  satellite/console/accountfreezes_test.go
  satellite/console/consoleweb/config.go
  satellite/console/consoleweb/consoleapi/analytics.go
  satellite/console/consoleweb/endpoints_test.go
  satellite/console/consoleweb/server.go
  satellite/console/service.go
  satellite/console/users.go
  satellite/payments/accountfreeze/chore_test.go
  satellite/satellite-config.yaml.lock
  satellite/satellitedb/consoledb/users_test.go
  testsuite/playwright-ui/server/edge.go
  testsuite/storjscan/storjscantest/run.go
  web/satellite/src/api/analytics.ts
  web/satellite/src/layouts/default/ProjectNav.vue
  web/satellite/src/router/index.ts
  web/satellite/src/store/modules/analyticsStore.ts
  web/satellite/src/types/analytics.ts
  web/satellite/src/types/common.ts
  web/satellite/src/types/config.gen.ts
  web/satellite/src/types/users.ts
  web/satellite/src/utils/constants/analyticsEventNames.ts
  web/satellite/src/utils/validation.ts
  web/satellite/src/views/ObjectMount.vue
Labels: cla-signed
